docs/configurations.md, docs/two-phase-commit-transactions.md
This backport addresses changes discussed in https://github.com/scalar-labs/scalardb/pull/1190.
=> Backport to branch(3.8) : Revise configuration-related docs

.github/workflows/release-snapshot.yaml
This PR reverts the commit of #1187 because we use snapshot versions of non-master/main branches in other repositories.
#1187
- Revert the change of #1187
N/A
N/A
=> Revert "Update the trigger of the GitHub Action to work only on master branch push (#1187)"

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1239
=> Backport to branch(3) : Bump org.xerial:sqlite-jdbc from 3.43.2.1 to 3.43.2.2

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1242
=> Backport to branch(3) : Bump org.apache.commons:commons-dbcp2 from 2.10.0 to 2.11.0

.github/workflows/create-release.yaml, .github/workflows/release.yaml, .github/workflows/upload-artifacts.yaml
The purpose of this PR are:
- Split `release.yaml` into two sub-workflows to facilitate rerunning the workflow when the workflow fails partially.
- Use [release-note-script](https://github.com/scalar-labs/actions/tree/main/release-note-script) to create the release note body by extracting from the PR description to make it more meaningful to the reader.
N/A
The changes made by this PR are as follows:
1. Splits `release.yaml` into two sub workflow files: `upload-artifacts.yaml` and `create-release.yaml`.
- `upload-artifacts.yaml` creates container images, registers them to the container registries, and registers Jar files in the Maven central.
- `create-release.yaml` generates release notes and uploads release assets.
2. Uses the [release-note-scritp](https://github.com/scalar-labs/actions/ …
=> Split release.yaml to two sub workflows

.github/workflows/auto-pr.yaml, ci/auto-pr/conv_proj_version_to_branch
Currently, if we create a PR based on a release branch, Auto-PR creates a PR for the base branch in addition to other target branches. Since the target change is already merged to the base branch, it's unnecessary. This PR addresses this issue.
N/A
- Change not to create a PR for a base branch
I've tested it in my private repository.
N/A
=> Should not create PR for base branch in Auto-PR

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1267
=> Backport to branch(3) : Bump junitVersion from 5.10.0 to 5.10.1

.github/workflows/merge-release-notes.yaml
This PR adds `merge-release-notes` workflow on GitHub Actions.
The workflow merges the release notes of the community edition (`ScalarDB`) and enterprise edition (`ScalarDB Cluster`, `ScalarDB GraphQL`, `ScalarDB SQL`) into one release note.
The merged release note replaces the ScalarDB's release note body for a specified version.
This workflow is invoked manually after ScalarDB's release notes (ScalarDB, ScalarDB Cluster, ScalarDB GraphQL, ScalarDB SQL) are created due to the new version release.
This PR related to #1231
Added `merge-release-notes.yaml` to merge the release notes of ScalarDB community edition and enterprise edition.
`secrets.GH_PROJECT_ACCESS_TOKEN` used by this workflow is needed to create before running this workflow. It should include `admin:org`, `project`, `repo`, …
=> Added merging the release notes workflow

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1288
=> Backport to branch(3) : Bump org.xerial:sqlite-jdbc from 3.43.2.2 to 3.44.0.0

server/Dockerfile
This PR fixes CVE-2023-39325 and GHSA-m425-mq94-257g by upgrading grpc-health-probe to `0.4.22`. 
N/A
- Upgraded grpc-health-probe to `0.4.22`
N/A
Upgraded grpc-health-probe to fix security issues. CVE-2023-39325 GHSA-m425-mq94-257g
=> Fix CVE-2023-39325 and GHSA-m425-mq94-257g

core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
This PR fixes a bug that unintentionally changes a storage table to a transaction table using the import function. This happens because we used the consensus commit `getTableMetadata()` API to check the existence of tables, but `getTableMetadata()` returns null not only if the table does not exist but if transaction metadata does not exist.
- #931
- Check the table metadata using storage admin API
Currently, we don't have an upgrade feature from storage to transaction, but probably we can do it easily using similar logic like import and repair in the future. 
Fixed to prevent importing existing storage table
=> Fix to prevent importing existing storage table

server/Dockerfile
=> Backport to branch(3) : Fix CVE-2023-39325 and GHSA-m425-mq94-257g

server/Dockerfile
=> Backport to branch(3.10) : Fix CVE-2023-39325 and GHSA-m425-mq94-257g

server/Dockerfile
=> Backport to branch(3.9) : Fix CVE-2023-39325 and GHSA-m425-mq94-257g

server/Dockerfile
=> Backport to branch(3.8) : Fix CVE-2023-39325 and GHSA-m425-mq94-257g

server/Dockerfile
=> Backport to branch(3.7) : Fix CVE-2023-39325 and GHSA-m425-mq94-257g

server/Dockerfile
=> Backport to branch(3.6) : Fix CVE-2023-39325 and GHSA-m425-mq94-257g

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1298
=> Backport to branch(3) : Bump log4jVersion from 2.21.1 to 2.22.0

core/src/main/java/com/scalar/db/common/AbstractDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/AbstractTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/DecoratedDistributedTransaction.java, core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransaction.java
Backport of https://github.com/scalar-labs/scalardb/pull/1295
=> Backport to branch(3) : Refactor DecoratedDistributedTransaction and DecoratedTwoPhaseCommitTransaction

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1325
=> Backport to branch(3) : Bump org.xerial:sqlite-jdbc from 3.44.0.0 to 3.44.1.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1326
=> Backport to branch(3) : Bump org.apache.commons:commons-lang3 from 3.13.0 to 3.14.0

docs/api-guide.md, docs/storage-abstraction.md
Add API documentation for the `admin.repairTable(...)` method to the v3.X doc version since it was missing.
N/A
Add a section for `admin.repairTable` method to the api-guide and api-abstraction documentation.
This PR targets the `3` branch and will be backport to all 3.X release branches.
N/A
=> Add API doc for `admin.repairTable` method for v3.X

core/src/main/java/com/scalar/db/api/Admin.java, docs/api-guide.md, docs/schema-loader.md, docs/storage-abstraction.md, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java, schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
The Admin API `repairTable()` method has existed since v3.6, but its behavior has changed (cf. #1125). Also, a new `repairNamespace` method was added to the Admin API (#1107). Finally, the `--repair-all` command of the Schema Loader will not only repair table but also repair namespace.  (#1203)
This PR will update the documentation for these changes.
- #1125 
- #1107 
- #1203
- Update javadoc for the Admin API `repairTable` and `repairNamespace`
- Add sections in the api-guide and storage abstraction guide for the Admin API `repairTable` and `repairNamespace`
- Update the Schema Loader doc 
> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes after you have read …
=> Update documentation for the repair feature

core/src/main/java/com/scalar/db/api/OperationBuilder.java, core/src/main/java/com/scalar/db/api/Put.java, core/src/main/java/com/scalar/db/api/PutBuilder.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/test/java/com/scalar/db/api/PutBuilderTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/util/ProtoUtilsTest.java, docs/api-guide.md, docs/storage-abstraction.md, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
This PR disables implicit pre-read by default for `Put` operations because the feature is backward incompatible.
- https://github.com/scalar-labs/scalardb/pull/1222
- Disabled implicit pre-read by default for `Put` operations
- Modified related unit tests and integration tests 
- Revised related documents
N/A
N/A
=> Disable implicit pre-read by default for Put operations

core/src/main/java/com/scalar/db/api/OperationBuilder.java, core/src/main/java/com/scalar/db/api/Put.java, core/src/main/java/com/scalar/db/api/PutBuilder.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/test/java/com/scalar/db/api/PutBuilderTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/util/ProtoUtilsTest.java, docs/api-guide.md, docs/storage-abstraction.md, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/1336
=> Backport to branch(3) : Disable implicit pre-read by default for Put operations

.github/workflows/auto-pr.yaml
We recently observed a few times that Auto-PR workflow wasn't triggered. I asked GitHub support and they recommended the following options:
1. Use [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) event instead of [pull_request](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) event
2. Remove the current guard condition `types: closed` to mitigate the risk of failing to trigger the workflow
For 1, `pull_request_target` is more powerful. But it also introduces some security concerns. So, trying 2 would be reasonable.
N/A
This PR removes the guard condition `types: closed` to mitigate the risk of failing to invoke the workflow. It should be okay since the workflow also has …
=> Make auto-pr robust to avoid timing issue or etc

.github/workflows/auto-pr.yaml
Reverts scalar-labs/scalardb#1347
as Auto-PR workflow hasn't worked since it was merged.
=> Revert "Make auto-pr robust to avoid timing issue or etc"

docs/api-guide.md, docs/storage-abstraction.md
Backport of https://github.com/scalar-labs/scalardb/pull/1310
=> Backport to branch(3.7) : Add API doc for `admin.repairTable` method for v3.X

core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitProvider.java, core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionProvider.java
This PR adds `TRANSACTION_MANAGER_NAME` variables to `XXXConfig`, specifically for transaction managers (`ConsensusCommitConfig` and `JdbcConfig`). These variables allow us to reference the transaction manager names elsewhere.
N/A
- Added static final variable `TRANSACTION_MANAGER_NAME` to `ConsensusCommitConfig` and `JdbcConfig`
N/A
N/A
=> Add TRANSACTION_MANAGER_NAME to XXXConfig

core/src/main/java/com/scalar/db/common/TableMetadataManager.java, core/src/main/java/com/scalar/db/util/ThrowableConsumer.java, core/src/main/java/com/scalar/db/util/ThrowableFunction.java, core/src/test/java/com/scalar/db/common/TableMetadataManagerTest.java
This PR adds a utility class `ThrowableConsumer` which can be used in ScalarDB ecosystem.
N/A
- Added `ThrowableConsumer`
- Refactored `ThrowableFunction`
N/A
N/A
=> Add ThrowableConsumer

core/src/main/java/com/scalar/db/api/AuthAdmin.java
This PR adds the `getUser()` method to the `AuthAdmin` interface.
- https://github.com/scalar-labs/scalardb/pull/1318
- Added the `getUser()` method to the `AuthAdmin` interface
- Revised Javadoc
N/A
N/A
=> Add getUser() to AuthAdmin

core/src/main/java/com/scalar/db/api/AuthAdmin.java
Backport of https://github.com/scalar-labs/scalardb/pull/1380
=> Backport to branch(3) : Add getUser() to AuthAdmin

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1371
=> Backport to branch(3) : Bump dropwizardMetricsVersion from 4.2.22 to 4.2.23

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1402
=> Backport to branch(3) : Bump awssdkVersion from 2.21.0 to 2.22.3

.github/workflows/upload-artifacts.yaml
This PR fixes the issue in the release workflow. To authenticate with AWS ECR by using `configure-aws-credentials` action, we have to set `permissions` configuration according to the [document of `configure-aws-credentials`](https://github.com/aws-actions/configure-aws-credentials).
N/A
* Update release workflows to push container images.
N/A
N/A
=> Add "permissions" in release workflow to use configure-aws-credentials

.github/workflows/upload-artifacts.yaml
This PR reverts to PR #1411. Sorry, I had a misunderstanding about the current workflow's structures... 🙇‍♀️
The workflow `upload-artifacts.yaml` is called from the parent workflow `release.yaml`. And the parent workflow `release.yaml` has the configuration of `permissions`.
So, the `upload-artifacts.yaml` can run with the same `permissions` settings that are inherited from `release.yaml`. Therefore, we don't need to set `permissions` on the `upload-artifacts.yaml` side explicitly.
FYI: The action ran properly when we released `v3.10.2` yesterday, without the fixes of #1411. Also from this log, we can see that we don't need the fix of #1411.
https://github.com/scalar-labs/scalardb/actions/runs/7322292094
#1411
* Update (revert) `upload-artifacts.yaml` file.
N/A
N/A
=> Revert PR #1411

docs/scalardb-supported-databases.md
This PR update the supported databases for ScalarDB 3.11.
N/A
- Added supported databases for ScalarDB 3.11
N/A
N/A
=> Update supported databases

docs/requirements.md
This PR adds a requirement for privileges of underlying databases.
- scalar-labs/scalardb-sql#392
- Update the requirement document regarding privileges of underlying databases
N/A
Added requirement for privileges of underlying databases.
=> Add a requirement for privileges of underlying databases

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1429
=> Backport to branch(3) : Bump org.assertj:assertj-core from 3.24.2 to 3.25.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1428
=> Backport to branch(3) : Bump log4jVersion from 2.22.0 to 2.22.1

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1433
=> Backport to branch(3) : Bump org.assertj:assertj-core from 3.25.0 to 3.25.1

core/src/main/java/com/scalar/db/config/ConfigUtils.java, core/src/test/java/com/scalar/db/config/ConfigUtilsTest.java
This PR adds a method `getStringFromFilePath()` to the `ConfigUtils` class. This method gets a configuration value from a file.
N/A
- Added `getStringFromFilePath()` to `ConfigUtils`
N/A
N/A
=> Add getStringFromFilePath() to ConfigUtils

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
I faced NPE when testing ScalarDB using PostgreSQL as a storage and a connection issue happened. I checked what occurred by adding a debug log.
- RdbEnginePostgresql.java
```java
@Override
public boolean isUndefinedTableError(SQLException e) {
logger.info("[========= DEBUG ===========]", e);
logger.info("[========= DEBUG ===========] SQLState:{}", e.getSQLState());
// 42P01: undefined_table
return e.getSQLState().equals("42P01");
}
```
```
[main] INFO com.scalar.db.storage.jdbc.RdbEnginePostgresql - [========= DEBUG ===========]
java.sql.SQLException: Cannot create PoolableConnectionFactory (Connection to postgresql:5442 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.)                                              
at …
```
=> Avoid NPE when checking SQLState in JDBC storage

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
Backport of https://github.com/scalar-labs/scalardb/pull/1442
=> Backport to branch(3.11) : Avoid NPE when checking SQLState in JDBC storage

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
Backport of https://github.com/scalar-labs/scalardb/pull/1442
=> Backport to branch(3.10) : Avoid NPE when checking SQLState in JDBC storage

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
Backport of https://github.com/scalar-labs/scalardb/pull/1442
=> Backport to branch(3) : Avoid NPE when checking SQLState in JDBC storage

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
Backport of https://github.com/scalar-labs/scalardb/pull/1442
=> Backport to branch(3.9) : Avoid NPE when checking SQLState in JDBC storage

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1449
=> Backport to branch(3) : Bump awssdkVersion from 2.22.3 to 2.23.3

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1454
=> Backport to branch(3) : Bump org.xerial:sqlite-jdbc from 3.44.1.0 to 3.45.0.0

docs/api-guide.md, docs/storage-abstraction.md
When I read the document to know how to specify inclusive/exclusive with ScanBuilder's `start()` and `end()`, I noticed the document didn't mention it. It would be helpful for users if the document shows how to specify `inclusive` param.
N/A
This PR added the usage and comment about `inclusive` param of `ScanBuilder`'s `start()` and `end()`.
Maybe I should've added some sentences about how to specify the parameter not just adding the comments (sorry, I'm lazy). Feel free to suggest changes if needed.
None
=> Add usages and comments about the inclusive param of `ScanBuilder`'s `start()` and `end()`

docs/api-guide.md, docs/storage-abstraction.md
=> Backport to branch(3) : Add usages and comments about the inclusive param of `ScanBuilder`'s `start()` and `end()`

docs/api-guide.md, docs/storage-abstraction.md
=> Backport to branch(3.11) : Add usages and comments about the inclusive param of `ScanBuilder`'s `start()` and `end()`

docs/api-guide.md, docs/storage-abstraction.md
=> Backport to branch(3.10) : Add usages and comments about the inclusive param of `ScanBuilder`'s `start()` and `end()`

docs/api-guide.md, docs/storage-abstraction.md
=> Backport to branch(3.9) : Add usages and comments about the inclusive param of `ScanBuilder`'s `start()` and `end()`

docs/api-guide.md, docs/storage-abstraction.md
=> Backport to branch(3.8) : Add usages and comments about the inclusive param of `ScanBuilder`'s `start()` and `end()`

core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosUtils.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosConfigTest.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosUtilsTest.java, docs/configurations.md
This PR makes Cosmos DB consistency level configurable by the property `scalar.db.cosmos.consistency_level` in the Cosmos DB adapter. `STRONG` or `BOUNDED_STALENESS` can be specified.
N/A
- Made Cosmos DB consistency level configurable
N/A
Made Cosmos DB consistency level configurable in the Cosmos DB adapter. Users can change the consistency level used for Cosmos DB operations by specifying the property `scalar.db.cosmos.consistency_level`. `STRONG` or `BOUNDED_STALENESS` can be specified.
=> Make Cosmos DB consistency level configurable

.github/workflows/vuln-check.yaml
Backport of https://github.com/scalar-labs/scalardb/pull/1473
=> Backport to branch(3) : Bump slackapi/slack-github-action from 1.24.0 to 1.25.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1474
=> Backport to branch(3) : Bump dropwizardMetricsVersion from 4.2.24 to 4.2.25

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1475
=> Backport to branch(3) : Bump org.assertj:assertj-core from 3.25.1 to 3.25.2

core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/UncommittedRecordException.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
Currently, when uncommitted records are read while executing implicit pre-read, lazy recovery is not performed, which is unexpected behavior. This PR addresses issue.
- https://github.com/scalar-labs/scalardb/pull/1222
- Make changes to perform lazy recovery when uncommitted records are read while executing implicit pre-read.
N/A
Fixed a bug where lazy recovery is not performed when uncommitted records are read while executing implicit pre-read.
=> Should perform lazy recovery in implicit pre-read

ci/vuln-check/find_latest_release
We made [the vulnerability check related script skip unexpected versions](https://github.com/scalar-labs/scalardb/pull/1452). But it was incomplete since the unexpected version `v3.11.0-alpha.1` contains another dot and it added a garbage version. The error handling should be enhanced.
https://github.com/scalar-labs/scalardb/pull/1452
This PR updates `ci/vuln-check/find_latest_release` to skip an unexpected version if any invalid version unit is included.
None
N/A
=> [vuln-check-workflow] Fix incomplete skip of unexpected versions

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1487
=> Backport to branch(3) : Bump junitVersion from 5.10.1 to 5.10.2

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1489
=> Backport to branch(3) : Bump org.xerial:sqlite-jdbc from 3.45.0.0 to 3.45.1.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1488
=> Backport to branch(3) : Bump org.assertj:assertj-core from 3.25.2 to 3.25.3

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1497
=> Backport to branch(3) : Bump awssdkVersion from 2.23.3 to 2.24.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1519
=> Backport to branch(3) : Bump org.eclipse.jetty:jetty-servlet from 9.4.53.v20231009 to 9.4.54.v20240208

server/Dockerfile
=> Backport to branch(3) : Bump scalar-labs/jre8 from 1.1.15 to 1.1.16 in /server

server/Dockerfile
=> Backport to branch(3.12) : Bump scalar-labs/jre8 from 1.1.15 to 1.1.16 in /server

server/Dockerfile
=> Backport to branch(3.11) : Bump scalar-labs/jre8 from 1.1.15 to 1.1.16 in /server

server/Dockerfile
=> Backport to branch(3.10) : Bump scalar-labs/jre8 from 1.1.15 to 1.1.16 in /server

server/Dockerfile
=> Backport to branch(3.9) : Bump scalar-labs/jre8 from 1.1.15 to 1.1.16 in /server

server/Dockerfile
=> Backport to branch(3.8) : Bump scalar-labs/jre8 from 1.1.15 to 1.1.16 in /server

schema-loader/Dockerfile
=> Backport to branch(3) : Bump scalar-labs/jre8 from 1.1.15 to 1.1.16 in /schema-loader

schema-loader/Dockerfile
=> Backport to branch(3.12) : Bump scalar-labs/jre8 from 1.1.15 to 1.1.16 in /schema-loader

schema-loader/Dockerfile
=> Backport to branch(3.10) : Bump scalar-labs/jre8 from 1.1.15 to 1.1.16 in /schema-loader

schema-loader/Dockerfile
=> Backport to branch(3.9) : Bump scalar-labs/jre8 from 1.1.15 to 1.1.16 in /schema-loader

schema-loader/Dockerfile
=> Backport to branch(3.8) : Bump scalar-labs/jre8 from 1.1.15 to 1.1.16 in /schema-loader

.github/workflows/ci.yaml, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraJapaneseIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosJapaneseIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoJapaneseIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseJapaneseIntegrationTest.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageJapaneseIntegrationTestBase.java
Currently, in the JDBC adapter, we use a hard-coded collation for SQL Server when creating tables. However, we've encountered an issue where Japanese cannot be used with the hard-coded collation in SQL Server. To resolve this, this PR removes the hard-coded collation for SQL Server. For consistency, it also eliminates the hard-coded collation for MySQL. As a result, the collation configured in the database will be used when creating tables.
N/A
- Removed the default collation for SQL Server and MySQL in JDBC adapter.
- Add an integration test for Japanese.
N/A
Removed the hard-coded collation for MySQL and SQL Server in the JDBC adapter. As a result, the collation configured in the underlying database will be used when creating tables.
=> Remove hard-coded collation in JDBC adapter

build.gradle
=> Backport to branch(3.9) : Bump org.postgresql:postgresql from 42.6.0 to 42.7.2

build.gradle
=> Backport to branch(3.8) : Bump org.postgresql:postgresql from 42.5.1 to 42.7.2

README.md, docs/getting-started-kotlin/build.gradle.kts, docs/getting-started/build.gradle, docs/index.md
Backport of https://github.com/scalar-labs/scalardb/pull/1559
=> Backport to branch(3) : Update ScalarDB dependency version to 3.12.1

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1562
=> Backport to branch(3) : Bump com.oracle.database.jdbc:ojdbc8 from 21.11.0.0 to 21.13.0.0

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh
This PR updates the CI (integration test) for SQL Server.
At this time, we are using a superuser (full privilege user) to test each backend DB. And, we state `ScalarDB basically requires a fully privileged account to access the underlying databases` in our document.
However, in some enterprise projects, the fully privileged user is not acceptable for some security reasons. For example, we got an inquiry `Q. What privileges do we need when we use MS SQL Server as a backend DB of ScalarDB?` from actual users.
So, we discussed and decided to test the backend DB by using no superuser one by one.
As a first step, I updated the SQL Server test in this PR.
N/A
* Add new script to create no superuser account in the backend SQL Server …
=> Update CI to use no superuser for SQL Server test

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.12) : Update CI to use no superuser for SQL Server test

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.9) : Update CI to use no superuser for SQL Server test

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.8) : Update CI to use no superuser for SQL Server test

ci/no-superuser/create-no-superuser-sqlserver.sh
This PR update the username of `SA` that is a `root` user of SQL Server.
Before we can use `SA` as a username because SQL Server treat username with case-insensitive.
However, recently we updated CI to set `Japanese_BIN2` as a collation of SQL Server.
As a result, SQL Server treat username with case-sensitive.
So, if we use `SA` as a username, the authentication of SQL Server failed.
To fix this issue, I updated username from `SA` to `sa`.
* https://github.com/scalar-labs/scalardb/actions/runs/8073265726/job/22056629519
* Update `create-no-superuser-sqlserver.sh` to use username `sa`.
I tested SQL Server with collation `Japanese_BIN2` as follows.
* Run SQL Server with collation `Japanese_BIN2`.
```console
docker run -d --name sqlserver22 -e "MSSQL_PID=Express" -e …
```
=> Use username "sa" instead of "SA" in CI of SQL Server

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3) : Use username "sa" instead of "SA" in CI of SQL Server

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.12) : Use username "sa" instead of "SA" in CI of SQL Server

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.11) : Use username "sa" instead of "SA" in CI of SQL Server

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.10) : Use username "sa" instead of "SA" in CI of SQL Server

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.9) : Use username "sa" instead of "SA" in CI of SQL Server

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.8) : Use username "sa" instead of "SA" in CI of SQL Server

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1583
=> Backport to branch(3) : Bump awssdkVersion from 2.24.0 to 2.25.1

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1582
=> Backport to branch(3) : Bump org.apache.commons:commons-dbcp2 from 2.11.0 to 2.12.0

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3) : Update CI to fix issues of SQL Server integration test

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1605
=> Backport to branch(3) : Bump log4jVersion from 2.23.0 to 2.23.1

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1611
=> Backport to branch(3) : Bump org.xerial:sqlite-jdbc from 3.45.1.0 to 3.45.2.0

README.md, docs/getting-started-kotlin/build.gradle.kts, docs/getting-started/build.gradle, docs/index.md
Backport of https://github.com/scalar-labs/scalardb/pull/1617
=> Backport to branch(3) : Update ScalarDB dependency version to 3.12.2

.github/workflows/ci.yaml
To reduce the CI time, we will implement the following measures:
1. Remove the CI trigger for branch pushes.
2. Enable "Require branches to be up to date before merging" in GitHub branch protection rules.
After implementing these changes, we need to ensure that a branch for a PR is up to date and run CI for it before merging it (2). As a result, CI does not need to be run after merging into the main branch, support branches, or release branches (1).
This PR does the step 1.
N/A
- Removed the CI trigger for branch pushes.
N/A
N/A
=> Remove the CI trigger for branch pushes

.github/workflows/ci.yaml
=> Backport to branch(3.12) : Remove the CI trigger for branch pushes

.github/workflows/ci.yaml
=> Backport to branch(3.11) : Remove the CI trigger for branch pushes

.github/workflows/ci.yaml
=> Backport to branch(3.10) : Remove the CI trigger for branch pushes

.github/workflows/ci.yaml
=> Backport to branch(3.9) : Remove the CI trigger for branch pushes

.github/workflows/ci.yaml
=> Backport to branch(3.8) : Remove the CI trigger for branch pushes

core/build.gradle
=> Backport to branch(3.9) : Use AWS SDK BOM

core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
=> Backport to branch(3.9) : Fix NullPointerException in EXTRA_READ validation

core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
=> Backport to branch(3.8) : Fix NullPointerException in EXTRA_READ validation

schema-loader/build.gradle
After https://github.com/scalar-labs/scalardb/pull/1622, the Schema Loader fat jar was unintentionally published to Maven Central. This PR addresses the issue.
- https://github.com/scalar-labs/scalardb/pull/1622
- Made the Schema Loader fat jar not published when running `publish` or `publishToMavenLocal`.
N/A
N/A
=> Should not publish Schema Loader fat jar to Maven central

schema-loader/build.gradle
=> Backport to branch(3) : Should not publish Schema Loader fat jar to Maven central

schema-loader/build.gradle
=> Backport to branch(3.12) : Should not publish Schema Loader fat jar to Maven central

schema-loader/build.gradle
=> Backport to branch(3.11) : Should not publish Schema Loader fat jar to Maven central

schema-loader/build.gradle
=> Backport to branch(3.10) : Should not publish Schema Loader fat jar to Maven central

schema-loader/build.gradle
=> Backport to branch(3.9) : Should not publish Schema Loader fat jar to Maven central

schema-loader/build.gradle
=> Backport to branch(3.8) : Should not publish Schema Loader fat jar to Maven central

core/src/main/java/com/scalar/db/util/groupcommit/BackgroundWorker.java, core/src/main/java/com/scalar/db/util/groupcommit/DelayedSlotMoveWorker.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCleanupWorker.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupSizeFixWorker.java, core/src/test/java/com/scalar/db/util/groupcommit/BackgroundWorkerTest.java, core/src/test/java/com/scalar/db/util/groupcommit/DelayedSlotMoveWorkerTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1641
=> Backport to branch(3) : Use the priority queue for DelayedSlotMoveWorker to easily reduce the latency to be handled in `util/groupcommit`

core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitMonitor.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitter.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupManager.java, core/src/main/java/com/scalar/db/util/groupcommit/Metrics.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterConcurrentTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupManagerTest.java
If an application using the group commit feature doesn't abort in-flight transactions (in-flight `slots` in terms of the group commit package) that failed before commit phase (before calling `ready()` method in terms of the group commit package), the client threads that have those failed in-flight transactions will wait until `old-group-timeout` is triggered even if `close()` is called. What if the application recreates the transaction manager including the GroupCommitter while there are failed in-flight transactions? The new GroupCommitter doesn't have any information about the in-flight transactions, resulting in that no one aborts them and the clients will wait forever. This case might sounds very weird, but https://github.com/scalar-labs/scalar-jepsen tests this type of situation, …
=> Wait until all groups get done when GroupCommitter is closed (was "Abort all in-flight groups on close in the group commit")

core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitMonitor.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitter.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupManager.java, core/src/main/java/com/scalar/db/util/groupcommit/Metrics.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterConcurrentTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupManagerTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1650
=> Backport to branch(3) : Wait until all groups get done when GroupCommitter is closed (was "Abort all in-flight groups on close in the group commit")

core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
This PR modifies the code to execute lazy recovery for put and delete operations. In put and delete operations, the implicit pre-read can be executed when the mutation condition is specified for the operations. In such cases, when an uncommitted record is read in the implicit pre-read, we should execute lazy recovery. This PR addresses this issue.
N/A
- Modified the code to execute lazy recovery for put and delete operations when an uncommitted record is read in the implicit pre-read.
N/A
Fixed a bug where lazy recovery was not executed for the implicit pre-read of put and delete operations.
=> Should execute lazy recovery for Put and Delete in Consensus Commit

core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitter.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupManagerTest.java, core/src/test/java/com/scalar/db/util/groupcommit/NormalGroupTest.java
Some warnings showed and a test failure happened in https://github.com/scalar-labs/scalardb/actions/runs/8733852248/job/23963337908. The warnings should be removed and the flaky test should be fixed. 
- https://github.com/scalar-labs/scalardb/pull/1650
- 
- Fix the warnings by removing the unused variables
- Fix the flaky test by increasing the timeout
None
N/A
=> Fix flaky test and warnings in group commit

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1686
=> Backport to branch(3) : Bump org.xerial:sqlite-jdbc from 3.45.2.0 to 3.45.3.0

.github/workflows/vuln-check.yaml
Backport of https://github.com/scalar-labs/scalardb/pull/1688
=> Backport to branch(3) : Bump slackapi/slack-github-action from 1.25.0 to 1.26.0

core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminImportTableIntegrationTestWithJdbcDatabase.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTableIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderImportIntegrationTest.java, integration-test/build.gradle, integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminImportTableIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminRepairIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageColumnValueIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageConditionalMutationIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageCrossPartitionScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageJapaneseIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultipleClusteringKeyScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultiplePartitionKeyIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageSecondaryIndexIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageSingleClusteringKeyScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageSinglePartitionKeyIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageWithReservedKeywordIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminImportTableIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminRepairIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionCrossPartitionScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionCrossPartitionScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderImportIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
I found some resource leaks including potential ones while executing `integrationTestJdbc`.  Resource leaks can cause unexpected exceptions (e.g., no available connection) and make it difficult to find actual problems of the implementation. This PR is to fix the resource leaks.
None
This PR contains the following changes:
- Improve the error handling of the clean-up operations in `@AfterAll` and `@AfterEach` annotated methods
- Release the resources that are not released
None
N/A
=> Fix resource leaks in `integrationTestJdbc`

core/src/main/java/com/scalar/db/api/OperationBuilder.java
Using interfaces in `OperationBuilder` simplifies the code and allows us to remove redundant code. It's worth making `OperationBuilder` public.
N/A
- Made `OperationBuilder` public.
N/A
N/A
=> Make OperationBuilder public

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1712
=> Backport to branch(3) : Bump com.azure:azure-cosmos from 4.58.0 to 4.59.0

core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java, core/src/test/java/com/scalar/db/storage/jdbc/RdbEngineOracleTest.java, core/src/test/java/com/scalar/db/storage/jdbc/RdbEnginePostgresqlTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1723
=> Backport to branch(3) : Optimization: Avoid creating an internal index in RDBMS after creating ScalarDB table as much as possible

integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitCrossPartitionScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitCrossPartitionScanIntegrationTestBase.java
Some integration tests sometimes fail because they use the same coordinator and metadata table names. I noticed this happened for Dynamo integration test since they run in parallel, cf. https://github.com/scalar-labs/scalardb/actions/runs/9202754667
The CosmosDB integration test could fail in the same manner, too.
https://github.com/scalar-labs/scalardb/pull/1682
Use a unique namespace prefix to avoid conflicts between table names used by different integration test classes.
N/A
N/A
=> Fix integration test failure because of conflicting use of table names 

integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitCrossPartitionScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitCrossPartitionScanIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/1762
=> Backport to branch(3) : Fix integration test failure because of conflicting use of table names 

core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitCrossPartitionScanIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosCrossPartitionScanIntegrationTest.java
Currently, some integration tests for Cosmos DB are failing occasionally due to table name conflicts. To avoid these conflicts, we should add a prefix to the namespaces for the failed integration tests. This PR addresses the issue.
- https://github.com/scalar-labs/scalardb/pull/1682
- Add a prefix to namespaces for Cosmos DB integration tests.
N/A
N/A
=> Should add prefix to namespaces for Cosmos DB integration tests

core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitCrossPartitionScanIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosCrossPartitionScanIntegrationTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1767
=> Backport to branch(3) : Should add prefix to namespaces for Cosmos DB integration tests

core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransactionManager.java
This PR adds `DecoratedDistributedTransactionManager` and `DecoratedTwoPhaseCommitTransactionManager`. They are abstract classes of decorator classes for `DistributedTransactionManager` and `TwoPhaseCommitTransactionManager`.
N/A
- Added `DecoratedDistributedTransactionManager` and `DecoratedTwoPhaseCommitTransactionManager`.
N/A
N/A
=> Add DecoratedDistributedTransactionManager and DecoratedTwoPhaseCommitTransactionManager

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
This PR changes the hard-coded password for the Oracle user to a more secure one in the JDBC adapter. The primary goal of this change is to avoid violating password policies.
N/A
- Changed the hard-coded password for the Oracle user to a more secure one in the JDBC adapter.
N/A
Changed the hard-coded password for the Oracle user to a more secure one in the JDBC adapter.
=> Change hard-coded password for Oracle user in JDBC adapter

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1789
=> Backport to branch(3) : Bump org.xerial:sqlite-jdbc from 3.45.3.0 to 3.46.0.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1792
=> Backport to branch(3) : Bump com.oracle.database.jdbc:ojdbc8 from 21.13.0.0 to 21.14.0.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1791
=> Backport to branch(3) : Bump org.assertj:assertj-core from 3.25.3 to 3.26.0

buildSrc/src/main/java/com/scalar/db/JdkConfigurationPlugin.java
Changes introduced by #1749 made the Gradle build require having a JDK 8 (temurin) installed on the system. This forced users cloning ScalarDB repository and using the master branch to have installed JDK 8 (temurin), which is inconvenient. 
This PR reverts to the previous behavior, which is not to force Gradle to use a specific JDK. Users can use any JDK they desire to build ScalarDB. 
Additionally, #1749 added Gradle project properties to configure Gradle to use a specific JDK version and vendor. This is left unchanged.
- #1749 
Updated `JdkConfigurationPlugin` to not require Java-related tasks to use JDK 8 (temurin). Java-related tasks will used by default the JDK used by Gradle.
> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or …
=> Revert behavior : the Gradle build does not require to use JDK 8 (temurin)

core/build.gradle
Recently, the Cosmos DB integration test is very flaky, and it looks like one of the reason is the lack of the heap memory. This PR addresses this issue and increases the heap size for the Cosmos DB integration test.
N/A
- Increased the heap size for the Cosmos DB integration test
N/A
N/A
=> Increase heap size for Cosmos DB integration test

.github/workflows/ci.yaml
We experienced [the build issue of the example project for getting started](https://github.com/scalar-labs/scalardb/pull/1852). This kind of issue likely happens without continuous build test. This PR adds tests for that.
- https://github.com/scalar-labs/scalardb/pull/1852
Add GitHub Actions Jobs to build the two example projects for getting started.
None
N/A
=> Add build tests for `getting started` example projects

.github/workflows/ci.yaml
=> Backport to branch(3.11) : Add build tests for `getting started` example projects

.github/workflows/ci.yaml
=> Backport to branch(3.9) : Add build tests for `getting started` example projects

.github/workflows/ci.yaml
=> Backport to branch(3.8) : Add build tests for `getting started` example projects

core/src/main/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitter.java
`CoordinatorGroupCommitKeyManipulator` contains various logics (e.g., determining whether a given string is a full key) about the group commit related keys. The logics are sometimes required in other projects, but the visibility of the class is not `public` in the current implementation. This PR changes the visibility to `public`.
None
- Change the visibility of `CoordinatorGroupCommitKeyManipulator` to public
None
N/A
=> Make CoordinatorGroupCommitKeyManipulator public to reuse the logic in other projects

core/src/main/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitter.java
Backport of https://github.com/scalar-labs/scalardb/pull/1864
=> Backport to branch(3) : Make CoordinatorGroupCommitKeyManipulator public to reuse the logic in other projects

ci/dockerfile_lint.sh, schema-loader/Dockerfile, server/Dockerfile
=> Backport to branch(3.8) : Use eclipse-temurin base image in Dockerfile

ci/dockerfile_lint.sh, schema-loader/Dockerfile, server/Dockerfile
=> Backport to branch(3.9) : Use eclipse-temurin base image in Dockerfile

ci/dockerfile_lint.sh, schema-loader/Dockerfile, server/Dockerfile
=> Backport to branch(3.10) : Use eclipse-temurin base image in Dockerfile

ci/dockerfile_lint.sh, schema-loader/Dockerfile, server/Dockerfile
=> Backport to branch(3.11) : Use eclipse-temurin base image in Dockerfile

ci/dockerfile_lint.sh, schema-loader/Dockerfile, server/Dockerfile
=> Backport to branch(3.12) : Use eclipse-temurin base image in Dockerfile

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1893
=> Backport to branch(3) : Bump dropwizardMetricsVersion from 4.2.25 to 4.2.26

.github/workflows/ci.yaml, core/build.gradle
Recent Cosmos DB integration tests are slow and unstable. We also need to manage Cosmos DB related resources for the integration tests. This PR uses [the Azure Cosmos DB emulator](https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-develop-emulator) instead using actual Cosmos DB.
None
- In the GitHub Actions workflow:
- Launch the Cosmos DB emulator in `windows-latest` image
- Install TLS certification extracted from the emulator in the Windows VM 
- Run the integration tests using the emulator
- Reduce the concurrency of the integration test from 3 to 1 to avoid tentative errors as much as possible
> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes after …
=> Use Cosmos DB emulator for the integration tests

core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosCrossPartitionScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java
After merging https://github.com/scalar-labs/scalardb/pull/1909, we observed the integration test often failed with the Cosmos DB emulator due to failing to create a namespace.
https://github.com/scalar-labs/scalardb/blob/6d43a3666ffccfedcc35f9c077a85c24800b0283/integration-test/src/main/java/com/scalar/db/api/DistributedStorageCrossPartitionScanIntegrationTestBase.java#L165
I noticed `CosmosCrossPartitionScanIntegrationTest` used the default thread number (10). So, this PR limits it to 1 as well as other tests.
- https://github.com/scalar-labs/scalardb/pull/1909
- Reduce the concurrency for DDL operations in `CosmosCrossPartitionScanIntegrationTest` from 10 to 3
> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on …
=> Reduce the number of concurrent DDLs from 10 to 1 for Cosmos DB in the integration tests

core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultipleClusteringKeyScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultiplePartitionKeyIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/1920 to branch(3.12).
Fixes https://github.com/scalar-labs/scalardb/issues/1924
=> Backport to branch(3.12): Reduce the number of concurrent DDLs from 10 to 1 for Cosmos DB in the integration tests

core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosCrossPartitionScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1920
=> Backport to branch(3) : Reduce the number of concurrent DDLs from 10 to 1 for Cosmos DB in the integration tests

core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultipleClusteringKeyScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultiplePartitionKeyIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/1920 to branch(3.11).
=> Backport to branch(3.11): Reduce the number of concurrent DDLs from 10 to 1 for Cosmos DB in the integration tests

core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultipleClusteringKeyScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultiplePartitionKeyIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/1920 to branch(3.10).
=> Backport to branch(3.10): Reduce the number of concurrent DDLs from 10 to 1 for Cosmos DB in the integration tests

core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultipleClusteringKeyScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultiplePartitionKeyIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/1920 to branch(3.9).
=> Backport to branch(3.9): Reduce the number of concurrent DDLs from 10 to 1 for Cosmos DB in the integration tests

core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultipleClusteringKeyScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultiplePartitionKeyIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/1920 to branch(3.8).
=> Backport to branch(3.8): Reduce the number of concurrent DDLs from 10 to 1 for Cosmos DB in the integration tests

.github/workflows/ci.yaml
The CosmosDB CI fails when using JDK11+ as the runtime for the integration test. This is because the way to import TLS/SSL certificate in the Java "cacerts" keystore is not supported for JDK11+.
- #1909 
- For the CosmosDB CI, based on the integration test Java runtime version, it uses the correct syntax to import TLS/SSL certificate in the Java "cacerts" keystore.
N/A 
N/A
=> Fix CosmosDB CI when running integration test with JDK11+

.github/workflows/ci.yaml
=> Backport to branch(3) : Fix CosmosDB CI when running integration test with JDK11+

.github/workflows/ci.yaml
=> Backport to branch(3.12) : Fix CosmosDB CI when running integration test with JDK11+

.github/workflows/ci.yaml
=> Backport to branch(3.11) : Fix CosmosDB CI when running integration test with JDK11+

.github/workflows/ci.yaml
=> Backport to branch(3.10) : Fix CosmosDB CI when running integration test with JDK11+

.github/workflows/ci.yaml
=> Backport to branch(3.9) : Fix CosmosDB CI when running integration test with JDK11+

.github/workflows/ci.yaml
=> Backport to branch(3.8) : Fix CosmosDB CI when running integration test with JDK11+

core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminRepairTableIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitCosmosEnv.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitCrossPartitionScanIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitNullMetadataIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitSpecificIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminRepairTableIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosColumnValueIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosConditionalMutationIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosCrossPartitionScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosEnv.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosJapaneseIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSecondaryIndexIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSingleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSinglePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosWithReservedKeywordIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/SingleCrudOperationTransactionAdminIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/SingleCrudOperationTransactionIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitSpecificIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithCosmos.java
Backport of https://github.com/scalar-labs/scalardb/pull/1918 to branch(3)
=> Backport to branch(3): Remove unnecessary `scalardb.cosmos.database_prefix` property

core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminRepairTableIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitNullMetadataIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitSpecificIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminRepairTableIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosColumnValueIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosConditionalMutationIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosEnv.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosJapaneseIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSecondaryIndexIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSingleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSinglePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosWithReservedKeywordIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitSpecificIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithCosmos.java
Backport of https://github.com/scalar-labs/scalardb/pull/1918 to branch(3.12)
=> Backport to branch(3.12): Remove unnecessary `scalardb.cosmos.database_prefix` property

core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminRepairTableIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitNullMetadataIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitSpecificIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminRepairTableIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosColumnValueIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosConditionalMutationIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosEnv.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSecondaryIndexIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSingleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSinglePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosWithReservedKeywordIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitSpecificIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithCosmos.java
Backport of https://github.com/scalar-labs/scalardb/pull/1918 to branch(3.11)
=> Backport to branch(3.11): Remove unnecessary `scalardb.cosmos.database_prefix` property

core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminRepairTableIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitNullMetadataIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitSpecificIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminRepairTableIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosColumnValueIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosConditionalMutationIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosEnv.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSecondaryIndexIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSingleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSinglePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosWithReservedKeywordIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitSpecificIntegrationTestWithCosmos.java
Backport of https://github.com/scalar-labs/scalardb/pull/1918 to branch(3.10)
=> Backport to branch(3.10): Remove unnecessary `scalardb.cosmos.database_prefix` property

core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminRepairTableIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitSpecificIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminRepairTableIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosColumnValueIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosConditionalMutationIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosEnv.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSecondaryIndexIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSingleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSinglePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosWithReservedKeywordIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitSpecificIntegrationTestWithCosmos.java
Backport of https://github.com/scalar-labs/scalardb/pull/1918 to branch(3.9)
=> Backport to branch(3.9): Remove unnecessary `scalardb.cosmos.database_prefix` property

core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminRepairTableIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitSpecificIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminRepairTableIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosColumnValueIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosConditionalMutationIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosEnv.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSecondaryIndexIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSingleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSinglePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosWithReservedKeywordIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitSpecificIntegrationTestWithCosmos.java
Backport of https://github.com/scalar-labs/scalardb/pull/1971
=> Backport to branch(3.8) : Backport to branch(3.9): Remove unnecessary `scalardb.cosmos.database_prefix` property

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1922
=> Backport to branch(3) : Bump software.amazon.awssdk:bom from 2.25.1 to 2.26.5

build.gradle
Integration tests [fail ](https://github.com/scalar-labs/scalardb/actions/runs/9594384574) when using Java 21 as the runtime because the `net.bytebuddy:byte-buddy` library current version is incompatible with Java 21. This library is a transitive dependency of `AsserJ` and `Mockito`. 
This PR updates this dependency to a version that supports Java 21.
N/A
I updated `AsserJ` so that its transitive dependency `net.bytebuddy:byte-buddy` is updated to a version that supports Java 21.
- CI run without the fix with Java 21 as runtime: …
=> [3.7~3.11] Fix error in integration test with Java 21 as runtime

server/Dockerfile
This PR fixes CVE-2024-24790, CVE-2023-45283, and CVE-2023-45288 by bumping up `grpc_health_probe` to `v0.4.28`.
N/A
- Bumped up `grpc_health_probe` to `v0.4.28`.
N/A
Upgraded `grpc_health_probe` to fix security issues. CVE-2024-24790, CVE-2023-45283, and CVE-2023-45288
=> Fix CVE-2024-24790, CVE-2023-45283, and CVE-2023-45288

server/Dockerfile
=> Backport to branch(3) : Fix CVE-2024-24790, CVE-2023-45283, and CVE-2023-45288

server/Dockerfile
=> Backport to branch(3.12) : Fix CVE-2024-24790, CVE-2023-45283, and CVE-2023-45288

server/Dockerfile
=> Backport to branch(3.11) : Fix CVE-2024-24790, CVE-2023-45283, and CVE-2023-45288

server/Dockerfile
=> Backport to branch(3.10) : Fix CVE-2024-24790, CVE-2023-45283, and CVE-2023-45288

server/Dockerfile
=> Backport to branch(3.9) : Fix CVE-2024-24790, CVE-2023-45283, and CVE-2023-45288

server/Dockerfile
=> Backport to branch(3.8) : Fix CVE-2024-24790, CVE-2023-45283, and CVE-2023-45288

core/src/main/java/com/scalar/db/api/TableMetadata.java, schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java, schema-loader/src/test/java/com/scalar/db/schemaloader/TableSchemaTest.java
This PR adds support for encrypted columns to Schema Loader. With this change, users can specify the `ENCRYPTED` flag in the column definition as follows:
```json
{
"sample_db.sample_table": {
"partition-key": [
"c1"
],
"clustering-key": [
"c4 ASC",
"c6 DESC"
],
"columns": {
"c1": "INT",
"c2": "TEXT ENCRYPTED",
"c3": "BLOB",
"c4": "INT",
"c5": "BOOLEAN ENCRYPTED",
"c6": "INT"
}
}
}
```
In the above example, the `ENCRYPTED` flag is specified for the `c2` and `c5` columns:
- https://github.com/scalar-labs/scalardb/pull/1907
- Added support for encrypted columns to Schema Loader.
N/A
Added support for encrypted columns to Schema Loader.
=> Support encrypted columns in Schema Loader

core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java, core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageConfigTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1486
=> Backport to branch(3) : Allow to specify global properties for all storages in multi-storage

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1977
CI check with Java 21: https://github.com/scalar-labs/scalardb/actions/runs/9705718888
=> Backport to branch (3.9), [3.7~3.11] Fix error in integration test with Java 21 as runtime

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1977
CI check with Java 21: https://github.com/scalar-labs/scalardb/actions/runs/9705747417
=> Backport to branch (3.8), [3.7~3.11] Fix error in integration test with Java 21 as runtime

core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderImportIntegrationTest.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java, docs/schema-loader.md, integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderImportIntegrationTestBase.java
I found that the current implementation of the import-table feature could access tables in other namespace that have the same table name when using MySQL storage. For example, in the following situation, the metadata of the columns `pk_unexpected` and `col_unexpected` of `ns2.tbl1` are handled and the import-table feature fails due to unsupported data types.
| namespace | table | column |
|----|----|----|
| ns1 | tbl1 | pk1 INT |
|  |  | col2 TEXT |
| ns1 | tbl2 | pk2 INT |
|  |  | col2 TEXT |
| ns2 | tbl1 | pk_unexpected DATE |
|  |  | col_unexpected JSON |
https://bugs.mysql.com/bug.php?id=94223
> Actually, it was never working in c/J, schemaPattern is ignored.
This comment fits what I observed. And [the implementation](https://github.com/mysql/mysql-connector-j/blob/release/8.x/src/main …
=> Fix a bug that the importing table feature accesses tables in other namespace that have the same table name with MySQL storage

build.gradle
Backport of #1977 
CI check with Java 21: https://github.com/scalar-labs/scalardb/actions/runs/9705672866
=> Backport to branch (3.10), [3.7~3.11] Fix error in integration test with Java 21 as runtime

core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderImportIntegrationTest.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java, integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderImportIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/2001 to branch(3)
Fixes https://github.com/scalar-labs/scalardb/issues/2006, https://github.com/scalar-labs/scalardb/issues/2007, and https://github.com/scalar-labs/scalardb/issues/2008.
=> Backport to branch(3): Fix a bug that the importing table feature accesses tables in other namespace that have the same table name with MySQL storage

core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionResult.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
This PR fixes a snapshot management issue, which occurs when a transaction issues multiple different get or scan operations with different conditions, and another transaction updates and commits the related record in between those operations. See an example situation below.
| ID  | Balance |
|-----|---------|
| 1   | 5       |
| 2   | 10      |
| 3   | 15      |
1. A transaction (Tx1) scans with a condition where balance > 0, then the read set will be filled with all records.
2. Another transaction (Tx2) updates ID=2 with 5 and commits.
3. Ongoing Tx1 scans with a different condition where balance < 10.
Currently, Tx1’s snapshot returns results from the read set if the key returned from storage already exists in the read set. So, in the above example, the client will see the records (1, …
=> Fix snapshot management issues

core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
=> Backport to branch(3.11) : Fix snapshot management issues

core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
=> Backport to branch(3.10) : Fix snapshot management issues

core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java, core/src/test/java/com/scalar/db/common/CheckedDistributedStorageAdminTest.java
This PR adds check for encrypted columns to `repairTable()`.
- https://github.com/scalar-labs/scalardb/pull/1907
- Added check for encrypted columns to `repairTable()`.
N/A
N/A
=> Add check for encrypted columns to repairTable()

docs/add-scalardb-to-your-build.md, docs/api-guide.md, docs/backup-restore.md, docs/configurations.md, docs/data-modeling.md, docs/design.md, docs/getting-started-with-scalardb-by-using-kotlin.md, docs/getting-started-with-scalardb.md, docs/index.md, docs/multi-storage-transactions.md, docs/overview.md, docs/requirements.md, docs/scalardb-server.md, docs/scalardb-supported-databases.md, docs/schema-loader-import.md, docs/schema-loader.md, docs/storage-abstraction.md, docs/two-phase-commit-transactions.md
This PR adds a cautionary notice to the top of the docs in the `docs` folder. Since the docs for all versions should now be updated in the [scalar-labs/docs-internal-scalardb](https://github.com/scalar-labs/docs-internal-scalardb) repository, the cautionary notice that I've added is to provide guidance for those who may not know where to update the docs.
> If this PR addresses or references any issues and/or other PRs, list them here. For example, "Fixes #123", "Related to #456", or "Addresses #789".
- Added a cautionary notice to the top of the docs in the `docs` folder, stating that the docs should be updated in the [scalar-labs/docs-internal-scalardb](https://github.com/scalar-labs/docs-internal-scalardb) repository.
> The following is a best-effort checklist. If any items in this …
=> Add caution notice about doc relocation to top of docs

core/src/main/java/com/scalar/db/common/TransactionExecutor.java, core/src/test/java/com/scalar/db/common/TransactionExecutorTest.java
This PR adds a utility class `TransactionExecutor` that is a `SingleCrudOperationTransactionManager`-aware transaction executor.
N/A
- Added a utility class `TransactionExecutor`.
N/A
N/A
=> Add TransactionExecutor

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java, docs/schema-loader.md
We noticed there was room to improve some JDBC storage column types.
The current data type mapping is as follows:
| RDBMS Storage Type | ScalarDB: INT | ScalarDB: BIGINT | ScalarDB: FLOAT | ScalarDB: DOUBLE |
|----|----|----|----|----|
| Oracle | Oracle:`INT` (==`NUMBER(38)`) | `NUMBER(19)` | - | - |
| PostgreSQL | - | - | PG:`FLOAT` (==`DOUBLE PRECISION`) | PG:`DOUBLE PRECISION` |
| MySQL | - | - | MySQL:`DOUBLE` | PG:`DOUBLE` |
ScalarDB's `INT` type is larger than `BIGINT` in Oracle. Also, ScalarDB's `FLOAT` and `DOUBLE` are the same data type in PostgreSQL and MySQL.
This PR changes the data type mapping as follows:
- In Oracle, ScalarDB `INT` type is changed from `INT` (`NUMBER(38)`) to `NUMBER(10)`
- In PostgreSQL, ScalarDB `FLOAT` type is changed from `FLOAT` (`DOUBLE PRECISION`) to …
=> Change some JDBC data types to proper ones

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2017
=> Backport to branch(3) : Bump junitVersion from 5.10.2 to 5.10.3

core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java
This is for the `3` branch.
Currently, the `getNamespaceNames()` method has a limitation where only namespaces that contain tables are returned, which can be confusing for users. This PR adds a warning message about this limitation to the `getNamespaceNames()` method.
- https://github.com/scalar-labs/scalardb/pull/2002
- Added a warning message for the `getNamespaceNames()` method.
N/A
N/A
=> Add warning message for getNamespaceNames()

core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java, core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java, core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
This is for the `3` branch.
Currently, when the system namespace is not created yet, the `getNamespaceNames()` API returns the system namespace but the `namespaceExists()` API with the system namespace returns false. This PR addresses this issue.
- https://github.com/scalar-labs/scalardb/pull/2002
- Added check for the system namespace to `namespaceExists()` for each storage adaptor.
N/A
N/A
=> Should return true for system namespace in namespaceExists()

core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminIntegrationTestWithCassandra.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminIntegrationTestWithJdbcDatabase.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/util/AdminTestUtils.java, server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithServer.java
We added the group commit feature for the coordinator table commit in version `3.13` and `4.x`. It added a new column `tx_child_ids` in `coordinator.state` table. So, our plan was as follows:
- In version 3, users manually need to drop and re-create the coordinator table if they want to use the group commit feature
- In version 4, users can migrate their coordinator table to the new schema that contains `tx_child_ids` using `schema-loader --upgrade` command
But, we noticed `schema-loader --repair-all --coordinator` command with JDBC storage updates the ScalarDB metadata table by adding `tx_child_ids` column while the existing coordinator table in underlying RDB is left as-is. It results in the inconsistent state and will cause an issue that `schema-loader --upgrade` wouldn't work with …
=> Use a proper coordinator table schema based on whether the group commit feature is enabled or not

core/src/main/java/com/scalar/db/api/DistributedStorage.java, core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java, core/src/main/java/com/scalar/db/api/DistributedTransactionAdmin.java
This PR makes the `DistributedStorage`, `DistributedTransactionAdmin`, and `DistributedStorageAdmin` interfaces extend `AutoCloseable`.
N/A
- Made the `DistributedStorage`, `DistributedTransactionAdmin`, and `DistributedStorageAdmin` interfaces extend `AutoCloseable`.
N/A
N/A
=> Make DistributedStorage, DistributedTransactionAdmin, and DistributedStorageAdmin extend AutoCloseable

core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java, core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
This is for the `3` and `3.13` branches.
This PR changes to create the metadata namespace and table if they does not exist before creating user tables.
N/A
- Changed to create the metadata namespace and table if they does not exist before creating user tables.
N/A
N/A
=> Create metadata namespace and table if they does not exist before creating user tables

README.md, docs/getting-started-kotlin/build.gradle.kts, docs/getting-started/build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2036
=> Backport to branch(3) : Update ScalarDB dependency version to 3.13.0

core/build.gradle
The size of the integration test report for Cosmos DB is more than 9MB while other report sizes are about a few hundreds KB. This PR reduces the log size by filtering out a few types of log messages.
None
Filter out the following types of log message
1. `INFO com.azure.cosmos.implementation.RxDocumentClientImpl - Initializing DocumentClient [3] with serviceEndpoint [https://localhost:8081/],...`
2. `INFO com.azure.cosmos.implementation.Configs - AZURE_COSMOS_DISABLE_NON_STREAMING_ORDER_BY property is: null`
3. `ERROR com.scalar.db.storage.cosmos.MutateStatementHandler - {"innerErrorMessage":"[\"Encountered exception while executing Javascript. Exception = Error: no mutation`
3 is ERROR, but it accounts for most of log messages. So, it needs to be filtered out.
> The following is a …
=> Reduce Cosmos DB log messages in the integration test

.github/workflows/ci.yaml
Backport of https://github.com/scalar-labs/scalardb/pull/1978
=> Backport to branch(3.13) : [CI] Install Oracle JDK 8 and 11 for integration test runtime

.github/workflows/ci.yaml
Backport of #1978 
CI check with Oracle JDK 8 : https://github.com/scalar-labs/scalardb/actions/runs/9904110429
=> Backport to branch(3.12) : [CI] Install Oracle JDK 8 and 11 for integration test runtime 

.github/workflows/ci.yaml
Backport of #1978
Oracle 8 CI : https://github.com/scalar-labs/scalardb/actions/runs/9949625009
=> Backport to branch(3.11) : [CI] Install Oracle JDK 8 and 11 for integration test runtime

.github/workflows/ci.yaml
Backport of #1978
CI for Oracle 8: https://github.com/scalar-labs/scalardb/actions/runs/9949729883
=> Backport to branch(3.9) : [CI] Install Oracle JDK 8 and 11 for integration test runtime 

.github/workflows/ci.yaml
Backport of #1978 
CI for Oracle 8 : https://github.com/scalar-labs/scalardb/actions/runs/9949724004
=> Backport to branch(3.10) : [CI] Install Oracle JDK 8 and 11 for integration test runtime 

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2069
=> Backport to branch(3) : Bump org.assertj:assertj-core from 3.26.0 to 3.26.3

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2078
=> Backport to branch(3) : Bump com.yugabyte:jdbc-yugabytedb from 42.3.5-yb-5 to 42.3.5-yb-6

.github/workflows/ci.yaml
Backport of https://github.com/scalar-labs/scalardb/pull/2061
=> Backport to branch(3.13) : [CI] Add integration test for MariaDB 11.4 and Oracle 19 

docs/getting-started-kotlin/build.gradle.kts
=> Backport to branch(3) : Fix compilation error when using the JDK 21 for Getting Started with Kotlin

docs/getting-started-kotlin/build.gradle.kts
=> Backport to branch(3.13) : Fix compilation error when using the JDK 21 for Getting Started with Kotlin

docs/getting-started-kotlin/build.gradle.kts
=> Backport to branch(3.12) : Fix compilation error when using the JDK 21 for Getting Started with Kotlin

docs/getting-started-kotlin/build.gradle.kts
=> Backport to branch(3.11) : Fix compilation error when using the JDK 21 for Getting Started with Kotlin

docs/getting-started-kotlin/build.gradle.kts
=> Backport to branch(3.10) : Fix compilation error when using the JDK 21 for Getting Started with Kotlin

docs/getting-started-kotlin/build.gradle.kts
=> Backport to branch(3.9) : Fix compilation error when using the JDK 21 for Getting Started with Kotlin

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh
Note: This PR fixes a similar issue with #2084.
This PR fixes the following CI error.
- https://github.com/scalar-labs/scalardb/actions/runs/10210235162/job/28250229001?pr=2156
Recently, the container image of MS SQL Server was updated, and the file path in the container was changed from `/opt/mssql-tools/bin/sqlcmd` to `/opt/mssql-tools18/bin/sqlcmd`.
So, I updated the script `create-no-superuser-sqlserver.sh`:
- Check if the `/opt/mssql-tools18/bin/sqlcmd` command exists or not in the container image.
- Use `mssql-tools18` (new one) if the `/opt/mssql-tools18/bin/sqlcmd` command exists.
- Use `mssql-tools` (old one) if the `/opt/mssql-tools18/bin/sqlcmd` command does NOT exist.
- #2084
- Update `create-no-superuser-sqlserver.sh`.
You can see the test result in the …
=> Fix CI issue of SQL Server (Check if the command exsits)

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2165
=> Backport to branch(3) : Bump org.xerial:sqlite-jdbc from 3.46.0.0 to 3.46.0.1

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2172
=> Backport to branch(3) : Bump com.oracle.database.jdbc:ojdbc8 from 21.14.0.0 to 21.15.0.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2179
=> Backport to branch(3) : Bump software.amazon.awssdk:bom from 2.26.5 to 2.27.4

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2187
=> Backport to branch(3) : Bump junitVersion from 5.10.3 to 5.11.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2188
=> Backport to branch(3) : Bump org.xerial:sqlite-jdbc from 3.46.0.1 to 3.46.1.0

.github/workflows/ci.yaml, .github/workflows/create-release.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/upload-artifacts.yaml, .github/workflows/vuln-check.yaml
```console
git checkout 3-pull-2164 &&
```
Thank you!
=> Backport to branch(3) : [Github actions] Fix the deprecation of `gradle-build-action`

.github/workflows/ci.yaml, .github/workflows/create-release.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/upload-artifacts.yaml, .github/workflows/vuln-check.yaml
```console
git checkout 3.13-pull-2164 &&
```
Thank you!
=> Backport to branch(3.13) : [Github actions] Fix the deprecation of `gradle-build-action`

.github/workflows/ci.yaml, .github/workflows/create-release.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/upload-artifacts.yaml, .github/workflows/vuln-check.yaml
```console
git checkout 3.11-pull-2164 &&
```
Thank you!
=> Backport to branch(3.11) : [Github actions] Fix the deprecation of `gradle-build-action`

.github/workflows/ci.yaml, .github/workflows/create-release.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/upload-artifacts.yaml, .github/workflows/vuln-check.yaml
```console
git checkout 3.10-pull-2164 &&
```
Thank you!
=> Backport to branch(3.10) : [Github actions] Fix the deprecation of `gradle-build-action`

.github/workflows/ci.yaml, .github/workflows/create-release.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/upload-artifacts.yaml, .github/workflows/vuln-check.yaml
```console
git checkout 3.9-pull-2164 &&
```
Thank you!
=> Backport to branch(3.9) : [Github actions] Fix the deprecation of `gradle-build-action`

.github/workflows/ci.yaml, .github/workflows/create-release.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/upload-artifacts.yaml, .github/workflows/vuln-check.yaml
```console
git checkout 3.12-pull-2164 &&
```
Thank you!
=> Backport to branch(3.12) : [Github actions] Fix the deprecation of `gradle-build-action`

.github/workflows/ci.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2170
- **Commit to backport:** e28624ceb92a563df0778cc91edc835b6a0de488
```console
git checkout 3.11-pull-2170 &&
git cherry-pick --no-rerere-autoupdate -m1 e28624ceb92a563df0778cc91edc835b6a0de488
```
Thank you!
=> Backport to branch(3.11) : [CI] Use official Oracle JDK image instead of in-house one

.github/workflows/ci.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2170
- **Commit to backport:** e28624ceb92a563df0778cc91edc835b6a0de488
```console
git checkout 3.10-pull-2170 &&
git cherry-pick --no-rerere-autoupdate -m1 e28624ceb92a563df0778cc91edc835b6a0de488
```
Thank you!
=> Backport to branch(3.10) : [CI] Use official Oracle JDK image instead of in-house one

.github/workflows/ci.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2170
- **Commit to backport:** e28624ceb92a563df0778cc91edc835b6a0de488
```console
git checkout 3.9-pull-2170 &&
git cherry-pick --no-rerere-autoupdate -m1 e28624ceb92a563df0778cc91edc835b6a0de488
```
Thank you!
=> Backport to branch(3.9) : [CI] Use official Oracle JDK image instead of in-house one

.github/workflows/ci.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2170
- **Commit to backport:** e28624ceb92a563df0778cc91edc835b6a0de488
```console
git checkout 3.12-pull-2170 &&
git cherry-pick --no-rerere-autoupdate -m1 e28624ceb92a563df0778cc91edc835b6a0de488
```
Thank you!
=> Backport to branch(3.12) : [CI] Use official Oracle JDK image instead of in-house one

.github/dependabot.yml
GitHub actions versions on support and release branches were not updated, so triggering the CI raised several deprecation warnings. Because of this, we decided to update the action on all branches.
Also, to reduce the number of PR being created, we configure Dependabot to group updates by ecosystem and branches.
To see an example of what it will look like, please check the [PR created](https://github.com/Torch3333/scalardb/pulls) on this ScalarDB fork where I did some tests.
> [!IMPORTANT]  
> We will need to update the Dependabot configuration every time a new ScalarDB version is released and/or become EOL so that actions on respective branches are updated accordingly. 
N/A
Update Dependabot config:
- Add a config to update actions for all branches
- Update the config to group updates …
=> [Dependabot] Group update PR & update actions on all branches

build.gradle, core/build.gradle
This PR fixes CVE-2023-22102 by bumping up the mysql driver to `9.0.0`.
N/A
- Bumped up the mysql driver to `9.0.0`.
N/A
Upgraded the mysql driver to fix security issues. CVE-2023-22102
=> Fix CVE-2023-22102

build.gradle, core/build.gradle
This reverts commit 7792f170f1e44b11a98f9522e6249dbabc6efd04. This is because the change causes the following error in the ScalarDB Cluster:
```java
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:362) …
```
=> Revert "Fix CVE-2023-22102 (#2227)"

build.gradle, core/build.gradle
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2238
- **Commit to backport:** d5c8457f73583045cdc16d49a765503bc3e43c4a
```console
git checkout 3.9-pull-2238 &&
git cherry-pick --no-rerere-autoupdate -m1 d5c8457f73583045cdc16d49a765503bc3e43c4a
```
Thank you!
=> Backport to branch(3.9) : Fix CVE-2023-22102

.github/workflows/ci.yaml
The CI job for SQLServer 2017 has been failing since the end of last week. It appears the SQLServer 2017 Docker container fails to start properly, cf. the logs in the "Additional notes” section below.
As a workaround, I downgraded the Github runner Ubuntu version from 22 to 20.
- Related issue on the SQLServer docker container repo: https://github.com/microsoft/mssql-docker/issues/899
Downgraded the CI Github runner Ubuntu version from 22 to 20 for the SQLServer2017 job to fix a container startup issue.
The logs for the SQLServer2017 Docker container which fails to …
=> [CI] Fix SQLServer 2017 job 

core/src/main/java/com/scalar/db/api/AuthAdmin.java, core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionAdmin.java
This PR adds the `getCurrentUser()` method to `AuthAdmin`, which retrieves the currently logged-in user.
N/A
- Added the `getCurrentUser()` method to `AuthAdmin`.
N/A
N/A
=> Add getCurrentUser() to AuthAdmin

.github/dependabot.yml
In #2220 , I forgot to set the reviewers for the actions update on all branches in the Dependabot configuration.
The action update PRs were created [successfully](https://github.com/scalar-labs/scalardb/pull/2226) but no reviewers were added automatically.
- #2220 
Set reviewers for actions update on all branches.
N/A
N/A
=> [Dependabot] Set reviewers for actions group updates

core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/storage/jdbc/ConditionalMutator.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineFactory.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java, core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2245
- **Commit to backport:** a4b2cf91488322391397c3ba1241cd43d6401108
```console
git checkout 3-pull-2245 &&
git cherry-pick --no-rerere-autoupdate -m1 a4b2cf91488322391397c3ba1241cd43d6401108
```
Thank you!
=> Backport to branch(3) : Change default key column size and make it configurable for MySQL and Oracle

core/src/main/java/com/scalar/db/storage/cosmos/ConcatenationVisitor.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosOperation.java, core/src/test/java/com/scalar/db/storage/cosmos/ConcatenationVisitorTest.java
Refactor `ConcatenationVisitor` that uses the deprecated `ValueVisitor` to use the `ColumnVisitor` instead.
The background is I take care of some refactoring to facilitate the implementation of time-related types.
N/A
Refactor `ConcatenationVisitor` that uses the deprecated `ValueVisitor` to use the `ColumnVisitor` instead.
N/A
N/A
=> Refactor ConcatenationVisitor to use ColumnVisitor

core/src/main/java/com/scalar/db/config/DatabaseConfig.java, core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
This PR changes the default value of the metadata cache expiration time (`scalar.db.metadata.cache_expiration_time_secs`) to 60 seconds. Strictly speaking, this may be an incompatible change, but I don't expect it to cause any problems. If there are any objections, please let me know.
N/A
- Changed the default value of the metadata cache expiration time (`scalar.db.metadata.cache_expiration_time_secs`) to 60 seconds.
N/A
Changed the default value of the metadata cache expiration time (`scalar.db.metadata.cache_expiration_time_secs`) to 60 seconds.
=> Change default value of metadata cache expiration time

core/src/main/java/com/scalar/db/config/DatabaseConfig.java, core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2274
- **Commit to backport:** d3251d36bbd286642cb97189b50c64e8b48aad27
```console
git checkout 3-pull-2274 &&
git cherry-pick --no-rerere-autoupdate -m1 d3251d36bbd286642cb97189b50c64e8b48aad27
```
Thank you!
=> Backport to branch(3) : Change default value of metadata cache expiration time

.github/workflows/manual-vuln-check.yaml, .github/workflows/vuln-check.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2288
- **Commit to backport:** de679ca7b576c22c53e40568ffaa5e33e0ca0681
```console
git checkout 3.13-pull-2288 &&
git cherry-pick --no-rerere-autoupdate -m1 de679ca7b576c22c53e40568ffaa5e33e0ca0681
```
Thank you!
=> Backport to branch(3.13) : Use reusable vulnerability check workflow

.github/workflows/manual-vuln-check.yaml, .github/workflows/vuln-check.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2288
- **Commit to backport:** de679ca7b576c22c53e40568ffaa5e33e0ca0681
```console
git checkout 3.12-pull-2288 &&
git cherry-pick --no-rerere-autoupdate -m1 de679ca7b576c22c53e40568ffaa5e33e0ca0681
```
Thank you!
=> Backport to branch(3.12) : Use reusable vulnerability check workflow

.github/workflows/manual-vuln-check.yaml, .github/workflows/vuln-check.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2288
- **Commit to backport:** de679ca7b576c22c53e40568ffaa5e33e0ca0681
```console
git checkout 3.11-pull-2288 &&
git cherry-pick --no-rerere-autoupdate -m1 de679ca7b576c22c53e40568ffaa5e33e0ca0681
```
Thank you!
=> Backport to branch(3.11) : Use reusable vulnerability check workflow

.github/workflows/manual-vuln-check.yaml, .github/workflows/vuln-check.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2288
- **Commit to backport:** de679ca7b576c22c53e40568ffaa5e33e0ca0681
```console
git checkout 3.10-pull-2288 &&
git cherry-pick --no-rerere-autoupdate -m1 de679ca7b576c22c53e40568ffaa5e33e0ca0681
```
Thank you!
=> Backport to branch(3.10) : Use reusable vulnerability check workflow

.github/workflows/ci.yaml
This updates the versions of the CI-tested MySQL and PostgreSQL versions to:
| MySQL versions | Current | New |
|----------------|---------|-----|
| 5.7            | X       | X   |
| 8.0            | X       | X   |
| 8.1            | X       |     |
| 8.4            |         | X   |
| PosgreSQL versions | Current | New |
|--------------------|---------|-----|
| 12                 | X       |     |
| 13                 | X       | X   |
| 14                 | X       | X   |
| 15                 | X       | X   |
| 16                 |         | X   |
| 17                 |         | X   |
N/A
Update the tested versions of MySQL and PosgreSQL on the CI
> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, …
=> Update MySQL and PostgreSQL versions tested on the CI

.github/workflows/ci.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2302
- **Commit to backport:** f16b810ff81e6704125035b29dea74136f7efd2d
```console
git checkout 3.12-pull-2302 &&
git cherry-pick --no-rerere-autoupdate -m1 f16b810ff81e6704125035b29dea74136f7efd2d
```
Thank you!
=> Backport to branch(3.12) : Update MySQL and PostgreSQL versions tested on the CI

.github/workflows/ci.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2302
- **Commit to backport:** f16b810ff81e6704125035b29dea74136f7efd2d
```console
git checkout 3.10-pull-2302 &&
git cherry-pick --no-rerere-autoupdate -m1 f16b810ff81e6704125035b29dea74136f7efd2d
```
Thank you!
=> Backport to branch(3.10) : Update MySQL and PostgreSQL versions tested on the CI

.github/workflows/ci.yaml
The CI for CosmosDB has been failing regularly (more than 50% some days) because the CosmosDB emulator fails to start within the default timeout of 4min.
This PR increases the timeout to 10min as a workaround. If failure continues to occur, we can consider implementing a retry mechanism.
N/A
Update the emulator of the CosmosDB CI startup timeout to 10min
N/A
N/A
=> [CI] Increase CosmosDB emulator startup timeout to 10min

core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/storage/cosmos/ConcatenationVisitor.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosOperationChecker.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitter.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosOperationCheckerTest.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitterTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2292
- **Commit to backport:** b4170b4bb8185902baf44631affef4fe4d3be01d
```console
git checkout 3.13-pull-2292 &&
git cherry-pick --no-rerere-autoupdate -m1 b4170b4bb8185902baf44631affef4fe4d3be01d
```
Thank you!
=> Backport to branch(3.13) : Add validation for primary key columns in Cosmos DB adapter

core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/storage/cosmos/ConcatenationVisitor.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosOperationChecker.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosOperationCheckerTest.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2292
- **Commit to backport:** b4170b4bb8185902baf44631affef4fe4d3be01d
```console
git checkout 3.12-pull-2292 &&
git cherry-pick --no-rerere-autoupdate -m1 b4170b4bb8185902baf44631affef4fe4d3be01d
```
Thank you!
=> Backport to branch(3.12) : Add validation for primary key columns in Cosmos DB adapter

core/src/main/java/com/scalar/db/storage/cosmos/ConcatenationVisitor.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosOperationChecker.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosOperationCheckerTest.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2292
- **Commit to backport:** b4170b4bb8185902baf44631affef4fe4d3be01d
```console
git checkout 3.11-pull-2292 &&
git cherry-pick --no-rerere-autoupdate -m1 b4170b4bb8185902baf44631affef4fe4d3be01d
```
Thank you!
=> Backport to branch(3.11) : Add validation for primary key columns in Cosmos DB adapter

core/src/main/java/com/scalar/db/storage/cosmos/ConcatenationVisitor.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosOperationChecker.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosOperationCheckerTest.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2292
- **Commit to backport:** b4170b4bb8185902baf44631affef4fe4d3be01d
```console
git checkout 3.10-pull-2292 &&
git cherry-pick --no-rerere-autoupdate -m1 b4170b4bb8185902baf44631affef4fe4d3be01d
```
Thank you!
=> Backport to branch(3.10) : Add validation for primary key columns in Cosmos DB adapter

core/src/main/java/com/scalar/db/api/Delete.java, core/src/main/java/com/scalar/db/api/DeleteBuilder.java, core/src/main/java/com/scalar/db/api/Get.java, core/src/main/java/com/scalar/db/api/GetBuilder.java, core/src/main/java/com/scalar/db/api/GetWithIndex.java, core/src/main/java/com/scalar/db/api/Insert.java, core/src/main/java/com/scalar/db/api/InsertBuilder.java, core/src/main/java/com/scalar/db/api/Mutation.java, core/src/main/java/com/scalar/db/api/Operation.java, core/src/main/java/com/scalar/db/api/OperationBuilder.java, core/src/main/java/com/scalar/db/api/Put.java, core/src/main/java/com/scalar/db/api/PutBuilder.java, core/src/main/java/com/scalar/db/api/Scan.java, core/src/main/java/com/scalar/db/api/ScanAll.java, core/src/main/java/com/scalar/db/api/ScanBuilder.java, core/src/main/java/com/scalar/db/api/ScanWithIndex.java, core/src/main/java/com/scalar/db/api/Selection.java, core/src/main/java/com/scalar/db/api/SelectionBuilder.java, core/src/main/java/com/scalar/db/api/Update.java, core/src/main/java/com/scalar/db/api/UpdateBuilder.java, core/src/main/java/com/scalar/db/api/Upsert.java, core/src/main/java/com/scalar/db/api/UpsertBuilder.java, core/src/main/java/com/scalar/db/util/ScalarDbUtils.java, core/src/test/java/com/scalar/db/api/GetBuilderTest.java, core/src/test/java/com/scalar/db/api/ScanBuilderTest.java, core/src/test/java/com/scalar/db/util/ScalarDbUtilsTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageWithReservedKeywordIntegrationTestBase.java
This PR refactors operations (Get, Scan, Put, Insert, Upsert, Update, and Delete) and their builders.
N/A
- Added constructors to set all parameters for operations.
- Use the added constructors in operation builders.
N/A
N/A
=> Refactor operations and their builders

core/src/main/java/com/scalar/db/api/Admin.java, core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java, core/src/main/java/com/scalar/db/common/error/CoreError.java
This PR revises features names in error messages.
Since we decided to use generic feature names rather than branded feature names for the encryption feature and the authentication and authorization feature, the error messages should be consistent with how we officially refer to these features.
- **PR that introduces the feature names:** https://github.com/scalar-labs/scalardb/pull/2182
- Changed `ScalarDB Auth` to `authentication and authorization`.
- Changed `ScalarDB Transparent Data Encryption` to `encryption`.
N/A
N/A
=> Revise feature names in error messages

core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorTest.java
The current implementation of `Coordinator.getStateForGroupCommit()` checks transaction states that were stored with the Group Commit feature enabled in the following order:
1. First, it tries to find a record whose `tx_id` is the full transaction ID, returning the state if it's found. This record type is created when a transaction is delayed and committed individually.
2. Next, it tris to find a record whose `tx_id` is the parent transaction ID, returning the state if it's found and the `tx_sub_ids` contains the child transaction ID. This record type is created when a transaction gets commit-ready in time and group-committed.
This order is optimized for lazy-recovery, which is more likely to happen if the commit timing is delayed after PREPARE record is created. However, basically …
=> Optimize `Coordinator#getStateForGroupCommit()` by first looking up the coordinator table with parent transaction ID

core/src/main/java/com/scalar/db/storage/cosmos/DeleteStatementHandler.java, core/src/test/java/com/scalar/db/storage/cosmos/DeleteStatementHandlerTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
This PR fixes the delete behavior in the Cosmos adapter. Currently, if we attempt to delete a non-existent record, the Cosmos adapter throws an `ExecutionException`. This behavior is inconsistent with other adapters. This PR adjusts it to ensure consistent behavior across adapters.
N/A
- Stop throwing an exception when attempting to delete a non-existent record in the Cosmos adapter.
N/A
Fixed the behavior when deleting a non-existing record in the Cosmos adapter.
=> Fix delete behavior in Cosmos adapter

core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
This PR revisits the behavior of multiple mutations for the same record in a transaction in Consensus Commit.
Expected behaviors for combinations of mutations on the same record are as follows:
1. Insert then Insert: the second Insert fails.
2. Insert then Upsert: merge Insert and Upsert (with implicit pre-read disabled), then execute.
3. Insert then Update: merge Insert and Update (with implicit pre-read disabled), then execute.
4. Insert then Delete: ~only execute Delete.~ not allowed in Consensus Commit.
5. Upsert then Insert: Insert fails.
6. Upsert then Upsert: merge the two Upserts, then execute.
7. Upsert then Update: merge Upsert and Update, then execute.
8. Upsert then Delete: only execute Delete.
9. Update then Insert: if the target record exists, Insert fails; if not, only …
=> Revisit behavior of multiple mutations for same record in transaction in Consensus Commit

core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2340
- **Commit to backport:** 3f20979c11a660dfb7b021809b727a69a0008bb9
```console
git checkout 3.14-pull-2340 &&
git cherry-pick --no-rerere-autoupdate -m1 3f20979c11a660dfb7b021809b727a69a0008bb9
```
Thank you!
=> Backport to branch(3.14) : Revisit behavior of multiple mutations for same record in transaction in Consensus Commit

core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java, server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithServer.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2340
- **Commit to backport:** 3f20979c11a660dfb7b021809b727a69a0008bb9
```console
git checkout 3.13-pull-2340 &&
git cherry-pick --no-rerere-autoupdate -m1 3f20979c11a660dfb7b021809b727a69a0008bb9
```
Thank you!
=> Backport to branch(3.13) : Revisit behavior of multiple mutations for same record in transaction in Consensus Commit

core/src/main/java/com/scalar/db/api/GetBuilder.java, core/src/main/java/com/scalar/db/api/ScanBuilder.java
This PR fixes bugs in GetBuilder and ScanBuilder, which wrongly enable where() to continue with “and” in the disjunctive normal form context and for “or” vice vasa. They were due to incorrect inheritance.
```java
// The following patterns should not be accepted.
Scan newScan = Scan.newBuilder(scan).where(andConditionSet).and(orConditionSet).build();
Scan newScan = Scan.newBuilder(scan).where(orConditionSet).or(andConditionSet).build();
// They should be the following.
Scan newScan = Scan.newBuilder(scan).where(orConditionSet).and(orConditionSet).build();
Scan newScan = Scan.newBuilder(scan).where(andConditionSet).or(andConditionSet).build();
```
The bugs were introduced in the following PRs.
- #1715
- #1834
So, the `ScanBuilder` fix should be included in the minor versions >= 3.10, I …
=> Fix GetBuilder and ScanBuilder

core/src/main/java/com/scalar/db/common/TransactionExecutor.java, core/src/test/java/com/scalar/db/common/TransactionExecutorTest.java
This PR adds the `executeWithRetries` methods to `TransactionExecutor`. These methods execute transactions and retry them when conflict errors occur.
N/A
- Added the `executeWithRetries` methods to `TransactionExecutor`.
`TransactionExecutor` is primarily intended for internal use.
N/A
=> Add executeWithRetries methods to TransactionExecutor

data-loader/core/build.gradle, data-loader/core/src/main/java/com/scalar/db/dataloader/core/ColumnInfo.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/ErrorMessage.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/exception/ColumnParsingException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/exception/KeyParsingException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/ColumnUtils.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/KeyUtils.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/ColumnUtilsTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/KeyUtilsTest.java
Backport to branch(3.11) : Add data loader core key and column utils
Added ErrorMessage and removed CoreError
https://github.com/scalar-labs/scalardb/pull/2385
Replaced CoreError (not available in current version and replaced with ErrorMessage class
NA
NA
=> Manual Backport to branch(3.10) : Add data loader core key and column utils

data-loader/core/build.gradle, data-loader/core/src/main/java/com/scalar/db/dataloader/core/ColumnInfo.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/ErrorMessage.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/exception/ColumnParsingException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/exception/KeyParsingException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/ColumnUtils.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/KeyUtils.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/ColumnUtilsTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/KeyUtilsTest.java
Backport to branch(3.11) : Add data loader core key and column utils 
Added ErrorMessage and removed CoreError
https://github.com/scalar-labs/scalardb/pull/2384
Replaced CoreError (not available in current version and replaced with ErrorMessage class
NA
NA
=> Manual Backport to branch(3.11) : Add data loader core key and column utils 

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/core/build.gradle, data-loader/core/src/main/java/com/scalar/db/dataloader/core/ColumnInfo.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/exception/ColumnParsingException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/exception/KeyParsingException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/ColumnUtils.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/KeyUtils.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/ColumnUtilsTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/KeyUtilsTest.java
Backport to branch(3.12) : Add data loader core key and column utils
Resolved conflicts in CoreError class
https://github.com/scalar-labs/scalardb/pull/2383
Resolved conflicts in CoreError class
NA
NA
=> Manual Backport to branch(3.12) : Add data loader core key and column utils

core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitter.java, core/src/main/java/com/scalar/db/util/groupcommit/DefaultGroupCommitKeyManipulator.java, core/src/main/java/com/scalar/db/util/groupcommit/DelayedGroup.java, core/src/main/java/com/scalar/db/util/groupcommit/Group.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitKeyManipulator.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitter.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupManager.java, core/src/main/java/com/scalar/db/util/groupcommit/NormalGroup.java, core/src/test/java/com/scalar/db/util/groupcommit/DelayedGroupTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterConcurrentTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupManagerTest.java, core/src/test/java/com/scalar/db/util/groupcommit/NormalGroupTest.java, core/src/test/java/com/scalar/db/util/groupcommit/TestableGroupCommitKeyManipulator.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
In the current implementation, `CoordinatorGroupCommitKeyManipulator` designed to manipulate GroupCommit keys that are all String. But, the functionality should be reusable in other use cases, not only for the Coordinator Group Commit feature. This PR moves the implementation of `CoordinatorGroupCommitKeyManipulator` to `DefaultGroupCommitKeyManipulator` to make the functionality easier to reuse.
- https://github.com/scalar-labs/scalardb-cluster/pull/834
- Move the implementation of `CoordinatorGroupCommitKeyManipulator` to `DefaultGroupCommitKeyManipulator`. `CoordinatorGroupCommitKeyManipulator` inherits `DefaultGroupCommitKeyManipulator` now.
- Rename interface `KeyManipulator` to `GroupCommitKeyManipulator` to clarify what kind of keys the interface manipulate.
> The following is a …
=> Refactoring `CoordinatorGroupCommitKeyManipulator` by moving the implementation to `DefaultGroupCommitKeyManipulator` to improve the reusability

core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommit.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
In the current implementation, `CommitHandler` has `onPrepareFailure()` and `onValidateFailure()`, but there is no need to separate them. This PR merges them to make it simpler.
None.
- Merge `onPrepareFailure()` and `onValidateFailure()` into `onFailureBeforeCommit()`
- Make the error handling more consistent
None
N/A (No behavior changed)
=> Refactoring the callbacks for the group commit error handling in `CommitHandler`

.github/workflows/ci.yaml, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultipleClusteringKeyScanIntegrationTest.java
The current integration test disabled 2 test cases when the underlying database is YugabyteDB to avoid https://github.com/yugabyte/yugabyte-db/issues/22140. But, the bug is already fixed, so this PR enabled the skipped test cases.
Note: this PR doesn't use the latest version of YugabyteDB Docker image, since another issue that DDL statements fail after the schema has been changed frequently occurs with recent versions.
None
- Remove 2 overridden test cases that skip test when the underlying database is YugabyteDB
- Change the YugabyteDB Docker image that has a fix for https://github.com/yugabyte/yugabyte-db/issues/22140
> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the …
=> Enable integration test cases skipped for YugabyteDB

core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTestUtils.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/config/DatabaseConfig.java, core/src/main/java/com/scalar/db/io/BigIntColumn.java, core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java, core/src/main/java/com/scalar/db/storage/cassandra/CassandraConfig.java, core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java, core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java, core/src/main/java/com/scalar/db/storage/dynamo/Namespace.java, core/src/main/java/com/scalar/db/storage/jdbc/ConditionalMutator.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java, core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithFetchFirstNRowsOnly.java, core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithLimitQuery.java, core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithTop.java, core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitConfig.java, gradle/spotbugs-exclude.xml, schema-loader/src/main/java/com/scalar/db/schemaloader/ImportSchemaParser.java, schema-loader/src/main/java/com/scalar/db/schemaloader/ImportTableSchema.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaParser.java, schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java
This PR updates the code to ignore the spotbugs warning `CT_CONSTRUCTOR_THROW`.
N/A
- Updated the code to ignore the spotbugs warning `CT_CONSTRUCTOR_THROW`.
N/A
N/A
=> Ignore Spotbugs warning CT_CONSTRUCTOR_THROW

core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/test/java/com/scalar/db/common/error/CoreErrorTest.java
This PR adds the prefix (`DB-`) to the error code.
N/A
- Added the prefix (`DB-`) to the error code.
N/A
N/A
=> Add prefix to error code

build.gradle, core/build.gradle
~~This updates slf4j to the latest version to resolve the following logger binding issue when running ScalarDB unit or integration test.~~
~~This forces Gradle to use the slf4j version defined by ScalarDB over any version pulled transitively.~~
This excludes the `slf4j-api` dependency from the maria-db driver to resolve the following logger binding issue when running ScalarDB unit or integration test.
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/Users/vguilpain/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.36/ …
```
=> Fix Slf4j providers not found error

data-loader/core/src/main/java/com/scalar/db/dataloader/core/ErrorMessage.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidationException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidator.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidatorTest.java
```console
git checkout 3.11-pull-2435 &&
```
Thank you!
=> Backport to branch(3.11) : Add export options validator

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidationException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidator.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidatorTest.java
```console
git checkout 3.12-pull-2435 &&
```
Thank you!
=> Backport to branch(3.12) : Add export options validator

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidationException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidator.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidatorTest.java
```console
git checkout 3.13-pull-2435 &&
```
Thank you!
=> Backport to branch(3.13) : Add export options validator

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidationException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidator.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidatorTest.java
```console
git checkout 3.14-pull-2435 &&
```
Thank you!
=> Backport to branch(3.14) : Add export options validator

data-loader/core/src/main/java/com/scalar/db/dataloader/core/ErrorMessage.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidationException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidator.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidatorTest.java
```console
git checkout 3.10-pull-2435 &&
```
Thank you!
=> Backport to branch(3.10) : Add export options validator

core/src/main/java/com/scalar/db/api/AbacOperationAttributes.java, core/src/test/java/com/scalar/db/api/AbacOperationAttributesTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/2448
=> Backport to branch(3): Add utility setter methods for ImmutableMap to AbacOperationAttributes (#2448)

core/src/integration-test/java/com/scalar/db/storage/cassandra/TwoPhaseConsensusCommitIntegrationTestWithCassandra.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageColumnValueIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
This PR:
- updates key integration tests of `TwoPhaseCommitTransactionIntegrationTestBase` to performs operations on a table with all the data types. Similar changes were made to `DistributedTransactionIntegrationTestBase` in https://github.com/scalar-labs/scalardb/pull/2437
- does small fixes in `DistributedStorageColumnValueIntegrationTestBase` and `DistributedStorageAdminIntegrationTestBase`
- https://github.com/scalar-labs/scalardb/pull/2437
See the description above.
This PR will be merged into the feature branch …
=> Finalize integration tests for time related types 

core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java, core/src/test/java/com/scalar/db/storage/jdbc/RdbEngine.java, core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
When adding the MariaDB driver in https://github.com/scalar-labs/scalardb/pull/2391, I forgot to modify some unit test related to the `RdbEngineMariaDB` class. 
- https://github.com/scalar-labs/scalardb/pull/2391
Add missing unit test change to test the `RdbEngineMariaDB` class fully.
N/A
N/A
=> Fix missing unit tests for MariaDB RdbEngine

core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionAdmin.java
This PR adds the `importTable` method without the `overrideColumnsType` argument to `DecoratedDistributedTransactionAdmin`.
N/A
Add the `importTable` method without the `overrideColumnsType` argument to `DecoratedDistributedTransactionAdmin`.
N/A
N/A
=> Add importTable without overrideColumnsType to DecoratedDistributedTransactionAdmin

integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
This removes a table added by mistake in https://github.com/scalar-labs/scalardb/pull/2474 for debugging purposes.
- https://github.com/scalar-labs/scalardb/pull/2474
Remove an unused table from `DistributedTransactionAdminIntegrationTestBase`
N/A
N/A
=> Remove unused table added by mistake from integration test

README.md
This PR updates the ScalarDB dependency version to 3.15.0, as ScalarDB 3.15.0 has been released.
N/A
- Updated ScalarDB dependency version to 3.15.0.
N/A
N/A
=> Update ScalarDB dependency version to 3.15.0 in README

core/src/main/java/com/scalar/db/storage/cosmos/ResultInterpreter.java, core/src/main/java/com/scalar/db/storage/dynamo/ResultInterpreter.java, core/src/main/java/com/scalar/db/storage/dynamo/bytes/BytesUtils.java, core/src/main/java/com/scalar/db/storage/dynamo/bytes/DateBytesEncoder.java, core/src/main/java/com/scalar/db/storage/dynamo/bytes/IntBytesEncoder.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineTimeTypeSqlite.java, core/src/main/java/com/scalar/db/util/TimeRelatedColumnEncodingUtils.java, core/src/test/java/com/scalar/db/storage/TimeRelatedColumnEncodingUtilsTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
The DATE type value was encoded as a `long` for DynamoDB, Cosmos DB, and SQLite. But since the full range of DATE values fits into an `int`, we change the encoding type from `long` to `int`
- https://github.com/scalar-labs/scalardb/pull/2468
Updates the DynamoDB, CosmosDB, and SQLite adapters to encode DATE value as `int` instead of `long` 
N/A
Same as #2468
=> Change DATE type encoding to integer

core/src/main/java/com/scalar/db/storage/cosmos/ResultInterpreter.java, core/src/main/java/com/scalar/db/storage/dynamo/ResultInterpreter.java, core/src/main/java/com/scalar/db/storage/dynamo/bytes/BytesUtils.java, core/src/main/java/com/scalar/db/storage/dynamo/bytes/DateBytesEncoder.java, core/src/main/java/com/scalar/db/storage/dynamo/bytes/IntBytesEncoder.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineTimeTypeSqlite.java, core/src/main/java/com/scalar/db/util/TimeRelatedColumnEncodingUtils.java, core/src/test/java/com/scalar/db/storage/TimeRelatedColumnEncodingUtilsTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2491
- **Commit to backport:** 9cb186774e8dbc9f3af6394383f55f6bca9c8e57
```console
git checkout 3.15-pull-2491 &&
git cherry-pick --no-rerere-autoupdate -m1 9cb186774e8dbc9f3af6394383f55f6bca9c8e57
```
Thank you!
=> Backport to branch(3.15) : Change DATE type encoding to integer

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileTable.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileTableFieldMapping.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataRequest.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataService.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/TableMetadataUtil.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataServiceTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/TableMetadataUtilTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2434
- **Commit to backport:** 85ca0eb166380f76eb514b9275aade21a44d6753
```console
git checkout 3.13-pull-2434 &&
git cherry-pick --no-rerere-autoupdate -m1 85ca0eb166380f76eb514b9275aade21a44d6753
```
Thank you!
=> Backport to branch(3.13) : Add table metadata service

integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminImportTableIntegrationTestBase.java
This fixes Javadoc warning when compiling the project.
N/A
Fix javadoc comment.
N/A
N/A
=> Fix Javadoc warning in integration test

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDBDao.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDBDaoException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDbStorageManager.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDbTransactionManager.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDBDaoTest.java, gradle/spotbugs-exclude.xml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2417
- **Commit to backport:** 08dd89383e495afb23d3cfb941a4229a674bee8a
```console
git checkout 3.13-pull-2417 &&
git cherry-pick --no-rerere-autoupdate -m1 08dd89383e495afb23d3cfb941a4229a674bee8a
```
Thank you!
=> Backport to branch(3.13) : Add ScalarDB Dao and related files 

data-loader/core/src/main/java/com/scalar/db/dataloader/core/ErrorMessage.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDBDao.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDBDaoException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDbStorageManager.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDbTransactionManager.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDBDaoTest.java, gradle/spotbugs-exclude.xml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2417
- **Commit to backport:** 08dd89383e495afb23d3cfb941a4229a674bee8a
```console
git checkout 3.11-pull-2417 &&
git cherry-pick --no-rerere-autoupdate -m1 08dd89383e495afb23d3cfb941a4229a674bee8a
```
Thank you!
=> Backport to branch(3.11) : Add ScalarDB Dao and related files 

README.md
This PR updates the ScalarDB dependency version to 3.15.1 in README, as ScalarDB 3.15.1 has been released.
N/A
- Updated ScalarDB dependency version to 3.15.1.
N/A
N/A
=> Update ScalarDB dependency version to 3.15.1 in README

data-loader/core/src/main/java/com/scalar/db/dataloader/core/ErrorMessage.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFile.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileValidationException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileValidator.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileValidatorTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2445
- **Commit to backport:** 81640781c3a4340207ca6429e34e98135e0c8774
```console
git checkout 3.11-pull-2445 &&
git cherry-pick --no-rerere-autoupdate -m1 81640781c3a4340207ca6429e34e98135e0c8774
```
Thank you!
=> Backport to branch(3.11) : Add Control file module files and validation 

data-loader/core/src/main/java/com/scalar/db/dataloader/core/ErrorMessage.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportOptions.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/log/LogMode.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/mapping/ImportDataMapping.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/validation/ImportSourceRecordValidationResult.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/validation/ImportSourceRecordValidator.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/task/mapping/ImportDataMappingTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/task/validation/ImportSourceRecordValidatorTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2446
- **Commit to backport:** 067b8babc73f2f99feb4b618598d2c0d6c4c9ff9
```console
git checkout 3.11-pull-2446 &&
git cherry-pick --no-rerere-autoupdate -m1 067b8babc73f2f99feb4b618598d2c0d6c4c9ff9
```
Thank you!
=> Backport to branch(3.11) : Add dtos and other classes for task

.github/workflows/release-snapshot.yaml, .github/workflows/release.yaml
This PR add the `workflow_dispatch` trigger to the GitHub Actions release workflows.
N/A
-  Added the `workflow_dispatch` trigger to the GitHub Actions release workflows.
N/A
N/A
=> Add workflow_dispatch to release workflows

data-loader/core/src/main/java/com/scalar/db/dataloader/core/DataLoaderObjectMapper.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/ErrorMessage.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/CsvExportManager.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/ExportManager.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/ExportReport.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/JsonExportManager.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/JsonLineExportManager.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/CsvProducerTask.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/JsonLineProducerTask.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/JsonProducerTask.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/ProducerResult.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/ProducerTask.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/ProducerTaskFactory.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/CsvExportManagerTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/ExportReportTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/JsonExportManagerTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/JsonLineExportManagerTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/producer/CsvProducerTaskTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/producer/JsonLineProducerTaskTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/producer/JsonProducerTaskTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/producer/ProducerTaskFactoryTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2450
- **Commit to backport:** 75f8a9cace2532f27f7485a410c84cf24bb0bef7
```console
git checkout 3.11-pull-2450 &&
git cherry-pick --no-rerere-autoupdate -m1 75f8a9cace2532f27f7485a410c84cf24bb0bef7
```
Thank you!
=> Backport to branch(3.11) : Add export tasks

build.gradle
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2552
- **Commit to backport:** 559de5c00cf26a729390fbeef0c179f88a55d1a2
```console
git checkout 3.15-pull-2552 &&
git cherry-pick --no-rerere-autoupdate -m1 559de5c00cf26a729390fbeef0c179f88a55d1a2
```
Thank you!
=> Backport to branch(3.15) : Bump the dependencies group across 1 directory with 2 updates

build.gradle
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2552
- **Commit to backport:** 559de5c00cf26a729390fbeef0c179f88a55d1a2
```console
git checkout 3.14-pull-2552 &&
git cherry-pick --no-rerere-autoupdate -m1 559de5c00cf26a729390fbeef0c179f88a55d1a2
```
Thank you!
=> Backport to branch(3.14) : Bump the dependencies group across 1 directory with 2 updates

build.gradle, core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2552
- **Commit to backport:** 559de5c00cf26a729390fbeef0c179f88a55d1a2
```console
git checkout 3.12-pull-2552 &&
git cherry-pick --no-rerere-autoupdate -m1 559de5c00cf26a729390fbeef0c179f88a55d1a2
```
Thank you!
=> Backport to branch(3.12) : Bump the dependencies group across 1 directory with 2 updates

build.gradle, core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2552
- **Commit to backport:** 559de5c00cf26a729390fbeef0c179f88a55d1a2
```console
git checkout 3.11-pull-2552 &&
git cherry-pick --no-rerere-autoupdate -m1 559de5c00cf26a729390fbeef0c179f88a55d1a2
```
Thank you!
=> Backport to branch(3.11) : Bump the dependencies group across 1 directory with 2 updates

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
ScalarDB BIGINT is mapped to Oracle's `NUMBER(19)` type. However, a lower precision of 16 digits is enough to accommodate the allowed maximum value `9007199254740992L` and minimum value `-9007199254740992L`. 
N/A
Change mapping of BIGINT datatype to Oracle `NUMBER(16)`
> Provide any additional information or notes that may be relevant to the reviewers or stakeholders.
ScalarDB BIGINT datatype will now be mapped to Oracle's NUMBER(16).
=> Adjust precision of mapped datatype for ScalarDB BIGINT on Oracle

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
```console
git checkout 3-pull-2566 &&
```
Thank you!
=> Backport to branch(3) : Adjust precision of mapped datatype for ScalarDB BIGINT on Oracle

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
```console
git checkout 3.15-pull-2566 &&
```
Thank you!
=> Backport to branch(3.15) : Adjust precision of mapped datatype for ScalarDB BIGINT on Oracle

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
```console
git checkout 3.14-pull-2566 &&
```
Thank you!
=> Backport to branch(3.14) : Adjust precision of mapped datatype for ScalarDB BIGINT on Oracle

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
```console
git checkout 3.12-pull-2566 &&
```
Thank you!
=> Backport to branch(3.12) : Adjust precision of mapped datatype for ScalarDB BIGINT on Oracle

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
```console
git checkout 3.13-pull-2566 &&
```
Thank you!
=> Backport to branch(3.13) : Adjust precision of mapped datatype for ScalarDB BIGINT on Oracle

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
```console
git checkout 3.11-pull-2566 &&
```
Thank you!
=> Backport to branch(3.11) : Adjust precision of mapped datatype for ScalarDB BIGINT on Oracle

README.md
This PR updates the ScalarDB dependency version to 3.15.2 in README, as ScalarDB 3.15.2 has been released.
N/A
- Updated ScalarDB dependency version to 3.15.2.
N/A
N/A
=> Update ScalarDB dependency version to 3.15.2 in README

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportEventListener.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportManager.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportOptions.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/CsvImportProcessor.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/DefaultImportProcessorFactory.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessor.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessorFactory.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessorParams.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/JsonImportProcessor.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/JsonLinesImportProcessor.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/TableColumnDataTypes.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportStorageTask.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportTask.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportTaskParams.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportTransactionalTask.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/ColumnUtils.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/KeyUtils.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/UnitTestUtils.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/CsvImportProcessorTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/DefaultImportProcessorFactoryTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/JsonImportProcessorTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/JsonLinesImportProcessorTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/TableColumnDataTypesTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/ColumnUtilsTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/KeyUtilsTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2462
- **Commit to backport:** 2eacbbc584f21c7de60a14b5188d487d4ca6751c
```console
git checkout 3.13-pull-2462 &&
git cherry-pick --no-rerere-autoupdate -m1 2eacbbc584f21c7de60a14b5188d487d4ca6751c
```
Thank you!
=> Backport to branch(3.13) : Add the import process implementation for data loader

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportEventListener.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportManager.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportOptions.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/CsvImportProcessor.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/DefaultImportProcessorFactory.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessor.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessorFactory.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessorParams.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/JsonImportProcessor.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/JsonLinesImportProcessor.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/TableColumnDataTypes.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportStorageTask.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportTask.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportTaskParams.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportTransactionalTask.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/ColumnUtils.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/KeyUtils.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/UnitTestUtils.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/CsvImportProcessorTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/DefaultImportProcessorFactoryTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/JsonImportProcessorTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/JsonLinesImportProcessorTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/TableColumnDataTypesTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/ColumnUtilsTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/KeyUtilsTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2462
- **Commit to backport:** 2eacbbc584f21c7de60a14b5188d487d4ca6751c
```console
git checkout 3.14-pull-2462 &&
git cherry-pick --no-rerere-autoupdate -m1 2eacbbc584f21c7de60a14b5188d487d4ca6751c
```
Thank you!
=> Backport to branch(3.14) : Add the import process implementation for data loader

conf/database.properties, core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposer.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/SerializableStrategy.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
This PR removes the `EXTRA_WRITE` strategy in Consensus Commit. After this change, if the `EXTRA_WRITE` strategy is specified when using Consensus Commit, the `EXTRA_READ` strategy will be used instead.
N/A
- Removed the `EXTRA_WRITE` strategy in Consensus Commit.
N/A
Removed the `EXTRA_WRITE` strategy from Consensus Commit. After this change, if the `EXTRA_WRITE` strategy is specified when using Consensus Commit, the `EXTRA_READ` strategy will be used instead.
=> Remove EXTRA_WRITE strategy in Consensus Commit

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
The Ubuntu 20.04 Github action runner was used to run SQL Server 2017 CI job, but this image is no longer available.
Also, the docker container for SQL Server 2017 is incompatible with other Ubuntu action runners (versions 22.04 and 24.04), so we switched to using a Windows Server runner instead. 
N/A
Update the CI and make some changes to some integration tests. See the review comments for more details.
N/A
N/A
=> Fix SQL Server 2017 CI

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2599
- **Commit to backport:** 41a86d7940ae4d40a6b938768e48866e153b8562
```console
git checkout 3.12-pull-2599 &&
git cherry-pick --no-rerere-autoupdate -m1 41a86d7940ae4d40a6b938768e48866e153b8562
```
Thank you!
=> Backport to branch(3.12) : Fix SQL Server 2017 CI

core/src/main/java/com/scalar/db/api/DistributedTransactionAdmin.java, core/src/main/java/com/scalar/db/api/ReplicationAdmin.java, core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionAdmin.java, core/src/main/java/com/scalar/db/common/error/CoreError.java
We've [implemented `ReplicationDistributedTransactionAdmin` in ScalarDB Cluster](https://github.com/scalar-labs/scalardb-cluster/pull/994) that has some new APIs. `DistributedAdmin` doesn't have the API yet, so users can't use the new APIs via `DistributedAdmin`. This PR add those new APIs to `DistributedAdmin`.
- https://github.com/scalar-labs/scalardb-cluster/pull/994
- Add `ReplicationAdmin` that contains the new replication related APIs
- Update `DistributedAdmin` to inherit `ReplicationAdmin` as well as other Admin interfaces
- Update `DecoratedDistributedTransactionAdmin` to support the new APIs as well as other Admin interfaces
> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please …
=> Add the replication related APIs to DistributedAdmin for SSR

core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/StateManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/StateManagedTwoPhaseCommitTransactionManager.java
This PR adds the `decorateTransactionOnBeginOrStart()` method to both `DecoratedDistributedTransactionManager` and `DecoratedTwoPhaseCommitTransactionManager` to reduce code duplication.
N/A
- Added the `decorateTransactionOnBeginOrStart()` method to `DecoratedDistributedTransactionManager` and `DecoratedTwoPhaseCommitTransactionManager`.
N/A
N/A
=> Improve DecoratedDistributedTransactionManager and DecoratedTwoPhaseCommitTransactionManager

README.md
This PR adds a link to the ScalarDB design doc in the root-level README. Since we added the same in the README in the [scalar-labs/scalardl repository](https://github.com/scalar-labs/scalardl) recently, we should do the same here for consistency.
- Previous PR for the README in this repository:
- https://github.com/scalar-labs/scalardb/pull/2611
- Similar PR for the README in the **scalar-labs/scalardl repository:**
- https://github.com/scalar-labs/scalardl/pull/128
- Added a link to the ScalarDB design doc on the docs site.
N/A
N/A
=> Add link to ScalarDB design doc in README

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommand.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/DirectoryUtils.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/FileUtils.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/InvalidFilePathException.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/DirectoryUtilsTest.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/FileUtilsTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2616
- **Commit to backport:** c242d80b44265d1661f88199a4af6932583b4452
```console
git checkout 3.14-pull-2616 &&
git cherry-pick --no-rerere-autoupdate -m1 c242d80b44265d1661f88199a4af6932583b4452
```
Thank you!
=> Backport to branch(3.14) : Add util classes for data loader CLI

core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java, core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
This PR addresses the following bug.
With DynamoDB and using the namespace prefix setting `scalar.db.dynamo.namespace.prefix`. The namespace returned by `DistributedStorageAdmin.getNamespaceNames()` contains the prefix, while it should not.
N/A
- `DynamoAdmin.getNamespaceNames()` properly removes the prefix from the namespace names
-  Fixed the associated faulty unit test 
N/A
Fixed an issue with `DistributedStorageAdmin.getNamespaceNames()` API when using the DynamoDB storage with the namespace prefix setting `scalar.db.dynamo.namespace.prefix`. The namespace names …
=> Fix for `admin.getNamespaceNames()` when used with DynamoDB with the namespace prefix setting

core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcUtilsTest.java
This PR updates the JDBC storage to use `Connection.setReadOnly()` to optimize read operations.
For details about the `Connection.setReadOnly()` method, see:  
https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#setReadOnly-boolean-
N/A
- Updated the JDBC storage to use `Connection.setReadOnly()` for the Get and Scan operations.
N/A
N/A
=> Optimize JDBC storage by using Connection.setReadOnly()

core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcUtilsTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2651
- **Commit to backport:** a763467df31151c38810e16c3b0d474b31c509f7
```console
git checkout 3-pull-2651 &&
git cherry-pick --no-rerere-autoupdate -m1 a763467df31151c38810e16c3b0d474b31c509f7
```
Thank you!
=> Backport to branch(3) : Optimize JDBC storage by using Connection.setReadOnly()

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/ColumnUtils.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/ColumnUtilsTest.java
I have added a catch clause to handle `DateTimeParseException` thrown on value conversion for field `TIMESTAMP` when a value of epoch time `1620822456000` which caused a `java.time.format.DateTimeParseException` during testing and for now it was decided to handle the exception and return a proper error message via log files so the user is informed clearly.
NA
* Added a catch clause for `java.time.format.DateTimeParseException` in column value conversion and also added  a error message to core error class. 
* Added a unit test case for it
For now, adding the proper …
=> Add exception handling for DateTimeParseException

core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Currently, in the prepare-records phase of Consensus Commit, both the transaction ID and version are set as conditions for Put and Delete operations. However, setting only the transaction ID should be sufficient since the transaction ID alone is enough to ensure correctness.
This PR removes the version column from the prepare-records conditions in Consensus Commit.
N/A
- Removed the version column from the prepare-records condition in Consensus Commit
- Updated the code to use only the transaction ID for comparison in the serializable validation phase.
N/A
N/A
=> Remove version from prepare-records condition in Consensus Commit

.github/CODEOWNERS, .github/workflows/assign-dependabot-pr-reviewers.yaml
https://github.com/scalar-labs/scalardb/pull/2681 sets up a `CODEOWNERS` file to automatically assign the ScalarDB team as reviewers to any pull request created. 
This was introduced primarily to assign reviewers for PR created by Dependabot.
However,  setting up `CODEOWNERS` also assigns reviewers for the backport PR, which is not wanted.
Instead, we create a GitHub action to assign reviewers only for PRs created by Dependabot.
- https://github.com/scalar-labs/scalardb/pull/2681
- Add action to assign reviewer to PR that Dependabot creates
- Remove the codeowner file …
=> Add GitHub action to assign reviewers on PR created by Dependabot

core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Currently, we create a `Snapshot.Key` instance from the `Get` object in `CrudHandler`, as shown here:
https://github.com/scalar-labs/scalardb/blob/63520ebb7c7b830032d5aaf0a88431bab2510847/core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java#L79
This approach works for regular Get operations. However, it is incorrect for Get operations using a secondary index, as they do not contain primary key information. In such cases, we should create the `Snapshot.Key` instance from the result of the secondary index Get operation. This bug can lead to unnecessary implicit pre-reads when updating records retrieved by a secondary index Get operation within a transaction.
To fix this issue, this PR updates `CrudHandler` to correctly handle Get operations that use secondary …
=> Handle Get with index correctly in CrudHandler

core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java, core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java, core/src/main/java/com/scalar/db/storage/jdbc/ScannerImpl.java, core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java, core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java, core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java, core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionTest.java
This PR adds a scanner API implementation for JDBC transactions.
Note that we are working on this feature in the `add-scanner-api-to-transaction-abstraction` feature branch.
- https://github.com/scalar-labs/scalardb/pull/2698
- Added a scanner API implementation for JDBC transactions.
N/A
N/A
=> Implement scanner API for JDBC transactions

core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTestBase.java
This PR adds a scanner API implementation for Consensus Commit transactions.
Note that we are working on this feature in the `add-scanner-api-to-transaction-abstraction` feature branch.
- https://github.com/scalar-labs/scalardb/pull/2698
- Added a scanner API implementation for Consensus Commit transactions.
N/A
N/A
=> Implement scanner API for Consensus Commit

data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDbDao.java
Currently, the data loader logs every operation related to DAO operations by default, which is not user-friendly, especially when importing data every get, put is printed to the console. So we should remove this default behavior and add a proper verbose option later in another PR. PTAL. Thank you.
NA
- Remove default logging in the Data Loader DAO
NA
NA
=> Remove default logging in the Data Loader DAO

data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportEventListener.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportManager.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/log/SingleFileImportLogger.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/log/SplitByDataChunkImportLogger.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/CsvImportProcessor.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessor.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/JsonImportProcessor.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/JsonLinesImportProcessor.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/CsvImportProcessorTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/JsonImportProcessorTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/JsonLinesImportProcessorTest.java
This PR refactors the import processors in the data loader and removes the unnecessary usage of the import result status map, which is no longer needed.
Previously, the status map was created and persisted for the entire lifetime of the application. This led to continuous memory growth during large imports, potentially causing excessive memory usage or even out-of-memory (OOM) issues. By removing this map, we reduce memory consumption and improve the overall efficiency and stability of the import process.
Please take a look when you get a chance. Thank you!
NA
- Move `process` method to parent class, as they are the same for import processors
- Remove the usage of the status map for storing import results
> The following is a best-effort checklist. If any items in this checklist are not …
=> Refactor import logic and remove redundant status mapping

core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java, core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ReadOnlyDistributedTransaction.java, core/src/main/java/com/scalar/db/common/StateManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/StateManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/service/TransactionService.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java, core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java, core/src/main/java/com/scalar/db/transaction/singlecrudoperation/SingleCrudOperationTransactionManager.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/singlecrudoperation/SingleCrudOperationTransactionIntegrationTestBase.java
This PR adds a `beginReadOnly()` method to `DistributedTransactionManager` to begin a transaction in read-only mode.
We do not add this method to `TwoPhaseCommitTransactionManager` because ensuring and managing read-only behavior across multiple transaction managers is challenging.
Please note that this feature is being developed in the `support-begin-in-read-only-mode` feature branch, as the changes may cause compile errors in dependent projects. Once all implementations are complete, we will merge this feature branch into the `master` branch.
N/A
Added some inline comments. Please take a look for the details!
> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes …
=> Add beginReadOnly() method to transaction abstraction

data-loader/build.gradle, data-loader/cli/build.gradle, data-loader/core/build.gradle, settings.gradle
This PR fixes the Gradle configuration in the `data-loader` module to resolve the release failure.
N/A
Added some inline comments. Please take a look for the details.
N/A
N/A
=> Fix Gradle configurations in data-loader module

core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java, core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java, core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
This PR adds support for beginning a transaction in read-only mode for JDBC transactions.
Note that this feature is being developed in the `support-begin-in-read-only-mode` feature branch.
- https://github.com/scalar-labs/scalardb/pull/2734
Added some inline comments. Please take a look for the details!
N/A
N/A
=> Support begin in read-only mode for JDBC transactions

core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/config/DatabaseConfig.java, core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java, core/src/main/java/com/scalar/db/storage/cassandra/SelectStatementHandler.java, core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java, core/src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java, core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java, core/src/main/java/com/scalar/db/storage/dynamo/QueryScanner.java, core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/ScannerImpl.java, core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java, core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java, core/src/test/java/com/scalar/db/storage/cassandra/SelectStatementHandlerTest.java, core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java, core/src/test/java/com/scalar/db/storage/cosmos/StatementHandlerTest.java, core/src/test/java/com/scalar/db/storage/dynamo/QueryScannerTest.java, core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTestBase.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2731
- **Commit to backport:** 4c5686cb2b755f712cd3d8e009440d01fe60b1cf
```console
git checkout 3-pull-2731 &&
git cherry-pick --no-rerere-autoupdate -m1 4c5686cb2b755f712cd3d8e009440d01fe60b1cf
```
Thank you!
=> Backport to branch(3) : Add support for scan fetch size in storage adapters

core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ReadOnlyDistributedTransaction.java, core/src/main/java/com/scalar/db/common/StateManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/StateManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/service/TransactionService.java, core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java, core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java, core/src/main/java/com/scalar/db/transaction/singlecrudoperation/SingleCrudOperationTransactionManager.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/singlecrudoperation/SingleCrudOperationTransactionIntegrationTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2749
- **Commit to backport:** 88ccee8a5566bc8c6aa0fde68efcf67ee2b61162
```console
git checkout 3-pull-2749 &&
git cherry-pick --no-rerere-autoupdate -m1 88ccee8a5566bc8c6aa0fde68efcf67ee2b61162
```
Thank you!
=> Backport to branch(3) : Add support for beginning transactions in read-only mode

.github/workflows/ci.yaml, .github/workflows/create-release.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/remove-untagged-images.yaml, .github/workflows/upload-artifacts.yaml, .github/workflows/vuln-check.yaml, data-loader/cli/Dockerfile, data-loader/cli/build.gradle
This PR adds Docker support for the ScalarDB Data Loader CLI. Also, make it part of the CI workflows. PTAL. Thank you.
N/A
- Added a new Dockerfile for the ScalarDB Data Loader CLI
- Updated the `build.gradle` file for the data-loader CLI to support Docker builds
- Modified GitHub workflow files to include the data-loader CLI in the CI/CD pipeline:
- Updated release-snapshot.yaml to build and push the data-loader CLI Docker image
- Updated upload-artifacts.yaml to include the data-loader CLI in the artifact upload process
- Updated create-release.yaml to build and upload the data-loader CLI JAR file
- Updated vuln-check.yaml to include the data-loader CLI in vulnerability scanning
N/A
Added Docker support for the ScalarDB Data Loader CLI, enabling containerized deployment of the data …
=> Add Docker support for ScalarDB Data Loader CLI

core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java
I found the current `com.scalar.db.storage.jdbc.JdbcDatabase#scan` doesn't close the connection when the target table doesn't exist. This PR fixes the issue.
None
- Close the connection for Scan operation in `JdbcDatabase.scan()` whenever an exception is thrown not only when SQLException is thrown, since `IllegalArgumentException` can be thrown when the target table doesn't exist
None
Fixed potential connection leak when using `jdbc` storage and Scan operation fails because the target table doesn't exist
=> Fix potential connection leak when using `jdbc` storage and Scan operation fails because the target table doesn't exist

core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2766
- **Commit to backport:** 644578b1fd323bc784b4fa93bce76317e90c4302
```console
git checkout 3.14-pull-2766 &&
git cherry-pick --no-rerere-autoupdate -m1 644578b1fd323bc784b4fa93bce76317e90c4302
```
Thank you!
=> Backport to branch(3.14) : Fix potential connection leak when using `jdbc` storage and Scan operation fails because the target table doesn't exist

build.gradle
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2772
- **Commit to backport:** 4054e6b568cc4bfb1224f5261058b24b828a3f33
```console
git checkout 3.14-pull-2772 &&
git cherry-pick --no-rerere-autoupdate -m1 4054e6b568cc4bfb1224f5261058b24b828a3f33
```
Thank you!
=> Backport to branch(3.14) : Fix CVE-2025-49146

core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2766
- **Commit to backport:** 644578b1fd323bc784b4fa93bce76317e90c4302
```console
git checkout 3.15-pull-2766 &&
git cherry-pick --no-rerere-autoupdate -m1 644578b1fd323bc784b4fa93bce76317e90c4302
```
Thank you!
=> Backport to branch(3.15) : Fix potential connection leak when using `jdbc` storage and Scan operation fails because the target table doesn't exist

core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ParallelExecutorTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
This PR renames some methods of `CommitHandler` to align with the [Consensus Commit documentation](https://scalardb.scalar-labs.com/docs/latest/consensus-commit/).
N/A
- Renamed some methods of `CommitHandler`.
N/A
N/A
=> Rename methods of CommitHandler

core/src/main/java/com/scalar/db/transaction/consensuscommit/AbstractMutationComposer.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposer.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposerTest.java
This PR updates the code to remove before images after committing or rolling back records in Consensus Commit to reduce disk usage.
N/A
- Updated `CommitMutationComposer` and `RollbackMutationComposer` to set the before image columns to null.
N/A
Updated the code to remove before images after committing or rolling back records in Consensus Commit to reduce disk usage.
=> Remove before images after committing or rolling back records in Consensus Commit

core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Currently, we always update the read set when the same record is read multiple times from storage. However, this behavior can lead to anomalies like lost updates.
You can reproduce the issue with the following test:
https://github.com/scalar-labs/scalardb/pull/2797/files#diff-7d8b7163e906546d45d9a7b662f97eb671e39030217ab77ef22325b0f74c2b5eR5898-R5981
In the test, two slightly different Get operations are used to force reading the same record multiple times from storage and bypass snapshot reads.
N/A
- Updated the code to prevent overwriting read set.
N/A
Fixed an …
=> Prevent overwriting read set in Consensus Commit

core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcTestUtils.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineDb2.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMariaDB.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcUtilsTest.java, core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2801
- **Commit to backport:** f3969d9ce521db900d042bbe76d2b7c3b6c90bb9
```console
git checkout 3-pull-2801 &&
git cherry-pick --no-rerere-autoupdate -m1 f3969d9ce521db900d042bbe76d2b7c3b6c90bb9
```
Thank you!
=> Backport to branch(3) : Optimize JDBC adaptor for MySQL

core/src/main/java/com/scalar/db/common/CoreError.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/MutationsGrouper.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/OnePhaseCommitMutationComposer.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommitTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/MutationsGrouperTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/OnePhaseCommitMutationComposerTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
This PR adds support for one-phase commit optimization in Consensus Commit. Users can enable it by setting the property `scalar.db.consensus_commit.one_phase_commit.enabled` to `true`. The default is `false`.
The basic idea is that if the storage can execute all mutations in a transaction atomically, we don’t need two-phase commit mechanisms such as prepare-records, commit-state, and then commit-records. Instead, we can simply perform commit-records in a single phase.
N/A
Added inline comments. Please take a look for the details.
N/A
Added support for one-phase commit …
=> Support one-phase commit optimization in Consensus Commit

.github/dependabot.yml, .github/workflows/scheduled-vuln-check.yaml
This PR updates the Scheduled Vulnerability Check and Dependabot configuration for the ScalarDB 3.16 release.
N/A
- Updated Scheduled Vulnerability Check and the Dependabot configuration.
N/A
N/A
=> Update Scheduled Vulnerability Check and Dependabot configuration

README.md
This PR updates the ScalarDB dependency version to 3.16.0 in README, as ScalarDB 3.16.0 has been released.
N/A
- Updated ScalarDB dependency version to 3.16.0.
N/A
N/A
=> Update ScalarDB dependency version to 3.16.0 in README

core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitterTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ParallelExecutorTest.java
This PR makes small adjustments to the unit tests.
N/A
Added inline comments. Please take a look for the details.
N/A
N/A
=> Minor fixes to unit tests

core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommitTest.java
This PR fixes error handling for one-phase commit.
N/A
Added an inline comment. Please take a look for the details.
N/A
Fixed a bug where a CommitException was thrown when committing a transaction, even though the transaction was actually committed.
=> Fix error handling for one-phase commit

core/src/main/java/com/scalar/db/storage/cassandra/BatchHandler.java, core/src/main/java/com/scalar/db/storage/cassandra/MutateStatementHandler.java, core/src/test/java/com/scalar/db/storage/cassandra/BatchHandlerTest.java, core/src/test/java/com/scalar/db/storage/cassandra/InsertStatementHandlerTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2827
- **Commit to backport:** e49e38c86c916a0260a0cadec9d5823eadf6eb44
```console
git checkout 3.14-pull-2827 &&
git cherry-pick --no-rerere-autoupdate -m1 e49e38c86c916a0260a0cadec9d5823eadf6eb44
```
Thank you!
=> Backport to branch(3.14) : Fix error handling for mutations in Cassandra

core/src/main/java/com/scalar/db/storage/cassandra/BatchHandler.java, core/src/main/java/com/scalar/db/storage/cassandra/MutateStatementHandler.java, core/src/test/java/com/scalar/db/storage/cassandra/BatchHandlerTest.java, core/src/test/java/com/scalar/db/storage/cassandra/InsertStatementHandlerTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2827
- **Commit to backport:** e49e38c86c916a0260a0cadec9d5823eadf6eb44
```console
git checkout 3.13-pull-2827 &&
git cherry-pick --no-rerere-autoupdate -m1 e49e38c86c916a0260a0cadec9d5823eadf6eb44
```
Thank you!
=> Backport to branch(3.13) : Fix error handling for mutations in Cassandra

core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommit.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommitTest.java
When I implemented the one-phase commit optimization, I somehow thought that we couldn’t support enabling both group commit and one-phase commit. However, on second thought, I realized that we actually can. This PR addresses that.
N/A
- Updated the logic to cancel group commit in the following situations:
- When canOnePhaseCommit() throws an `Exception`
- When a one-phase commit is performed
N/A
Fixed a bug where group commit did not work correctly with one-phase commit.
=> Fix behavior of group commit with one-phase commit

.github/workflows/release-snapshot.yaml, .github/workflows/upload-artifacts.yaml, build.gradle, core/build.gradle, data-loader/core/build.gradle, integration-test/build.gradle, schema-loader/build.gradle
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2849
- **Commit to backport:** 7e746c503069bef778aca63a49335189bd94b7a4
```console
git checkout 3.16-pull-2849 &&
git cherry-pick --no-rerere-autoupdate -m1 7e746c503069bef778aca63a49335189bd94b7a4
```
Thank you!
=> Backport to branch(3.16) : Use JReleaser to release artifacts in Maven Central

.github/workflows/release-snapshot.yaml, .github/workflows/upload-artifacts.yaml, build.gradle, core/build.gradle, integration-test/build.gradle, schema-loader/build.gradle
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2849
- **Commit to backport:** 7e746c503069bef778aca63a49335189bd94b7a4
```console
git checkout 3.14-pull-2849 &&
git cherry-pick --no-rerere-autoupdate -m1 7e746c503069bef778aca63a49335189bd94b7a4
```
Thank you!
=> Backport to branch(3.14) : Use JReleaser to release artifacts in Maven Central

.github/workflows/release.yaml, .github/workflows/upload-artifacts.yaml
This PR is an addendum change of https://github.com/scalar-labs/scalardb/pull/2849.
- https://github.com/scalar-labs/scalardb/pull/2849
- Removed unnecessary secrets
N/A
N/A
=> [addendum] Use JReleaser to release artifacts in Maven Central

.github/workflows/release.yaml, .github/workflows/upload-artifacts.yaml
In https://github.com/scalar-labs/scalardb/pull/2849, I forgot to pass the necessary secrets to the `upload-artifacts` workflow. This PR addresses the issue.
- https://github.com/scalar-labs/scalardb/pull/2849
- Updated the workflows to pass or receive the necessary secrets.
N/A
N/A
=> Pass necessary secrets to release workflow

.github/workflows/release-snapshot.yaml, .github/workflows/upload-artifacts.yaml
When publishing artifacts to Maven Central using the `jreleaserDeploy` task, we encountered an OOM error. To address this, this PR increases the heap size allocated to the `jreleaserDeploy` task.
N/A
- Increased the heap size for the `jreleaserDeploy` task.
N/A
N/A
=> Increase heap size for jreleaserDeploy task

core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2888
- **Commit to backport:** bf49281ebd019623f3f82ca90af39fd5e5c5785b
```console
git checkout 3.16-pull-2888 &&
git cherry-pick --no-rerere-autoupdate -m1 bf49281ebd019623f3f82ca90af39fd5e5c5785b
```
Thank you!
=> Backport to branch(3.16) : Fix Oracle engine to support multiple Oracle users for index operations

.github/workflows/ci.yaml, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java, core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageEnv.java
This PR changes the default database for integration tests to PostgreSQL, which offers the best performance among the supported databases in ScalarDB.
N/A
- Changed the default database for integration tests to PostgreSQL
N/A
N/A
=> Use PostgreSQL in integration tests by default

.github/workflows/ci.yaml, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java, core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageEnv.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2894
- **Commit to backport:** 819ae90540417d49cd73976f6ba976ee94654290
```console
git checkout 3.13-pull-2894 &&
git cherry-pick --no-rerere-autoupdate -m1 819ae90540417d49cd73976f6ba976ee94654290
```
Thank you!
=> Backport to branch(3.13) : Use PostgreSQL in integration tests by default

.github/workflows/ci.yaml, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java, core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageEnv.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2894
- **Commit to backport:** 819ae90540417d49cd73976f6ba976ee94654290
```console
git checkout 3.14-pull-2894 &&
git cherry-pick --no-rerere-autoupdate -m1 819ae90540417d49cd73976f6ba976ee94654290
```
Thank you!
=> Backport to branch(3.14) : Use PostgreSQL in integration tests by default

.github/workflows/ci.yaml, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java, core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageEnv.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2894
- **Commit to backport:** 819ae90540417d49cd73976f6ba976ee94654290
```console
git checkout 3.15-pull-2894 &&
git cherry-pick --no-rerere-autoupdate -m1 819ae90540417d49cd73976f6ba976ee94654290
```
Thank you!
=> Backport to branch(3.15) : Use PostgreSQL in integration tests by default

.github/workflows/permission-check.yaml, core/build.gradle, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminPermissionIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcPermissionIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcPermissionTestUtils.java
This PR adds a permission test for major JDBC databases, specifically MySQL, PostgreSQL, Oracle, and SQL Server under ScalarDB. To check what permissions are required for all ScalarDB operations, all DistributedStorage and DistributedStorageAdmin methods are tested. This is a third step of the permission tests project. Permission tests for other JDBC backends will be added in the future.
- https://github.com/scalar-labs/scalardb/pull/2822
- https://github.com/scalar-labs/scalardb/pull/2847
- Added a new integration test for the implementations of DistributedStorage in JDBC adapter with MySQL, PostgreSQL, Oracle, and SQL Server engines.
- Added a new integration test for the implementations of DistributedStorageAdmin in JDBC adapter with MySQL, PostgreSQL, Oracle, and SQL Server engines.
- …
=> Add JDBC database permission test

.github/workflows/manual-vuln-check.yaml, .github/workflows/scheduled-vuln-check.yaml, .github/workflows/vuln-check.yaml
This PR removes the `CR_PAT` secret from all vulnerability check workflows as it is no longer required.
- scalar-labs/actions#23
- Removed `CR_PAT` secret requirement from `vuln-check.yaml` workflow
- Removed `CR_PAT` secret passing from `manual-vuln-check.yaml` workflow
- Removed `CR_PAT` secret passing from all jobs in `scheduled-vuln-check.yaml` workflow
- [xI have updated the documentation to reflect the changes.
This PR depends on scalar-labs/actions#23, which must be merged first.
Removed the `CR_PAT` secret from all vulnerability check workflows.
=> Remove CR_PAT secret from vuln-check workflows

integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
This PR fixes the test to use a getter to retrieve the object name. This fix addresses on omission from the following PR:
#2908 
#2908 
Fix to use getter to get `TABLE1` and `COL_NAME2` in `DistributedStorageAdminIntegrationTestBase`
N/A
N/A
=> Fix to use getter to get object names

.github/workflows/assign-dependabot-pr-reviewers.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2958
- **Commit to backport:** cb1cbaaf2343b53804fe7e9f5543d0f3adf949be
```console
git checkout 3.15-pull-2958 &&
git cherry-pick --no-rerere-autoupdate -m1 cb1cbaaf2343b53804fe7e9f5543d0f3adf949be
```
Thank you!
=> Backport to branch(3.15) : Fix Action to assign reviewers for Dependabot PRs

.github/workflows/assign-dependabot-pr-reviewers.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2958
- **Commit to backport:** cb1cbaaf2343b53804fe7e9f5543d0f3adf949be
```console
git checkout 3.13-pull-2958 &&
git cherry-pick --no-rerere-autoupdate -m1 cb1cbaaf2343b53804fe7e9f5543d0f3adf949be
```
Thank you!
=> Backport to branch(3.13) : Fix Action to assign reviewers for Dependabot PRs

.github/workflows/assign-dependabot-pr-reviewers.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2958
- **Commit to backport:** cb1cbaaf2343b53804fe7e9f5543d0f3adf949be
```console
git checkout 3.14-pull-2958 &&
git cherry-pick --no-rerere-autoupdate -m1 cb1cbaaf2343b53804fe7e9f5543d0f3adf949be
```
Thank you!
=> Backport to branch(3.14) : Fix Action to assign reviewers for Dependabot PRs

integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminPermissionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStoragePermissionIntegrationTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2994
- **Commit to backport:** 2f021d490d2b4d68ebf38a65bb31321bc5a5fc0d
```console
git checkout 3-pull-2994 &&
git cherry-pick --no-rerere-autoupdate -m1 2f021d490d2b4d68ebf38a65bb31321bc5a5fc0d
```
Thank you!
=> Backport to branch(3) : Add a new line between ARRANGE and ACT/ASSERT sections in permission tests

integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminPermissionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStoragePermissionIntegrationTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2994
- **Commit to backport:** 2f021d490d2b4d68ebf38a65bb31321bc5a5fc0d
```console
git checkout 3.13-pull-2994 &&
git cherry-pick --no-rerere-autoupdate -m1 2f021d490d2b4d68ebf38a65bb31321bc5a5fc0d
```
Thank you!
=> Backport to branch(3.13) : Add a new line between ARRANGE and ACT/ASSERT sections in permission tests

core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminIntegrationTestWithJdbcDatabase.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminCaseSensitivityIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseCrossPartitionScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultiplePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSecondaryIndexIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSingleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSinglePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/SingleCrudOperationTransactionAdminIntegrationTestWithJdbcDatabase.java, core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminIntegrationTest.java, core/src/main/java/com/scalar/db/common/CoreError.java, core/src/main/java/com/scalar/db/common/checker/OperationChecker.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcOperationChecker.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineDb2.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java, core/src/test/java/com/scalar/db/common/checker/OperationCheckerTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcOperationCheckerTest.java, core/src/test/java/com/scalar/db/storage/jdbc/RdbEngineDb2Test.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageCrossPartitionScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/3000
- **Commit to backport:** f1765d6aa7707205efe3d5082d9cd623c47ebe82
```console
git checkout 3-pull-3000 &&
git cherry-pick --no-rerere-autoupdate -m1 f1765d6aa7707205efe3d5082d9cd623c47ebe82
```
Thank you!
=> Backport to branch(3) : For IBM Db2, change the data type for BLOB column to support storing up to 2GB
