scalar-labs/scalardb

- jepsen/scalardb/src/scalardb/runner.clj
You can use any tarball cassandra for Jepsen testing
For example,
- local cassandra tarball
```
$ lein run test --test transfer --tarball file:///my/cassandra/cassandra.tar.gz
```
- other version
```
$ lein run test --test transfer --tarball http://archive.apache.org/dist/cassandra/3.11.1/apache-cassandra-3.11.1-bin.tar.gz
```
> support tarball cassandra

- tools/schema/internal/parser/parser.go
Remove the method to disambiguate the parsing input as it seems not necessary anymore with the participle version 0.2.0.
> Fix the parsing error caused by the 3rd party parsing library update

- src/test/java/com/scalar/database/util/TransactionUtility.java
To become the performance of Scalar DB stable, I've changed the compaction strategy of a user table to LCS as default in `TransactionUtility.java`
> add compaction strategy

- jepsen/scalardb/project.clj
- jepsen/scalardb/src/scalardb/core.clj
- jepsen/scalardb/src/scalardb/runner.clj
- jepsen/scalardb/src/scalardb/transfer.clj
Jepsen crash tests often failed because a client couldn't get the final balances due to disconnection to the cluster.
I've added reconnection when many failures happen.
- A client has DistributedStorageService and DistributedTransactionService
- After many failures, a client tries to reconnect to the cluster
- Close all connections at the end
> a client reconnects to the cluster when many failures

- jepsen/scalardb/project.clj
- jepsen/scalardb/src/scalardb/core.clj
- jepsen/scalardb/src/scalardb/transfer.clj
- Modified reconnection to the cluster
- Skip an `op` when there is no `DistributedTransactionService`
- Modified checking the coordinator table
> Fix jepsen reconnection

- jepsen/scalardb/src/scalardb/transfer.clj
When a long test ran, the checker's timeline which made an HTML timeline of history failed due to OOM.
We haven't seen the HTML and perf for now.
So, I want to remove them.
> Remove perf and timeline for the checker to avoid OOM

- jepsen/scalardb/src/scalardb/transfer.clj
This PR changes the range of the amount.
I couldn't specify a wrong transaction which causes inconsistency.
That's because too many transactions which transferred the same amount were requested.
> to specify a transaction by an amount

- jepsen/scalardb/src/scalardb/transfer.clj
When unknown transactions are checked and all records are read by a transaction for checking the consistency, it sometimes fails because nemesis is still working.
To avoid this issue, [`terminate-nemesis`](https://github.com/scalar-labs/jepsen/blob/d1a49b1d256366c2b4a717c143e5d0656bef5eea/cassandra/src/cassandra/conductors.clj#L101) is inserted. This function stops the current failure.
And, I want to add checking if the transaction service exists before reading all records.
> Terminate nemesis before checking the state of the end

- jepsen/scalardb/README.md
- jepsen/scalardb/src/scalardb/runner.clj
- jepsen/scalardb/src/scalardb/transfer_append.clj
https://scalar-labs.atlassian.net/browse/DLT-2052
Adds an append test to Jepsen, and slightly updates the readme so that getting in up and running can be done from one place.
By the way, is there any particular reason why the jepsen tests are in the scalardb directory? Is it possible to fork jepsen and keep the test in there, or alternatively, to fork and create a new branch and leave the test in there (similar to how Riptano kept its Cassandra tests in the cassandra branch: https://github.com/riptano/jepsen).
I ask because it quite inconvenient to have to clone two repos, jepsen and scalardb, then copy over the jepsen tests from scalardb to jepsen, in order to run the tests. Then after any changes, copying the files back to the scalardb directory.
Thank you!
> New jepsen test

- src/main/java/com/scalar/database/api/DistributedTransactionManager.java
- src/main/java/com/scalar/database/service/TransactionService.java
- src/main/java/com/scalar/database/transaction/consensuscommit/ConsensusCommitManager.java
This is a scalardb part of [the story](https://scalar-labs.atlassian.net/browse/DLT-1691).
Usually we should use `start()` or `start(isolation)`, but accepting user-provided transaction id if user can be responsible for uniqueness of the transaction id.
> start with an user-provided transaction ID

- .circleci/config.yml
The verification test in CircleCI assumes there is non-versioned scalardb library, so if a version is specified in the build.gradle, the CI fails. (This is what happening in the current CircieCI)
So, this PR makes it able to work in any version.
> make it work with any scalardb version

- scripts/sample_schema/tx_transfer.cql
I want to use the return value of applying this schema in a script and usually it is non-zero because the coordinator keyspace already exists and without the IF NOT EXISTS cqlsh will send a return value of 2.
This is 1/2 of the fix for https://scalar-labs.atlassian.net/browse/DLT-3413.
> Add "IF NOT EXISTS" in a number of places

- src/test/java/com/scalar/database/util/AccountBalanceTransferHandler.java
Added `getMessage()` when readRecords fails to investigate the failure of `readRecordsWithRetry`
> getMessage when readRecords fails

- src/main/java/com/scalar/database/storage/cassandra4driver/ConditionSetter.java
- src/main/java/com/scalar/database/storage/cassandra4driver/DeleteStatementHandler.java
- src/main/java/com/scalar/database/storage/cassandra4driver/InsertStatementHandler.java
- src/main/java/com/scalar/database/storage/cassandra4driver/MutateStatementHandler.java
- src/main/java/com/scalar/database/storage/cassandra4driver/StatementHandler.java
- src/main/java/com/scalar/database/storage/cassandra4driver/UpdateStatementHandler.java
- src/test/java/com/scalar/database/storage/cassandra4driver/DeleteStatementHandlerTest.java
- src/test/java/com/scalar/database/storage/cassandra4driver/InsertStatementHandlerTest.java
- src/test/java/com/scalar/database/storage/cassandra4driver/UpdateStatementHandlerTest.java
- Change the import paths
- Use [`Relation`](https://docs.datastax.com/en/drivers/java/4.3/com/datastax/oss/driver/api/querybuilder/relation/Relation.html) for where clause
- Modify `ConditionSetter` to use `BuildableQuery` and [`Condition`](https://docs.datastax.com/en/drivers/java/4.3/com/datastax/oss/driver/api/querybuilder/condition/Condition.html) and update it by replacing the `BuildableQuery` instance
- Get `BuildableQuery` instance after all conditions are set
- `StatementHandler#bind()` returns [`BoundStatementBuilder`](https://docs.datastax.com/en/drivers/java/4.3/com/datastax/oss/driver/api/core/cql/BoundStatementBuilder.html)
- A mutable `builder` will be set consistency level and will be built for execution
- Remove the cache of prepared statements because the driver 4.x …
> [Driver4] Add statement handlers for mutation

- src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTest.java
- src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
- src/main/java/com/scalar/db/exception/transaction/CommitRuntimeException.java
- src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
- src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
- src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
- src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
- src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
It fixes part of https://github.com/scalar-labs/scalardb/issues/65 .
The fix should probably be called workaround since it aborts if it reads empty record. So the write skew case with empty records can not happen in Scalar DB. 
It's a little limitation in the current implementation but I think there seems nothing else we can do since we detect conflicts by using records.
> fix write skew issue

- docs/design.md
- src/main/java/com/scalar/db/api/ConditionalExpression.java
- src/main/java/com/scalar/db/api/Delete.java
- src/main/java/com/scalar/db/api/DeleteIf.java
- src/main/java/com/scalar/db/api/DeleteIfExists.java
- src/main/java/com/scalar/db/api/Get.java
- src/main/java/com/scalar/db/api/Mutation.java
- src/main/java/com/scalar/db/api/Operation.java
- src/main/java/com/scalar/db/api/Put.java
- src/main/java/com/scalar/db/api/PutIf.java
- src/main/java/com/scalar/db/api/PutIfExists.java
- src/main/java/com/scalar/db/api/PutIfNotExists.java
- src/main/java/com/scalar/db/api/Scan.java
- src/main/java/com/scalar/db/api/Selection.java
- src/test/java/com/scalar/db/api/DeleteTest.java
- src/test/java/com/scalar/db/api/GetTest.java
- src/test/java/com/scalar/db/api/PutTest.java
- src/test/java/com/scalar/db/api/ScanTest.java
I noticed Operations don't have hashCode, so this PR adds hashCode for all Operations related class.
(Scan.hashCode is needed to put Scan to Map in future PR for https://scalar-labs.atlassian.net/browse/DLT-5833 )
> add hashCode to Operations

- src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTest.java
- src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
- src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
Another workaround for a case where scan reads empty records in  #65.
This could technically be fixed by writing DELETE record but it is even tricker since clustering key might be unknown in scan.
> avoid another write skew case (could be tentative workaround)

- src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTest.java
- src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
- src/main/java/com/scalar/db/api/DistributedTransactionManager.java
- src/main/java/com/scalar/db/api/SerializableStrategy.java
- src/main/java/com/scalar/db/service/TransactionService.java
- src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
- src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
- src/main/java/com/scalar/db/transaction/consensuscommit/SerializableStrategy.java
- src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
- src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
- src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
This PR contains updates for another serializable strategy proposed by @Yonezawa-T2  in
https://github.com/scalar-labs/scalardb/pull/70 .
There are still some unknowns as discussed in #70  but I think it is a good alternative so I actually implemented it as yet another `SerializableStrategy` and named it `Extra Read` strategy (the existing strategy is now called `Extra Write` strategy). We will do benchmarking and verification once it is merged.
> add another serializable strategy

- src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTest.java
- src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
- src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
- src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
- src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
- src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Basically renamed `toSerializable` to `toSerializableWithExtraWrite` and updated the for loop with usual `for` instead of using lambda `forEach` for consistency with extra read strategy added in #72. Note that the logic is not changed.
Additionally, some related unit tests are added.
> refactor extra write and add/update some related tests

- src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTest.java
- src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
- src/main/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposer.java
- src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java
- src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java
- src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
- src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Decided not to introduce logical delete for now so make Extra-write work with non-existing read records.
https://github.com/scalar-labs/scalardb/issues/65
> Make extra-write strategy work for reading non-existing records

- src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTest.java
- src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
- src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
https://scalar-labs.atlassian.net/browse/DLT-6038 (internal)
As the title says, EXTRA_WRITE is specified in tests explicitly if not specified. Test names are changed accordingly.
> specify serializable strategy explicitly in tests and update test names based on it

- src/main/java/com/scalar/db/storage/cosmos/MapVisitor.java
- src/main/java/com/scalar/db/storage/cosmos/ResultImpl.java
- src/test/java/com/scalar/db/storage/cosmos/MapVisitorTest.java
- src/test/java/com/scalar/db/storage/cosmos/ResultImplTest.java
https://scalar-labs.atlassian.net/browse/DLT-7035
I found a bug about reading blob value from Cosmos DB.
In this modification, Scalar DB requests a write of blob value, does not convert it to `String`, and Cosmos DB will convert to String by Base64 encoding.
When reading the blob value, Scalar DB decodes the value because Cosmos DB returns it as String.
I tested the blob conversion to String in Scalar DB before. It worked well when the blob was short.
This PR supports long blob values.
> Fix reading blob from Cosmos DB

- src/main/java/com/scalar/db/storage/cosmos/ResultImpl.java
#89
Scalar DB failed to cast to a long value on Cosmos DB.
```
Execution error (ClassCastException) at com.scalar.db.storage.cosmos.ResultImpl/convert (ResultImpl.java:142).
java.lang.Integer cannot be cast to java.lang.Long
```
A value read from Cosmos DB is a Number. Some values like zero were cast to Integer.
Cast a number via Number
> Fix the cast for numbers on Cosmos DB

- tools/scalar-schema/src/scalar_schema/dynamo_schema.clj
To specify the RU for DynamoDB.
- RU couldn't set for DynamoDB
```
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
```
- The given type wasn't correct for `readCapacityUnits()` and `writeCapacityUnits()`
- Cast to Long
> fix RU type for DynamoDB

- src/main/java/com/scalar/db/storage/dynamo/TableMetadata.java
- src/test/java/com/scalar/db/storage/dynamo/TableMetadataTest.java
- When no clustering key exists, NullPointerException was thrown.
```
Execution error (NullPointerException) at com.scalar.db.storage.dynamo.TableMetadata/convert (TableMetadata.java:61).
```
- The metadata couldn't be converted from the values on the metadata table because the value was null when no clustering key
- When no clustering key, the name set of clustering keys is set as an empty set.
> fix metadata

- src/main/java/com/scalar/db/storage/dynamo/DynamoMutation.java
- src/test/java/com/scalar/db/storage/dynamo/DynamoMutationTest.java
We can simplify the condition for IfNotExists and IfExists because we have `concatenatedClusteringKey` attribute after supporting multiple clustering keys.
> Simplify the condition

- tools/scalar-schema/src/scalar_schema/dynamo_schema.clj
https://scalar-labs.atlassian.net/browse/DLT-7404
https://scalar-labs.atlassian.net/browse/DLT-7499
- Schema tool failed to create a secondary index which had more than 20 non-key attributes
```
'localSecondaryIndexes.1.member.projection.nonKeyAttributes' failed to satisfy constraint: Member must have length less than or equal to 20
```
- The API `nonKeyAttributes()` couldn't receive more than 20 attributes
- Use `ProjectionType/ALL` instead of `ProjectionType/INCLUDE` to set all attributes
> Fix the schema tool to modify the secondary index table

- src/main/java/com/scalar/db/storage/dynamo/DynamoMutation.java
- src/main/java/com/scalar/db/storage/dynamo/DynamoOperation.java
- src/main/java/com/scalar/db/storage/dynamo/PutStatementHandler.java
- src/test/java/com/scalar/db/storage/dynamo/DynamoMutationTest.java
https://scalar-labs.atlassian.net/browse/DLT-7500
To use column names reserved by DynamoDB like `date`, `user`.
Set aliases of columns and the name map to the update request.
> Alias for update expression

- src/main/java/com/scalar/db/storage/dynamo/ResultImpl.java
- src/main/java/com/scalar/db/storage/dynamo/ValueBinder.java
- src/test/java/com/scalar/db/storage/dynamo/ResultImplTest.java
https://scalar-labs.atlassian.net/browse/DLT-7534
- Put with a null value failed
```
Caused by: com.scalar.db.exception.storage.ExecutionException: Invalid UpdateExpression: An expression attribute value used in expression is not defined; ...
```
- A null string(bytes) could not be defined as an AttributeValue
```
:val0=AttributeValue(S=foo, SS=[], NS=[], BS=[], M={}, L=[])
:val4=AttributeValue(SS=[], NS=[], BS=[], M={}, L=[])
```
- A null string(bytes) is set as a null type value
```
:val4=AttributeValue(SS=[], NS=[], BS=[], M={}, L=[], NUL=true)
```
> fix for a null value

- src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java
- src/test/java/com/scalar/db/storage/dynamo/BatchHandlerTest.java
Similar to #106
Sorry, I forgot to add the aliases of columns for a bach operation.
https://scalar-labs.atlassian.net/browse/DLT-7500
To use column names reserved by DynamoDB like `date`, `user`.
Set aliases of columns and the name map to the update request for a batch operation.
> use aliases of columns for batch

- tools/scalar-schema/src/scalar_schema/cassandra.clj
- tools/scalar-schema/src/scalar_schema/cosmos.clj
Fixed a bug about database existence before deleting.
- Failed to delete all tables for Cassandra and Cosmos DB
- For DynamoDB, it worked well because each table has a unique name
- Tried deleting non-existing databases
- Check database existence before deleting
> Check existence before deleting

- tools/scalar-schema/src/scalar_schema/common.clj
Fixed the ordering because the clustering keys were reordered by Set
> Fix clustering key order

- tools/scalar-schema/src/scalar_schema/core.clj
In case of an error in the scalar-schema CLI options, it should fail with an exit status other than `0`.
It is needed to notify tools like Ansible and Terraform of the result of the scalar-schema tool.
For example, if the argument for the `--region` option is missing, it should fail with a status other than `0` to tell Terraform to abort.
The following case should not complete successfully.
```
module.scalardl.module.scalardl_blue.module.scalardl_provision.null_resource.scalardl_schema[0] (remote-exec): ERROR: ["Missing required argument for \"--region REGION\""]
...
module.scalardl.module.scalardl_blue.module.scalardl_provision.null_resource.scalardl_schema[0]: Creation complete after 8s [id=5751361347562494241]
```
https://scalar-labs.atlassian.net/browse/DLT-7415
> Update scalar-schema tool to exit with status 1 if errors in CLI options

- tools/scalar-schema/README.md
- tools/scalar-schema/project.clj
- tools/scalar-schema/sample_schema/sample_schema.json
- tools/scalar-schema/src/scalar_schema/core.clj
- tools/scalar-schema/src/scalar_schema/cosmos.clj
- tools/scalar-schema/src/scalar_schema/dynamo.clj
- tools/scalar-schema/src/scalar_schema/dynamo/auto_scaling.clj
- tools/scalar-schema/src/scalar_schema/dynamo/common.clj
- tools/scalar-schema/test/scalar_schema/common_test.clj
https://scalar-labs.atlassian.net/browse/DLT-7579
To register ScalableTarget and set ScalingPocily to each table.
ScalableTarget specifies the minimum and the maximum Capacity Unit.
ScalingPolicy specifies the interval and the usage rate to scale in/out the CU.
Ref. https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/AutoScaling.html
> Support auto-scaling for DynamoDB

- tools/scalar-schema/src/scalar_schema/dynamo/auto_scaling.clj
https://scalar-labs.atlassian.net/browse/DLT-7716
- Failed to create tables without `-r` option
```
Exception in thread "main" java.lang.ClassCastException: Cannot cast java.lang.Long to java.lang.Integer
at java.lang.Class.cast(Class.java:3369)
at clojure.lang.Reflector.boxArg(Reflector.java:552)
at clojure.lang.Reflector.boxArgs(Reflector.java:585)
at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:132)
at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:102)
at scalar_schema.dynamo.auto_scaling$make_scaling_request.invokeStatic(auto_scaling.clj:42)
at scalar_schema.dynamo.auto_scaling$enable_auto_scaling$fn__3265.invoke(auto_scaling.clj:93)
at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
at …
```
> fix the default type for auto-scaling

- src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
- src/main/java/com/scalar/db/storage/cosmos/PutStatementHandler.java
- src/test/java/com/scalar/db/storage/cosmos/PutStatementHandlerTest.java
- tools/scalar-schema/stored_procedure/mutate.js
https://scalar-labs.atlassian.net/browse/DLT-7425
- Non-updated columns are removed when partial updating
- before updating
| partition key | clustering key | c1 | c2 |
--|--|--|--
| 0 | 1 | "inserted" |  null |
- after updating the only c2, c1's value is removed
| partition key | clustering key | c1 | c2 |
--|--|--|--
| 0 | 1 | null |  "new" |
- [Cosmos DB doesn't support partial update](https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/6693091-be-able-to-do-partial-updates-on-document#%7Btoggle_previous_statuses%7D)
- Use the stored procedure to read the existing record and update it
- Insert a new record when the record doesn't exist
> partial update for Cosmos DB

- build.gradle
Make it include the integration tests of `transaction/consensuscommit, which was excluded by a previous commit.
Somehow,
`srcDir file('src/integration-test/java/com/scalar/db/transaction/consensuscommit')`
or 
`exclude 'src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java'`
doesn't work.
So, I came to the current solution. But I'm not sure if it's the best way.
Please suggest if you know a better way.
I'll fix the broken test in another PR.
> Include transaction/consensuscommit

- src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
- src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
While adding the JDBC adapter, I found some scanners in CrudHandler and Snapshot are not closed. We should close them.
> Some scanners in CrudHandler and Snapshot are not closed

- src/integration-test/java/com/scalar/db/storage/cassandra/CassandraIntegrationTest.java
- src/main/java/com/scalar/db/storage/Utility.java
- src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
https://scalar-labs.atlassian.net/browse/DLT-3333
There is no check in the current C* adapter if given operations have proper keys or not.
So, I fixed it in this PR as well since it is pretty related to the bug.
> Check operations if they are given with correct keys

- src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTest.java
- src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
- src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
- src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
https://scalar-labs.atlassian.net/browse/DLT-7979
> Fix Snapshot to handle deleteSet properly when a delete operation is mixed with other operations.

- tools/scalar-schema/java/src/CosmosTableMetadata.java
- tools/scalar-schema/src/scalar_schema/cosmos.clj
https://scalar-labs.atlassian.net/browse/DLT-8021
This PR is for Cosmos DB
For Cassandra: #140 
For DynamoDB: #142 
Please merge after #140
> [Scalar-Schema] Set Cosmos secondary index

- tools/scalar-schema/src/scalar_schema/dynamo.clj
- tools/scalar-schema/src/scalar_schema/dynamo/auto_scaling.clj
- tools/scalar-schema/src/scalar_schema/dynamo/common.clj
https://scalar-labs.atlassian.net/browse/DLT-8021
This PR is for DynamoDB.
We use global secondary indexes for the Scalar DB secondary index because the local secondary index requires the partition key.
The consistency is only **eventual consistency** in DynamoDB global secondary index.
For Cassandra: #140 
For Cosmos DB: #141 
Please merge after #140
> [Scalar-Schema] Set DynamoDB secondary index

- src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
- src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
- src/main/java/com/scalar/db/storage/dynamo/DynamoOperation.java
- src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
- src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
https://scalar-labs.atlassian.net/browse/DLT-7881
- Use global secondary indexes of DynamoDB
- The consistency of global secondary indexes on Dynamo DB is eventual consistency
- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html
> Support secondary indexes on DynamoDB

- .circleci/config.yml
It came to fail suddenly. By explicitly specifying the version of `get-pip`, it seems working fine.
> Fix pip install failure in CI

- tools/scalar-schema/src/scalar_schema/dynamo/auto_scaling.clj
https://scalar-labs.atlassian.net/browse/DLT-8333
When auto-scaling is enabled for DynamoDB, the RU of each table wasn't applied.
> Fix to set RU for DynamoDB

- .circleci/config.yml
- build.gradle
After this change, we can run the integration tests for Cassandra and JDBC as follows:
Cassandra:
```
gradle integrationTestCassandra
```
JDBC (MySQL):
```
gradle integrationTestJdbc -Dscalardb.jdbc.url=jdbc:mysql://localhost:3306/ -Dscalardb.jdbc.username=root -Dscalardb.jdbc.password=mysql
```
> Divide the integration test into Cassandra and JDBC

- tools/scalar-schema/src/scalar_schema/core.clj
- tools/scalar-schema/src/scalar_schema/dynamo.clj
- tools/scalar-schema/src/scalar_schema/dynamo/continuous_backup.clj
https://scalar-labs.atlassian.net/browse/DLT-8207
Enabled the continuous backup (for Point Time In Recovery)
Note:
This doesn't enable the backup of the `scalardb.metadata` table.
The restored metadata would be useless because the user table name should be changed.
(DynamoDB cannot restore data to the existing table.)
So, we have to remake the metadata table with this tool with the new prefix after restoring other tables.
> Enable dynamo backup

- src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
Since DynamoDB seems not able to scan with an exclusive range like `a < x < b`,  I updated it to throw an exception instead of giving the warning message.
> Fix not to return unexpected results

- src/main/java/com/scalar/db/api/Operation.java
- src/main/java/com/scalar/db/storage/dynamo/DynamoOperation.java
- tools/scalar-schema/src/scalar_schema/common.clj
- tools/scalar-schema/src/scalar_schema/core.clj
- tools/scalar-schema/src/scalar_schema/dynamo/common.clj
https://scalar-labs.atlassian.net/browse/DLT-8207
For DyanmoDB recovery, the prefix for index tables is removed.
Scalar DB requires the same name about index tables after restoring the table. However, the name of the restored tables should be different from that of the source table to restore data. This requirement can be satisfied by adding the prefix. Also, the name of an index table couldn't be modified after restoring the table on DyanmoDB.
That's why I don't want to add a prefix to the index.
> Remove prefix from indexes of DynamoDB

- tools/scalar-schema/README.md
- tools/scalar-schema/project.clj
- tools/scalar-schema/src/scalar_schema/core.clj
- tools/scalar-schema/src/scalar_schema/jdbc.clj
- tools/scalar-schema/src/scalar_schema/operations.clj
https://scalar-labs.atlassian.net/browse/DLT-7846
As I'm new to Clojure, this code might not be good. Please review it from the Clojure perspective as well 😄
> Support table creation of Scalar DB on JDBC in schema-tool

- src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
We need to specify a driver class corresponding to the specified JDBC URL to the dataSource in order to avoid the "No suitable driver" error when ServiceLoader in java.sql.DriverManager doesn't work (ex. we dynamically load a driver class from a fatJar).
I'm not sure this is the best solution, but I think it's a reasonable one. If you have any better idea for it, please let me know.
> Specify a driver class corresponding to the JDBC URL to the dataSource

- docs/index.md
ReadTheDocs doesn't resolve links that are outside of the `docs` dir correctly.
> Fix the broken TLA+ link

- src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
https://scalar-labs.atlassian.net/browse/DLT-8704
Currently, the ConsensusCommit integration tests are performed only for single table transactions. From the test coverage perspective, we should perform the integration tests for multi-table transactions. In this story, we will extend the existing integration tests to cover multi-table transactions.
> Extend the ConsensusCommit integration tests to cover multi-table transactions

- src/integration-test/java/com/scalar/db/storage/IntegrationTestBase.java
- src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
- src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
- src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java
- src/integration-test/java/com/scalar/db/storage/jdbc/JdbcMetadataIntegrationTest.java
- src/integration-test/java/com/scalar/db/storage/jdbc/test/TestEnv.java
- src/main/java/com/scalar/db/storage/jdbc/metadata/JdbcTableMetadata.java
- src/main/java/com/scalar/db/storage/jdbc/metadata/TableMetadataManager.java
- src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java
- src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
- src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
- src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
- src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
- tools/scalar-schema/src/scalar_schema/jdbc.clj
https://scalar-labs.atlassian.net/browse/DLT-8642
I changed the integration tests to make them match the following requirements:
- The code doesn't assume determined sort orders for clustering keys
- No more tests that are ignored due to the scan results ordering issue
- The code doesn't assume determined sort orders for scan with secondary indexes
Also, I realized that the `index_order` column in JDBC metadata is unnecessary, so removed it in this PR.
> Fix scan related tests in Scalar DB

- tools/scalar-schema/src/scalar_schema/core.clj
- tools/scalar-schema/src/scalar_schema/dynamo.clj
- tools/scalar-schema/src/scalar_schema/dynamo/auto_scaling.clj
https://scalar-labs.atlassian.net/browse/DLT-8880
By supporting endpoint_override in Schema Tool for DynamoDB, we can use DynamoDB local that is a downloadable version of DynamoDB that enables developers to develop and test applications using a version of DynamoDB running in your own development environment:
https://hub.docker.com/r/amazon/dynamodb-local
It will be useful for test.
> Add support for endpoint_override in Schema Tool for DynamoDB

- tools/scalar-schema/src/scalar_schema/cassandra.clj
- tools/scalar-schema/src/scalar_schema/jdbc.clj
- tools/scalar-schema/src/scalar_schema/operations.clj
https://scalar-labs.atlassian.net/browse/DLT-8878
Currently, Schema Tool for JDBC doesn’t drop schemas and the metadata table/schema, which is different behavior from the others. We should unify it in this PR.
> Unify the behavior with -D (deleting all tables) in Schema Tool

- build.gradle
Upgrade the guice version to avoid some warnings with java 11
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/Users/boney/Documents/scalar-labs/15-mar-2021/scalar/client/build/install/client/lib/guice-4.2.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
> upgrade guice version to 5.0.1 for java 11 compatibility 

- src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
- src/main/java/com/scalar/db/storage/multistorage/MultiStorage.java
- src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
I found that we are using the `javax.inject.Inject` annotations in some parts. In this change, I fixed it to use the `com.google.inject.Inject` annotations.
> Use com.google.inject.Inject instead of javax.inject.Inject

- src/main/java/com/scalar/db/config/DatabaseConfig.java
- src/main/java/com/scalar/db/storage/cassandra/ClusterManager.java
- src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
- src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
- src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
- src/test/java/com/scalar/db/config/DatabaseConfigTest.java
- src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseConfigTest.java
- src/test/java/com/scalar/db/storage/multistorage/MultiStorageConfigTest.java
Some databases might not need a username and a password, but they are currently required in `DatabaseConfig`. This PR will fix it. Please take a look at this!
> Allow username and password to be null in DatabaseConfig

- src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
- src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageIntegrationTest.java
- src/main/java/com/scalar/db/storage/multistorage/MultiStorage.java
- src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
- src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
- src/test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTest.java
- src/test/java/com/scalar/db/storage/multistorage/MultiStorageConfigTest.java
- src/test/java/com/scalar/db/storage/multistorage/MultiStorageTest.java
Currently, we only have a table mapping support in MultiStorage as follows:
```
scalar.db.multi_storage.table_mapping=user.ORDER:cassandra,user.CUSTOMER:mysql,coordinator.state:cassandra
```
This PR adds a namespace mapping support where we can define namespace mappings as follows:
```
scalar.db.multi_storage.namespace_mapping=user:cassandra,coordinator:mysql
```
> Support namespace mappings in MultiStorage

- src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
- src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
What I did here is as follows:
- Add a pseudo transaction ID `txId` to `JdbcTransaction`
- Make `JdbcTransactionManager` always return `UNKNOWN`
> Some refactoring for JdbcTransaction

- src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java
This is a very minor change. Please take a look!
> Refactor the integration tests for transaction

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Since the default Gradle version in the openjdk image in Circle CI was upgraded to 7, it's a good time to upgrade our Gradle build to 7, as well.
Note that the Cosmos DB integration test is still failing. I will resolve that in the next PR after it's merged.
> Upgrade the gradle build to 7

- build.gradle
To fix the Cosmos DB integration test failure, we can upgrade the Cosmos DB client.
> Upgrade Cosmos DB client

- build.gradle
https://scalar-labs.atlassian.net/browse/DLT-9205
This issue is created by upgrading Gradle version to 7 in #217. 
It looks like we need to add `duplicatesStrategy` to the `installDist` task to fix the issue described in the above Jira. 
> Add duplicatesStrategy to installDist

- src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
- src/main/java/com/scalar/db/server/DistributedStorageService.java
- src/main/java/com/scalar/db/server/DistributedTransactionService.java
- src/test/java/com/scalar/db/server/DistributedStorageServiceTest.java
- src/test/java/com/scalar/db/server/DistributedTransactionServiceTest.java
What I did in this PR is as follows:
- Use `Empty.getDefaultInstance()` instead of `Empty.newBuilder().build()`
- Rename Throwable `e` to `t`
- Use the `mutate(List)` method for all mutation cases in DistributedStorageService and DistributedTransactionService
> Some refactoring for the gRPC services

- conf/database.properties
- core/src/main/java/com/scalar/db/config/DatabaseConfig.java
- core/src/main/java/com/scalar/db/service/TransactionModule.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseConfig.java
- core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseConfigTest.java
- docs/getting-started-with-scalardb-on-jdbc.md
- docs/getting-started-with-scalardb.md
- server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithJdbcTransactionIntegrationTest.java
To support transactions through the Scalar DB server, I added a new transaction manager property (`scalar.db.transaction_manager`). We can set `consensus-commit` (default) or `jdbc` or `grpc` to this property. When we set `grpc`, we can perform transactions through the Scalar DB server. And if we set `jdbc`, we also need to set `jdbc` to `scalar.db.storage`.
I also removed the `scalar.db.jdbc.transaction_manager_type` property in this PR because we can replace it with the new property. So this is an incompatible change.
> Add transaction manager config

- server/build.gradle
- server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
- server/src/main/java/com/scalar/db/server/DistributedStorageService.java
- server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
- server/src/main/java/com/scalar/db/server/Metrics.java
- server/src/main/java/com/scalar/db/server/service/ServerModule.java
- server/src/test/java/com/scalar/db/server/DistributedStorageAdminServiceTest.java
- server/src/test/java/com/scalar/db/server/DistributedStorageServiceTest.java
- server/src/test/java/com/scalar/db/server/DistributedTransactionServiceTest.java
I used the `dropwizard metrics` lib to expose the Scalar DB Server metrics:
https://github.com/dropwizard/metrics
And the metrics are exposed via JMX by using `JmxReporter`  in `dropwizard metrics`.
The following metrics are exposed:
* totalSucceeded (produced by `Counter`)
* totalFailed (produced by `Counter`)
* metrics for per gRPC endpoint (produced by `Timer`)
* Max
* Min
* Mean
* 50thPercentile
* 75thPercentile
* 95thPercentile
* 98thPercentile
* 99thPercentile
* 999thPercentile
* StdDev
* DurationUnit
* Count
* OneMinuteRate
* FiveMinuteRate
* FifteenMinuteRate
* MeanRate 
* RateUnit
> Add metrics to Scalar DB Server

- server/build.gradle
- server/src/main/java/com/scalar/db/server/ScalarDbServer.java
- server/src/main/java/com/scalar/db/server/config/ServerConfig.java
- server/src/main/java/com/scalar/db/server/service/ServerModule.java
- server/src/test/java/com/scalar/db/server/config/ServerConfigTest.java
To support Prometheus, I used `simpleclient_dropwizard` (https://github.com/prometheus/client_java/tree/master/simpleclient_dropwizard) published by Prometheus officially instead of `jmx_exporter` (https://github.com/prometheus/jmx_exporter) that's also published by Prometheus officially.
This change will start an HTTP endpoint for Prometheus (port: 8080, path: /metrics).
> Support Prometheus in Scalar DB Server

- core/src/main/java/com/scalar/db/service/StorageModule.java
- core/src/main/java/com/scalar/db/service/TransactionModule.java
- core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
- core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java
- core/src/main/java/com/scalar/db/storage/rpc/GrpcScanOnBidirectionalStream.java
- core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
- core/src/main/java/com/scalar/db/storage/rpc/GrpcTableMetadataManager.java
- core/src/main/java/com/scalar/db/storage/rpc/ScannerImpl.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java
- core/src/main/java/com/scalar/db/util/Utility.java
- core/src/test/java/com/scalar/db/storage/rpc/GrpcAdminTest.java
- core/src/test/java/com/scalar/db/storage/rpc/GrpcStorageTest.java
- core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionManagerTest.java
- server/src/integration-test/java/com/scalar/db/server/ConsensusCommitWithDistributedStorageServiceIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithJdbcTransactionIntegrationTest.java
> Support deadline in Scalar DB Server clients

- core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
I changed to use the default port (`60051`) if `contact_port` is not specified in Scalar DB server client.
> Use the Scalar DB server default port if not specified in the Scalar DB server client

- docs/backup-restore.md
> Add a backup guide for the Scalar DB server

- .github/workflows/release.yaml
- build.gradle
- core/build.gradle
- rpc/archive.gradle
- rpc/build.gradle
- server/archive.gradle
- server/build.gradle
- settings.gradle
> Some changes for release

- core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoWithReservedKeywordIntegrationTest.java
- core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
This is for the issue reported in the following:
https://stackoverflow.com/questions/68587760/syntax-error-when-using-scalardb-with-dynamodb-reserved-words-as-column-names
To fix the issue, I think we need to use a column name alias for the projection expressions.
> Use column name alias for projection expressions in the DynamoDB adapter

- .circleci/config.yml
This adds the integration test for JDBC Sqlserver to the circle-ci configuration.
> Add integration test for JDBC SqlServer to the CI configuration

- core/build.gradle
- server/build.gradle
This is a very trivial thing. Just renamed the `integrationTest` source set to `integrationTestAll` to avoid compile errors in Scalar DB Server integration tests in my intelliJ.
> Rename the integrationTest source set to integrationTestAll

- .circleci/config.yml
This is for avoiding the multi-storage integration test failure with exit code `137`:
https://support.circleci.com/hc/en-us/articles/115014359648-Exit-code-137-Out-of-memory
> Reduce the Cassandra heap size for the multi-storage integration test

- docs/scalardb-server.md
- server/src/integration-test/java/com/scalar/db/server/ConsensusCommitWithDistributedStorageServiceIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithJdbcTransactionIntegrationTest.java
- server/src/main/java/com/scalar/db/server/config/ServerConfig.java
- server/src/main/java/com/scalar/db/server/service/ServerModule.java
- server/src/test/java/com/scalar/db/server/config/ServerConfigTest.java
The changes are as follows:
- Rename the config name `scalar.db.server.prometheus_http_endpoint_port` to `scalar.db.server.prometheus_exporter_port`
- Change the behavior to disable the Prometheus exporter when a negative number port is given
- Change the Prometheus HTTP endpoint path from `/metrics` to `/stats/prometheus`
> Refactor Prometheus exporter

- core/src/main/java/com/scalar/db/api/DistributedStorage.java
- core/src/main/java/com/scalar/db/service/StorageFactory.java
- core/src/main/java/com/scalar/db/service/TransactionFactory.java
- core/src/main/java/com/scalar/db/storage/multistorage/MultiStorage.java
- core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
- server/src/main/java/com/scalar/db/server/service/ServerModule.java
I think we can introduce factory classes to instantiate storage and transaction objects rather than expose the Guice dependency.
For example:
The original way to get a `DistributedStorage` instance, which exposes the Guice dependency:
```
Injector injector = Guice.createInjector(new StorageModule(new DatabaseConfig(props)));
StorageService storage = injector.getInstance(StorageService.class);
```
The new way to get a `DistributedStorage` instance:
```
StorageFactory factory = new StorageFactory(databaseConfig);
DistributedStorage storage = factory.getStorage();
```
> Introduce factory classes to instantiate storage and transaction

- server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
- server/src/main/java/com/scalar/db/server/DistributedStorageService.java
- server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
- server/src/main/java/com/scalar/db/server/Metrics.java
- server/src/main/java/com/scalar/db/server/service/ServerModule.java
Renamed the names of the metrics on the basis of the following naming rule.
For JMX:
```
scalardb.stats.<grpc-service-name>.<some-request-identifier>…
```
For Prometheus:
```
scalardb_stats_<grpc-service-name>_<some-request-identifier>…
```
Examples for Prometheus:
```
// total
scalardb_stats_total_success 3268.0
scalardb_stats_total_failure 67.0
// DistributedStorage
scalardb_stats_distributed_storage_get{quantile="0.5",} 0.0026463000000000003
scalardb_stats_distributed_storage_get{quantile="0.75",} 0.0034989
scalardb_stats_distributed_storage_get{quantile="0.95",} 0.0057957
scalardb_stats_distributed_storage_get{quantile="0.98",} 0.007284400000000001
scalardb_stats_distributed_storage_get{quantile="0.99",} 0.0094631
scalardb_stats_distributed_storage_get{quantile="0.999",} …
```
> Rename metrics names of Scalar DB server

- rpc/build.gradle
This change fixes the following warnings in the `:rpc:processResources` and `:rpc:sourcesJar` gradle tasks:
```
> Task :rpc:processResources
Execution optimizations have been disabled for task ':rpc:processResources' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: '/Users/toshihiro.suzuki/work/scalar-labs/scalardb/rpc/src/main/proto'. Reason: Task ':rpc:processResources' uses this output of task ':rpc:generateProto' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
- Gradle detected a problem …
```
> Fix optimization warnings

- core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java
I added a useful method, the createTable method without any options, to DistributedStorageAdmin in this PR. Please take a look!
> Add a new createTable() method without any options to DistributedStorageAdmin

- .circleci/config.yml
- core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithMultiStorageIntegrationTest.java
This refactor the MultiStorage integration test classes to rely on the Cassandra Admin instead of managing schema using cqlsh. Thanks to that, cqlsh is not needed anymore by the integration testing so I removed it from the CI configuration.
> Use Cassandra Admin in MultiStorage integration test

- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCosmosIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithDynamoIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithJdbcDatabaseIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithMultiStorageIntegrationTest.java
- core/src/main/java/com/scalar/db/api/SerializableStrategy.java
- core/src/main/java/com/scalar/db/config/DatabaseConfig.java
- core/src/main/java/com/scalar/db/service/TransactionModule.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
- core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
- server/src/integration-test/java/com/scalar/db/server/ConsensusCommitWithDistributedStorageServiceIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java
I moved the consensus commit related config from `DatabaseConfig` to `ConsensusCommitConfig` that I added in this PR. After this change, we will add new consensus commit related config to `ConsensusCommitConfig`.
> Separate consensus commit related config from DatabaseConfig

- core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
- core/src/main/java/com/scalar/db/util/Utility.java
- core/src/test/java/com/scalar/db/storage/rpc/GrpcConfigTest.java
- core/src/test/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManagerTest.java
- server/src/main/java/com/scalar/db/server/service/ServerModule.java
This PR adds `active_transactions_management` config to `GrpcTwoPhaseCommitTransactionManager`. This config is basically the same as `TwoPhaseConsensusCommitManager`'s one. Please take a look!
> Add active_transactions_management config to GrpcTwoPhaseCommitTransactionManager

- core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java
> Add Javadoc for DistributedStorageAdmin

- core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCosmosIntegrationTest.java
- core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
- core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
- core/src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadataManager.java
- core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
What I did in this PR are:
- Rename `CosmosAdmin.RU` to `CosmosAdmin.REQUEST_UNIT` and `CosmosAdmin.DEFAULT_RU` to `CosmosAdmin.DEFAULT_REQUEST_UNIT` for consistency
- Make `CompactionStrategy` and `ReplicationStrategy` in `CassandraAdmin` public
> Refactor CassandraAdmin and CosmosAdmin

- docs/two-phase-commit-transactions.md
The link to the `Microservice Transaction Sample` was broken, so I fixed it.
> Fixed broken link.

- core/src/main/java/com/scalar/db/transaction/consensuscommit/Attribute.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
The metadata column in `Coordinator` is no longer needed. This PR removes it. Please take a look!
> Remove metadata from Coordinator

- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCosmosIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithDynamoIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithJdbcDatabaseIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithMultiStorageIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorTest.java
- server/src/integration-test/java/com/scalar/db/server/ConsensusCommitWithDistributedStorageServiceIntegrationTest.java
Currently, the table metadata database name is fixed `coordinator`. This PR makes it configurable with the `scalar.db.consensus_commit.coordinator.namespace` property. Please take a look!
> Make Coordinator namespace name configurable

- .circleci/config.yml
- core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCosmosIntegrationTest.java
- core/src/main/java/com/scalar/db/service/StorageModule.java
- core/src/main/java/com/scalar/db/service/TransactionModule.java
- core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
- core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
- core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java
- core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
- core/src/test/java/com/scalar/db/storage/cosmos/CosmosConfigTest.java
Currently, the table metadata database name in the Cosmos DB adapter is fixed `scalardb`. In some cases, we need to change it. This PR allows us to do that with the `scalar.db.cosmos.table_metadata.database` property. Please take a look!
> Make table metadata database name configurable in Cosmos DB adapter

- core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
- core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoConfigTest.java
Currently, the table metadata namespace name in the DynamoDB adapter is fixed `scalardb`. This PR allows us to change it with the `scalar.db.dynamo.table_metadata.namespace` property. Please take a look!
> Make table metadata namespace name configurable in DynamoDB adapter

- core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdminTest.java
Currently, the table metadata schema name in the JDBC adapter is fixed `scalardb`. This PR allows us to change it with the `scalar.db.jdbc.table_metadata.schema` property. Please take a look!
> Make table metadata schema name configurable in JDBC adapter

- core/src/main/java/com/scalar/db/config/DatabaseConfig.java
- core/src/main/java/com/scalar/db/storage/common/TableMetadataManager.java
- core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
- core/src/test/java/com/scalar/db/storage/common/TableMetadataManagerTest.java
This PR allows us to set Table metadata cache expiration configuration with the `scalar.db.table_metadata.cache_expiration_time_secs` property. Please take a look!
> Add Table metadata cache expiration configuration

- core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
#320 changed the signature of the Coordinator's constructor, which breaks backward compatibility. This PR will add a constructor that has the original signature again and fix the issue. Please take a look!
> Make Coordinator backward compatible

- core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java
I think `ifExists` support for `dropNamespace()`/`dropTable()` in `DistributedStorageAdmin` is useful for many use cases. This PR adds it. Please take a look!
> Add ifExists support to dropNamespace() and dropTable() in DistributedStorageAdmin

- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
I forgot to add methods to truncate and drop coordinator table to ConsensusCommitAdmin in the previous PRs 😞  This PR adds those method. Please take a look.
> Add methods to truncate and drop coordinator table to ConsensusCommitAdmin

- .circleci/config.yml
Lately, the Cosmos DB integration test is sometimes failing due to the following error:
```
Too long with no output (exceeded 10m0s): context deadline exceeded
```
We can set `no_output_timeout` to longer time in the CI configuration for the Cosmos DB integration test to avoid this error.
> Add no_output_timeout option for Cosmos DB integration test

- core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdminTest.java
- docs/schema.md
I found `FloatValue` should be mapped to `double` type in MySQL as mentioned in the following:
https://stackoverflow.com/questions/46247940/why-is-mysql-float-different-than-java-float
This PR fixes the issue. Note that I didn't fix the issue in the schema loader as it will be removed and replaced with the new one soon. Please take a look!
> FloatValue should be mapped to double type in MySQL

- core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
The current default values of JDBC connection pool configurations might be too low for most cases. This PR changes it to new values. I'm not sure the new values are reasonable. I also want to discuss it here as well. 
the configurations `maxTotal`, `maxIdle` and `minIdle` are explained in the following document:
https://commons.apache.org/proper/commons-dbcp/configuration.html
> Change the default values of JDBC connection pool configurations

- .github/workflows/release.yaml
This PR adds the following Schema loader related things to the the release action:
- Push the schema loader docker image to the GitHub Container Registry
- Build and upload the schema loader jar to the release
> Add Schema loader things to the release action

- core/src/main/java/com/scalar/db/storage/common/checker/ColumnChecker.java
- core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
Sorry, I didn't have to add an empty check for partition key and clustering key in #370. I needed to add only null check there. This PR reverts the empty check. Please take a look!
> Allow empty value for partition key and clustering key

- core/src/main/java/com/scalar/db/io/BigIntValue.java
- core/src/main/java/com/scalar/db/io/BlobValue.java
- core/src/main/java/com/scalar/db/io/BooleanValue.java
- core/src/main/java/com/scalar/db/io/DoubleValue.java
- core/src/main/java/com/scalar/db/io/FloatValue.java
- core/src/main/java/com/scalar/db/io/IntValue.java
- core/src/main/java/com/scalar/db/io/Key.java
- core/src/main/java/com/scalar/db/io/TextValue.java
I think we need to use `name` in `hashCode()` as well as `equals()` in `XXXValue` and `Key` classes. Please take a look!
> Fix hashCode() in XXXValue and Key classes

- server/Dockerfile
- server/README.md
- server/build.gradle
- server/conf/database.properties.tmpl
- Add dockerize to Dockerfile
- Since we have a use case where we want to be able to configure the database with environment variables.
``` shell
$ docker run --env SCALAR_DB_CONTACT_POINTS=cassandra --env SCALAR_DB_CONTACT_PORT=9042 --env SCALAR_DB_USERNAME=cassandra --env SCALAR_DB_PASSWORD=cassandra --env SCALAR_DB_STORAGE=cassandra -d -p 60051:60051 -p 8080:8080 ghcr.io/scalar-labs/scalardb-server:<version> dockerize -template database.properties.tmpl:database.properties /scalardb/server/bin/scalardb-server --config=database.properties
```
> Add dockerize to Dockerfile for grpc-server

- core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdminTest.java
For the clustering order support for the JDBC adapter, we need to add the following:
- For MySQL and SQL Server, we need to add the clustering orders in the primary key definition as follows:
```
CREATE TABLE `test_ns.test_table` (`id1` INT, `id2` INT, `col1` INT, PRIMARY KEY (`id1` ASC, `id2` DESC));
```
- For PostgreSQL and Oracle database, we need to add a unique index for the clustering orders:
```
CREATE UNIQUE INDEX "test_ns.test_table_clustering_order_idx" ON "test_ns.test_table" ("id1" ASC, "id2" DESC);
```
> Add clustering order support to JDBC adapter

- core/src/main/java/com/scalar/db/storage/common/checker/ColumnChecker.java
- core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
I'm very sorry for the confusion. After all, I think we should disallow empty values for Partition key and Clustering key. This PR makes the change for it. Please take a look!
> Disallow empty values for Partition key and Clustering key

- core/src/integration-test/java/com/scalar/db/storage/StorageSecondaryIndexIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSecondaryIndexIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSecondaryIndexIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSecondaryIndexIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSecondaryIndexIntegrationTest.java
- core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
- core/src/main/java/com/scalar/db/storage/cosmos/ValueBinder.java
This PR adds secondary index related integration tests. The integration tests check if all data types for secondary indexes are handled correctly. Please take a look!
> Add secondary index integration test

- core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
- core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
- core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
This PR adds clustering order support to the Dynamo adapter. The main changes for it are in `SelectStatementHandler`, and I put some comments for the points there. Please take a look!
> Add clustering order support to Dynamo adapter

- server/Dockerfile
- server/build.gradle
- server/docker-entrypoint.sh
- Added `-XX:MaxRAMPercentage` for optimizing the upper limit of `Heap Size`.
- Default -XX:MaxRAMPercentage `50.0`
* -XX:MaxRAMPercentage `50.0`
```
resources:
requests:
cpu: 800m
memory: 1Gi
limits:
cpu: 1200m
memory: 1.5Gi
```
> Add -XX:MaxRAMPercentage parameter to SCALARDB_SERVER_OPTS

- core/build.gradle
- core/src/integration-test/java/com/scalar/db/storage/StorageMultipleClusteringKeyScanIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/storage/StorageMultiplePartitionKeyIntegrationTestBase.java
It looks like the current integration test concurrency is too aggressive, causing the integration test failures sometimes. This PR reduces the integration test concurrency. Please take a look!
> Reduce integration test concurrency

- core/build.gradle
- core/src/integration-test/java/com/scalar/db/storage/StorageMultipleClusteringKeyScanIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/storage/StorageMultiplePartitionKeyIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcMultipleClusteringKeyScanIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcMultiplePartitionKeyIntegrationTest.java
It looks like the integration tests are still failing sometimes after reducing the concurrency in #397. This PR further adjusts the integration test concurrency to resolve the issue. Please take a look!
> Adjust integration test concurrency

- core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoWithReservedKeywordIntegrationTest.java
This is a very trivial thing. The integration tests are now running concurrently, and the name of the metadata table used in the integration tests should be different to avoid conflict. I handled it in the previous PR, but I missed doing that for `DynamoWithReservedKeywordIntegrationTest`. This PR fixes it. Please take a look!
> Should add a suffix to the metadata table name in DynamoWithReservedKeywordIntegrationTest

- schema-loader/build.gradle
I faced the similar issue to the issue mentioned in the following article when using Schema Loader with Scalar DB server:
https://stackoverflow.com/questions/55484043/how-to-fix-could-not-find-policy-pick-first-with-google-tts-java-client
As this article says, after adding `mergeServiceFiles` for `shadowJar` in `build.gradle` for `schema-loader`, the issue is fixed.
> Add mergeServiceFiles for shadowJar in Schema Loader

- core/src/main/java/com/scalar/db/storage/cassandra/MutateStatementHandler.java
- core/src/main/java/com/scalar/db/storage/cassandra/ReadRepairableExecutionException.java
- core/src/test/java/com/scalar/db/storage/cassandra/InsertStatementHandlerTest.java
Since `ReadRepairableExecutionException` is a Cassandra specific exception, we should have it in the Cassandra package. This PR moves `ReadRepairableExecutionException` to the Cassandra package. Please take a look!
> Move ReadRepairableExecutionException to the Cassandra package

- core/src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java
- core/src/main/java/com/scalar/db/storage/dynamo/DeleteStatementHandler.java
- core/src/main/java/com/scalar/db/storage/dynamo/PutStatementHandler.java
- core/src/test/java/com/scalar/db/storage/dynamo/BatchHandlerTest.java
In DynamoDB, `TransactionConflict` happens when we are writing/updating/deleting an item and there is an ongoing transaction for the same item. In that case, we can basically retry that operation, so I think we should throw `RetriableExecutionException`. This PR adds that logic. Please take a look!
Referencies:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transaction-apis.html
https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/dynamodb/model/TransactionConflictException.html
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/TransactionCanceledException.html
> Throw RetriableExecutionException when TransactionConflict happens in the Dynamo adapter

- core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
- core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java
- core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
Since a mutate operation in the JDBC adapter executes multiple put/delete operations in a transaction, conflicts can happen. This PR makes it throw `RetriableExecutionException` in that case. Please take a look!
> Throw RetriableExecutionException in mutate operations when conflicts happen in the JDBC adapter

- core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
Since we can retry when we catch `RetriableExecutionException` when preparing records in ConsensusCommit, we should throw `CommitConflictException` in that case. This PR adds that logic. Please take a look!
> Handle RetriableExecutionException in ConsensusCommit

- conf/database.properties
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
- core/src/main/java/com/scalar/db/api/Isolation.java
- core/src/main/java/com/scalar/db/config/DatabaseConfig.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/Isolation.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
- core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
- server/conf/database.properties.tmpl
- server/src/integration-test/java/com/scalar/db/server/ServerEnv.java
This PR moves the `Isolation` class to the `consensuscommit` package. Also, the property name is changed to `scalar.db.consensus_commit.isolation_level`. But we can still use the old property name `scalar.db.isolation_level` for backward compatibility.
> Move Isolation to the consensuscommit package

- core/src/main/java/com/scalar/db/storage/common/ResultImpl.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
Currently, `Result.getClusteringKey()` returns a `Key` object with no `Value` objects when there is no clustering key, but it should return `Optional.empty()` in that case. This PR fixes this issue. Please take a look!
> Result.getClusteringKey() should return empty when there is no clustering key

- core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
In Dynamo DB, a response of getting the table list is paginated to a maximum of 100, so we have to handle it correctly. This PR is made to fix it. PTAL! Thank you!
> Fix get tables in Dynamo adapter when actual number of tables exceed the maximum in a response.

- core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
This PR restores the method `initDataSource(JdbcConfig config)` in `JdbcUtils` that was removed in #412 to keep the backward compatibility. Please take a look!
> Restore JdbcUtils.initDataSource(JdbcConfig config)

- schema-loader/Dockerfile
- server/Dockerfile
This PR uses a self-maintained JRE Docker image to avoid adding CVE patches through Dockerfile.
The Docker file is maintained in 
https://github.com/scalar-labs/docker/blob/main/jre/8/Dockerfile
> Use the internal JRE Docker image to avoid CVE fixing commands

- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
I don't think we need the `synchronized` in `ConsensusCommitManager`. This PR removes them. Please take a look!
> Remove synchronized from ConsensusCommitManager

- .github/workflows/release.yaml
This PR changes the ordering of commands in the release CI workflow to log in to GitHub Container Registry first before building the Docker image.
(Sorry, I forgot about the internal JRE image is a private image)
> Log in GitHub Container Registry first

- graphql/src/main/java/com/scalar/db/graphql/schema/CommonSchema.java
- graphql/src/main/java/com/scalar/db/graphql/schema/TableGraphQlModel.java
- graphql/src/test/java/com/scalar/db/graphql/schema/TableGraphQlModelTest.java
This PR aims to align the GraphQL argument vocabulary with Scalar DB. Only `stringValue` was different.
> Rename stringValue GraphQL field name to textValue

- server/conf/database.properties.tmpl
- Added support for configuring the server port, as there are some use cases that run on ports other than the default server port (60051).
> Add `SCALAR_DB_SERVER_PORT` to database.properties.tmpl

- build.gradle
We need to upgrade the log4j version because it has a vulnerability explained in the following article:
https://www.lunasec.io/docs/blog/log4j-zero-day/
In Scalar DB, only Scalar DB Server uses log4j for now.
> Upgrade log4j version

- graphql/src/main/java/com/scalar/db/graphql/GraphQlFactory.java
- graphql/src/main/java/com/scalar/db/graphql/schema/TableGraphQlModel.java
- graphql/src/test/java/com/scalar/db/graphql/schema/TableGraphQlModelTest.java
This PR changes the schema generation as follows, for example, for a table named `table_1`.
Before:
```graphql
type Mutation {
abort: Boolean
commit: Boolean
table_1_delete(delete: [table_1_DeleteInput!]!): table_1_DeletePayload
table_1_put(put: [table_1_PutInput!]!): table_1_PutPayload
}
```
After:
```graphql
type Mutation {
abort: Boolean!
commit: Boolean!
table_1_bulkDelete(delete: [table_1_DeleteInput!]!): Boolean!
table_1_bulkPut(put: [table_1_PutInput!]!): Boolean!
table_1_delete(delete: table_1_DeleteInput!): Boolean!
table_1_mutate(delete: [table_1_DeleteInput!], put: [table_1_PutInput!]): Boolean!
table_1_put(put: table_1_PutInput!): Boolean!
}
```
1. Make the type of `commit` and `abort` non-null.
2. Add `put` and `delete` mutations that accept a single input object. The …
> GraphQL schema change of Mutation type

- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- core/src/main/java/com/scalar/db/storage/common/ResultImpl.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/FilteredResult.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtilsTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/FilteredResultTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
Currently, Get/Scan operations results include the transactional columns and non-projected columns in Consensus Commit. After this change, we will get the Get/Scan operations results without the transactional columns, and it also adds a Projection function support. Please take a look!
> Filter transactional columns and support projection for get/scan in Consensus Commit

- core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
- core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcUtilsTest.java
- core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
- docs/getting-started-with-scalardb-on-jdbc.md
Currently, since using the same datasource (connection pool) in Crud (Get/Scan/Put/Delete/Mutate) operations and the table metadata operation, something like a deadlock could happen (it's a very rare case, though). This PR makes the table metadata operation use a different datasource (connection pool) from Crud operations to avoid the deadlock. Please take a look!
> Use different datasource for table metadata in JDBC adapter

- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/CoordinatorException.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/RecoveryHandlerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
Since `CoordinatorException` is Consensus Commit specific, we should move it to the `consensuscommit` package. Please take a look!
> Move CoordinatorException to the consensuscommit package

- docs/scalardb-server.md
> Add gRPC deadline duration configuration to the Scalar DB Server documentation

- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
- core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/RecoveryHandlerTest.java
This PR introduces the following parameters:
```
scalar.db.consensus_commit.parallel_preparation.enabled
scalar.db.consensus_commit.parallel_commit.enabled
scalar.db.consensus_commit.parallel_rollback.enabled
scalar.db.consensus_commit.parallel_executor_count
```
When we set `parallel_preparation.enabled` to `true`, the record preparation will be done in parallel. Also, when we the `parallel_commit.enabled` and `parallel_rollback.enabled` parameter to `true`, the record commit/rollback will be done in parallel. The `parallel_executor_count` determines the number of threads for the parallel execution. 
> Support parallel preparation/commit/rollback in Consensus Commit

- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ParallelExecutorTest.java
This PR introduces the following parameters:
```
scalar.db.consensus_commit.async_commit.enabled
scalar.db.consensus_commit.async_rollback.enabled
```
When we set `async_commit.enabled` to `true`, the record commit will be done asynchronously. Similarly, when we set `async_rollback.enabled` to `true`, the record rollback will be done asynchronously. Please take a look!
> Support async commit/rollback in Consensus Commit

- core/src/integration-test/java/com/scalar/db/storage/AdminIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/storage/StorageIntegrationTestBase.java
- core/src/main/java/com/scalar/db/io/Key.java
- core/src/test/java/com/scalar/db/io/KeyTest.java
- core/src/test/java/com/scalar/db/storage/cassandra/SelectStatementHandlerTest.java
- core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
- core/src/test/java/com/scalar/db/storage/cosmos/CosmosOperationTest.java
- core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
- core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
- core/src/test/java/com/scalar/db/storage/rpc/GrpcStorageTest.java
- server/src/test/java/com/scalar/db/server/DistributedStorageServiceTest.java
This PR revisits the `Key` construction. After this change, we can follow the following guideline to construct `Key` objects:
1. If the key consists of a single value (column), use the constructors for a single value (column) as follows:
```
Key key1 = new Key("col1", 1);
Key key2 = new Key("col1", 100L);
Key key3 = new Key("col1", 1.3d);
Key key4 = new Key("col1", "value");
```
2. If the key consists of 2 - 5 values (columns), use the constructors for multiple values (columns) as follows:
```
Key key1 = new Key("col1", 1, "col2", 100L);
Key key2 = new Key("col1", 1, "col2", 100L, "col3", 1.3d);
Key key3 = new Key("col1", 1, "col2", 100L, "col3", 1.3d, "col4", "value");
Key key4 = new Key("col1", 1, "col2", 100L, "col3", 1.3d, "col4", "value", "col5", false);
```
3. If the key consists of …
> Revisit Key construction

- core/src/integration-test/java/com/scalar/db/storage/TestUtils.java
- core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminIntegrationTest.java
- core/src/main/java/com/scalar/db/config/DatabaseConfig.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
- core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
- core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
This PR renames `JdbcDatabaseAdmin` to `JdbcAdmin` because I think `JdbcAdmin` is a more proper name. Please take a look!
> Rename JdbcDatabaseAdmin to JdbcAdmin

- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
It looks like the current EXTRA_READ validation always rejects transactions that have multiple scans. This PR fixes this issue. Please take a look!
> Transactions that have multiple scans are always rejected in EXTRA_READ

- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ParallelExecutorTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
This PR introduces a parameter `scalar.db.consensus_commit.async_commit.enabled`. After this change, when we set the parameter to `true`, the validation for `EXTRA_READ` is done in parallel. Please take a look!
> Support parallel validation for EXTRA_READ in Consensus Commit

- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationBulkDeleteDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationBulkPutDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationDeleteDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationMutateDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationPutDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/QueryGetDataFetcherTest.java
This fixes the unit test names for GraphQL data fetchers. (Especially `PutXXX` was mistakenly used for tests of Delete operations).
> Fix unit test method names for GraphQL data fetchers

- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionalTableMetadata.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionalTableMetadataManager.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtilsTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TransactionalTableMetadataManagerTest.java
This PR adds `TransactionalTableMetadataManager` that retrieves and caches `TransactionalTableMetadata` instances with table metadata and transactional meta info for transactional tables. We don't use these classes yet but will use them in another PR. Please take a look!
> Add TransactionalTableMetadataManager

- graphql/src/main/java/com/scalar/db/graphql/datafetcher/DataFetcherHelper.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationBulkDeleteDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationBulkPutDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationDeleteDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationMutateDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationPutDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/QueryGetDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/QueryScanDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/schema/TableGraphQlModel.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/DataFetcherTestBase.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationBulkDeleteDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationBulkPutDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationDeleteDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationMutateDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationPutDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/QueryGetDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/QueryScanDataFetcherTest.java
Before, in GraphQL operations, whether each table had transactional metadata or not was used to determine which method,  `transaction` or `storage`, was used for data access. This means that the `storage` method was used for tables without transactional metadata even if a `@transaction` directive was specified.
```graphql
query op1 @transaction {
storage_table_get(get: {...}) {  # -> storage is used for this table
...
}
transactional_table_get(get: {...}) { # -> transaction is used for this table
...
}
}
```
This PR changes this behavior. That is, only the `@transaction` directive determines whether `transaction` or `storage` is used in a whole operation. If the `@transaction` directive is specified in the input of a GraphQL operation (in which case the transaction object is kept in the …
> Use only one of transaction or storage method regardless of the table type in one GraphQL operation

- graphql/src/main/java/com/scalar/db/graphql/GraphQlFactory.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/DataFetcherHelper.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationBulkDeleteDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationBulkPutDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationDeleteDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationMutateDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationPutDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/QueryGetDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/QueryScanDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/schema/Constants.java
- graphql/src/main/java/com/scalar/db/graphql/schema/TableGraphQlModel.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/DataFetcherTestBase.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationBulkDeleteDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationBulkPutDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationDeleteDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationMutateDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationPutDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/QueryGetDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/QueryScanDataFetcherTest.java
(Once #460 is merged, I will update this PR.)
This PR adds the exception names to the results of data fetchers that are thrown while running Scalar DB operations.
When a Scalar DB storage throws `ExecutionException` or a transaction throws `CrudException` (or `CrudConflictException`), they should be handled in the `get` method of `DataFetcher` objects and the name should be included in the `"errors"` -> `"extensions"` key of the result JSON.
Here are the example query and response.
```graphql
query @transaction(commit: true, txId: "9a04e41e-364d-4ee3-b77a-8f7b560ea4c0") {
book1: books_by_isbn_tx_get(get: {key: {isbn: "978-4-09-386620-0", version: 1}}) {
books_by_isbn_tx {
isbn
}
}
}
```
If the above query encounters a `CrudConflictException`, the response should be returned like the …
> Handle GraphQL data fetching errors

- graphql/src/main/java/com/scalar/db/graphql/datafetcher/DataFetcherHelper.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/QueryGetDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/QueryScanDataFetcher.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/DataFetcherTestBase.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/QueryGetDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/QueryScanDataFetcherTest.java
For get and scan operations, use the `withProjections()` according to the specified selections of the GraphQL inputs.
For example, the GraphQL query
```graphql
query {
table1_scan(scan: { partitionKey: { c1: 1 }}) {
table1 {
c1
c2
}
}
```
will be converted to a `Scan` command like the following:
```java
new Scan(new Key(new IntValue("c1", 1)))
.withProjections(Arrays.asList("c1", "c2"))
```
> Add projections to Get and Scan operations in GraphQL

- core/src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
- core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
This PR makes the sort order for Scan without orderings follow clustering order in the Cosmos adapter. Please take a look!
> Sort order for Scan without orderings should follow clustering order in Cosmos adapter

- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitIntegrationTest.java
This PR allows getting already written data in Consensus Commit.
Note that we only support `get-after-put` in this PR, not `scan-after-put`. `scan-after-put` still throw `IllegalArgumentException` even after this change.
> Allow getting already written data in Consensus Commit

- core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
- core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
Currently, the check for mutation operations in `OperationChecker` doesn't take `Namespace` into account. So when we specify multiple mutations with the same table and partition key but a different namespace, `OperationChecker` doesn't throw `IllegalArgumentException`. This PR fixes this bug. Please take a look!
> Fix OperationChecker for mutation operations

- core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
This PR handles SQL Server conflict error. After this change, when SQL Server throws a conflict error exception, the JDBC adapter throws `XXXConflictException`. Please take a look!
> Handle SQL Server conflict error

- core/src/integration-test/java/com/scalar/db/storage/StorageIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/storage/StorageMultipleClusteringKeyScanIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/storage/StorageSingleClusteringKeyScanIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/storage/StorageWithReservedKeywordIntegrationTestBase.java
This adds more integration tests for Scan as follows: 
- Add tests checking if the scan result follows clustering orders
- Add tests for scans with various orderings specified
- Add tests for scans with limit specified
> Add more integration tests for Scan

- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
It looks like the current scan logic in `CrudHandler` is not correct when a record of the scan result is already deleted (the record is in the delete set). This PR fixes the issue. Please take a look!
> Fix Scan logic in CrudHandler in Consensus Commit

- .circleci/config.yml
It looks like the Cosmos DB adapter CI is taking longer time recently and it's failing with `Too long with no output (exceeded 20m0s): context deadline exceeded` error. To address this issue, we can increase `no_output_timeout` for Cosmos DB adapter CI. This PR does it. Please take a look!
> Increase no_output_timeout for Cosmos DB adapter CI

- graphql/src/main/java/com/scalar/db/graphql/GraphQlFactory.java
- graphql/src/main/java/com/scalar/db/graphql/instrumentation/ScalarDbTransactionError.java
- graphql/src/main/java/com/scalar/db/graphql/instrumentation/TransactionInstrumentation.java
- graphql/src/test/java/com/scalar/db/graphql/GraphQlFactoryTest.java
- graphql/src/test/java/com/scalar/db/graphql/instrumentation/TransactionInstrumentationTest.java
As mentioned in https://github.com/scalar-labs/scalardb/pull/471#issue-1110295385, this PR moves the `TransactionInstrumentation` (and `ScalarDbTransactionError`) class from the package `com.scalar.db.graphql.datafetcher` to `com.scalar.db.graphql.instrumentation`.
> GraphQL package reorganization

- graphql/src/main/java/com/scalar/db/graphql/datafetcher/DataFetcherHelper.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationBulkDeleteDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationBulkPutDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationDeleteDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationMutateDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationPutDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/QueryGetDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/QueryScanDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/schema/TableGraphQlModel.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationBulkDeleteDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationBulkPutDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationDeleteDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationMutateDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationPutDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/QueryGetDataFetcherTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/QueryScanDataFetcherTest.java
1. In the GraphQL schema generation, the consensus commit meta columns are hidden from the GraphQL schema only if a table has all meta columns. (`ConsensusCommitUtils.isTransactionalTableMetadata(tableMetadata)` is `true`).
2. Accessing a table with storage method will fail if it has consensus commit meta columns.
|                  | No meta columns | CC meta columns |
|------------------|-----------------|-----------------|
| Storage          | OK              | **Error**       |
| Consensus Commit | Error           | OK              |
| JDBC             | OK              | OK (*)          |
(*) Since there is no way to know that the transaction is backed by JDBC native transaction at runtime, the GraphQL interface doesn't reject access to CC tables with JDBC. Alternatively, it would be …
> GraphQL should reject storage access to consensus commit transactional tables

- graphql/src/main/java/com/scalar/db/graphql/GraphQlConstants.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/DataFetcherHelper.java
- graphql/src/main/java/com/scalar/db/graphql/datafetcher/MutationAbortDataFetcher.java
- graphql/src/main/java/com/scalar/db/graphql/instrumentation/TransactionInstrumentation.java
- graphql/src/main/java/com/scalar/db/graphql/instrumentation/validation/AbortFieldValidation.java
- graphql/src/main/java/com/scalar/db/graphql/instrumentation/validation/ConditionalExpressionValidation.java
- graphql/src/main/java/com/scalar/db/graphql/instrumentation/validation/ScanStartAndEndValidation.java
- graphql/src/main/java/com/scalar/db/graphql/schema/ScalarDbTypes.java
- graphql/src/test/java/com/scalar/db/graphql/GraphQlFactoryTest.java
- graphql/src/test/java/com/scalar/db/graphql/datafetcher/DataFetcherTestBase.java
- graphql/src/test/java/com/scalar/db/graphql/instrumentation/TransactionInstrumentationTest.java
Refactoring of the "`Constants`" class.
1. Moved the class from the package `com.scalar.graphql.schema` to `com.scalar.graphql` (and renamed it to `GraphQlConstants `) since it is not limited to schema-related things.
2. Inlined constants of the schema element names (`"transaction"`, `"txId"`, and `"commit"`), since other keywords of the same kind, such as `"get"`, `"name"`, and `"PutCondition"`, are simply hard-coded.
> GraphQL constants

- core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
I don't think we need to compare all the values of a read record and a re-read record in the validation in EXTRA_READ. I think it's enough to compare `id` and `version` values. This PR makes it. Please take a look!
> Use only id and version to check if a read record is not changed in the validation in EXTRA_READ

- schema-loader/build.gradle
Currently, the `shadowJar` task for Schema Loader overwrites the original jar because we set `archiveClassifier` to empty in the `shadowJar` task as follows:
https://github.com/scalar-labs/scalardb/blob/cb65eaacd27795e98aa51c5208ac602b4e130a83/schema-loader/build.gradle#L141
As a result, we publish the fat jar to the maven repository, which can cause a dependency conflict issue. To address this issue, it seems like we can exclude the `shadowJar` task when we run the `publish` task (and the `publishToMavenLocal` task). This PR fixes it. Please take a look!
> Should not publish a fat jar for Schema Loader to the maven repository

- core/src/main/java/com/scalar/db/storage/cassandra/ResultInterpreter.java
- core/src/main/java/com/scalar/db/storage/cosmos/ResultInterpreter.java
- core/src/main/java/com/scalar/db/storage/dynamo/ResultInterpreter.java
- core/src/main/java/com/scalar/db/storage/jdbc/ResultInterpreter.java
- core/src/main/java/com/scalar/db/util/ProtoUtils.java
- core/src/main/java/com/scalar/db/util/ResultImpl.java
- core/src/test/java/com/scalar/db/storage/common/ResultImplTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/FilteredResultTest.java
Now that the `ResultImpl` class is not used only for the classes in the `storage` package, we should move it to the `util` package. This PR does that. Please take a look!
> Move ResultImpl to the util package

- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
- core/src/main/java/com/scalar/db/service/TransactionModule.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/UncommittedRecordException.java
- core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/RecoveryHandlerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
After this change, when reading a record in Consensus Commit, we filter out the before image columns to reduce the query cost (disk I/O and network I/O). Please take a look!
> Unnecessary columns are not read any more in Consensus Commit

- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/MutationComposer.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/RecoveryHandlerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Currently, in RollbackMutationComposer, we check if the column name prefix is `before_` to identity if the column is a before image column or not. However, that's not enough, and there are some corner cases actually. Instead, we can use before image column names returned by `TransactionalTableMetadata.getBeforeImageColumnNames()` to address this issue. This PR fixes it. Please take a look!
> Use before image column names from TransactionalTableMetadata in RollbackMutationComposer

- core/src/main/java/com/scalar/db/config/ConfigUtils.java
- core/src/main/java/com/scalar/db/config/DatabaseConfig.java
- core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
This PR adds `ConfigUtils.getStringArray()` utility method that is for getting a string array property from a comma-separated string in a properties file.
It is applied to the existing `DatabaseConfig` and `MultiStorageConfig`. Note that there is a slight difference in how a trailing _regex_ in a property is treated between `split(regex, -1)` and `split(regex)` (equivalent to `split(regex, 0)`). In the latter case, trailing empty strings will be discarded (e.g., `scalar.db.contact_points = server1, , ,` is parsed into a one-element array). This should not be a problem.
> Add ConfigUtils.getStringArray()

- core/src/main/java/com/scalar/db/io/Key.java
- core/src/test/java/com/scalar/db/io/KeyTest.java
- core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
This PR actually reverts some of the changes in #447.
It seems like the current standard of Java API is more explicit method names rather than using overload.
After this reverting, We can use the Key builder as follows:
```java
Key key = Key.newBuilder()
.addInt("col1", 1)
.addBigInt("col2", 100L)
.addDouble("col3", 1.3d)
.addText("col4", "value")
.addBoolean("col5", false)
.addInt("col6", 100)
.build();
```
Note that we don't need to consider its compatibility since we have not yet released the changes in #447.
> Change Key builder

- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/RecoveryHandlerTest.java
This is a PR for refactoring. I think it's better to move the `RecoveryHandler.rollbackRecords()` method to `CommitHandler` because the method is only used in `CommitHandler`. Please take a look!
> Move the rollbackRecords method from RecoveryHandler to CommitHandler

- core/src/main/java/com/scalar/db/util/ImmutableLinkedHashSet.java
This PR changes `ImmutableLinkedHashSet` to use `ImmutableSet` internally and delegate to it. Please take a look!
> Refactor ImmutableLinkedHashSet

- core/src/main/java/com/scalar/db/api/Operation.java
It seems that javadoc of com.scalar.db.api.Operation Class has a typo.
I think that "table" is correct in the description of the Operation.forTable() method.
> Fix typo in the javadoc

- core/src/main/java/com/scalar/db/api/Put.java
- core/src/test/java/com/scalar/db/api/PutTest.java
This PR adds more explicit methods to add values like `withBooleanValue()` and `withIntValue()` to the `Put` class and deprecates the existing methods `withValue()`. Please take a look!
> Add more explicit methods to Put

- core/src/main/java/com/scalar/db/io/Key.java
- core/src/test/java/com/scalar/db/io/KeyTest.java
This PR adds factory methods to the `Key` class.
We can use the factory methods as follows:
```java
// for a key that consists of a single column of Int
Key key1 = Key.ofInt("col1", 1);
// for a key that consists of a single column of BigInt
Key key2 = Key.ofBigInt("col1", 100L);
// for a key that consists of a single column of Double
Key key3 = Key.ofDouble("col1", 1.3d);
// for a key that consists of a single column of Text
Key key4 = Key.ofText("col1", "value");
// for a key that consists of 2 - 5 columns
Key key5 = Key.of("col1", 1, "col2", 100L);
Key key6 = Key.of("col1", 1, "col2", 100L, "col3", 1.3d);
Key key7 = Key.of("col1", 1, "col2", 100L, "col3", 1.3d, "col4", "value");
Key key8 = Key.of("col1", 1, "col2", 100L, "col3", 1.3d, "col4", "value", "col5", false);
```
We can still …
> Add factory methods to Key

- core/src/main/java/com/scalar/db/api/Scan.java
- core/src/test/java/com/scalar/db/api/ScanTest.java
This PR adds factory methods to the `Scan.Ordering` class.
We can use them as follows:
```
// for asc ordering
Scan.Ordering ascOrdering = Scan.Ordering.asc("col1");
// for desc ordering
Scan.Ordering descOrdering = Scan.Ordering.desc("col2");
```
This PR also deprecates the constructor of `Scan.Ordering`. Please take a look!
> Add factory methods to Scan.Ordering

- core/build.gradle
- core/src/integration-test/java/com/scalar/db/storage/StorageAdminIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/transaction/TransactionAdminIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminWithJdbcDatabaseIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminIntegrationTest.java
- core/src/main/java/com/scalar/db/api/DistributedTransactionAdmin.java
- core/src/main/java/com/scalar/db/config/DatabaseConfig.java
- core/src/main/java/com/scalar/db/service/StorageModule.java
- core/src/main/java/com/scalar/db/service/TransactionFactory.java
- core/src/main/java/com/scalar/db/service/TransactionModule.java
- core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdmin.java
- core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
- core/src/test/java/com/scalar/db/storage/cosmos/CosmosConfigTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoConfigTest.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
- core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminTest.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
This PR introduces a new `DistributedTransactionAdmin` class that abstracts the administrative operations for distributed transactions like createNamespace/createTable/getTableMetadata. This PR also adds the implementation classes of `DistributedTransactionAdmin`, `ConsensusCommitAdmin` and `JdbcTransactionAdmin`. I will add inline comment for more details. Please take a look!
> Introduce DistributedTransactionAdmin

- core/src/integration-test/java/com/scalar/db/storage/StorageIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
This PR adds a integration test putting a null value for secondary index column. It looks like DynamoDB doesn't support putting a null value for a secondary index column, so I ignored the test for DynamoDB. Please take a look!
> Add a integration test putting a null value for secondary index column

- core/src/main/java/com/scalar/db/api/DistributedTransaction.java
- core/src/main/java/com/scalar/db/api/TransactionCrudOperable.java
- core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransaction.java
This PR extracts an interface for transaction CRUD operations from `DistributedTransaction` and `TwoPhaseCommitTransaction`. I would like to discuss if the interface name `TransactionCrudOperable` is good. Please take a look!
> Extract an interface for transaction CRUD operations

- core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Currently, when a key is contained in WriteSet and ReadSet but the result in ReadSet is empty, it doesn't return primary key, which is not expected behavior. This PR fixes this issue. 
Note that this bug is only in the branch `3.5`, but the `master` branch doesn't have it. So this bug fix is only for the branch `3.5`.
> Should return primary key when key is contained in WriteSet and ReadSet but the result in ReadSet is empty in Consensus Commit

- core/src/main/java/com/scalar/db/sql/DmlStatementExecutor.java
- core/src/main/java/com/scalar/db/sql/Projection.java
- core/src/main/java/com/scalar/db/sql/ResultIteratorResultSet.java
- core/src/main/java/com/scalar/db/sql/ResultRecord.java
- core/src/main/java/com/scalar/db/sql/StatementValidator.java
- core/src/main/java/com/scalar/db/sql/builder/SelectStatementBuilder.java
- core/src/main/java/com/scalar/db/sql/builder/StatementBuilder.java
- core/src/main/java/com/scalar/db/sql/statement/SelectStatement.java
- core/src/test/java/com/scalar/db/sql/DmlStatementExecutorTest.java
- core/src/test/java/com/scalar/db/sql/ProjectionTest.java
- core/src/test/java/com/scalar/db/sql/ResultIteratorResultSetTest.java
- core/src/test/java/com/scalar/db/sql/ResultRecordTest.java
- core/src/test/java/com/scalar/db/sql/StatementValidatorTest.java
- core/src/test/java/com/scalar/db/sql/builder/StatementBuilderTest.java
This PR supports alias in SQL API.
After this change, we can specify projections with aliases (with the `as()` method) as follows:
```java
SelectStatement statement =
StatementBuilder.select(Projection.column("col2").as("a"), Projection.column("col3").as("b"))
.from("ns", "tbl")
.where(Predicate.column("col1").isEqualTo(Value.ofInt(10)))
.and(Predicate.column("col2").isGreaterThan(Value.ofText("aaa")))
.and(Predicate.column("col2").isLessThan(Value.ofText("ccc")))
.orderBy(
ClusteringOrdering.column("col2").desc(), ClusteringOrdering.column("col3").desc())
.limit(10)
.build();
```
> Support alias in SQL API

- core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
- core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
`Query condition missed key schema element` error happens when executing Scan/Get operations using secondary index and specifying projections in DynamoDB. This PR fixes this bug. Please take a look!
> Fix `Query condition missed key schema element` error in DynamoDB

- core/src/main/java/com/scalar/db/sql/Assignment.java
- core/src/main/java/com/scalar/db/sql/BindMarker.java
- core/src/main/java/com/scalar/db/sql/DmlStatementExecutor.java
- core/src/main/java/com/scalar/db/sql/NamedBindMarker.java
- core/src/main/java/com/scalar/db/sql/PositionalBindMarker.java
- core/src/main/java/com/scalar/db/sql/Predicate.java
- core/src/main/java/com/scalar/db/sql/SqlStatementSession.java
- core/src/main/java/com/scalar/db/sql/SqlUtils.java
- core/src/main/java/com/scalar/db/sql/StatementValidator.java
- core/src/main/java/com/scalar/db/sql/Term.java
- core/src/main/java/com/scalar/db/sql/Value.java
- core/src/main/java/com/scalar/db/sql/builder/SelectStatementBuilder.java
- core/src/main/java/com/scalar/db/sql/statement/BindableStatement.java
- core/src/main/java/com/scalar/db/sql/statement/DeleteStatement.java
- core/src/main/java/com/scalar/db/sql/statement/InsertStatement.java
- core/src/main/java/com/scalar/db/sql/statement/SelectStatement.java
- core/src/main/java/com/scalar/db/sql/statement/TruncateCoordinatorTableStatement.java
- core/src/main/java/com/scalar/db/sql/statement/UpdateStatement.java
- core/src/test/java/com/scalar/db/sql/AssignmentTest.java
- core/src/test/java/com/scalar/db/sql/DmlStatementExecutorTest.java
- core/src/test/java/com/scalar/db/sql/PredicateTest.java
- core/src/test/java/com/scalar/db/sql/ResultIteratorResultSetTest.java
- core/src/test/java/com/scalar/db/sql/ResultRecordTest.java
- core/src/test/java/com/scalar/db/sql/StatementValidatorTest.java
- core/src/test/java/com/scalar/db/sql/TransactionSessionTest.java
- core/src/test/java/com/scalar/db/sql/builder/StatementBuilderTest.java
- core/src/test/java/com/scalar/db/sql/statement/DeleteStatementTest.java
- core/src/test/java/com/scalar/db/sql/statement/InsertStatementTest.java
- core/src/test/java/com/scalar/db/sql/statement/SelectStatementTest.java
- core/src/test/java/com/scalar/db/sql/statement/UpdateStatementTest.java
This PR adds a Support for parameterized statements in SQL API.
There are two kinds of bind markers, `positional bind marker` and `named bind marker`.
The following code shows how to use parameterized statements:
```java
SqlStatementSession sqlStatementSession = ...;
// Select statement with positional bind markers
SelectStatement selectStatement =
StatementBuilder.select("col1", "col2", "col3")
.from("ns", "tbl")
.where(Predicate.column("col1").isEqualTo(BindMarker.positional()))
.and(Predicate.column("col2").isEqualTo(BindMarker.positional()))
.limit(BindMarker.positional())
.build();
// Positional values
List<Value> positionalValues = Arrays.asList(Value.ofInt(10), Value.ofText("aaa"), Value.ofInt(100));
// Execute with the parameter values
sqlStatementSession.execute(selectStatement, …
```
> Support parameterized statement in SQL API

- schema-loader/Dockerfile
- server/Dockerfile
This PR updates the in-house JRE Docker base image to 1.1.0.
> Update the base image jre8 to 1.1.0

- core/src/main/java/com/scalar/db/api/Scan.java
- core/src/main/java/com/scalar/db/api/ScanAll.java
- core/src/main/java/com/scalar/db/io/Key.java
This PR introduces a `ScanAll` operation that scans all the data of a database. This PR doesn't contain the actual implementation of `ScanAll` but it contains only  the `ScanAll` operation class.
I added the `ScanAll` as a subclass of `Scan` because I think that minimizes the total change cost.
I assume the `ScanAll` operation is used with the existing `scan()` API as follows:
```java
Scanner scanner =
storage.scan(
new ScanAll().withProjection("col1").withLimit(10).forNamespace("ns").forTable("tbl"));
```
Currently `ScanAll` only supports specifying projections and limit.
> Introduce ScanAll operation

- core/src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
- core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
This PR is a fix for a bug where an SQL syntax error happens when scanning a table without clustering key in JDBC adapter. We basically don't need to scan a table without clustering key, but an error should not happen if we do that. Please take a look!
> Fix SQL syntax error that happens when scanning a table without clustering key in JDBC adapter

- core/src/main/java/com/scalar/db/sql/DdlStatementExecutor.java
- core/src/main/java/com/scalar/db/sql/SqlStatementSessionFactory.java
- core/src/main/java/com/scalar/db/sql/TransactionSession.java
- core/src/main/java/com/scalar/db/sql/TwoPhaseCommitTransactionSession.java
- core/src/main/java/com/scalar/db/sql/metadata/CachedMetadata.java
- core/src/main/java/com/scalar/db/sql/metadata/CachedNamespaceMetadata.java
- core/src/main/java/com/scalar/db/sql/metadata/ColumnMetadata.java
- core/src/main/java/com/scalar/db/sql/metadata/ColumnMetadataImpl.java
- core/src/main/java/com/scalar/db/sql/metadata/IndexMetadata.java
- core/src/main/java/com/scalar/db/sql/metadata/IndexMetadataImpl.java
- core/src/main/java/com/scalar/db/sql/metadata/Metadata.java
- core/src/main/java/com/scalar/db/sql/metadata/NamespaceMetadata.java
- core/src/main/java/com/scalar/db/sql/metadata/TableMetadata.java
- core/src/main/java/com/scalar/db/sql/metadata/TableMetadataImpl.java
- core/src/test/java/com/scalar/db/sql/DdlStatementExecutorTest.java
- core/src/test/java/com/scalar/db/sql/DmlStatementExecutorTest.java
- core/src/test/java/com/scalar/db/sql/StatementValidatorTest.java
- core/src/test/java/com/scalar/db/sql/metadata/CachedMetadataTest.java
This PR adds a logic to invalidate metadata cache when schema change happens in SQL API. I will inline comments to make it more readable. Please take a look!
> Invalidate metadata cache when schema change happens in SQL API

- .github/workflows/ci.yaml
To be able to display a CI badge on the repository main page, we need to trigger the CI on push event on the master branch.
> Trigger CI for "push" event on the master branch

- schema-loader/Dockerfile
- server/Dockerfile
This PR updates the in-house JRE Docker base image to 1.1.1. Please take a look!
> Update the base image jre8 to 1.1.1

- server/Dockerfile
This PR upgrades `grpc_health_probe` to address CVE-2020-14040 and CVE-2021-38561.
> Upgrade grpc_health_probe

- build.gradle
This PR upgrades the PostgreSQL driver to address GHSA-673j-qm5f-xpv8 and GMS-2022-75. Please take a look!
> Upgrade PostgreSQL driver

- .github/workflows/ci.yaml
When we push commits to the support and release branches (like `3`, `3.4`, `3.5`), we always need to run CI for them. So this PR adds triggers for CI for them. Please take a look!
> Add CI triggers for "push" events on support and release branches

- core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
- core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
- core/src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
- core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
This adds the ScanAll operation for the Cosmos DB storage. 
Please have a look.
> Add ScanAll for Cosmos DB storage

- build.gradle
- server/src/main/java/com/scalar/db/server/AdminService.java
- server/src/main/java/com/scalar/db/server/GateKeeper.java
- server/src/main/java/com/scalar/db/server/LockFreeGateKeeper.java
- server/src/main/java/com/scalar/db/server/SynchronizedGateKeeper.java
This PR implements the new Admin gRPC service `checkPaused` by which the client can get the pause status.
I tested it with the scalar-admin 1.2.0's executables and it works as expected.
@Torch3333 
Vincent, for your reference.
Scalar server has implemented a gRPC server for these services of this [Protocol Buffers](https://github.com/scalar-labs/scalar-admin/blob/main/admin.proto) by which we can pause/unpause the Scalar server.
This PR implements the new service `checkPaused` which is used for getting the pause status of the Scalar server.
> Implement the checkPaused service according to scalar-admin 1.2.0

- server/src/main/java/com/scalar/db/server/AdminService.java
This PR uses the gRPC optional argument max_pause_wait_time to drain the service.
The optional argument `max_pause_wait_time` was added in scalar-admin 1.1.0, but, for a release issue, it wasn't applied on the server side yet.
This PR does the makeup.
> Use `max_pause_wait_time` in AdminService

- core/src/integration-test/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
- core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java
- core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java
- core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransaction.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
- core/src/main/java/com/scalar/db/util/ActiveExpiringMap.java
- core/src/test/java/com/scalar/db/storage/rpc/GrpcConfigTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
- core/src/test/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManagerTest.java
- docs/two-phase-commit-transactions.md
- server/src/main/java/com/scalar/db/server/ServerModule.java
This is actually a backward incompatible change for Two-phase Commit Transactions. But I don't think the 2PC transaction feature is not widely used, so we can change it for now.
Currently, when we join a transaction (with `TwoPhaseCommitTransactionManager.join()`), the transaction object is automatically put in the object map (`activeTransactions`), and we can resume this transaction with `TwoPhaseCommitTransactionManager.resume()`. But after this change, we need to call `TwoPhaseCommitTransactionManager.suspend()` explicitly if you want to resume the transaction.
I also modified the document for this feature:
https://github.com/scalar-labs/scalardb/blob/add-suspend-to-2pc/docs/two-phase-commit-transactions.md#suspend-and-resume-the-transaction
> Add suspend method to TwoPhaseCommitTransactionManager

- server/Dockerfile
- server/README.md
- server/build.gradle
- server/conf/database.properties.tmpl
- server/conf/log4j2.properties.tmpl
- server/docker-entrypoint.sh
This PR updates Dockerfile of Scalar DB Server to use `dockerize` for templating of database.properteis file.
In the Helm Charts of Scalar DB, I want to pass the username and password as a secret resource.
And, I want to set them as environment variables in the database.properties file as follows.
```
scalar.db.contact_points=localhost
scalar.db.contact_port=9042
scalar.db.storage=cassandra
scalar.db.username={{ default .Env.SCALAR_DB_USERNAME "" }}
scalar.db.password={{ default .Env.SCALAR_DB_PASSWORD "" }}
```
To achieve the above purpose, first, I need to update the Dockerfile of Scalar DB to use `dockerize` command by default.
> Use dockerize command by default in the Dockerfile

- core/src/integration-test/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
- core/src/main/java/com/scalar/db/storage/cosmos/ResultInterpreter.java
- core/src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
- core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
Currently, columns are not projected when doing a Selection operation for Cosmos DB, the projected columns are filtered on the client side after the query is executed.
With this PR, the projected columns are now parametrized in the query directly. 
Please have a look.
> Handle projections in query for Cosmos DB

- docs/getting-started-with-scalardb-on-cassandra.md
- docs/getting-started-with-scalardb-on-cosmosdb.md
- docs/getting-started-with-scalardb-on-dynamodb.md
- docs/getting-started-with-scalardb-on-jdbc.md
The getting started guides build scalardb from the source code so we need Java 8 to do it instead of higher versions.
> Update the docs

- core/src/integration-test/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
- core/src/main/java/com/scalar/db/api/DeleteBuilder.java
- core/src/main/java/com/scalar/db/api/Get.java
- core/src/main/java/com/scalar/db/api/GetBuilder.java
- core/src/main/java/com/scalar/db/api/GetWithIndex.java
- core/src/main/java/com/scalar/db/api/IndexGet.java
- core/src/main/java/com/scalar/db/api/IndexScan.java
- core/src/main/java/com/scalar/db/api/OperationBuilder.java
- core/src/main/java/com/scalar/db/api/PutBuilder.java
- core/src/main/java/com/scalar/db/api/ScanBuilder.java
- core/src/main/java/com/scalar/db/api/ScanWithIndex.java
- core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
- core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
- core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
- core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
- core/src/main/java/com/scalar/db/util/ProtoUtils.java
- core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
- core/src/test/java/com/scalar/db/api/GetBuilderTest.java
- core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
- core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
- core/src/test/java/com/scalar/db/util/ProtoUtilsTest.java
This PR introduces `GetWithIndex` and `ScanWithIndex` operations that are read operations using secondary indexes.
We can build `GetWithIndex` and `ScanWithIndex` operations with the builder, and after this change, we can execute read operations using secondary indexes as follows:
```java
Get get =
Get.newBuilder()
.namespace("ns")
.table("tbl")
.indexKey(Key.ofInt("<index key column>", 0)) // specify the index key
.build();
Optional<Result> result = transaction.get(get);
Scan scan =
Scan.newBuilder()
.namespace("ns")
.table("tbl")
.indexKey(Key.ofInt("<index key column>", 0)) // specify the index key
.build();
List<Result> results = transaction.scan(scan);
```
We can already execute read operations using secondary indexes with the existing `Get` and `Scan` actually, but I think using the …
> Introduce GetWithIndex and ScanWithIndex operations

- core/src/main/java/com/scalar/db/storage/common/EmptyScanner.java
- core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
- core/src/main/java/com/scalar/db/storage/cosmos/DeleteStatementHandler.java
- core/src/main/java/com/scalar/db/storage/cosmos/MutateStatementHandler.java
- core/src/main/java/com/scalar/db/storage/cosmos/PutStatementHandler.java
- core/src/main/java/com/scalar/db/storage/cosmos/ScannerImpl.java
- core/src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
- core/src/main/java/com/scalar/db/storage/cosmos/SingleRecordScanner.java
- core/src/main/java/com/scalar/db/storage/cosmos/StatementHandler.java
- core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
- core/src/test/java/com/scalar/db/storage/cosmos/ScannerImplTest.java
- core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
- core/src/test/java/com/scalar/db/storage/cosmos/SingleRecordScannerTest.java
This updates the Cosmos Adapter for Scan operation. Up until now, the `Scanner` object, returned by performing a Scan,  downloaded all at once the records eagerly. Now, the Scanner retrieves the records on demand page by page.
> Add Scanner paging support for scan operations to the Cosmos adapter

- core/src/main/java/com/scalar/db/storage/cosmos/ScannerImpl.java
This updates the ScannerImpl of the Cosmos DB adapter according to this PR comments that could not be applied before the merge on master. 
https://github.com/scalar-labs/scalardb/pull/619#discussion_r910671596
https://github.com/scalar-labs/scalardb/pull/619#discussion_r910672615
> Remove non useful operation in ScannerImpl from the Cosmos DB adapter

- core/src/integration-test/java/com/scalar/db/util/AdminTestUtils.java
- core/src/integration-test/java/com/scalar/db/util/CassandraAdminTestUtils.java
- schema-loader/README.md
- schema-loader/src/integration-test/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
- schema-loader/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
- schema-loader/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
- schema-loader/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderIntegrationTest.java
- schema-loader/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
- schema-loader/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
- schema-loader/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageSchemaLoaderIntegrationTest.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/command/CassandraCommand.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/command/CosmosCommand.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/command/DynamoCommand.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/command/JdbcCommand.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommand.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/command/CassandraCommandTest.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/command/CosmosCommandTest.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/command/DynamoCommandTest.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/command/JdbcCommandTest.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/command/SchemaLoaderCommandTest.java
This adds a `--repair-all` command the Schema Loader Tool used to repair the tables present in the schema file.
For the detailed command usage, please refer to the "Repair table" section in the [readme](https://github.com/scalar-labs/scalardb/blob/d97fe328c9ee460af0db366e899f96bcef861935/schema-loader/README.md#repair-tables).
> Add repair table command to the Schema Loader Tool

- docs/getting-started-with-scalardb.md
- docs/getting-started/build.gradle
Currently, we need to build the `scalardb` project before running the Getting Started app, which is a bit troublesome. This PR resolves this issue by adding the Scalar DB dependency to `build.gradle` in the Getting Started app. Please take a look!
> Update Scalar DB dependency in Getting Started

- schema-loader/README.md
- schema-loader/src/integration-test/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/TableSchemaTest.java
Currently, if we don't specify the `transaction` field in a table definition in a schema file, the table is considered a non-transaction table. But I think the default should be a transaction table in Scalar DB because Scalar DB users usually use Transaction API and Storage API is an advanced feature for experts. This PR changes the default. Please take a look!
> Change default value of is-transaction-table in Schema Loader

- core/src/integration-test/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java
- core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java
- core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
- schema-loader/README.md
**Problem**
Creating a secondary index using the `Admin.createIndex()` will fail for the storage and Scalar DB column type combination below because the current native RDB column type is not compatible with becoming an index.
- MySQL:  TEXT and BLOB
- PostgreSQL : TEXT
- Oracle: TEXT and BLOB
**Implemented fixes**
- Update the `JdbcAdmin.createIndex()` implementation to alter the column type if necessary to be compatible with a secondary index and then create the index. If the column holds data whose size is too big for the new altered type, an exception will be thrown.
- When an index is deleted using `JdbcAdmin.dropIndex()` the column type will be altered from the index compatible type back to the regular column type if necessary.
- Since Oracle does not natively support the column type …
> In the Admin create and drop index methods, alter column type if necessary

- build.gradle
This fixes CVE-2022-31197
The docker CI is failing because of another CVE located in the JRE image, cf. https://github.com/scalar-labs/docker/pull/9
> Fix CVE-2022-31197 affecting PostgreSQL driver

- schema-loader/Dockerfile
- server/Dockerfile
This PR updates the JRE image to `jre8:1.1.5` to fix the CVE-2021-46828. 
The docker CI is failing because of the other CVE affecting the PosgreSQL driver. The driver is being updated in https://github.com/scalar-labs/scalardb/pull/650
> Fix CVE-2021-46828 by bumping the jre8 dependency version

- schema-loader/Dockerfile
- server/Dockerfile
This PR updates the JRE image to `jre8:1.1.6` to fix the CVE-2022-2509. Please take a look!
> Fix CVE-2022-2509

- core/src/integration-test/java/com/scalar/db/api/DistributedStorageAdminRepairTableIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/api/DistributedTransactionAdminRepairTableIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminRepairTableIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminRepairTableIntegrationTestWithCassandra.java
- core/src/integration-test/java/com/scalar/db/util/AdminTestUtils.java
- core/src/integration-test/java/com/scalar/db/util/CassandraAdminTestUtils.java
- core/src/integration-test/java/com/scalar/db/util/CosmosAdminTestUtils.java
- core/src/integration-test/java/com/scalar/db/util/DynamoAdminTestUtils.java
- core/src/integration-test/java/com/scalar/db/util/JdbcAdminTestUtils.java
- core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
- core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
- core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
This updates the `Admin.repairTable()` method implementation to handle the case if the metadata for the table is corrupted. 
So far, the method implementation was only creating the metadata for the table if it did not exist. This PR updates it so that if the metadata are present, they are : 
- for the `JdbcAdmin`, they are deleted and then added
- for the `CosmosAdmin` and `DynamoAdmin`, they are upserted.
> Admin "repairTable()" handle metadata corruption

- core/src/integration-test/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
- core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
- core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransaction.java
- core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java
- core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransaction.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionOnBidirectionalStream.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
- core/src/test/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManagerTest.java
- rpc/src/main/grpc/com/scalar/db/rpc/TwoPhaseCommitTransactionGrpc.java
- rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
- rpc/src/main/java/com/scalar/db/rpc/TwoPhaseCommitTransactionRequest.java
- rpc/src/main/java/com/scalar/db/rpc/TwoPhaseCommitTransactionRequestOrBuilder.java
- rpc/src/main/java/com/scalar/db/rpc/TwoPhaseCommitTransactionResponse.java
- rpc/src/main/java/com/scalar/db/rpc/TwoPhaseCommitTransactionResponseOrBuilder.java
- rpc/src/main/proto/scalardb.proto
- server/src/main/java/com/scalar/db/server/TwoPhaseCommitTransactionService.java
- server/src/test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceTest.java
This PR adds `begin()` and `abort()` methods to Two-phase Commit Transaction API. I'll add inline comments for the details. Please take a look!
> Add begin() and abort() to Two-phase Commit Transaction API

- core/src/main/java/com/scalar/db/api/Admin.java
Since `Admin.getTableMetadata()` may return null, we should add `@Nullable` to it. Please take a look!
> Add @Nullable to Admin.getTableMetadata()

- core/src/integration-test/java/com/scalar/db/util/DynamoAdminTestUtils.java
- core/src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java
- core/src/main/java/com/scalar/db/storage/dynamo/DeleteStatementHandler.java
- core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
- core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
- core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
- core/src/main/java/com/scalar/db/storage/dynamo/Namespace.java
- core/src/main/java/com/scalar/db/storage/dynamo/PutStatementHandler.java
- core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
- core/src/test/java/com/scalar/db/storage/dynamo/BatchHandleWithNamespacePrefixTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/BatchHandleWithoutNamespacePrefixTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/BatchHandlerTestBase.java
- core/src/test/java/com/scalar/db/storage/dynamo/DeleteStatementHandlerTestBase.java
- core/src/test/java/com/scalar/db/storage/dynamo/DeleteStatementHandlerWithPrefixTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/DeleteStatementHandlerWithoutPrefixTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestWithDefaultConfigTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminWithDefaultConfigTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminWithNamespacePrefixAndTableMetadataNamespaceConfigTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminWithNamespacePrefixConfigTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoConfigTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/PutStatementHandlerTestBase.java
- core/src/test/java/com/scalar/db/storage/dynamo/PutStatementHandlerWithPrefixTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/PutStatementHandlerWithoutPrefixTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTestBase.java
- core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerWithPrefixTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerWithoutPrefixTest.java
- docs/getting-started-with-scalardb-on-dynamodb.md
This PR adds a new configuration when using DynamoDB to be able to set a namespace prefix 
```
scalar.db.dynamo.namespace.prefix=my_prefix_
```
> Add namespace prefix support for Dynamo

- server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
- server/src/main/java/com/scalar/db/server/TwoPhaseCommitTransactionService.java
We should log when UnknownTransactionStatusException is thrown for debugging in Scalar DB Server. This PR adds logging for it. Please take a look!
> Add logging for UnknownTransactionStatusException in Scalar DB Server

- schema-loader/Dockerfile
- server/Dockerfile
This PR updates the JRE image to `jre8:1.1.7` to fix CVE-2022-37434. Please take a look!
> Fix CVE-2022-37434

- core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcUtilsTest.java
As we have found how to avoid the "No suitable driver" error in https://github.com/scalar-labs/kelpie/pull/28, we no longer need to call `setDriver()` for `BasicDataSource`.
> Delete setDriver() for BasicDataSource in JDBC

- core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java
- core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/util/CosmosAdminTestUtils.java
- core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
- core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java
- core/src/main/java/com/scalar/db/storage/cosmos/CosmosNamespace.java
- core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
- core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminWithMetadataDatabaseConfigTest.java
- core/src/test/java/com/scalar/db/storage/cosmos/CosmosConfigTest.java
This implement the `admin.getNamespaceNames()` for the CosmosAdmin .
> Add method to retrieve the namespace names for Cosmos Admin

- core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminIntegrationTestWithCassandra.java
- core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
- core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
- core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
- core/src/main/java/com/scalar/db/storage/cassandra/CassandraConfig.java
- core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTestBase.java
- core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminWithDefaultConfigTest.java
- core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminWithMetadataKeyspaceConfigTest.java
- core/src/test/java/com/scalar/db/storage/cassandra/CassandraConfigTest.java
This implements the `admin.getNamespaceNames()` for the Cassandra admin.
> Add method to retrieve the namespace names for Cassandra Admin

- core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
This PR updates the `JdbcAdmin.namespaceExists()` method to only return true if the namespace was created through Scalar DB.
> Update JdbcAdmin.namespaceExists() 

- .github/workflows/release.yaml
This PR updates release workflow to push container image to ECR of AWS Marketplace.
I use Identity Provider (OpenID Connect) instead of access key and secret access key to authenticate ECR in the CI.
I will add some comment in the code.
> Update release workflow to push container to ECR of Marketplace

- schema-loader/Dockerfile
- server/Dockerfile
This fixes several CVEs by updating the internal JRE used in docker images.
The CI is failing because of another CVE targeting the `grpc_health_probe` package, which will be addressed in another PR as there is no fix available as of now.
> Fix CVE-2021-3999, CVE-2022-1586 and CVE-2022-1587

- docs/getting-started/src/main/java/sample/ElectronicMoney.java
- docs/getting-started/src/main/java/sample/ElectronicMoneyMain.java
Add external Scalar DB property file support to getting-started application for compatibility tests and other external use.
Now we can run getting-started application with/without external property file
```
./gradlew run --args="-action charge -amount 1000 -to user1"
```
or
```
./gradlew run --args="-config <Scalar DB property file path> -action charge -amount 1000 -to user1"
```
The CI failed because of some other vulnerabilities.
Ref: https://github.com/scalar-labs/scalar-qa/pull/5#discussion_r969213496
> Add external Scalar DB property file support to getting-started application

- docs/scalardb-supported-databases.md
I got an exception while connecting  the Scalar DB version `3.x` to AWS Aurora Mysql 5.7
```
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
...
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
at sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:171)
at sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
```
But it is working fine …
> Update the Scalar DB supported database matrix with Scalar DB 3.7

- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminWithCoordinatorNamespaceConfigTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminWithDefaultConfigTest.java
This PR refactor the `ConsensusCommitAdmin` unit test class to be able to write tests easily for different values of `ConsensusCommitConfig.COORDINATOR_NAMESPACE`. All the storage admin classes were refactored the same way, for example, the [JdbcAdmin](https://github.com/scalar-labs/scalardb/pull/670/files)
> Refactor ConsensusCommitAdmin unit test

- .github/workflows/ci.yaml
The Azure VM running the CI for the Cosmos integration test ended up running out of disk space.
One of the reasons was that Gradle daemon creates a lot of log files. In this case, 20GB of logs file were created in the span of 5 months. 
So we decided to add a step to the CI to delete these log files. Below is the output produced by the new step.
> In the Cosmos DB job of the CI, add a step to clean up gradle daemon logs file

- core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java
- core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminTestUtils.java
- core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
- core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
This implement the `CosmosAdmin.upgrade()` method in relation to the namespace management feature as it was done for the `JdbcAdmin` (cf. https://github.com/scalar-labs/scalardb/pull/696). 
FYI, the target branch is [feat/namespaces_management](https://github.com/scalar-labs/scalardb/tree/feat/namespaces_management)
> Add upgrade() method to the Cosmos Admin

- core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java
- core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminTestUtils.java
- core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
This implement the `DynamoAdmin.upgrade()` method in relation to the namespace management feature as it was done for the `JdbcAdmin` (cf. https://github.com/scalar-labs/scalardb/pull/696). 
FYI, the target branch is [feat/namespaces_management](https://github.com/scalar-labs/scalardb/tree/feat/namespaces_management)
> Add upgrade() method to the Dynamo Admin

- core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminTestUtils.java
- core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminIntegrationTestWithCassandra.java
- core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTestUtils.java
- core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
- core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTestBase.java
This implement the `Cassandra.upgrade()` method in relation to the namespace management feature as it was done for the `JdbcAdmin` (cf. https://github.com/scalar-labs/scalardb/pull/696). 
FYI, the target branch is [feat/namespaces_management](https://github.com/scalar-labs/scalardb/tree/feat/namespaces_management)
> Add upgrade() method to the Cassandra Admin

- server/Dockerfile
This PR fixes CVE-2022-27664 by updating the `grpc_health_probe` package. Please take a look!
> Fix CVE-2022-27664

- core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java
- core/src/main/java/com/scalar/db/service/TransactionService.java
- core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java
- core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
- core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionManagerTest.java
- docs/api-guide.md
- integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
This PR add a method `resume()` to `DistributedTransactionManager`. And it also makes `DistributedTransactionManager` hold the ongoing transactions, and we will be able to get these transactions with the `resume()` method. Please take a look!
> Add resume() to DistributedTransactionManager

- core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/common/WrappedDistributedTransaction.java
- core/src/main/java/com/scalar/db/transaction/common/WrappedTwoPhaseCommitTransaction.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
- core/src/test/java/com/scalar/db/transaction/common/AbstractDistributedTransactionManagerTest.java
- core/src/test/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransactionManagerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
This PR adds transaction state management to improve usability. The purpose of this state management is to unify the call sequence of the transaction object (e.g. CRUD -> prepare -> validate -> commit or CRUD -> prepare (failed) -> rollback, etc.). I'll add inline comments for the details. Please take a look!
> Add transaction state management

- docs/schema-loader.md
This PR adds the description of limitations of data types in the docs of the schema. For example, the range of `BIGINT` is described in the javadoc only. So, I added the link of javadoc to see the details of data types.
> Add description of limitations of data types

- core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/common/ActiveTransactionManagedTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
This is a refactoring thing. This PR separate the active transaction management from `AbstractDistributedTransactionManager` and `AbstractTwoPhaseCommitTransactionManager`, and it adds `ActiveTransactionManagedTransactionManager` and `ActiveTransactionManagedTransactionManager` to manage active transactions.
> Separate active transaction management from AbstractDistributedTransactionManager and AbstractTwoPhaseCommitTransactionManager

- docs/backup-restore.md
This PR fixes the broken link of the scalar-admin client tool in the backup document.
> Fix the broken link in the backup document

- server/Dockerfile
This PR fixes CVE-2022-32149 by upgrading [grpc-health-probe](https://github.com/grpc-ecosystem/grpc-health-probe).
> Fix CVE-2022-32149

- build.gradle
- core/build.gradle
This PR fixes CVE-2022-42003 and CVE-2022-42004 by upgrading the Azure Cosmos client. Please take a look!
> Fix CVE-2022-42003 and CVE-2022-42004

- build.gradle
- gradle/spotbugs-exclude.xml
- rpc/build.gradle
A similar change to https://github.com/scalar-labs/scalardb-sql/pull/74. PTAL~
> I noticed we can't build this project with JDK 9 or later, but JDK 8 isn't actively supported. So I tried supporting JDK 9 or later by fixing build dependency and spotbugs issues while I tested it only with JDK 11.
> The package of this project is built on CI using JDK 8, so I don't think this change affects the Maven package artifacts.
~"spotlessApply" gradle task changed the Javadoc comments this time, though.~ 
Hmm. ~This~ `spotlessCheck` error happened only on my laptop. Reverted the changes.
> Fix dependency and spotbugs issues for >JDK 8

- core/src/main/java/com/scalar/db/storage/dynamo/DynamoOperationChecker.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoOperationCheckerTest.java
Since Dynamo DB doesn't allow putting an empty value to a secondary index column, we should throw an exception in that situation. Please take a look!
> Throw an exception when putting an empty value to a secondary index column in Dynamo DB

- core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
I found by chance small errors in two unit tests of the `OperationChecker`, this PR fixes them. Please see the inline comments for more details.
NB: the "docker" CI is failing because of a CVE
> Fix two unit tests of OperationChecker

- core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java
In current implementation, `scalar.db.consensus_commit.parallel_commit.enabled` is true by default. As a result, JVM process won't finish without explicitly calling `ParallelExecutor#close`, `System.exit` or receiving signals. This might block some kinds of applications or components which don't have chance to call `ParallelExecutor#close` for some reasons.
In this PR, we've changed ParallelExecutor workers to daemon threads not to block JVM process termination. Even if a user don't have chance to call `ParallelExecutor#close` for some reasons, `java.lang.Runtime#addShutdownHook` can be used to call the method as it's guaranteed that daemon threads will continue to run during the shutdown sequence https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Runtime.html#addShutdo …
> Make ParallelExecutor workers daemon thread

- build.gradle
- core/build.gradle
- integration-test/build.gradle
- schema-loader/build.gradle
- server/build.gradle
I noticed there were sometimes differences between the spotlessCheck results on my laptop (JDK11) and CI (JDK8.) It seems different versions of https://github.com/google/google-java-format are internally used via the spotless plugin. This PR specifies the google-java-format version to make JDK11+ use the same version as JDK8 uses.
> Make JDK11+ use the same google java format version as JDK8 uses

- core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminIntegrationTest.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminIntegrationTestBase.java
- server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedTransactionAdminService.java
**Background**
This PR is part of the namespace management feature and targets its feature branch [feat/namespaces_management](https://github.com/scalar-labs/scalardb/tree/feat/namespaces_management)
**Changes** 
We decided that the `ConsensusCommitAdmin` methods should not expose the coordinator namespace and table (implemented by https://github.com/scalar-labs/scalardb/pull/702).  
To stay consistent, this updates the `ConsensusCommitAdmin.getNamespaceNames()` to not return the coordinator namespace name.
> Make ConsensusCommitAdmin.getNamespaceNames() to not return the coordinator namespace name

- core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSchemaLoaderIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageSchemaLoaderIntegrationTest.java
- docs/schema-loader.md
- integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/command/SchemaLoaderCommandTest.java
**Context**
This PR is part of the namespace management feature and targets its feature branch [feat/namespaces_management](https://github.com/scalar-labs/scalardb/tree/feat/namespaces_management)
**Changes** 
This PR adds the `--upgrade` command to the schema loader which is identical to calling the [admin.upgrade(Map<String, String options)](https://github.com/scalar-labs/scalardb/blob/9fce0686aa0a2d2b07f6562a5ea17c5d6638ed6c/core/src/main/java/com/scalar/db/api/Admin.java#L392-L399) method. 
For a concrete explanation of what running this method does, please refer to this [PR](https://github.com/scalar-labs/scalardb/pull/696#issue-1367431598)
> Add upgrade command to schema loader

- .github/workflows/ci.yaml
- .github/workflows/vuln-check.yaml
Current main CI workflow contains vulnerability check tasks and they sometimes results in CI failure due to third party security issue that we can't always handle on our side. This PR moves the check to a separate daily scheduled workflow not to block our PR flows.
We'll take care of vuln check for some released versions as a different PR.
> Move vuln check to a separate daily workflow

- .github/workflows/vuln-check.yaml
This is a follow up PR to https://github.com/scalar-labs/scalardb/pull/737, although there is room to improve it. PTAL~
> Conduct daily vulnerability checks on releases not only on `main` branch

- docs/api-guide.md
It seems that there are some key definitions in the sample of the `all()` method of the `Scan` API.
However, I think we don't need to set the partition key and clustering key if we use the `Scan.all()`.
So, this PR removes the above unnecessary key definitions in the sample of `Scan.all()`.
> Remove unnecessary key definition from API guide

- core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java
- core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java
- core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTransactionManager.java
- core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
- core/src/main/java/com/scalar/db/exception/transaction/TransactionNotFoundException.java
- core/src/main/java/com/scalar/db/service/TransactionService.java
- core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
- core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
- core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionManagerTest.java
- core/src/test/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManagerTest.java
- integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
This PR adds `TransactionNotFoundException` and throws it when resuming a transaction but it's not found. We need this because we need special handling for the transaction not found situation, so it is helpful that we can catch a dedicated exception for that situation. Please take a look!
> Throw TransactionNotFoundException when resuming a transaction but it's not found

- docs/api-guide.md
I think ScalarDB needs to read records (prepare ReadSet) using `Get` or `Scan` before it runs `Put` (update) or `Delete`.
However, it seems that there is no description/note about it in the API guide. So, I added the note in the API guide.
> Add note for Put/Delete operation in the API guide

- core/src/main/java/com/scalar/db/api/Result.java
- core/src/main/java/com/scalar/db/common/ResultImpl.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/FilteredResult.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/MergedResult.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionResult.java
This PR deprecates the `getPartitionKey()` and `getClusteringKey()` methods of the `Result` class. This is because those methods are more like utility ones, so we should separate them into another utility class. I will add that utility class in another PR, and this PR just deprecates the methods. Please take a look!
> Deprecate getPartitionKey() and getClusteringKey() of Result

- integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/util/TestUtils.java
As the `getPartitionKey()` and `getClusteringKey()` methods of the `Result` class are deprecated in #750, this PR removes the usages from the integration tests. Please take a look!
> Remove usages of getPartitionKey() and getClusteringKey() of Result from integration tests

- core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java
- core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
- core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java
- core/src/test/java/com/scalar/db/storage/cosmos/CosmosConfigTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoConfigTest.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
- core/src/test/java/com/scalar/db/storage/rpc/GrpcConfigTest.java
When I forgot to set `scalar.db.contact_points`, I ran into `java.lang.ArrayIndexOutOfBoundsException: 0` exception. It's not so user friendly for users. This PR adds a validation to confirm if `contactPoints` isn't empty in XxxxConfig classes.
> Validate contact points size in XxxxConfig to avoid "java.lang.ArrayIndexOutOfBoundsException: 0"

- README.md
In the current Github Packages, anyone can pull the `scalardb-server` image despite it being provided only a commercial license.
And, anyone can build the `scalardb-server` image in their local environment since the code and Dockerfile are public.
Also, in AWS/Azure marketplace, it describes that the ScalarDB Server is provided as BYOL clearly.
So, I think it would be better to describe it in the README of the GitHub repository.
> Add ScalarDB Server's license description in the README

- integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminRepairTableIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
This PR makes some of the fields and the methods in integration test bases for the transaction API `protected` to make them extendable. Please take a look!
> Make integration test bases for transaction extendable

- schema-loader/Dockerfile
- server/Dockerfile
The vulnerability check result is https://github.com/scalar-labs/scalardb/actions/workflows/manual-vuln-check.yaml
> Upgrade docker image version to fix CVE-2021-46848

- build.gradle
This PR fixes CVE-2022-21363 and CVE-2021-2471 by upgrading the MySQL driver. These vulnerabilities are detected in https://mvnrepository.com/artifact/com.scalar-labs/scalardb/3.7.2.
> Fix CVE-2022-21363 and CVE-2021-2471

- core/src/main/java/com/scalar/db/config/ConfigUtils.java
- core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
- core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java
- core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
- core/src/main/java/com/scalar/db/storage/rpc/GrpcUtils.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionAdmin.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
- core/src/test/java/com/scalar/db/config/ConfigUtilsTest.java
- core/src/test/java/com/scalar/db/storage/rpc/GrpcConfigTest.java
- docs/scalardb-server.md
- server/src/main/java/com/scalar/db/server/ScalarDbServer.java
- server/src/main/java/com/scalar/db/server/ServerConfig.java
- server/src/test/java/com/scalar/db/server/ServerConfigTest.java
This PR adds the following configurations for gRPC:
For the client side:
```properties
scalar.db.grpc.max_inbound_message_size=
scalar.db.grpc.max_inbound_metadata_size=
```
For the server side:
```properties
scalar.db.server.grpc.max_inbound_message_size=
scalar.db.server.grpc.max_inbound_metadata_size=
```
> Add configurations for gRPC

- docs/schema-loader.md
Indeed these types are valid in SQLite 3:
```console
% sqlite3
SQLite version 3.37.0 2021-12-09 01:34:53
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> create table t2 (c1 boolean, c2 int, c3 bigint, c4 float, c5 double, c6 text, c7 blob);
```
Note that types in SQLite are quite loose and column types do not affect value types.
(see: https://www.sqlite.org/datatype3.html and https://www.sqlite.org/flextypegood.html if interested)
> docs: add SQLite data type mapping in schema-loader doc

- core/src/main/java/com/scalar/db/common/AbstractDistributedTransactionManager.java
- core/src/main/java/com/scalar/db/common/AbstractTwoPhaseCommitTransactionManager.java
- core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java
- core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
- core/src/main/java/com/scalar/db/common/DecoratedDistributedTransaction.java
- core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransaction.java
- core/src/main/java/com/scalar/db/common/DistributedTransactionDecorator.java
- core/src/main/java/com/scalar/db/common/TwoPhaseCommitTransactionDecorator.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
This PR introduces `DistributedTransactionDecorator` and `TwoPhaseCommitTransactionDecorator` that decorate transaction objects (`DistributedTransaction` and `TwoPhaseCommitTransaction` instances) before returning the objects. With this extension point, we can add some behavior to the transaction objects with the decorator pattern.
> Add transaction decorator

- docs/scalardb-server.md
I was not able to find the description of how to build a Docker image of ScalarDB Server from the source code.
From the perspective of customers/users, there is no problem since they can get the docker image from Github Packages or each marketplace.
However, from the perspective of developers (mainly new development members), I think this is useful information.
So, I added it to the document. Please take a look!
> Add description how to build docker image of ScalarDB Server

- docs/scalardb-server.md
- server/Dockerfile
- server/build.gradle
- server/conf/database.properties
- server/conf/log4j2.properties
Note: **This PR does NOT keep backward compatibility** since users cannot use the `dockerize (Go text/template)` syntax to configure some properties in the properties file.
This PR removes the `dockerize` command from the ScalarDB Server container image and renames/updates related files.
Before, we use the template feature of the `dockerize` command to set credentials to properties files from environment variables. And, we use the `dockerize` command to use this feature only.
However, the ScalarDB Server natively supports setting credentials from environment variables now.  
https://github.com/scalar-labs/scalardb/pull/770
So, we don't need to use the `dockerize` command now.
---
For your reference, I was able to run the ScalarDB Server image without the `dockerize` …
> Remove dockerize command from container image

- core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java
- core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
In the active transaction management, we hold active transactions in the `ActiveExpiringMap`, which expires and rolls back a transaction in a dedicated thread when the transaction is timed out. 
ActiveTransactionManagedDistributedTransactionManager:
https://github.com/scalar-labs/scalardb/blob/should-synchronize-in-active-transaction-management/core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java#L42
ActiveTransactionManagedTwoPhaseCommitTransactionManager:
https://github.com/scalar-labs/scalardb/blob/should-synchronize-in-active-transaction-management/core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java#L44
In that case, a transaction object can be accessed by multiple threads at the same time, …
> Should synchronize in active transaction management

- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
- docs/two-phase-commit-transactions.md
Before this change, one of the limitations in 2PC transaction was that we need to call `commit()`/`rollback()` in a coordinator process before calling `commit()`/`rollback()` in participant processes. This PR gets rid of this limitation. After this change, we can call `commit()`/`rollback()` in parallel in all coordinator/participant processes.
I'll add inline comments for the details. Please take a look!
> Allow commit() and rollback() to be called in parallel in all coordinator/participant processes in 2PC transactions

- schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
Currently, `SchemaOperator` in Schema Loader has two admin instances (`storageAdmin` and `transactionAdmin`), and it creates the instances in the constructor even if they are used or not. But we can create them lazily only when they are really used. This PR fixes it. Please take a look!
> Load admins lazily in Schema Loader

- schema-loader/Dockerfile
- server/Dockerfile
This PR fixes CVE-2022-42898 by updating the internal JRE used in docker images. Please take a look!
> Fix CVE-2022-42898

- build.gradle
- core/src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java
- core/src/test/java/com/scalar/db/storage/dynamo/BatchHandlerTestBase.java
Amazon DynamoDB now supports up to 100 actions per transaction according to the following article:
https://aws.amazon.com/about-aws/whats-new/2022/09/amazon-dynamodb-supports-100-actions-per-transaction/
So, this PR modifies the DynamoDB adapter based on it. Please take a look!
> DynamoDB supports up to 100 actions per transaction

- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
- docs/configurations-for-consensus-commit.md
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminRepairTableIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
- server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedTransactionAdminService.java
- server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminRepairTableIntegrationTestWithDistributedTransactionAdminService.java
- server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithDistributedTransactionService.java
- server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithTwoPhaseCommitTransactionService.java
This PR reverts the async commit default value to `false` (disabled) because enabling the async commit feature can cause `UncommittedRecordException` when reading a record right after writing the record in another transaction, which can be an incompatible behavior change. After we add some optimization to avoid that behavior change to the consensus commit, we can re-enable the async commit feature by default. Please take a look.
> Revert async commit default value

- .github/workflows/vuln-check.yaml
Trivy workflow often fails these days. It seems the root cause is that `search.maven.org` API is recently unstable. https://github.com/aquasecurity/trivy/issues/3421
`--offline-scan` might be an option, but it looks to have some security trade offs.
This PR increases Trivy timeout using `--timeout` option without any negative impact.
> Increase Trivy timeout

- .github/workflows/scheduled-vuln-check.yaml
We increased the timeout of the vulnerability check workflow to mitigate Trivy timeout issue. It's been working fine, but it might be increasing the consumption of GitHub Action execution time budget. This PR reduces the frequency of the vulnerability check.
> Run vulnerability check twice a week

- core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
With the changes introduced by https://github.com/scalar-labs/scalardb/pull/786 , In a 2pc scenario, after the first participant commits the transaction, the other participant who will commit will trigger this warning log message to be printed even though it is a nominal execution (cf. https://github.com/scalar-labs/scalardb/pull/786#discussion_r1063237976)
```
[main] WARN com.scalar.db.transaction.consensuscommit.Coordinator - mutation seems applied already
com.scalar.db.exception.storage.NoMutationException: no mutation was applied
at com.scalar.db.storage.jdbc.JdbcDatabase.put(JdbcDatabase.java:111)
at com.scalar.db.transaction.consensuscommit.Coordinator.put(Coordinator.java:118)
at com.scalar.db.transaction.consensuscommit.Coordinator.putState(Coordinator.java:70)
at …
```
> Remove the log "mutation seems applied already"

- docs/backup-restore.md
This PR updates the links of ScalarDB Server and Schema Loader in the backup/restore guide.
Before it links code directories of [ScalarDB Server](https://github.com/scalar-labs/scalardb/tree/master/server) and [Schema Loader](https://github.com/scalar-labs/scalardb/tree/master/schema-loader).
However, there are no README.md in those directories at this time.
From the perspective of users, I think it would be better to link to the documents of [ScalarDB Server](https://github.com/scalar-labs/scalardb/blob/master/docs/scalardb-server.md) and [Schema Loader](https://github.com/scalar-labs/scalardb/blob/master/docs/schema-loader.md).
> Update links of ScalarDB Server and Schema Loader

- docs/scalardb-supported-databases.md
According to the AWS official document, it seems that `Amazon Aurora` is the correct name.
This PR fixes `AWS Aurora` to `Amazon Aurora`.
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/CHAP_AuroraOverview.html
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.AuroraMySQL.html
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.AuroraPostgreSQL.html
> Fix product name of Amazon Aurora

- .pre-commit-config.yaml
- README.md
- docs/index.md
ScalarDB developers execute `gradlew spotlessApply` or IDE code formatter manually as a part of development. But the manual operation should be automated and documented for new contributors. This PR describes how to setup the automated operation. The drawback is every commit invokes `gradlew spotless` and it would increase the latency of commit a bit (especially for the first invocation of Gradle daemon.)
> Automatically format source code with pre-commit

- docs/api-guide.md
- docs/backup-restore.md
- docs/design.md
- docs/getting-started-with-scalardb-on-cosmosdb.md
- docs/getting-started.md
- docs/scalardb-server.md
- docs/scalardb-supported-databases.md
- docs/schema-loader.md
- docs/storage-abstraction.md
This PR updates the Cosmos DB name from `Cosmos DB` to `Cosmos DB for NoSQL` in the supported DB document since the official name was changed.
https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/
Also, I want to discuss whether we should update this name in the documents other than the supported DB document.
There are some documents that state `Cosmos DB`. So, if we should update them to `Cosmos DB for NoSQL`, I will do it in this PR.
What do you think?
> Update Cosmos DB name in supported DB docs

- docs/api-guide.md
- docs/backup-restore.md
- docs/design.md
- docs/getting-started-with-scalardb-on-cosmosdb.md
- docs/getting-started.md
- docs/scalardb-server.md
- docs/scalardb-supported-databases.md
- docs/schema-loader.md
- docs/storage-abstraction.md
Note: This PR depends on PR #813.
This PR updates the steps of creating/configuring the `Cosmos DB for NoSQL` account for ScalarDB in the getting started guide.
Before, the getting started guide explains concrete steps based on the Azure portal page, but there is a possibility that the UI of the portal page will be changed in the future.
So, I updated it to describe the overview of steps and add links to the official document.
This can reduce the maintenance cost of documents when the Azure portal UI is changed.
> Update docs how to create a Cosmos DB for NoSQL account

- schema-loader/Dockerfile
- server/Dockerfile
This fixes the CVE-2023-0286 by updating the internal JRE8 version to 1.1.11
I confirmed the vulnerability check is passing with https://github.com/scalar-labs/scalardb/actions/runs/4199712570
> Fix CVE-2023-0286

- .github/workflows/release-snapshot.yaml
- .github/workflows/release.yaml
- .github/workflows/vuln-check.yaml
**Problem** 
All vulnerability checks actions are failing because the "set-version" step of the `vuln-check` workflow fails. 
**Root cause**
This step is using gradle that comes preinstalled with the workflow image. Lately, the pre-installed gradle version was updated to gradle 8 which does not seem compatible with  the `com.palantir.docker` plugin.
**Fix**
Use the project `./gradlew` instead of `gradle` which will use gradle 7 in the `vuln-check` WF as well in all other WF as a preemptive measure.
**Validation**
I confirmed the step is working properly with `./gradlew`  on this commit https://github.com/scalar-labs/scalardb/pull/822/commits/3a34f7b128d5ae44f5ebac8eda5d6599fb996555. 
You can see the full `vuln-check` workflow run for this commit here : …
> Replace usage of gradle by gradle wrapper in Github workflows

- core/src/main/java/com/scalar/db/api/DeleteBuilder.java
- core/src/main/java/com/scalar/db/api/GetBuilder.java
- core/src/main/java/com/scalar/db/api/OperationBuilder.java
- core/src/main/java/com/scalar/db/api/PutBuilder.java
- core/src/main/java/com/scalar/db/api/ScanBuilder.java
- core/src/test/java/com/scalar/db/api/DeleteBuilderTest.java
- core/src/test/java/com/scalar/db/api/GetBuilderTest.java
- core/src/test/java/com/scalar/db/api/PutBuilderTest.java
- core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
As the first part of the changes to be able to set a default operation namespace via the ScalarDB configuration, this PR : 
- makes it optional to set a namespace in the operation builder
- adds a `clearNamespace()` method when building from an existing operation.
> Make namespace optional on operation builder

- integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminRepairTableIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedStorageColumnValueIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedStorageConditionalMutationIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedStorageSecondaryIndexIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedStorageSingleClusteringKeyScanIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedStorageSinglePartitionKeyIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedStorageWithReservedKeywordIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminRepairTableIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
- server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedTransactionAdminService.java
- server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithDistributedTransactionService.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceColumnValueIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceConditionalMutationIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSecondaryIndexIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSingleClusteringKeyScanIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSinglePartitionKeyIntegrationTest.java
- server/src/integration-test/java/com/scalar/db/server/SchemaLoaderIntegrationTestWithScalarDbServer.java
- server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithTwoPhaseCommitTransactionService.java
This PR makes overridden methods in the integration tests throw `Exception`. We do this because we can't assume which exception will be thrown in the overriding methods. Please take a look!
> Make overridden methods throw Exception in integration tests

- docs/backup-restore.md
This PR adds how to repair stored procedures of Cosmos DB for NoSQL.
We must repair tables manually after we restore tables using PITR since it doesn't restore stored procedures automatically.
> Add repair section for cosmosdb restore

- server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithServer.java
- server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminRepairTableIntegrationTestWithServer.java
- server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithServer.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminIntegrationTestWithServer.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminRepairTableIntegrationTestWithServer.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageColumnValueIntegrationTestWithServer.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageConditionalMutationIntegrationTestWithServer.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageIntegrationTestWithServer.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageMultipleClusteringKeyScanIntegrationTestWithServer.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageMultiplePartitionKeyIntegrationTestWithServer.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageSecondaryIndexIntegrationTestWithServer.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageSingleClusteringKeyScanIntegrationTestWithServer.java
- server/src/integration-test/java/com/scalar/db/server/DistributedStorageSinglePartitionKeyIntegrationTestWithServer.java
- server/src/integration-test/java/com/scalar/db/server/SchemaLoaderIntegrationTestWithServer.java
- server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithServer.java
This PR renames the integration test classes for Server to `XXXWithServer`. Please take a look!
> Rename integration test classes for Server

- schema-loader/Dockerfile
- server/Dockerfile
This PR take care of CVE-2023-0361 and CVE-2022-41723 to handle the following failures
- https://github.com/scalar-labs/scalardb/actions/runs/4538103121/jobs/7996675492
- https://github.com/scalar-labs/scalardb/actions/runs/4536073392/jobs/7992310369
> Fix CVE-2023-0361 and CVE-2022-41723

- core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminTestUtils.java
- core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTestUtils.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
- core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
- core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
- core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
- core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
- core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
- core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcUtilsTest.java
- server/src/integration-test/java/com/scalar/db/server/ServerAdminTestUtils.java
This PR explicitly specifies a driver class in the JDBC adapter to avoid the "No suitable driver" error in case when `ServiceLoader` in `java.sql.DriverManager` doesn't work (e.g., when we dynamically load a driver class from a fatJar).
> Explicitly specify driver class in JDBC adapter

- docs/getting-started/build.gradle
This PR adds `slf4j-simple` to the sample application for [Getting Started with ScalarDB](https://github.com/scalar-labs/scalardb/blob/master/docs/getting-started-with-scalardb.md).
The current sample application doesn't include any logging libraries. So, it outputs some WARNING messages of SLF4J as follows.
```console
$ ./gradlew run --args="-action charge -amount 1000 -to user1"
> Task :run
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
BUILD SUCCESSFUL in 1s
2 actionable tasks: 1 executed, 1 up-to-date
```
Sometimes, these messages make users confusing. Users think "Any problem occurs?" by seeing these messages.
(Actually, I …
> Add SLF4J Simple Binding to sample application

- docs/getting-started-with-scalardb-on-jdbc.md
As described in https://github.com/scalar-labs/scalardb/pull/819#discussion_r1161205858
> docs: write about `busy_timeout` parameter for JDBC SQLite storage

- .github/workflows/ci.yaml
- build.gradle
- core/build.gradle
- core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminIntegrationTestWithJdbcDatabase.java
- core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminTestUtils.java
- core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminIntegrationTest.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
- core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineFactory.java
- core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java
- core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
- core/src/test/java/com/scalar/db/storage/jdbc/RdbEngine.java
- core/src/test/java/com/scalar/db/storage/jdbc/RdbEngineSqliteTest.java
- core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
PR to #762 
I intend to finish all the implementations and automated tests to support SQLite.
I mean, after this PR is merged to `feat/jdbc-sqlite` branch, #762 can be merged to master.
If I miss anything, please let me know.
- ~~@brfrn169 [requested to add integration tests](https://github.com/scalar-labs/scalardb/pull/819#pullrequestreview-1300899804). I will do it in another PR.~~ -> TODO in this PR
- @feeblefakie [requested to add doc comments in RdbEngineStrategy](https://github.com/scalar-labs/scalardb/pull/819#discussion_r1111946857)
I conducted the following manual tests.
1. Modified `core/build.gradle` to create a shadow JAR: <https://github.com/scalar-labs/scalardb/pull/816/files#diff-8661f4ba56dd608a0331a1b951fcc910c80ddd53de7dec30cdf6c0e773cab6d0>
2. Modified …
> feat: SQLite support implementations and tests

- .github/workflows/release-snapshot.yaml
This PR adds new steps to the SNAPSHOT release workflow. These new steps push the SNAPSHOT version container images.
Sometimes, we need to update Helm Chart based on the new feature of ScalarDB.
However, in the Scalar Helm Chart repository, it uses the container images of the latest release version (not the snapshot version) in the CI.
This causes CI failures of the Helm Chart repository. For example, when the new feature of ScalarDB is merged into the `master` branch, we need to update Helm Chart and test the chart using ScalarDB of the `master` branch (i.e., SNAPSHOT version).
So, I want to push the SNAPSHOT version container images and use them in the CI of the Scalar Helm Chart.
> Push SNAPSHOT version container images

- docs/getting-started-with-scalardb-on-cassandra.md
- docs/getting-started-with-scalardb-on-cosmosdb.md
- docs/getting-started-with-scalardb-on-dynamodb.md
- docs/getting-started-with-scalardb-on-jdbc.md
- docs/getting-started/gradle/wrapper/gradle-wrapper.properties
This PR updates the description of the supported Java version in the getting started guide.
In the previous getting started guide, we built ScalarDB itself in that steps. So, we must use Java 8 to build ScalarDB.
However, in the current getting started guide, we can use `Java 8 or higher` since it gets pre-compiled ScalarDB from the Maven repository.
And, I think there is a possibility that the current description may mislead users that `ScalarDB only supports Java 8`.
(Actually, I got a such question from a user.)
So, I think it is better to describe `Java 8 or higher` in the getting started guide.
Also, Gradle 7.1 doesn't support Java 17 or higher.
So, I updated the Gradle version of the getting started project to 7.6 (current latest version). …
> Update supported Java version in getting started

- core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionTableMetadata.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TransactionTableMetadataManagerTest.java
Currently, when we create a non-primary key column with a name that starts with `before_`, the column is not handled correctly. Specifically, the before column is not updated correctly in the prepare phase, as explained in the following comment:
https://github.com/scalar-labs/scalardb/pull/841#discussion_r1171065262
This PR fixes the issue. Please take a look!
> Allow to create `before_` prefixed columns in Consensus Commit

- docs/scalardb-server.md
- server/src/main/java/com/scalar/db/server/HealthService.java
- server/src/main/java/com/scalar/db/server/ScalarDbServer.java
- server/src/main/java/com/scalar/db/server/ServerConfig.java
- server/src/test/java/com/scalar/db/server/ServerConfigTest.java
This PR adds a decommissioning state to ScalarDB Server to achieve graceful shutdown. Please take a look!
> Add decommissioning state to ScalarDB Server

- .github/workflows/ci.yaml
**Issue** 
Dependabot is failing to parse the current CI file even though it is valid by Github actions standards.
**Fix**
This is a known issue (cf. https://github.com/dependabot/dependabot-core/issues/5453) for value starting with the semicolon `:` character that the Dependabot parser does not seem to recognize as a string. A workaround is to quote the problematic part to clear up the ambiguity.
> Apply workaround on CI for Dependabot

- .github/dependabot.yml
**Context** 
Since Aws sdk patch versions are released every few days, Dependabot will end up creating PR to update its version every week, which is not justified.
**Changes**
Dependabot won't update Aws sdk dependencies for patch versions anymore. Eventually, Aws sdk will only be updated when minor versions are released.
> [Dependabot] Ignore patch versions for Aws sdk

- docs/design.md
- docs/two-phase-commit-transactions.md
> **Note**
> 
Markdown syntax supports adding images, so I've updated the docs in the `master` branch to follow that standard.
> Change HTML syntax to Markdown for images (master)

- docs/design.md
- docs/two-phase-commit-transactions.md
> **Note**
> 
Markdown syntax supports adding images, so I've updated the docs for branch `3.9`, which is under support, to follow that standard.
> Change HTML syntax to Markdown for images (3.9)

- docs/design.md
- docs/two-phase-commit-transactions.md
> **Note**
> 
Markdown syntax supports adding images, so I've updated the docs for branch `3.8`, which is under support, to follow that standard.
> Change HTML syntax to Markdown for images (3.8)

- docs/design.md
- docs/two-phase-commit-transactions.md
> **Note**
> 
Markdown syntax supports adding images, so I've updated the docs for branch `3.7`, which is under support, to follow that standard.
> Change HTML syntax to Markdown for images (3.7)

- docs/design.md
> **Note**
> 
Markdown syntax supports adding images, so I've updated the docs for branch `3.6`, which is under support, to follow that standard.
> Change HTML syntax to Markdown for images (3.6)

- docs/design.md
> **Note**
> 
Markdown syntax supports adding images, so I've updated the docs for branch `3.5`, which is under support, to follow that standard.
> Change HTML syntax to Markdown for images (3.5)

- .github/workflows/auto-pr.yaml
- ci/auto-pr/conv_proj_version_to_branch
- ci/auto-pr/create_pull_requests
- ci/auto-pr/fetch_gh_proj_versions
- ci/auto-pr/fetch_gh_user_info
We manage the support branches (e.g. `3`) and the release branches (e.g. `3.7`), and manually back-port a merge PR change to them if needed. This kind of operation should be automated as much as possible.
This PR adds a GitHub Actions workflow that automatically does the following operations
- Check GitHub projects (e.g. `ScalarDB 3.7.1`, `ScalarDB 3.8.1`, `ScalarDB 4.0.0`) associated with the merged PR
- Extract full versions (e.g. `3.7.1`, `3.8.1`, `4.0.0`) from the project names
- Extract support versions (e.g. `3`, `4`) and release versions (e.g. `3.7`, `3.8`, `4.0`) from the full versions
- Checkout those Git branch and apply the merged PR change to them, and create a PR for each branch
Then, the author of the original PR merges the automatically created PR if it's good
I've tested a …
> Add GHA workflow to automatically create pull requests to apply a merged PR changes

- .github/workflows/auto-pr.yaml
This is a followup PR of https://github.com/scalar-labs/scalardb/pull/884. The previous PR used a wrong PAT that doesn't have proper permissions. This PR fixes the issue.
> Use a proper PAT in the GHA workflow for automated PR creation

- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitMutationOperationChecker.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitMutationOperationCheckerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
**Context**
There is no validation to ensure Put or Delete operations do not mutate consensus commit metadata columns. Since these columns are only for internal use, users should not be allowed to modify them.
**Changes**
A validation step is added to make sure Put or Delete operations do not mutate consensus commit metadata columns. Additionally, setting operation conditions (see https://github.com/scalar-labs/scalardb/pull/837 ) targeting consensus commit metadata columns are also forbidden.
> Add validation for consensus commit mutation operation

- .github/workflows/remove-untagged-images.yaml
This PR adds a new workflow that removes untagged container images in the GitHub Packages.
When we push a new SNAPSHOT image, the old SNAPSHOT image remains as an untagged image in GitHub Packages. We remove those untagged images by using this workflow.
I use the [camargo/delete-untagged-action](https://github.com/camargo/delete-untagged-action) since this is a simple action. It only removes untagged images. There are no other features.
For your reference, I tested this workflow in the following repository.
* [GitHub Packages (Container registry)](https://github.com/users/kota2and3kan/packages/container/package/untagged-image-test)
* [Workflow file](https://github.com/kota2and3kan/untagged-image-test/blob/main/.github/workflows/remove-untagged-image.yaml)
* [Result of …
> Remove untagged container images

- README.md
- docs/add-scalardb-to-your-build.md
- docs/getting-started/build.gradle
- docs/index.md
This PR changes the version of ScalarDB mentioned in the `docs/add-scalardb-to-your-build.md` doc (`3.8.0`) to match the version that is mentioned in the repository's `README.md` (`3.9.1-SNAPSHOT`).
I think we might need to update `docs/add-scalardb-to-your-build.md` and `README.md` in the `master` branch as well. If the changes in this PR look OK, I will submit a similar PR for the `master` branch.
> Change version in `add-scalardb-to-your-build.md` from `3.8.0` to `3.9.0`

- .github/workflows/auto-pr.yaml
- ci/auto-pr/create_pull_requests
- ci/auto-pr/fetch_gh_user_info
We've introduced https://github.com/scalar-labs/scalardb/pull/884 and related changes. But we ran into a failure https://github.com/scalar-labs/scalardb/actions/runs/5183834740/jobs/9342161161 that occurred as the original PR creator `dependabot` wasn't an actual GitHub user and the workflow failed to assign `dependabot` to the new PRs.
This PR updates the GHA workflow and related scripts to avoid assigning someone to new PRs and issues if it can't get GitHub user information based on the original PR creator name.
> Handle PRs created by dependabot in auto-pr GHA workflow

- core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java
- core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java
- docs/api-guide.md
- docs/two-phase-commit-transactions.md
> Improve documents for Handle Exceptions

- ci/auto-pr/create_pull_requests
- ci/auto-pr/fetch_gh_proj_versions
- ci/auto-pr/fetch_gh_user_info
https://github.com/scalar-labs/scalardb/actions/runs/5262633849/jobs/9512108324 failed due to the argument validation error of `create_pull_requests` script. But the number of parameters passed to the script was 10, which is enough for the validation. The cause was the script compares "10" and "5" as strings.
This PR revises the validation to treat the values as integers.
> Fix the wrong argument validations in Auto PR workflow

- core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseRelationalScanIntegrationTest.java
- core/src/main/java/com/scalar/db/api/Scan.java
- core/src/main/java/com/scalar/db/common/checker/OperationChecker.java
- core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
- core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
- core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
- core/src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java
- core/src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
- core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
- core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
- core/src/test/java/com/scalar/db/storage/cassandra/CassandraTest.java
- core/src/test/java/com/scalar/db/storage/cosmos/CosmosTest.java
- core/src/test/java/com/scalar/db/storage/dynamo/DynamoTest.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
- core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
- integration-test/src/main/java/com/scalar/db/api/DistributedStorageRelationalScanIntegrationTestBase.java
This PR adds the relational scan feature for JDBC storage. For transactions, it only supports the consensus-commit transaction. JDBC and gRPC transactions will be introduced by other PRs.
> Add relational scan for JDBC storage and consensus commit transaction

- .github/workflows/ci.yaml
This PR adds integration tests for MariaDB to the CI. Please take a look!
> Add integration tests for MariaDB to CI

- core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitRelationalScanIntegrationTestWithJdbcDatabase.java
- core/src/integration-test/java/com/scalar/db/storage/jdbc/TwoPhaseConsensusCommitRelationalScanIntegrationTestWithJdbcDatabase.java
- integration-test/src/main/java/com/scalar/db/api/DistributedTransactionRelationalScanIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionRelationalScanIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitRelationalScanIntegrationTestBase.java
- integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitRelationalScanIntegrationTestBase.java
This PR adds more integration tests for the relational scan, especially from the transaction perspective. DistributedTransactionXX and TwoPhaseCommitTransactionXX cover the basic tests with relational scan. ConsensusCommitTransactionXX and TwoPhaseConsensusCommitTransactionXX include the overlap check to prevent scan-after-writes.
> Add integration tests for transaction with relational scan

- core/src/main/java/com/scalar/db/common/AbstractDistributedTransactionManager.java
- core/src/main/java/com/scalar/db/common/AbstractTwoPhaseCommitTransactionManager.java
- core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java
- core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
- core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionOnBidirectionalStream.java
Currently, some transaction wrapper classes do not implement the `abort()` method. As a result, when a transaction is aborted, the `abort()` method of the wrapped transaction class is not called; instead, the `rollback()` method is called. To address this issue, this PR implements the `abort()` method in the transaction wrapper classes.
> Should call abort() when aborting transaction in transaction wrapper classes

- core/src/main/java/com/scalar/db/api/GetWithIndex.java
- core/src/main/java/com/scalar/db/api/Scan.java
- core/src/main/java/com/scalar/db/api/ScanAll.java
- core/src/main/java/com/scalar/db/api/ScanWithIndex.java
- core/src/main/java/com/scalar/db/api/Selection.java
We noticed `ScanAll.toString()` returns a bit weird string https://github.com/scalar-labs/scalardb-analytics-postgresql/pull/18/files#diff-cb027cc25fd71ee28416a31ef37f102db2146445322c88bee5be311a65c60a29R98.
```java
public static void main(String[] args){
System.out.println(new GetWithIndex(Key.of()));
System.out.println(new Scan(Key.of()));
System.out.println(new ScanWithIndex(Key.of()));
System.out.println(new ScanAll());
}
```
```
GetWithIndex{namespace=Optional.empty, table=Optional.empty, partitionKey=Key{}, clusteringKey=Optional.empty, projections=[], consistency=SEQUENTIAL}GetWithIndex{}
Scan{namespace=Optional.empty, table=Optional.empty, partitionKey=Key{}, clusteringKey=Optional.empty, projections=[], consistency=SEQUENTIAL}Scan{startClusteringKey=Optional.empty, …
```
> Improve some `toString` expressions of Selection Operators

- ci/auto-pr/create_pull_requests
The auto-PR backport GHA workflow [failed](https://github.com/scalar-labs/scalardb/actions/runs/5407948409/jobs/9826502966) generated the unexpected large diffs and conflicts (https://github.com/scalar-labs/scalardb/pull/922 and https://github.com/scalar-labs/scalardb/pull/923). But as for branch `3.9`, it succeeds on my local environment with the expected diff. I think the first cherry-pick on branch `3.7` generated dirty changes and the following cherry-picks unexpectedly used it.
This PR adds the following improvement to fix the problem.
- Execute `git cherry-pick --abort` when cherry-pick fails
- Cleanup the working dir just in case
> Run `git cherry-pick --abort` after it fails

- .github/workflows/scheduled-vuln-check.yaml
Since we have released the new patch versions `3.9.1`, `3.8.2`, `3.7.5`, and `3.6.6`, this PR updates the scheduled vulnerability check workflow. Please take a look!
> Update Scheduled Vulnerability Check workflow

- docs/api-guide.md
This PR revises the document for handling exceptions. Please take a look!
> Revise document for handling exceptions

- server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
Currently, there is a chance that the outgoing requests counter could be decremented twice when a transaction is being committed or rolled back, and an error occurs simultaneously. To prevent this, this PR introduces a safety measure to ensure the counter is only decremented once. Please take a look!
> Avoid decrementing outstanding requests counter duplicately

- build.gradle
- rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageAdminGrpc.java
- rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageGrpc.java
- rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionAdminGrpc.java
- rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionGrpc.java
- rpc/src/main/grpc/com/scalar/db/rpc/TwoPhaseCommitTransactionGrpc.java
This update fixes CVE-2023-1428 and CVE-2023-32731 by upgrading the gRPC library to version `1.53.0`. I've confirmed its backward compatibility. Please take a look!
> Fix CVE-2023-1428 and CVE-2023-32731

- build.gradle
This PR fixes CVE-2023-2976 by upgrading the Guava library to version `32.1.1-jre`. Please take a look!
> Fix CVE-2023-2976

- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtilsTest.java
**Context**
`ConsensusCommitUtils.isTransactionTableMetadata(metadata)` is a utility method that returns true if the given table metadata is transactional. 
**Changes**
This method is not working correctly when it verifies that the after column is present for a given before column. This PR fixes this wrong behavior.
> Fix utility method to check transactional table metadata

- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtilsTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/950
> Backport to branch(3) : Fix utility method to check transactional table metadata

- core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtilsTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/950
> Backport to branch(3.9) : Fix utility method to check transactional table metadata

- core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java
- core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
- core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
- core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionManagerTest.java
- docs/api-guide.md
This PR adds the `join()` method to `DistributedTransactionManager`. With this method, we can join an ongoing transaction managed by a transaction manager. In fact, this method works in the same way as the `resume()` method.
This method is particularly useful in a stateful application where a transaction spans across multiple client requests. In such a scenario, the application can start a transaction during the first client request. Then, in the subsequent client requests, it can join the ongoing transaction using the `join()` method.
`TwoPhaseCommitTransactionManager` already includes the `join()` method. Therefore, for the sake of consistency, I think we can also add it to `DistributedTransactionManager.`
> Add join() to DistributedTransactionManager

- README.md
- docs/add-scalardb-to-your-build.md
- docs/getting-started/build.gradle
- docs/index.md
Since we have released 3.10.0, this PR update the ScalarDB dependency version. Please take a look!
> Update the ScalarDB dependency version to 3.10.0

- docs/two-phase-commit-transactions.md
This PR revises the document for handling exceptions for Two-phase Commit Transactions. Please take a look!
> Revise document for handling exceptions for Two-phase Commit Transactions

- .github/workflows/auto-pr.yaml
An Auto-PR workflow job failed https://github.com/scalar-labs/scalardb/actions/runs/5606662051/jobs/10257033504 due to a failure of git-push for GHA workflow files.
```
To https://github.com/scalar-labs/scalardb
! [remote rejected]   3-pull-931 -> 3-pull-931 (refusing to allow a GitHub App to create or update workflow `.github/workflows/ci.yaml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/scalar-labs/scalardb'
```
It seems the git-push attempt doesn't use the PAT which has `workflows` permission.
This PR sets `token` parameter of `actions/checkout` to make subsequent git-push succeed.
```markdown
```
https://github.com/actions/checkout#usage
> Use PAT that has `workflows` permission in auto-pr

- docs/api-guide.md
- docs/two-phase-commit-transactions.md
This PR revises `Handle exceptions` sections in `Java API Guide` based on the changes in https://github.com/scalar-labs/scalardb/pull/934. Please take a look!
> Revise document for Handle exceptions

- README.md
- docs/add-scalardb-to-your-build.md
- docs/getting-started/build.gradle
- docs/index.md
Since we have released the new patch version `3.10.1`, this PR updates the ScalarDB dependency version. Please take a look!
> Update the ScalarDB dependency version to 3.10.1

- .github/workflows/auto-pr.yaml
The `auto-pr` workflow failed in https://github.com/scalar-labs/scalardb/actions/runs/5850991695. The cause was the PR title contained double quotes.
This PR escapes quotes in PR title using [a recommended way](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable).
> Escape PR title in `auto-pr` workflow

- README.md
- docs/api-guide.md
- docs/index.md
- docs/storage-abstraction.md
This PR fixes broken links that were not updated in the https://github.com/scalar-labs/scalardb/pull/990.
I've replaced the broken link with the link that points to [Getting Started with ScalarDB](https://github.com/scalar-labs/scalardb/blob/master/docs/getting-started-with-scalardb.md).
> Fix broken links to the "Getting Started" doc

- core/src/main/java/com/scalar/db/api/ScanBuilder.java
- core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1006
> Backport to branch(3.10) : Fix to ignore empty condition set when building Scan object

- core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminTestUtils.java
- core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
- core/src/main/java/com/scalar/db/storage/cosmos/CosmosMutation.java
- core/src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadata.java
- core/src/main/java/com/scalar/db/storage/cosmos/Record.java
- core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
- core/src/test/java/com/scalar/db/storage/cosmos/ResultInterpreterTest.java
**Changes**
This PR makes the `CosmosMetadata` and `Record` objects immutable. These DTO (Data Transfer Object) are used by the Cosmos SDK which uses Jackson.
**Note**
This PR originated thanks to this discussion https://github.com/scalar-labs/scalardb/pull/989#discussion_r1285761870
> Make Cosmos DTO objects immutable

- docs/backup-restore.md
- docs/getting-started-with-scalardb-on-cassandra.md
- docs/getting-started-with-scalardb-on-cosmosdb.md
- docs/getting-started-with-scalardb-on-dynamodb.md
- docs/getting-started-with-scalardb-on-jdbc.md
- docs/getting-started-with-scalardb.md
- docs/getting-started.md
- docs/index.md
- docs/requirements.md
- docs/scalardb-server.md
- docs/schema.md
- docs/two-phase-commit-transactions.md
This PR adds an "include" that contains a banner to the top of ScalarDB 3.4 docs. The banner states version 3.4 is no longer supported. 
> **Note**
> 
> The banner is displayed on ScalarDB 3.4 pages on only our docs site. Visitors to the Markdown files in this repository will only see `{% include end-of-support.html %}` at the top of the document. That line will then be displayed as expected when the docs are rendered in Jekyll, the static site generator for our docs site.
> 
> **Reference:** The include file on the docs site: [`end-of-support.html`](https://github.com/scalar-labs/docs-scalardb/blob/main/_includes/end-of-support.html).
> Add out-of-support banner to docs to show that ScalarDB 3.4 is no longer supported on the docs site

- schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/740
> Backport to branch(3.7) : Should drop namespace only when no tables are in the namespace in Schema Loader

- schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/740
> Backport to branch(3.6) : Should drop namespace only when no tables are in the namespace in Schema Loader

- docs/add-scalardb-to-your-build.md
This PR revises the document that shows users how to add ScalarDB to their application build by using Gradle or Maven. By putting the build tools in content tabs, users can select their preferred build tool to see instructions for how to add ScalarDB to their application.
N/A
- Added content tabs for Gradle and Maven contents.
- Revised the contents, adding headings and providing additional context to the instructions.
- `master`
- `3.10`
- `3.9`
- `3.8`
- `3.7`
- `3.6`
- `3.5`
I ran our docs site locally and confirmed that the content tabs for Gradle and Maven in this doc appear and work as expected. The following screenshot shows how the tabs look.
Please see my comment in the doc.
> Revise the "Add ScalarDB to Your Build" doc

- core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTestUtils.java
- core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
- core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
- core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
This PR fixes handling supported data types correctly. Without this fix, users can accidentally import some minor unsupported data types like "geometry" as the blob type in ScalarDB.
> Fix to handle supported data types properly when importing tables in MySQL and SQL Server

- README.md
We've [updated](https://github.com/scalar-labs/scalardb/pull/985) all the exception and log messages in this project to apply the consistent message style. But no rule or guideline on it is written down yet.
This PR adds "Exception and log message guideline" section to README so that contributors to this project know the message style.
> Add "Exception and log message guideline" section to README

- docs/getting-started-with-scalardb-by-using-kotlin.md
- docs/getting-started-with-scalardb.md
> Backport to branch(3.5) : Clarify the supported Oracle JDK and OpenJDK versions; add a note about other JDKs and versions

- docs/getting-started-with-scalardb-by-using-kotlin.md
- docs/getting-started-with-scalardb.md
> Backport to branch(3.6) : Clarify the supported Oracle JDK and OpenJDK versions; add a note about other JDKs and versions

- docs/getting-started-with-scalardb-by-using-kotlin.md
- docs/getting-started-with-scalardb.md
> Backport to branch(3.7) : Clarify the supported Oracle JDK and OpenJDK versions; add a note about other JDKs and versions

- docs/getting-started-with-scalardb-by-using-kotlin.md
- docs/getting-started-with-scalardb.md
> Backport to branch(3.8) : Clarify the supported Oracle JDK and OpenJDK versions; add a note about other JDKs and versions

- docs/getting-started-with-scalardb-by-using-kotlin.md
- docs/getting-started-with-scalardb.md
> Backport to branch(3.9) : Clarify the supported Oracle JDK and OpenJDK versions; add a note about other JDKs and versions

- docs/getting-started-with-scalardb-by-using-kotlin.md
- docs/getting-started-with-scalardb.md
> Backport to branch(3.10) : Clarify the supported Oracle JDK and OpenJDK versions; add a note about other JDKs and versions

- core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
- core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
- core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
- core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
**Context** 
Storage Admin implementations (CassandraAdmin, CosmosAdmin...) are wrapped by the [CheckedDistributedStorageAdmin](https://github.com/scalar-labs/scalardb/blob/b858fe12ec9d6d496cf4825662c0d9426d2e675b/core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java#L23-L34). 
The Storage Admin implementations use storage-specific synonyms instead of `namespace` and `table` : 
* the `CassandraAdmin` uses `keyspace` and `table`
* the `DynamoAdmin` uses `namespace` and `table`
* the `CosmosAdmin` uses `database` and `container`
* the `JdbcAdmin` uses `schema` and `table` 
This wording is also used in exception messages. Though, all exceptions thrown by the Storage Admin implementations will be ultimately caught and rethrown by the `CheckedDistributedStorageAdmin` …
> Unify styles of the exception messages of Storage Admin implementations

- docs/scalardb-supported-databases.md
**Context**
We completed verifying the support for new database versions in https://github.com/scalar-labs/scalardb/pull/1005
**Changes**
This updates the supported databases document by 
* Adding support for:
* Aurora PostgreSQL 15
* MySQL 8.1
* Oracle 23.2.0-free
* PostgreSQL 15
* Removing support for Cassandra 2.2 since this version has reached end-of-life
> Revise supported databases

- tla+/consensus-commit/CC.tla
- tla+/consensus-commit/CCSpec.tla
- tla+/consensus-commit/README.md
I ran into some errors when I tried to run `tla+/consensus-commit` on TLA+ Toolbox v1.8.0. This PR fixed the following issues:
1. `CC.tla` and `CCSpec.tla` don't have module-end line (`======`) which is required in the specification. See `2.2 The TLA+ Module` in https://lamport.azurewebsites.net/tla/p-manual.pdf for details
2. The README says `Consistent` invariant can be used with `Spec`. But it doesn't work
---
BTW, the following error still happens. I'll look into it later when I have a time
```
The subscript of the next-state relation specified by the specification
does not seem to contain the state variable msgs
The subscript of the next-state relation specified by the specification
does not seem to contain the state variable rPrepared
current state is not a legal state
While working …
```
> Fix tla+/consensus-commit

- .github/workflows/auto-pr.yaml
We've already installed `auto-pr.yaml` which automatically creates PRs based on specified Projects. But it only supports the default branches (`main`/`master`.) We'll need to manage the backports from branch `3` to branch `3.x` after releasing version 4. `auto-pr` needs to support the release/support branches not only the default branches.
N/A
Add regex pattern for the release/support branches to `pull_request.branches` in `auto-pr.yaml`
- This change isn't tested, but it doesn't affect current operations.
- I'll backport this change to other ScalarDB projects once confirming it works.
N/A
> Support release/support branches in auto-pr

- core/src/main/java/com/scalar/db/api/Admin.java
- docs/api-guide.md
This PR revises the contents of the ScalarDB Java API Guide, mostly from an editorial perspective.
Related to #1082 (some similarities in content)
- Revised content.
- Added notice blocks for noteworthy content.
- Added content tabs for databases.
- `master`
> **Note**
> 
> After this PR is approved and merged, I will create another PR for branches `3.10`, `3.9`, `3.8`, `3.7`, and `3.6` that removes the **Get existing namespaces** section, which doesn't apply to those branches.
I ran our docs site locally with these changes and confirmed that these revised docs, including content tabs, notice blocks, and formatting, appeared as expected. Attached is a screenshot of the `api-guide.md` doc as it appears on the docs site.
The following screenshot shows `api-guide.md`:
Please see my comments …
> Revise the contents of the Java API guide

- server/Dockerfile
In the following PR, we found an issue about busybox. This issue prevents the building container images. So, I fix it in this PR.
https://github.com/scalar-labs/scalardb-cluster/pull/178#discussion_r1346053889
https://github.com/scalar-labs/scalardb-cluster/pull/178#discussion_r1346053889
* Update the busybox version.
I reproduced the issue with `1.32` and confirmed that we can resolve this issue by using `1.36` as follows.
```console
$ docker run -it --rm busybox:1.32
/ #
/ # wget -q -O grpc_health_probe "https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.17/grpc_health_probe-linux-amd64"
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
/ #
```
```console
$ …
```
> Update busybox version in dockerfile

- .github/workflows/ci.yaml
The CI job running the integration test on Oracle 23 has been failing consistently for a few days. The reason is a lack of storage space.
The Github runner only [guarantees 14GB of available disk space](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), but practically, about 16 GB is allocated. This leaves enough room to start the Oracle container, which requires 15GB, but not enough to run the integration test, which requires about 1GB.
To free up storage, we can delete unused tooling provided in the runner, such as .NET libraries weighting about 2GB.
To fix the issues, I considered two options:
1. Free up storage after the Oracle container is started and before the integration …
> Free up storage space in CI for Oracle 23 job

- .github/workflows/ci.yaml
> Backport to branch(3.10) : Free up storage space in CI for Oracle 23 job

- .github/workflows/ci.yaml
> Backport to branch(3.8) : Free up storage space in CI for Oracle 23 job

- .github/workflows/ci.yaml
> Backport to branch(3.7) : Free up storage space in CI for Oracle 23 job

- .github/workflows/ci.yaml
> Backport to branch(3.6) : Free up storage space in CI for Oracle 23 job

- .github/workflows/ci.yaml
> Backport to branch(3.9) : Free up storage space in CI for Oracle 23 job

- .github/workflows/ci.yaml
Yesterday's fix made in https://github.com/scalar-labs/scalardb/pull/1126 was eventually too optimistic and we need to implement the option 2 I mentioned in the PR description.
Oracle 23 CI is failing because of a lack of storage space to run the job. 14GB of storage is at least provided, while the job requires about 16 GB. 
The solution is to free up storage space by removing unused tooling in the runner machine before the Oracle container is started.
https://github.com/scalar-labs/scalardb/pull/1126
Rewrite the Oracle 23 job to free up storage space (~14GB) before starting the Oracle 23 container.
> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes after you …
> Fix Oracle 23 CI

- core/src/main/java/com/scalar/db/api/Admin.java
- docs/api-guide.md
> **Note**
> 
> Reviewed and modified the contents of this doc for the `3.10` branch to check alignment with the changes we made on the `master` branch in #1084.
> 
> Backport to branch(3.10) : Revise the contents of the Java API guide

- core/src/main/java/com/scalar/db/api/Admin.java
- docs/api-guide.md
> **Note**
> 
> Reviewed and modified the contents of this doc for the `3.8` branch to check alignment with the changes we made on the `master` branch in #1084.
> 
> Backport to branch(3.8) : Revise the contents of the Java API guide

- core/src/main/java/com/scalar/db/api/Admin.java
- docs/api-guide.md
> **Note**
> 
> Reviewed and modified the contents of this doc for the `3.9` branch to check alignment with the changes we made on the `master` branch in #1084.
> 
> Backport to branch(3.9) : Revise the contents of the Java API guide

- core/src/main/java/com/scalar/db/api/Admin.java
- docs/api-guide.md
> **Note**
> 
> Reviewed and modified the contents of this doc for the `3.7` branch to check alignment with the changes we made on the `master` branch in #1084.
> 
> Backport to branch(3.7) : Revise the contents of the Java API guide

- docs/api-guide.md
> **Note**
> 
> Reviewed and modified the contents of this doc for the `3.6` branch to check alignment with the changes we made on the `master` branch in #1084.
>
> Backport to branch(3.6) : Revise the contents of the Java API guide

- schema-loader/Dockerfile
> Backport to branch(3.10) : Bump scalar-labs/jre8 from 1.1.14 to 1.1.15 in /schema-loader

- schema-loader/Dockerfile
> Backport to branch(3.9) : Bump scalar-labs/jre8 from 1.1.14 to 1.1.15 in /schema-loader

- schema-loader/Dockerfile
> Backport to branch(3.8) : Bump scalar-labs/jre8 from 1.1.14 to 1.1.15 in /schema-loader

- schema-loader/Dockerfile
> Backport to branch(3.7) : Bump scalar-labs/jre8 from 1.1.14 to 1.1.15 in /schema-loader

- schema-loader/Dockerfile
> Backport to branch(3.6) : Bump scalar-labs/jre8 from 1.1.14 to 1.1.15 in /schema-loader

- server/Dockerfile
Backport of https://github.com/scalar-labs/scalardb/pull/1144
> Backport to branch(3.7) : Bump scalar-labs/jre8 from 1.1.14 to 1.1.15 in /server

- server/Dockerfile
Backport of https://github.com/scalar-labs/scalardb/pull/1144
> Backport to branch(3.8) : Bump scalar-labs/jre8 from 1.1.14 to 1.1.15 in /server

- server/Dockerfile
Backport of https://github.com/scalar-labs/scalardb/pull/1144
> Backport to branch(3.9) : Bump scalar-labs/jre8 from 1.1.14 to 1.1.15 in /server

- server/Dockerfile
Backport of https://github.com/scalar-labs/scalardb/pull/1144
> Backport to branch(3.10) : Bump scalar-labs/jre8 from 1.1.14 to 1.1.15 in /server

- build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1142
> Bump org.eclipse.jetty:jetty-servlet from 9.4.51.v20230217 to 9.4.53.v20231009

- build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1142
> Bump org.eclipse.jetty:jetty-servlet from 9.4.43.v20210629 to 9.4.53.v20231009

- .github/workflows/release-snapshot.yaml
Since we don't use snapshot versions of non-master/main branches, we decided not create and upload packages and containers.
N/A
Update the trigger of the GitHub Action to work only on master branch push.
N/A
N/A
> Update the trigger of the GitHub Action to work only on master branch push

- docs/storage-abstraction.md
Backport of #1119
> **Note**
>
> This removes a section (mistakenly introduced in #1015) that shouldn't be in this version of the doc.
> Backport to branch(3.6) : Revise the contents of the storage abstraction doc (additional fix)

- .github/workflows/auto-pr.yaml
We allowed Auto PR workflow to work with release/support branches. But it didn't work since the destination branches don't have the workflow.
- https://github.com/scalar-labs/scalardb/pull/1118
This PR copies the latest Auto PR workflow file to the release/support branch.
This change is to update the existing old workflow. The diff is same as the diff between `3.10` and `master`. As for other release/support branches that don't have the workflow file, I'll create another PR to create it.
N/A
> Port auto-pr workflow to branch `3`

- .github/workflows/auto-pr.yaml
We allowed Auto PR workflow to work with release/support branches. But it didn't work since the destination branches don't have the workflow.
- https://github.com/scalar-labs/scalardb/pull/1118
- https://github.com/scalar-labs/scalardb/pull/1209
This PR copies the latest Auto PR workflow file to the old release branches (<= 3.9).
N/A
N/A
> Port (Add) the auto-pr workflow to old release branches

- .github/workflows/auto-pr.yaml
We tried to port `auto-pr.yaml` to the old branches `3.9` or older in https://github.com/scalar-labs/scalardb/pull/1210. But the PR didn't contain related scripts. The change was applied only to `3.9` because Auto-PR didn't work due to the missing scripts.
We also ported the missing related scripts to the old branches `3.9` or older in https://github.com/scalar-labs/scalardb/pull/1212. They were ported to `3.9` or older branches as expected. But the first change for `auto-pr.yaml` isn't ported to `3.8` or older ones since the second PR created only the related scripts.
So we need to port `auto-pr.yaml` to `3.8` or older branches... Sorry for trying and errors PRs.
Fixes https://github.com/scalar-labs/scalardb/pull/1210 and https://github.com/scalar-labs/scalardb/pull/1212
Port …
> Add missing Auto-PR workflow file

- .github/workflows/auto-pr.yaml
(See https://github.com/scalar-labs/scalardb/pull/1217 for details) The Auto PR workflow file is still missing. We need to add it to `3.6`.
Fixes https://github.com/scalar-labs/scalardb/pull/1217
Add `ci/auto-pr.yaml`
N/A
N/A
> Add auto-pr.yaml for 3.6

- .github/workflows/auto-pr.yaml
(See https://github.com/scalar-labs/scalardb/pull/1217 for details) The Auto PR workflow file is still missing. We need to add it to `3.7`.
Fixes https://github.com/scalar-labs/scalardb/pull/1217
Add `ci/auto-pr.yaml`
N/A
N/A
> Add auto-pr.yaml for 3.7

- core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSchemaLoaderIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderIntegrationTest.java
- core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTestUtils.java
- core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageSchemaLoaderIntegrationTest.java
- core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
- core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java
- integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
- schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
- schema-loader/src/test/java/com/scalar/db/schemaloader/command/SchemaLoaderCommandTest.java
- server/src/integration-test/java/com/scalar/db/server/SchemaLoaderIntegrationTestWithServer.java
So far, the Schema Loader command `--repair-all` would only to repair the tables in the schema. For now on, this command will additionally repair the namespaces. 
- Related to https://github.com/scalar-labs/scalardb/pull/1107
- Related to https://github.com/scalar-labs/scalardb/pull/989
Update the Schema Loader `--repair-all` command to additionally repair namespaces, besides repairing the tables of the schema.
I will update the documentation in another PR.
Updated the Schema Loader `--repair-all` command to additionally repair namespaces besides repairing the tables …
> Schema Loader `--repair-all` command will also repair namespaces
