scalar-labs/scalardb

archive.gradle, build.gradle, gradle.properties, src/main/resources/META-INF/COPYING, src/main/resources/META-INF/NOTICE
Scalar DB is now able to be uploaded to maven central repo with `gradle uploadArchives`.
=> make it updatable to maven central with `gradle uploadArchives`

jepsen/scalardb/src/scalardb/runner.clj, jepsen/scalardb/test/scalardb/scalardb_test.clj
Add Jepsen clock-drift tests for Scalar DB
=> add clock-drift tests

tools/schema/loader.go
I think add new line is better when failed.
=> add new line when schema generation and loading failed

script/setup/README.md, script/setup/config_cassandra_for_dlt.sh, script/setup/default/cassandra.yaml, script/setup/node_params
=> modify the setup script

scripts/sample_schema/tx_transfer.cql
To replace the values of the replication factor by the benchmarking script.
=> fix replication_factor

src/integration-test/java/com/scalar/database/storage/cassandra/CassandraIntegrationTest.java, src/main/java/com/scalar/database/io/Key.java, src/main/java/com/scalar/database/storage/cassandra/Cassandra.java, src/main/java/com/scalar/database/storage/cassandra/ClusterManager.java, src/main/java/com/scalar/database/storage/cassandra/ResultImpl.java, src/main/java/com/scalar/database/storage/cassandra/ScannerImpl.java, src/main/java/com/scalar/database/storage/cassandra/ScannerIterator.java, src/main/java/com/scalar/database/storage/cassandra/TableMetadata.java, src/test/java/com/scalar/database/storage/cassandra/ResultImplTest.java
https://github.com/scalar-labs/scalardb/issues/25
This is caused by unchecked primary key in put in storage, so this PR fixes that to fix the above issue.
=> fix the reported bug and add some unit tests

src/test/java/com/scalar/database/verification/GetTotal.java
Want to return an error code so the calling script knows when to stop.
=> If readRecordsWithRetry fails exit properly

jepsen/scalardb/project.clj, jepsen/scalardb/src/scalardb/transfer.clj
Sorry, these files were updated in the directory where they were being run, but I seemed to have not updated them when copying to this repository.
In any case, I think this fixes the problem.
=> Update to the latest version of Jepsen

jepsen/scalardb/README.md, jepsen/scalardb/project.clj, jepsen/scalardb/src/scalardb/core.clj, jepsen/scalardb/src/scalardb/runner.clj, jepsen/scalardb/src/scalardb/transfer.clj, jepsen/scalardb/src/scalardb/transfer_append.clj
https://scalar-labs.atlassian.net/browse/DLT-2310
Seems like there is quite a few formatting changes too that Cursive did. Mostly lining up the values of maps.
=> Rewrite Jepsen tests using the Alia Cassandra driver

tools/schema/generator.go, tools/schema/internal/parser/parser.go, tools/schema/loader.go
https://scalar-labs.atlassian.net/browse/DLT-2105
Resolves Issue #39
It seems that once the parser matches "CREATE" it will only match the first line, so pull it out and move it to the Schema struct. This will let Declaration match any of the options.
=> Pull out "CREATE" from the Declaration struct

src/main/java/com/scalar/database/api/Scanner.java, src/main/java/com/scalar/database/storage/cassandra/ScannerImpl.java
- Make Scanner implement Closeable interface
- Make the methods of Scanner throw ExecutionException
=> Some changes for Scanner interface

src/main/java/com/scalar/database/storage/cassandra4driver/ClusterManager.java, src/test/java/com/scalar/database/storage/cassandra4driver/ClusterManagerTest.java
For supporting Cassandra Java 4.x
- `Cluster` does not exist anymore
- Make `CqlSessionBuilder`, then build `CqlSession`
=> [Driver4] Add ClusterManager

src/main/java/com/scalar/database/storage/cassandra4driver/ResultImpl.java, src/main/java/com/scalar/database/storage/cassandra4driver/TableMetadata.java, src/main/java/com/scalar/database/storage/cassandra4driver/ValueBinder.java, src/test/java/com/scalar/database/storage/cassandra4driver/ResultImplTest.java, src/test/java/com/scalar/database/storage/cassandra4driver/ValueBinderTest.java
For supporting Cassandra Java driver 4.x
- Replace import paths
- Modify `DataType` comparison
- Replace `BoundStatement` with `BoundStatementBuilder` in `ValueBinder`
=> [Driver4] Add modules

src/main/java/com/scalar/database/storage/cassandra4driver/ScannerImpl.java, src/main/java/com/scalar/database/storage/cassandra4driver/ScannerIterator.java, src/main/java/com/scalar/database/storage/cassandra4driver/SelectStatementHandler.java, src/test/java/com/scalar/database/storage/cassandra4driver/SelectStatementHandlerTest.java
- Change the import paths
- Use [`Relation`](https://docs.datastax.com/en/drivers/java/4.3/com/datastax/oss/driver/api/querybuilder/relation/Relation.html) for where clause
- Replace `Ordering` with [`ClusteringOrder`](https://docs.datastax.com/en/drivers/java/4.3/com/datastax/oss/driver/api/core/metadata/schema/ClusteringOrder.html)
=> [Driver4] Add a statement handler for selection

src/main/java/com/scalar/database/storage/cassandra4driver/BatchComposer.java, src/main/java/com/scalar/database/storage/cassandra4driver/BatchHandler.java, src/main/java/com/scalar/database/storage/cassandra4driver/StatementHandlerManager.java, src/test/java/com/scalar/database/storage/cassandra4driver/BatchComposerTest.java, src/test/java/com/scalar/database/storage/cassandra4driver/BatchHandlerTest.java, src/test/java/com/scalar/database/storage/cassandra4driver/StatementHandlerManagerTest.java
- Change the import paths
- Use [`BatchStatementBuilder`](https://docs.datastax.com/en/drivers/java/4.3/com/datastax/oss/driver/api/core/cql/BatchStatementBuilder.html)
=> [Driver4] Add batch handler and handler manager

src/main/java/com/scalar/database/storage/cassandra4driver/Cassandra.java
- Replace `Session` with `CqlSession`
=> [Driver4] Add cassandra

src/main/java/com/scalar/database/api/DistributedTransactionManager.java, src/main/java/com/scalar/database/api/TransactionState.java, src/main/java/com/scalar/database/service/TransactionService.java, src/main/java/com/scalar/database/transaction/consensuscommit/ConsensusCommitManager.java, src/test/java/com/scalar/database/transaction/consensuscommit/ConsensusCommitManagerTest.java
https://scalar-labs.atlassian.net/browse/DLT-4243
=> Implement check for returning transaction state

src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTest.java, src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java, src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
https://scalar-labs.atlassian.net/browse/DLT-5833
=> Repeatable scan

docs/design.md, src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTest.java, src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java, src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java, src/test/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposerTest.java
=> fix #66 (lost update issue)

src/main/java/com/scalar/db/storage/cosmos/CosmosMutation.java, src/main/java/com/scalar/db/storage/cosmos/CosmosOperation.java, src/main/java/com/scalar/db/storage/cosmos/DeleteStatementHandler.java, src/test/java/com/scalar/db/storage/cosmos/CosmosMutationTest.java, src/test/java/com/scalar/db/storage/cosmos/CosmosOperationTest.java, src/test/java/com/scalar/db/storage/cosmos/DeleteStatementHandlerTest.java
https://scalar-labs.atlassian.net/browse/DLT-6574
- Delete operation
```java
Key partitionKey = new Key(new IntValue("c1", 0));
Key clusteringKey = new Key(new IntValue("c2", 1));
Delete delete = new Delete(partitionKey);
storage.delete(delete);
```
- Before
|"c1" (PartitionKey)|"c2" (ClusteringKey)|"c3" (ClusteringKey)|"c4"|
--|--|--|--
|0|0|0|100|
|0|1|0|100|
|0|1|1|100|
|0|1|2|100|
|0|2|0|100|
|0|2|1|100|
|0|2|2|100|
- After
|"c1" (PartitionKey)|"c2" (ClusteringKey)|"c3" (ClusteringKey)|"c4"|
--|--|--|--
|0|0|0|100|
|0|2|0|100|
|0|2|1|100|
|0|2|2|100|
=> Delete multiple records from Cosmos DB

src/main/java/com/scalar/db/storage/cosmos/MapVisitor.java, src/main/java/com/scalar/db/storage/cosmos/ResultImpl.java, src/test/java/com/scalar/db/storage/cosmos/MapVisitorTest.java, src/test/java/com/scalar/db/storage/cosmos/ResultImplTest.java
https://scalar-labs.atlassian.net/browse/DLT-6876
=> fix request for blob data

tools/scalar-schema/README.md, tools/scalar-schema/java/src/TableMetadata.java, tools/scalar-schema/project.clj, tools/scalar-schema/resources/log4j.properties, tools/scalar-schema/sample_schema/sample_schema.json, tools/scalar-schema/src/scalar_schema/cassandra_schema.clj, tools/scalar-schema/src/scalar_schema/common.clj, tools/scalar-schema/src/scalar_schema/core.clj, tools/scalar-schema/src/scalar_schema/cosmos_schema.clj, tools/scalar-schema/stored_procedure/mutate.js
https://scalar-labs.atlassian.net/browse/DLT-7167
I'd like to move my schema tool for Scalar DB to this repository from [my repository](https://github.com/yito88/cosmos-scalar-schema).
I added table creation options for Cassandra.
=> Add scalar-schema tool

src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java, src/test/java/com/scalar/db/storage/dynamo/BatchHandlerTest.java, src/test/java/com/scalar/db/storage/dynamo/ConditionExpressionBuilderTest.java, src/test/java/com/scalar/db/storage/dynamo/DeleteStatementHandlerTest.java, src/test/java/com/scalar/db/storage/dynamo/DynamoMutationTest.java, src/test/java/com/scalar/db/storage/dynamo/DynamoOperationTest.java, src/test/java/com/scalar/db/storage/dynamo/MapVisitorTest.java, src/test/java/com/scalar/db/storage/dynamo/PutStatementHandlerTest.java, src/test/java/com/scalar/db/storage/dynamo/ResultImplTest.java, src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java, src/test/java/com/scalar/db/storage/dynamo/TableMetadataManagerTest.java
https://scalar-labs.atlassian.net/browse/DLT-7304
To merge this branch into `integrate_dynamodb` (not master)
For the scan operation, we need to support multiple clustering keys, but I have not started it yet.
So, the current unit tests are temporary for the current implementation.
=> Add unit tests for DynamoDB integration

src/main/java/com/scalar/db/api/DistributedStorage.java, src/main/java/com/scalar/db/api/DistributedTransaction.java, src/main/java/com/scalar/db/api/DistributedTransactionManager.java, src/main/java/com/scalar/db/service/StorageService.java, src/main/java/com/scalar/db/service/TransactionService.java, src/main/java/com/scalar/db/storage/cassandra/Cassandra.java, src/main/java/com/scalar/db/storage/cosmos/Cosmos.java, src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java, src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
Part of https://scalar-labs.atlassian.net/browse/DLT-7234.
To make Auditor uses another namespace, only the ledger namespace needs to be configured.
=> add setters and getters for namespace and table name

tools/scalar-schema/README.md, tools/scalar-schema/project.clj, tools/scalar-schema/src/scalar_schema/core.clj, tools/scalar-schema/src/scalar_schema/dynamo_schema.clj
https://scalar-labs.atlassian.net/browse/DLT-7397
- Create the metadata table `scalardb.metadata`
- Insert tables' metadata
- Create index tables for clustering keys
- Create user tables
=> Support DynamoDB in the schema tool

conf/database.properties, src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java, src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
To specify the AWS credentials from the config file.
=> Specify AWS credentials

src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java, src/main/java/com/scalar/db/storage/dynamo/DynamoOperation.java, src/main/java/com/scalar/db/storage/dynamo/ItemSorter.java, src/main/java/com/scalar/db/storage/dynamo/ScannerImpl.java, src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java, src/main/java/com/scalar/db/storage/dynamo/TableMetadata.java, src/test/java/com/scalar/db/storage/dynamo/DynamoOperationTest.java, src/test/java/com/scalar/db/storage/dynamo/ItemSorterTest.java, src/test/java/com/scalar/db/storage/dynamo/ResultImplTest.java, src/test/java/com/scalar/db/storage/dynamo/ScannerImplTest.java, src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
To support multiple clustering keys with secondary indexes
=> Support multiple clustering keys

src/main/java/com/scalar/db/storage/dynamo/DynamoMutation.java, src/main/java/com/scalar/db/storage/dynamo/PutStatementHandler.java, src/test/java/com/scalar/db/storage/dynamo/PutStatementHandlerTest.java
To upsert items
According to this [disscussion](https://github.com/scalar-labs/scalardb/pull/84#discussion_r498612446), we should be able to overwrite the existing item like C*.
Dynamo DB client's `putItem()` cannot overwrite it.
So, I replaced it with `updateItem()`.
=> Replace putItem with updateItem for upsert

src/main/java/com/scalar/db/service/TransactionModule.java
To support transactions on DynamoDB
=> add a provider for Dynamo

src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java, src/test/java/com/scalar/db/storage/dynamo/BatchHandlerTest.java
This PR is almost the same as #97 to replace put request with update request.
=> Replace a put request for batch

tools/scalar-schema/README.md, tools/scalar-schema/project.clj
Also updated the name of uberjar to `*-standalone-<version>.jar`.
=> Update version of scalar-schema tool

tools/scalar-schema/src/scalar_schema/dynamo_schema.clj
Minor spelling correction in data type
Issue: https://scalar-labs.atlassian.net/browse/DLT-7507
=> Minor spelling correction in schema tool

tools/scalar-schema/project.clj, tools/scalar-schema/src/scalar_schema/cassandra.clj, tools/scalar-schema/src/scalar_schema/common.clj, tools/scalar-schema/src/scalar_schema/core.clj, tools/scalar-schema/src/scalar_schema/cosmos.clj, tools/scalar-schema/src/scalar_schema/dynamo.clj, tools/scalar-schema/src/scalar_schema/operations.clj, tools/scalar-schema/src/scalar_schema/protocols.clj
https://scalar-labs.atlassian.net/browse/DLT-7617
Added a protocol (like an interface) to reduce redundant processes
=> Refactor the schema tool

tools/scalar-schema/sample_schema/sample_schema.json, tools/scalar-schema/src/scalar_schema/common.clj, tools/scalar-schema/test/scalar_schema/common_test.clj
Added unit tests
A test helped me find a bug.
It made unneeded columns by #115. Not critical.
=> Add tests and fix bugs about unneeded columns

docs/README.md, docs/getting-started-with-dynamodb.md, docs/getting-started-with-scalardb.md
Getting started document for scalar db on dynamo db
Task: https://scalar-labs.atlassian.net/browse/DLT-7541
Note:- The current master branch does not support Dynamo DB.
=> Getting started document for scalar db on dynamo db

tools/scalar-schema/README.md
Schema tool document modified with the standalone build details for DynamoDB
=> Schema tool doc modified with standalone build for DynamoDB

tools/scalar-schema/src/scalar_schema/common.clj, tools/scalar-schema/src/scalar_schema/core.clj, tools/scalar-schema/src/scalar_schema/cosmos.clj, tools/scalar-schema/src/scalar_schema/dynamo.clj, tools/scalar-schema/src/scalar_schema/operations.clj, tools/scalar-schema/test/scalar_schema/common_test.clj
https://scalar-labs.atlassian.net/browse/DLT-7606
Modify the schema tool to add the specified prefix to each namespace with `--prefix` option
=> Modify the schema tool to add prefix

build.gradle, tools/scalar-schema/project.clj
https://scalar-labs.atlassian.net/browse/DLT-6929
It seems the release rush gets settled.
Transfer test works well.
=> Update Cosmos DB SDK

docs/getting-started-with-scalardb.md
Fix error typo on the file  docs/getting-started-with-scalardb.md.
=> Fix english typo

conf/database.properties, src/main/java/com/scalar/db/api/DistributedTransactionManager.java, src/main/java/com/scalar/db/config/DatabaseConfig.java, src/main/java/com/scalar/db/service/TransactionModule.java, src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java, src/test/java/com/scalar/db/config/DatabaseConfigTest.java, src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
https://scalar-labs.atlassian.net/browse/DLT-7818
=> make isolation level and serilizable strategy configrable with properties

src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
It requires https://github.com/scalar-labs/scalardb/pull/130 to be merged first.
=> Fix the broken tests

src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTest.java, src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java, src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
Thank you, Yuji! 🙏 
https://scalar-labs.atlassian.net/browse/DLT-7969
=> Fix inconsistent read bug

src/main/java/com/scalar/db/storage/TableMetadata.java, src/main/java/com/scalar/db/storage/cassandra/CassandraTableMetadata.java, src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadata.java, src/main/java/com/scalar/db/storage/dynamo/DynamoTableMetadata.java
Modify TableMetadata for columns for secondary indexes
=> Modify TableMetadata for secondary indexes

tools/scalar-schema/sample_schema/sample_schema.json, tools/scalar-schema/src/scalar_schema/cassandra.clj, tools/scalar-schema/src/scalar_schema/common.clj
https://scalar-labs.atlassian.net/browse/DLT-8021
This PR is for Cassandra
For Cosmos DB: #141 
For DynamoDB: #142
=> [Scalar-Schema] Set Cassandra secondary index

src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTest.java, src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java, src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
https://github.com/scalar-labs/scalardb/issues/150
=> Fix snapshot scan bug

docs/getting-started-with-scalardb-on-cassandra.md, docs/getting-started-with-scalardb-on-cosmosdb.md, docs/getting-started-with-scalardb-on-dynamodb.md, docs/getting-started-with-scalardb-on-jdbc.md, docs/getting-started-with-scalardb.md, docs/getting-started.md, docs/getting-started/scalardb.properties, docs/getting-started/src/main/java/sample/ElectronicMoney.java, docs/getting-started/src/main/java/sample/ElectronicMoneyWithTransaction.java
https://scalar-labs.atlassian.net/browse/DLT-8024
=> Add documentation for the JDBC adapter

docs/backup-restore.md
https://scalar-labs.atlassian.net/browse/DLT-8025
=> Add the backup documentation for JDBC databases

docs/getting-started-with-scalardb-on-cosmosdb.md, docs/getting-started-with-scalardb.md, tools/scalar-schema/README.md
Minor label correction for Cosmos DB credentials for better understanding
Ref:- https://scalar-labs.atlassian.net/browse/DLT-8371
=>  Label correction for Cosmos DB credential

docs/getting-started-with-scalardb-on-cassandra.md, docs/getting-started-with-scalardb.md
Schema deletion commands modified in getting started doc.
Ref:- https://scalar-labs.atlassian.net/browse/DLT-8372
=> Schema deletion commands modified in getting started doc

docs/getting-started-with-scalardb-on-cassandra.md
Minor word correction in getting started with Cassandra doc
=> Minor word correction in getting started with cassandra doc

docs/backup-restore.md, src/main/java/com/scalar/db/api/DistributedStorage.java, src/main/java/com/scalar/db/api/DistributedTransaction.java, src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java, src/main/java/com/scalar/db/transaction/consensuscommit/SerializableStrategy.java
https://scalar-labs.atlassian.net/browse/DLT-7909
=> Add more documentation including limitations in the Scalar DB docs

.circleci/config.yml
This PR updates the pip URL since it seems changed.
https://app.circleci.com/pipelines/github/scalar-labs/scalardb/788/workflows/2ab57e05-b0dc-416f-b5ae-45de7b297cd6/jobs/947
=> Update pip URL

conf/database.properties, docs/getting-started-with-scalardb-on-jdbc.md, docs/getting-started-with-scalardb.md, src/main/java/com/scalar/db/config/DatabaseConfig.java, src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseConfig.java
https://scalar-labs.atlassian.net/browse/DLT-8753
=> Refactor some configuration names

docs/schema.md, tools/scalar-schema/README.md
Ref: https://scalar-labs.atlassian.net/browse/DLT-8777
This PR also fixes typo in scalar-schema [Readme](https://github.com/scalar-labs/scalardb/tree/master/tools/scalar-schema#create-tables)
=> Update data type mapping 

tools/scalar-schema/src/scalar_schema/cassandra.clj, tools/scalar-schema/src/scalar_schema/jdbc.clj
- Format cassandra.clj
- Rename `get-text-type` to `get-text-type-fn`
=> Refactor Scalar Schema tool for more consistency

src/main/java/com/scalar/db/api/Put.java, src/main/java/com/scalar/db/io/BigIntValue.java, src/main/java/com/scalar/db/io/BlobValue.java, src/main/java/com/scalar/db/io/BooleanValue.java, src/main/java/com/scalar/db/io/DoubleValue.java, src/main/java/com/scalar/db/io/FloatValue.java, src/main/java/com/scalar/db/io/IntValue.java, src/main/java/com/scalar/db/io/Key.java, src/main/java/com/scalar/db/io/TextValue.java, src/main/java/com/scalar/db/io/Value.java, src/test/java/com/scalar/db/api/PutTest.java, src/test/java/com/scalar/db/io/BigIntValueTest.java, src/test/java/com/scalar/db/io/BlobValueTest.java, src/test/java/com/scalar/db/io/BooleanValueTest.java, src/test/java/com/scalar/db/io/DoubleValueTest.java, src/test/java/com/scalar/db/io/FloatValueTest.java, src/test/java/com/scalar/db/io/IntValueTest.java, src/test/java/com/scalar/db/io/KeyTest.java, src/test/java/com/scalar/db/io/TextValueTest.java
I added utility methods for Value/Put and a builder class for Key, which I believe will make Scalar DB easy to use.
=> Add utility methods for Value/Put and a builder class for Key

src/main/java/com/scalar/db/exception/transaction/CrudConflictException.java, src/main/java/com/scalar/db/exception/transaction/UncommittedRecordException.java, src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java, src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java, src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
https://scalar-labs.atlassian.net/browse/DLT-9026
=> Refactor exceptions in Scalar DB for easier retry handling

src/main/java/com/scalar/db/io/Key.java, src/test/java/com/scalar/db/api/PutTest.java, src/test/java/com/scalar/db/io/KeyTest.java
I added two methods (add() and addAll()) to the `Key.Builder` class. Please take a look!
=> Add some more useful methods to Key.Builder

src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java, src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java, src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithDynamoIntegrationTest.java, src/main/java/com/scalar/db/service/StorageModule.java, src/main/java/com/scalar/db/service/TransactionModule.java, src/main/java/com/scalar/db/storage/dynamo/Dynamo.java, src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java, src/main/java/com/scalar/db/storage/dynamo/DynamoDatabaseConfig.java, src/test/java/com/scalar/db/storage/dynamo/DynamoDatabaseConfigTest.java
Supporting the endpoint override feature for Dynamo is useful for tests.
=> Support the endpoint override feature for Dynamo

.circleci/config.yml, core/build.gradle
I did some refactoring for the CI config. Note that I removed the short verification here because we conduct the periodic verification everyday.
=> Reorganize the CI config

core/src/main/java/com/scalar/db/storage/dynamo/DynamoDatabaseConfig.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseConfig.java, server/Dockerfile, server/README.md, server/build.gradle, server/conf/log4j.properties
=> Add Docker support for Scalar DB Server

docs/getting-started/build.gradle
It seems like the getting started project doesn't work after converting this project to multi-project. I realized that while reviewing #229. This PR will fix this issue. Please take a look!
=> Fix the getting started project

server/src/main/java/com/scalar/db/server/config/ServerConfig.java, server/src/test/java/com/scalar/db/server/config/ServerConfigTest.java
I realized that I forgot to add unit tests for `ServerConfig`. This PR adds them. BTW, when adding the tests, I found that `ServerConfig` had a bug 😞  Please take a look!
=> Add unit tests for ServerConfig

core/src/integration-test/java/com/scalar/db/storage/AdminIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java, core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java, core/src/main/java/com/scalar/db/service/AdminService.java, core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java, core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java, core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java, core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java, core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdminTest.java, core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTest.java, core/src/test/java/com/scalar/db/storage/rpc/GrpcAdminTest.java, server/src/test/java/com/scalar/db/server/DistributedStorageAdminServiceTest.java
I think DistributedStorageAdmin should throw some kind of Exception. This PR makes DistributedStorageAdmin throw ExecutionException.
=> Make DistributedStorageAdmin throw ExecutionException

README.md
This PR mainly revises README.md to replace `compile` configuration with `implementation`. It also removes some trailing spaces.
=> Revise README.md of root folder

core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java, core/src/main/java/com/scalar/db/storage/rpc/GrpcScanOnBidirectionalStream.java, core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java, core/src/main/java/com/scalar/db/storage/rpc/GrpcTableMetadataManager.java, core/src/main/java/com/scalar/db/storage/rpc/ScannerImpl.java, core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java, core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java, core/src/main/java/com/scalar/db/util/retry/Retry.java, core/src/main/java/com/scalar/db/util/retry/ServiceTemporaryUnavailableException.java, server/build.gradle, server/src/main/java/com/scalar/db/server/AdminService.java, server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java, server/src/main/java/com/scalar/db/server/DistributedStorageService.java, server/src/main/java/com/scalar/db/server/DistributedTransactionService.java, server/src/main/java/com/scalar/db/server/Pauser.java, server/src/main/java/com/scalar/db/server/ScalarDbServer.java, server/src/main/java/com/scalar/db/server/service/ServerModule.java, server/src/test/java/com/scalar/db/server/DistributedStorageServiceTest.java, server/src/test/java/com/scalar/db/server/DistributedTransactionServiceTest.java
I implemented the admin interface that pauses/unpauses a Scalar DB server and get some statistics in this PR.
=> Add the admin interface to Scalar DB server

core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java, core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java, core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithDynamoIntegrationTest.java, core/src/main/java/com/scalar/db/storage/rpc/GrpcScanOnBidirectionalStream.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java, core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java, core/src/main/java/com/scalar/db/util/retry/Retry.java, server/src/main/java/com/scalar/db/server/Pauser.java
=> Use Uninterruptibles in Guava

core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java, core/src/main/java/com/scalar/db/storage/cassandra/CassandraTableMetadataManager.java, core/src/main/java/com/scalar/db/storage/cassandra/ClusterManager.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java, core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java, core/src/test/java/com/scalar/db/storage/cassandra/ClusterManagerTest.java
=> Some refactoring for the implementations of DistributedStorageAdmin

core/src/main/java/com/scalar/db/storage/rpc/GrpcScanOnBidirectionalStream.java, core/src/main/java/com/scalar/db/storage/rpc/ScannerImpl.java, core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java, server/src/main/java/com/scalar/db/server/DistributedStorageService.java
This is a refactoring thing for the code around onCompleted() in bidirectional streaming of gRPC.
=> Revisit the code around onCompleted() in bidirectional streaming of gRPC

server/src/main/java/com/scalar/db/server/ScalarDbServer.java
I tested this in my env and it looks like it worked properly.
=> Support graceful shutdown

server/Dockerfile
=> Expose the Prometheus HTTP endpoint port in the Scalar DB server Docker image

docs/getting-started-with-scalardb.md, docs/scalardb-server.md, server/README.md
I added very simple documentation of the Scalar DB Server. We need to extend it in the future.
=> Add documentation of Scalar DB Server

docs/getting-started-with-scalardb.md, docs/multi-storage.md
=> Add multi-storage documentation

build.gradle, core/build.gradle, rpc/build.gradle, server/build.gradle
=> Refactor build.gradle

server/src/integration-test/java/com/scalar/db/server/ConsensusCommitWithDistributedStorageServiceIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithJdbcTransactionIntegrationTest.java, server/src/main/java/com/scalar/db/server/service/ServerModule.java
=> Disable Prometheus HTTP endpoint when the port is specified to zero in Scalar DB server

core/src/main/java/com/scalar/db/api/TableMetadata.java, core/src/main/java/com/scalar/db/storage/cassandra/CassandraTableMetadataManager.java, core/src/main/java/com/scalar/db/storage/common/TableMetadataManager.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadataManager.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoTableMetadataManager.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcTableMetadataManager.java, core/src/main/java/com/scalar/db/storage/rpc/GrpcTableMetadataManager.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcTableMetadataManagerTest.java
This implements the methods to add and delete table metadata of the JdbcMetadataManager
=> Implement addition and deletion of metadata table for jdbc metadata manager

core/src/main/java/com/scalar/db/api/Put.java, core/src/main/java/com/scalar/db/io/BlobValue.java, core/src/main/java/com/scalar/db/io/Key.java, core/src/main/java/com/scalar/db/io/TextValue.java, core/src/main/java/com/scalar/db/io/Value.java, core/src/test/java/com/scalar/db/io/KeyTest.java
I think adding constructors to Key with a single value is useful for some use cases.
=> Add useful constructors to Key with a single value

tools/scalar-schema/Dockerfile
I added this to be able to do the following
https://docs.google.com/document/d/1FepHOSeKz7PxkHGo5xSI6Pa4FJT61ua4_0KnzsFvUAo/edit#heading=h.5yqkuawp7xby
=> add scalar-schema dockerfile

core/build.gradle, rpc/build.gradle, server/build.gradle
=> Add publishToMavenLocal for archiving and uploading to maven central

core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java, server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
=> Add tests for getState() and abort() in DistributedTransactionManager to the ConsensusCommit integration test

core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java, core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java, core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTest.java
This updates the `MultiStorageAdmin` with the changes of the `DistributedStorageAdmin` interface.
=> Update MultiStorageAdmin with new interface

server/Dockerfile
This PR fixes CVE-2021-3711. Please take a look!
=> Fix CVE-2021-3711

docs/scalardb-server.md
This should be merged after [This PR](https://github.com/scalar-labs/scalardb-samples/pull/4) is merged. Please take a look!
=> Update Scalar DB Server Sample URL

core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
This is a very minor thing. This PR just removes unchecked warnings. Please take a look!
=> Remove unchecked warnings

build.gradle, core/build.gradle, rpc/build.gradle, server/build.gradle
What I did in this PR is:
- Change the Javadoc titles
- Remove the `notimestamp` option
=> Fix Javadoc related things

build.gradle
This PR upgrades the Error Prone plugin. Actually, It is a trivial thing but my intelliJ shows warning for it. Please take a look!
=> Upgrade the Error Prone plugin

server/src/main/java/com/scalar/db/server/TwoPhaseCommitTransactionService.java
=> Change service name of TwoPhaseCommitTransactionService

core/src/main/java/com/scalar/db/api/TableMetadata.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
This PR adds `ConsensusCommitAdmin` that creates transactional tables and a coordinator table. Please take a look!
=> Add ConsensusCommitAdmin that manages transactional tables and coordinator table

core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoWithReservedKeywordIntegrationTest.java, core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithDynamoIntegrationTest.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoTableMetadataManager.java
This PR does refactoring the integration tests for the DynamoDB adapter and adds checking empty metadata before being put. Please take a look. Thank you!
=> Refactoring dynamo integration tests

core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
I forgot to create Coordinator namespace in `ConsensusCommitAdmin` in the previous PR. This PR fixes this. Please take a look!
=> Create Coordinator namespace in ConsensusCommitAdmin

.circleci/config.yml
This PR is for the `3.1` branch and fixes the `cqlsh` install failure.
=> Fix cqlsh install failure

docs/multi-storage-transactions.md
=> Improve Multi-storage documentation

schema-loader/README.md
=> Improve Schema loader document

core/src/main/java/com/scalar/db/config/ConfigUtils.java, core/src/main/java/com/scalar/db/config/DatabaseConfig.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java, core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java, core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java, core/src/main/java/com/scalar/db/util/Utility.java, core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java, core/src/test/java/com/scalar/db/storage/rpc/GrpcConfigTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java, server/src/main/java/com/scalar/db/server/config/ServerConfig.java, server/src/test/java/com/scalar/db/server/config/ServerConfigTest.java
This PRs adds `ConfigUtils` that has some utility methods for configuration and refactors `XXXConfig` classes. Please take a look!
=> Refactor XXXConfig classes

core/src/main/java/com/scalar/db/storage/common/checker/ColumnChecker.java, core/src/main/java/com/scalar/db/storage/common/checker/ConditionChecker.java, core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java, core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
Since we don't accept null or empty partition key/clustering key, this PR adds null or empty check for partition key and clustering key. Please take a look!
=> Add null or empty check for partition key and clustering key

core/src/test/java/com/scalar/db/storage/dynamo/bytes/KeyBytesEncoderTest.java
This PR adds min and max values to the target list to improve the test coverage of `KeyBytesEncoderTest`. Please take a look!
=> Improve KeyBytesEncoderTest

core/src/integration-test/java/com/scalar/db/storage/StorageMultipleClusteringKeysIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeysIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoMultipleClusteringKeysIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcMultipleClusteringKeysIntegrationTest.java, core/src/main/java/com/scalar/db/io/BlobValue.java, core/src/main/java/com/scalar/db/storage/jdbc/ResultInterpreter.java, core/src/test/java/com/scalar/db/storage/jdbc/ResultInterpreterTest.java
This PR adds some more tests to the multiple clustering key integration test. Also, it refactors the the multiple clustering key integration test as well. Please take a look!
=> Add more tests to the multiple clustering key integration test

core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeysIntegrationTest.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
This is a very minor thing. Please take a look when you have time!
=> Refactor CosmosAdmin

core/src/integration-test/java/com/scalar/db/storage/StorageColumnValueIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraColumnValueIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosColumnValueIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoColumnValueIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcColumnValueIntegrationTest.java, core/src/main/java/com/scalar/db/storage/cosmos/ResultInterpreter.java
This PR adds column value related integration tests. The integration tests check if all data types of columns are handled correctly. Please take a look!
=> Add column value integration test

.circleci/config.yml, core/src/integration-test/java/com/scalar/db/storage/StorageMultiplePartitionKeyIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageSinglePartitionKeyIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraMultiplePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSinglePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSinglePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoMultiplePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSinglePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcMultiplePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSinglePartitionKeyIntegrationTest.java, core/src/main/java/com/scalar/db/storage/cosmos/ConcatenationVisitor.java, core/src/test/java/com/scalar/db/storage/cosmos/ConcatenationVisitorTest.java
This PR adds partition key related integration tests. The integration tests check if all data types for partition keys are handled correctly. Please take a look!
=> Add partition key integration tests

README.md
This is a vary minor thing. Please take a look when you have time!
=> Add syntax highlighting for the dependency in README.md

.circleci/config.yml, core/build.gradle, core/src/integration-test/java/com/scalar/db/storage/AdminIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageColumnValueIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageMultipleClusteringKeyScanIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageMultiplePartitionKeyIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageSecondaryIndexIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageSingleClusteringKeyScanIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageSinglePartitionKeyIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/TestUtils.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoWithReservedKeywordIntegrationTest.java, core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java
This PR makes the integration tests run concurrently to speed them up. Please take a look!
=> Run integration tests concurrently

build.gradle, server/build.gradle, server/src/main/java/com/scalar/db/server/Metrics.java
This PR introduces prometheus `simpleclient_hotspot` to expose the Hotspot JVM metrics. Please take a look!
=> Introduce prometheus simpleclient_hotspot

server/Dockerfile
- I modified the container to run as non-root user for security improvement measures.
=> Modify Dockerfile to run as non-root

core/src/integration-test/java/com/scalar/db/storage/AdminIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
=> Add some more admin integration tests

build.gradle, core/src/test/java/com/scalar/db/storage/cosmos/ConcatenationVisitorTest.java
This PR does the following things to reduce the Intellij warnings:
- Upgrade the error-prone version
- Remove an unnecessary semi colon
=> Reduce Intellij warnings

README.md, docs/index.md
=> Update the Scalar DB version in README

core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java, core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
This is very trivial refactoring. Please take a look!
=> Refactor DistributedStorageAdmin

README.md, docs/index.md, schema-loader/build.gradle, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java, schema-loader/src/main/java/com/scalar/db/schemaloader/core/SchemaOperatorFactory.java
This PR fix warnings in javadoc of schema-loader. PTAL! Thank you!
=> Update schema-loader javadoc to fix warning

core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposer.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
=> Revisit logging in Consensus Commit

.circleci/config.yml
Please take a look! Thank you!
=> Upgrade supported storage database version in the CI

core/src/main/java/com/scalar/db/storage/common/checker/ColumnChecker.java, core/src/main/java/com/scalar/db/storage/common/checker/ConditionChecker.java, core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
This PR refactors `OperationChecker` a little bit. Please take a look when you have time!
=> Refactor OperationChecker

README.md, docs/index.md
=> Update the Scalar DB version of the dependency in README

docs/getting-started-with-scalardb-on-cassandra.md, docs/getting-started-with-scalardb-on-cosmosdb.md, docs/getting-started-with-scalardb-on-dynamodb.md
This PR is for minor document modifications. Please take a look!
=> Improve Getting Started with Scalar DB on X

build.gradle
=> Upgrade log4j to 2.17.0

schema-loader/src/main/java/com/scalar/db/schemaloader/command/CosmosCommand.java
Please take a look! Thank you!
=> Add -u option for Cosmos DB in schema loader for backward compatibility 

core/src/integration-test/java/com/scalar/db/storage/AdminIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageColumnValueIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageMultipleClusteringKeyScanIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageMultiplePartitionKeyIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageSecondaryIndexIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageSingleClusteringKeyScanIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageSinglePartitionKeyIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosColumnValueIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSecondaryIndexIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSingleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSinglePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageIntegrationTest.java, core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCosmosIntegrationTest.java, core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithMultiStorageIntegrationTest.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java, schema-loader/src/main/java/com/scalar/db/schemaloader/command/CosmosCommand.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/ServerEnv.java, server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitWithExtraReadIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitWithExtraWriteIntegrationTest.java
=> Refactor integration tests

graphql/build.gradle, graphql/src/test/java/com/scalar/db/graphql/datafetcher/DataFetcherHelperTest.java, graphql/src/test/java/com/scalar/db/graphql/datafetcher/MutationPutDataFetcherTest.java, graphql/src/test/java/com/scalar/db/graphql/datafetcher/QueryGetDataFetcherTest.java
This PR adds SpotBugs and Error Prone plugins to the graphql subproject.
=> Add SpotBugs and Error Prone plugins to graphql subproject

docs/getting-started-with-scalardb.md, docs/getting-started/src/main/java/sample/ElectronicMoneyWithTransaction.java
=> Update the Getting Started doc and code

core/src/main/java/com/scalar/db/config/DatabaseConfig.java, core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java, server/src/main/java/com/scalar/db/server/config/ServerConfig.java
I found we forgot to close FileInputStream in `XXXConfig`. This PR fixes it. Please take a look!
=> Should close FileInputStream in XXXConfig

core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java, core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
I found we don't rollback a transaction when expiring it in Two-phase commit transactions. This PR fixes it. Please take a look!
=> Should rollback a transaction when expiring it in Two-phase commit transactions

schema-loader/src/integration-test/java/com/scalar/db/schemaloader/server/SchemaLoaderWithScalarDbServer.java, server/src/integration-test/java/com/scalar/db/server/ConsensusCommitWithDistributedStorageServiceIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithJdbcTransactionIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/ServerEnv.java, server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitWithExtraReadIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitWithExtraWriteIntegrationTest.java, server/src/main/java/com/scalar/db/server/Metrics.java, server/src/main/java/com/scalar/db/server/ScalarDbServer.java, server/src/main/java/com/scalar/db/server/ServerConfig.java, server/src/main/java/com/scalar/db/server/ServerModule.java, server/src/test/java/com/scalar/db/server/ServerConfigTest.java
This is very trivial things. Please take a look!
=> Refactor Scalar DB Server code

core/src/main/java/com/scalar/db/service/AdminService.java, core/src/main/java/com/scalar/db/service/StorageFactory.java, core/src/main/java/com/scalar/db/service/StorageService.java, core/src/main/java/com/scalar/db/service/TransactionFactory.java, core/src/main/java/com/scalar/db/service/TransactionService.java, core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java
Since I think we no longer need the `XXXService` classes, this PR deprecates them. Please take a look!
=> Deprecate XXXService classes

core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcUtilsTest.java, docs/getting-started-with-scalardb-on-jdbc.md
This PR adds connection pool configurations for `JdbcAdmin`. Please take a look!
=> Add connection pool configurations for JdbcAdmin

core/src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java, core/src/main/java/com/scalar/db/storage/dynamo/ConditionExpressionBuilder.java, core/src/main/java/com/scalar/db/storage/dynamo/DeleteStatementHandler.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoMutation.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoOperation.java, core/src/main/java/com/scalar/db/storage/dynamo/PutStatementHandler.java, core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java, core/src/test/java/com/scalar/db/storage/dynamo/ConditionExpressionBuilderTest.java, core/src/test/java/com/scalar/db/storage/dynamo/DynamoMutationTest.java, core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
This PR refactors the PR #462. Please take a look and check if this refactoring is correct!
=> Refactor #462

core/src/integration-test/java/com/scalar/db/storage/StorageWithReservedKeywordIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoWithReservedKeywordIntegrationTest.java, core/src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java, core/src/main/java/com/scalar/db/storage/dynamo/ConditionExpressionBuilder.java, core/src/main/java/com/scalar/db/storage/dynamo/DeleteStatementHandler.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoMutation.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoOperation.java, core/src/main/java/com/scalar/db/storage/dynamo/PutStatementHandler.java, core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java, core/src/test/java/com/scalar/db/storage/dynamo/ConditionExpressionBuilderTest.java, core/src/test/java/com/scalar/db/storage/dynamo/DynamoMutationTest.java, core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
Please take a look! Thank you!
=> Handling namespaces/tables/columns with reserved keywords in DynamoDB adapter

core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseColumnValueIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultiplePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSecondaryIndexIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSingleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSinglePartitionKeyIntegrationTest.java
This PR renames JDBC integration tests for consistency. Please take a look!
=> Rename JDBC integration tests

docs/backup-restore.md
Update Scalar DB backup and restoration guide
=> Update Scalar DB backup and restoration guide

build.gradle
Update PostgreSQL driver version for vulnerability fix
```
Total: 1 (HIGH: 1, CRITICAL: 0)
+---------------------------+------------------+----------+-------------------+-----------------+---------------------------------------+
|          LIBRARY          | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION  |                 TITLE                 |
+---------------------------+------------------+----------+-------------------+-----------------+---------------------------------------+
| org.postgresql:postgresql | CVE-2022-21724   | HIGH     | 42.2.18           | 42.3.2, 42.2.25 | Remote code execution vulnerability   |
|                           |                  |          |                   |                 | using plugin features                 |
| …
```
=> Update PostgreSQL driver version for vulnerability fix

core/src/main/java/com/scalar/db/api/ConditionalExpression.java
=> Add constructors to ConditionalExpression

core/src/integration-test/java/com/scalar/db/storage/TestUtils.java, core/src/main/java/com/scalar/db/api/ConditionalExpression.java, core/src/main/java/com/scalar/db/api/Put.java, core/src/main/java/com/scalar/db/io/BlobValue.java, core/src/main/java/com/scalar/db/io/Key.java, core/src/main/java/com/scalar/db/io/TextValue.java, core/src/main/java/com/scalar/db/storage/cassandra/ResultInterpreter.java, core/src/main/java/com/scalar/db/util/ProtoUtils.java, core/src/test/java/com/scalar/db/api/PutTest.java, core/src/test/java/com/scalar/db/io/BlobValueTest.java, core/src/test/java/com/scalar/db/io/KeyTest.java, core/src/test/java/com/scalar/db/storage/cassandra/ValueBinderTest.java
This PR adds ByteBuffer support for Blob type. Please take a look!
=> Add ByteBuffer support for Blob type

docs/getting-started-with-scalardb-on-jdbc.md
This is a PR for documentation. Please take a look!
=> Support SQL Server and Amazon Aurora officially

core/src/main/java/com/scalar/db/api/Isolation.java, core/src/main/java/com/scalar/db/api/SerializableStrategy.java, core/src/main/java/com/scalar/db/io/TextValue.java, core/src/main/java/com/scalar/db/service/AdminService.java, core/src/main/java/com/scalar/db/service/StorageService.java, core/src/main/java/com/scalar/db/service/TransactionService.java, core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
=> Classes/Methods deprecated in 3.x should be removed in 5.0.0

core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java, core/src/main/java/com/scalar/db/storage/cassandra/StatementHandler.java, core/src/main/java/com/scalar/db/storage/cassandra/ValueBinder.java, core/src/main/java/com/scalar/db/storage/cosmos/BatchHandler.java, core/src/main/java/com/scalar/db/storage/cosmos/StatementHandler.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java, core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java, core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java, schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java, schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommand.java, server/src/main/java/com/scalar/db/server/ScalarDbServer.java
This is a PR for refactoring. This PR basically removes unnecessary logging and make the logging use placeholders. Please take a look!
=> Revisit logging

graphql/src/main/java/com/scalar/db/graphql/instrumentation/TransactionInstrumentation.java, graphql/src/test/java/com/scalar/db/graphql/instrumentation/TransactionInstrumentationTest.java
Previously, GraphQL queries containing variables in the `@transaction` directive, such as the following, were not supported even though they were syntactically correct. This PR addresses this issue.
```graphql
query balances($tx_id: String, $commit: Boolean) @transaction(txId: $tx_id, commit: $commit) {
tx_transfer_get(get: { ... }) { ... }
}
```
This is important for clients to be able to reuse the "`query`" part of the request document (JSON) without any string formatting.
=> GraphQL: Handling variable references in @transaction directive

core/src/test/java/com/scalar/db/storage/cassandra/BatchHandlerTest.java, core/src/test/java/com/scalar/db/storage/cassandra/DeleteStatementHandlerTest.java, core/src/test/java/com/scalar/db/storage/cassandra/InsertStatementHandlerTest.java, core/src/test/java/com/scalar/db/storage/cassandra/SelectStatementHandlerTest.java, core/src/test/java/com/scalar/db/storage/cassandra/UpdateStatementHandlerTest.java, core/src/test/java/com/scalar/db/storage/cosmos/BatchHandlerTest.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosMutationTest.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosOperationTest.java, core/src/test/java/com/scalar/db/storage/cosmos/DeleteStatementHandlerTest.java, core/src/test/java/com/scalar/db/storage/cosmos/PutStatementHandlerTest.java, core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java, core/src/test/java/com/scalar/db/storage/dynamo/BatchHandlerTest.java, core/src/test/java/com/scalar/db/storage/dynamo/DeleteStatementHandlerTest.java, core/src/test/java/com/scalar/db/storage/dynamo/DynamoMutationTest.java, core/src/test/java/com/scalar/db/storage/dynamo/DynamoOperationTest.java, core/src/test/java/com/scalar/db/storage/dynamo/PutStatementHandlerTest.java, core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/PartitionedMutationsKeyTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/PartitionedMutationsTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotKeyTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
This is a PR for refactoring. Please take a look!
=> Rename `keyspace` to `namespace` in unit tests

core/src/main/java/com/scalar/db/io/BlobValue.java, core/src/main/java/com/scalar/db/io/TextValue.java, core/src/main/java/com/scalar/db/io/Value.java, core/src/test/java/com/scalar/db/io/BigIntValueTest.java, core/src/test/java/com/scalar/db/io/BlobValueTest.java, core/src/test/java/com/scalar/db/io/BooleanValueTest.java, core/src/test/java/com/scalar/db/io/DoubleValueTest.java, core/src/test/java/com/scalar/db/io/FloatValueTest.java, core/src/test/java/com/scalar/db/io/IntValueTest.java, core/src/test/java/com/scalar/db/io/TextValueTest.java
In addition to #497, this PR adds `ByteBuffer` support to `Value`. Please take a look!
=> Add ByteBuffer support to Value

core/src/main/java/com/scalar/db/api/DistributedStorage.java, core/src/main/java/com/scalar/db/api/DistributedTransaction.java, core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java, core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransaction.java, core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/service/StorageService.java, core/src/main/java/com/scalar/db/service/TransactionService.java, core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java, core/src/main/java/com/scalar/db/storage/common/AbstractDistributedStorage.java, core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransaction.java, core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransactionManager.java, core/src/main/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransaction.java, core/src/main/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransactionManager.java
=> Deprecate the methods for default namespace and table

core/src/integration-test/java/com/scalar/db/storage/StorageConditionalMutationIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraConditionalMutationIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosConditionalMutationIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoConditionalMutationIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseConditionalMutationIntegrationTest.java
This PR adds a conditional mutation integration test. Please take a look!
=> Add conditional mutation integration test

core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposerTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitIntegrationTest.java
This PR allows deleting non-existing records in Consensus Commit. Please take a look!
=> Allow deleting non existing records in Consensus Commit

core/src/integration-test/java/com/scalar/db/storage/StorageConditionalMutationIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageMultipleClusteringKeyScanIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/StorageMultiplePartitionKeyIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosConditionalMutationIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseConditionalMutationIntegrationTest.java
I added the conditional mutation integration tests in #522, but they are taking a long time and making the CI time longer. This PR makes the conditional mutation integration tests run parallel to speed them up. Please take a look!
=> Execute conditional mutation integration tests in parallel

core/src/main/java/com/scalar/db/sql/builder/CreateCoordinatorTableStatementBuilder.java, core/src/main/java/com/scalar/db/sql/builder/CreateIndexStatementBuilder.java, core/src/main/java/com/scalar/db/sql/builder/CreateNamespaceStatementBuilder.java, core/src/main/java/com/scalar/db/sql/builder/CreateTableStatementBuilder.java, core/src/main/java/com/scalar/db/sql/builder/DropCoordinatorTableStatementBuilder.java, core/src/main/java/com/scalar/db/sql/builder/DropIndexStatementBuilder.java, core/src/main/java/com/scalar/db/sql/builder/DropNamespaceStatementBuilder.java, core/src/main/java/com/scalar/db/sql/builder/DropTableStatementBuilder.java, core/src/test/java/com/scalar/db/sql/builder/StatementBuilderTest.java
This PR adds several utility methods to the SQL builders. Please take a look!
=> Add more methods to SQL builders

core/src/main/java/com/scalar/db/sql/ResultRecord.java, core/src/main/java/com/scalar/db/sql/metadata/TableMetadata.java
This PR is a small refactoring thing. Please take a look!
=> Use collectors in Guava

docs/index.md
=> Update CI status badge in index.md

.github/workflows/release-snapshot.yaml, .github/workflows/release.yaml
This PR adds a GitHub actions workflow to release SNAPSHOT versions. Please take a look!
=> Release SNAPSHOT versions

build.gradle, core/build.gradle, core/src/integration-test/java/com/scalar/db/api/DistributedStorageWithReservedKeywordIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/sql/SqlStatementWithTransactionSessionIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/sql/SqlStatementWithTwoPhaseCommitTransactionSessionIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/SqlStatementWithTransactionSessionIntegrationTestWithCassandra.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/SqlStatementWithTwoPhaseCommitTransactionSessionIntegrationTestWithCassandra.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/SqlStatementWithTransactionSessionIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/SqlStatementWithTwoPhaseCommitTransactionSessionIntegrationTestCosmos.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/SqlStatementWithTransactionSessionIntegrationTestWithDynamo.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/SqlStatementWithTwoPhaseCommitTransactionSessionIntegrationTestDynamo.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/SqlStatementWithTransactionSessionIntegrationTestWithJdbcDatabase.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/SqlStatementWithTwoPhaseCommitTransactionSessionIntegrationTestWithJdbcDatabase.java, core/src/main/java/com/scalar/db/sql/ResultRecord.java, core/src/main/java/com/scalar/db/sql/SqlStatementSessionFactory.java, core/src/main/java/com/scalar/db/sql/builder/SelectStatementBuilder.java, core/src/main/java/com/scalar/db/sql/builder/StatementBuilder.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java, core/src/test/java/com/scalar/db/sql/builder/StatementBuilderTest.java
This PR adds integration tests for SQL API. It also includes some bug fixes found by the integration tests. Please take a look!
=> Add integration tests for SQL API

.github/workflows/ci.yaml, ci/scripts/dockerfile_lint.sh, schema-loader/Dockerfile, schema-loader/build.gradle, server/build.gradle
This PR adds a docker check job to the CI workflow. Please take a look!
=> Add docker check to CI

core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java, core/src/test/java/com/scalar/db/storage/rpc/GrpcAdminTest.java, rpc/src/main/java/com/scalar/db/rpc/CreateIndexRequest.java, rpc/src/main/java/com/scalar/db/rpc/CreateIndexRequestOrBuilder.java, rpc/src/main/java/com/scalar/db/rpc/DropIndexRequest.java, rpc/src/main/java/com/scalar/db/rpc/DropIndexRequestOrBuilder.java, rpc/src/main/java/com/scalar/db/rpc/DropNamespaceRequest.java, rpc/src/main/java/com/scalar/db/rpc/DropNamespaceRequestOrBuilder.java, rpc/src/main/java/com/scalar/db/rpc/DropTableRequest.java, rpc/src/main/java/com/scalar/db/rpc/DropTableRequestOrBuilder.java, rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java, rpc/src/main/proto/scalardb.proto, server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java, server/src/test/java/com/scalar/db/server/DistributedStorageAdminServiceTest.java
I realized that I forgot to add `ifNotExists` and `ifExists` flags for some of the gPRC endpoints of Scalar DB Server. This PR fixes them. Please take a look!
=> Add ifNotExists and ifExists flags to RPC

.github/workflows/release.yaml
This PR add new steps in the release.yaml to push scalardb-server container image to Azure Container Registry.
(We don't need to push scalardb-schema-loader, because it is not used in Azure Market Place.)
Depending on the specification (requirement) of Azure Market Place, we need to push container image not only `patch version (X.Y.Z)` but also `minor version (X.Y)` and `latest tag`.
So, this PR add new steps to push the following three containers to Azure Container Registry, when the tag pushed.
* `scalardb-server:X.Y.Z`
* `scalardb-server:X.Y`
* `scalardb-server:latest`
Also, I tested the behavior of logic to detect latest version and create `minor version` / `latest` tag using following yaml.
<details>
<summary>YAML for test</summary>
```yaml
name: Release Test for Azure Container …
```
=> Add new steps in the release.yaml to push container to Azure Container Registry

core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java, core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
This PR enables PITR for the metadata table in Dynamo DB adapter. Please take a look!
=> Enable PITR for metadata table in Dynamo DB adapter

core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java, core/src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java, core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithTop.java, core/src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java, core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
This implements ScanAll for the JDBC storage. Please have a look.
=> Add ScanAll for JDBC storage

schema-loader/Dockerfile, server/Dockerfile
This updates the jre base image to 1.1.2. 
Please have a look.
=> Update jre8 base image to 1.1.2

core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java, core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
=> Add check for empty key

build.gradle, rpc/build.gradle
=> Merge protocVersion and protobufVersion

core/src/main/java/com/scalar/db/api/ConditionalExpression.java, core/src/main/java/com/scalar/db/api/DeleteIf.java, core/src/main/java/com/scalar/db/api/DeleteIfExists.java, core/src/main/java/com/scalar/db/api/PutIf.java, core/src/main/java/com/scalar/db/api/PutIfExists.java, core/src/main/java/com/scalar/db/api/PutIfNotExists.java
=> Add toString() to condition related classes

core/src/main/java/com/scalar/db/common/TableMetadataManager.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionalTableMetadataManager.java
=> Add a way to disable metadata cache

core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtilsTest.java
=> Refactor ConsensusCommitUtils

core/build.gradle
=> Remove copyDependencies task

schema-loader/Dockerfile, server/Dockerfile
This fixes [CVE-2022-1664](https://github.com/advisories/GHSA-q7pv-fjh6-6xq6)
Please have a look !
=> Fix CVE-2022-1664

core/src/main/java/com/scalar/db/api/Put.java, core/src/test/java/com/scalar/db/api/PutTest.java
=> Fix incompatible change

core/src/main/java/com/scalar/db/common/AbstractResult.java, core/src/main/java/com/scalar/db/service/StorageService.java, core/src/main/java/com/scalar/db/service/TransactionService.java, core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java, core/src/main/java/com/scalar/db/storage/common/AbstractDistributedStorage.java, core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransaction.java, core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransactionManager.java, core/src/main/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransaction.java, core/src/main/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java, core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java, core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java, core/src/main/java/com/scalar/db/util/ProtoUtils.java
=> Add @deprecated javadoc to overriding methods

core/src/main/java/com/scalar/db/service/StorageModule.java, core/src/main/java/com/scalar/db/service/TransactionModule.java
=> Refactor Guice modules

core/src/main/java/com/scalar/db/api/GetBuilder.java, core/src/main/java/com/scalar/db/api/OperationBuilder.java, core/src/main/java/com/scalar/db/api/ScanBuilder.java, core/src/main/java/com/scalar/db/service/StorageFactory.java, core/src/main/java/com/scalar/db/service/TransactionFactory.java, core/src/test/java/com/scalar/db/api/GetBuilderTest.java, core/src/test/java/com/scalar/db/api/ScanBuilderTest.java, gradle/spotbugs-exclude.xml, schema-loader/Dockerfile
While creating API guide, I found several methods that it would be better if we have. This PR adds those. Please take a look!
=> Add some useful methods

README.md, conf/database.properties, docs/configurations-for-consensus-commit.md, docs/design.md, docs/getting-started-with-scalardb-on-dynamodb.md, docs/getting-started-with-scalardb-on-jdbc.md, docs/index.md, docs/multi-storage-transactions.md, docs/scalardb-server.md, docs/two-phase-commit-transactions.md, server/conf/database.properties.tmpl
=> Add documentation for Consensus Commit configurations

schema-loader/Dockerfile, server/Dockerfile
=> Fix CVE-2022-2068

core/archive.gradle, rpc/archive.gradle, schema-loader/archive.gradle, server/archive.gradle
This adds my information in the `developers` field of the published pom file.
=> Add myself in the released pom file "developers" information

README.md, docs/api-guide.md, docs/getting-started-with-scalardb.md, docs/index.md, docs/storage-abstraction.md
=> Add documentation for Storage abstraction

README.md, docs/index.md
=> Add GraphQL and SQL to License section in README

docs/api-guide.md, docs/design.md, docs/getting-started-with-scalardb.md, docs/multi-storage-transactions.md, docs/scalardb-server.md, docs/storage-abstraction.md, docs/two-phase-commit-transactions.md
=> Small modifications for documentation

README.md, core/archive.gradle, docs/index.md, schema-loader/archive.gradle, server/archive.gradle
=> Modify descriptions in archive.gradle

docs/api-guide.md, docs/storage-abstraction.md
=> Several fixes for documents

core/src/main/java/com/scalar/db/api/Admin.java, docs/api-guide.md, docs/storage-abstraction.md
This adds documentation for the `Admin.addNewColumnToTable` in the API guide and updates the javadoc.
=> Add documentation for admin.addNewColumnToTable()

core/src/main/java/com/scalar/db/common/TableMetadataManager.java, core/src/main/java/com/scalar/db/util/ThrowableFunction.java, core/src/test/java/com/scalar/db/common/TableMetadataManagerTest.java
=> Refactor TableMetadataManager

core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java, core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java, docs/api-guide.md, docs/two-phase-commit-transactions.md
This PR updates the API Guide for the new API methods added in #657. Please take a look!
=> Update API Guide

README.md, docs/api-guide.md, docs/getting-started-with-scalardb.md, docs/index.md, docs/schema-loader.md, docs/storage-abstraction.md
=> Move Schema Loader document to docs directory

core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
=> Improve error messages in OperationChecker

core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminWithDefaultConfigTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminWithTableMetadataSchemaConfigTest.java
This PR does the same refactoring for `JdbcAdminTest` as the one for `DynamoAdminTest` in #658. Please take a look!
=> Refactor JdbcAdminTest

core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTableMetadataDatabaseConfigTest.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminWithDefaultConfigTest.java
This PR does the same refactoring for `CosmosAdminTest` as the one for `DynamoAdminTest` in #658. Please take a look!
=> Refactor CosmosAdminTest

core/src/integration-test/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminRepairTableIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java, docs/configurations-for-consensus-commit.md, server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedTransactionAdminService.java, server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminRepairTableIntegrationTestWithDistributedTransactionAdminService.java, server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithDistributedTransactionService.java, server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithTwoPhaseCommitTransactionService.java
=> Enable parallel/async commit by default

core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseConditionalMutationIntegrationTest.java, core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java, core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java, core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosOperationChecker.java, core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java, core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosOperationCheckerTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
This PR adds more checks for conditions for Dynamo and Cosmos. And it also includes some refactoring for `OperationChecker`. I will add inline comments for the details. Please take a look!
=> Add more checks for conditions for Dynamo and Cosmos

.github/workflows/ci.yaml, schema-loader/build.gradle, schema-loader/src/integration-test/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java, schema-loader/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSchemaLoaderWithStorageSpecificArgsIntegrationTest.java, schema-loader/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderWithStorageSpecificArgsIntegrationTest.java, schema-loader/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderIntegrationTest.java, schema-loader/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderWithStorageSpecificArgsIntegrationTest.java, schema-loader/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderWithStorageSpecificArgsIntegrationTest.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java, schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommand.java, server/build.gradle, server/src/integration-test/java/com/scalar/db/server/SchemaLoaderIntegrationTestWithScalarDbServer.java
This PR refactors the schema loader integration tests. I'll add inline comments for the details. Please take a look!
=> Refactor schema loader integration tests

schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java, schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
=> Use DistributedTransactionAdmin for transaction tables in SchemaOperator

core/src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java, core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
=> Fix Javadoc warnings

README.md, docs/getting-started/build.gradle, docs/index.md
=> Update Scalar DB version dependency

schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
=> Should support `--config=` and `-c=` styles for configuration file option in Schema Loader

build.gradle
=> Upgrade Spotless Gradle Plugin

core/src/integration-test/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
This PR fixes typos in admin integration test classes.
=> Fix typo in admin integration test classes

server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedTransactionAdminService.java, server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithDistributedTransactionService.java, server/src/integration-test/java/com/scalar/db/server/ServerEnv.java, server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithTwoPhaseCommitTransactionService.java
=> Disable include metadata tests if external server used in server integration tests

core/src/integration-test/java/com/scalar/db/storage/cassandra/TwoPhaseConsensusCommitIntegrationTestWithCassandra.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/TwoPhaseConsensusCommitIntegrationTestWithDynamo.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/TwoPhaseConsensusCommitIntegrationTestWithJdbcDatabase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTestBase.java, server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithTwoPhaseCommitTransactionService.java
=> Refactor two-phase commit transaction integration tests

core/src/integration-test/java/com/scalar/db/storage/cassandra/TwoPhaseConsensusCommitSpecificIntegrationTestWithCassandra.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitSpecificIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/TwoPhaseConsensusCommitSpecificIntegrationTestWithDynamo.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/TwoPhaseConsensusCommitSpecificIntegrationTestWithJdbcDatabase.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
=> Refactor consensus commit specific integration tests

core/src/main/java/com/scalar/db/api/TableMetadata.java
This fixes typos in exception messages.
=> Fix typos in exception messages

core/src/main/java/com/scalar/db/io/BigIntColumn.java, core/src/test/java/com/scalar/db/api/PutBuilderTest.java, core/src/test/java/com/scalar/db/io/BigIntColumnTest.java
This PR adds the check of the value range of `BigIntColumn`. Please take a look!
=> Should check the value range of BigIntColumn

core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransactionManager.java, core/src/main/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java, core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java, core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionManagerTest.java, core/src/test/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManagerTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
=> Should throw IllegalStateException when transaction is not found and already exists

core/src/main/java/com/scalar/db/util/ActiveExpiringMap.java, core/src/test/java/com/scalar/db/util/ActiveExpiringMapTest.java
This PR adds several methods (`containsValue()`, `keySet()`, `values()`, and `entrySet()`) to `ActiveExpiringMap`. Please take a look!
=> Add several methods to ActiveExpiringMap

integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
=> Small integration test modifications for the resume feature

README.md, docs/getting-started/build.gradle, docs/index.md
=> Update the Scalar DB dependency version to 3.7.1

build.gradle
This PR fixes CVE-2022-40151 and CVE-2022-40152 by upgrading the Cosmos DB client. Please take a look!
=> Fix CVE-2022-40151 and CVE-2022-40152

.github/workflows/scheduled-vuln-check.yaml
This PR updates the Scheduled Vulnerability Check workflow as the new patch versions are released. Please take a look!
=> Update Scheduled Vulnerability Check workflow

README.md, docs/getting-started/build.gradle, docs/index.md
=> Update the Scalar DB dependency version to 3.7.2

integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java, server/build.gradle, server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedTransactionAdminService.java, server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminRepairTableIntegrationTestWithDistributedTransactionAdminService.java, server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithDistributedTransactionService.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceRepairTableIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceColumnValueIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceConditionalMutationIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceMultipleClusteringKeyScanIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceMultiplePartitionKeyIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSecondaryIndexIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSingleClusteringKeyScanIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSinglePartitionKeyIntegrationTest.java, server/src/integration-test/java/com/scalar/db/server/SchemaLoaderIntegrationTestWithScalarDbServer.java, server/src/integration-test/java/com/scalar/db/server/ServerEnv.java, server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithTwoPhaseCommitTransactionService.java
=> Refactor server integration tests

core/src/main/java/com/scalar/db/api/Admin.java, core/src/main/java/com/scalar/db/api/DistributedStorage.java, core/src/main/java/com/scalar/db/api/DistributedTransactionAdmin.java, core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java, core/src/main/java/com/scalar/db/api/Scanner.java, core/src/main/java/com/scalar/db/api/TransactionCrudOperable.java, core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/TableMetadataManager.java, core/src/main/java/com/scalar/db/storage/cassandra/BatchHandler.java, core/src/main/java/com/scalar/db/storage/cassandra/MutateStatementHandler.java, core/src/main/java/com/scalar/db/storage/cassandra/StatementHandler.java, core/src/main/java/com/scalar/db/storage/cosmos/BatchHandler.java, core/src/main/java/com/scalar/db/storage/cosmos/MutateStatementHandler.java, core/src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java, core/src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionTableMetadataManager.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
=> Small modifications for Javadoc and comments

integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminRepairTableIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminRepairTableIntegrationTestBase.java
=> Should close admin in afterEach() in the repair integration tests

docs/backup-restore.md
=> docs: backup & restore from SQLite

core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
This PR is just a refactoring thing, so it basically doesn't change the behavior. Please take a look!
=> Refactor prepare logic

core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ParallelExecutorTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
This PR is just a refactoring thing, so it basically doesn't change the behavior. Please take a look!
=> Refactor validation logic

README.md, docs/getting-started/build.gradle, docs/index.md
=> Update the Scalar DB dependency version to 3.7.3

core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CoordinatorConflictException.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
I'll add inline comments for the details. Please take a look!
=> Revisit commit and abort state logic

core/src/main/java/com/scalar/db/util/ScalarDbUtils.java, core/src/test/java/com/scalar/db/util/ScalarDbUtilsTest.java
=> Should care about ScanWithIndex in ScalarDbUtils.copyAndSetTargetToIfNot()

README.md, docs/getting-started/build.gradle, docs/index.md
=> Update the Scalar DB dependency version to 3.8.0

server/Dockerfile
Our scheduled vuln check workflow has detected https://avd.aquasec.com/nvd/2022/cve-2022-41721/
=> Fix CVE-2022-41721

core/src/main/java/com/scalar/db/io/BigIntColumn.java
=> Remove unnecessary string building

.github/workflows/ci.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/release.yaml, .github/workflows/vuln-check.yaml
This PR renames a job name and upgrades some actions and replaces the set-output command. Please take a look!
=> Update GitHub actions workflows

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
=> docs(fix): DB name in comment (PostgreSQL -> SQL Server)

schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
This PR modifies the schema loader command name. Please take a look!
=> Modify schema-loader-command-name

core/src/main/java/com/scalar/db/config/ConfigUtils.java
This is very trivial thing. This PR adds the `@Nullable` annotation to several methods and their arguments in `ConfigUtils` to make them more explicit. Please take a look!
=> Add `@Nullable` in ConfigUtils

core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminIntegrationTestWithJdbcDatabase.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminIntegrationTest.java
=> Fix Error Prone warnings

core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/util/ActiveExpiringMap.java, core/src/test/java/com/scalar/db/util/ActiveExpiringMapTest.java
This PR adds `computeIfAbsent()` and `computeIfPresent()` methods to `ActiveExpiringMap`. It also does some refactoring for `ActiveExpiringMap`. Please take a look!
=> Add computeIfXXX methods to ActiveExpiringMap

README.md, docs/getting-started/build.gradle, docs/index.md
=> Update the Scalar DB dependency version to 3.9.0

core/src/main/java/com/scalar/db/api/TransactionCrudOperable.java, core/src/main/java/com/scalar/db/exception/transaction/UnsatisfiedConditionException.java
This PR adds a constructor to `UnsatisfiedConditionException`. Please take a look!
=> Add a constructor to UnsatisfiedConditionException

core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionRelationalScanIntegrationTest.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
This PR adds relational scan processing for JDBC transactions. PTAL!
=> Add relational scan for JDBC transactions

README.md, docs/add-scalardb-to-your-build.md, docs/getting-started/build.gradle, docs/index.md
=> Update the ScalarDB dependency version to 3.9.1

core/src/main/java/com/scalar/db/api/DistributedTransaction.java, core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java, core/src/main/java/com/scalar/db/api/TransactionCrudOperable.java, core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransaction.java, core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/exception/transaction/AbortException.java, core/src/main/java/com/scalar/db/exception/transaction/CommitConflictException.java, core/src/main/java/com/scalar/db/exception/transaction/CommitException.java, core/src/main/java/com/scalar/db/exception/transaction/CrudConflictException.java, core/src/main/java/com/scalar/db/exception/transaction/CrudException.java, core/src/main/java/com/scalar/db/exception/transaction/PreparationConflictException.java, core/src/main/java/com/scalar/db/exception/transaction/PreparationException.java, core/src/main/java/com/scalar/db/exception/transaction/RollbackException.java, core/src/main/java/com/scalar/db/exception/transaction/TransactionNotFoundException.java, core/src/main/java/com/scalar/db/exception/transaction/ValidationConflictException.java, core/src/main/java/com/scalar/db/exception/transaction/ValidationException.java
This PR revises the Javadoc for the exceptions to make them more precise. Please take a look!
=> Revise Javadoc for exceptions

core/src/main/java/com/scalar/db/api/DistributedTransaction.java, core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java, core/src/main/java/com/scalar/db/api/TransactionCrudOperable.java, core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransaction.java, core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/exception/transaction/AbortException.java, core/src/main/java/com/scalar/db/exception/transaction/CommitConflictException.java, core/src/main/java/com/scalar/db/exception/transaction/CommitException.java, core/src/main/java/com/scalar/db/exception/transaction/CrudConflictException.java, core/src/main/java/com/scalar/db/exception/transaction/CrudException.java, core/src/main/java/com/scalar/db/exception/transaction/PreparationConflictException.java, core/src/main/java/com/scalar/db/exception/transaction/PreparationException.java, core/src/main/java/com/scalar/db/exception/transaction/RollbackException.java, core/src/main/java/com/scalar/db/exception/transaction/TransactionNotFoundException.java, core/src/main/java/com/scalar/db/exception/transaction/ValidationConflictException.java, core/src/main/java/com/scalar/db/exception/transaction/ValidationException.java
Backport of https://github.com/scalar-labs/scalardb/pull/930
=> Backport to branch(3) : Revise Javadoc for exceptions

docs/api-guide.md
Backport of https://github.com/scalar-labs/scalardb/pull/932
=> Backport to branch(3) : Revise document for handling exceptions

server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
=> Backport to branch(3) : Avoid decrementing outstanding requests counter duplicately

server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
=> Backport to branch(3.9) : Avoid decrementing outstanding requests counter duplicately

server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
=> Backport to branch(3.8) : Avoid decrementing outstanding requests counter duplicately

server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
=> Backport to branch(3.6) : Avoid decrementing outstanding requests counter duplicately

server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
=> Backport to branch(3.7) : Avoid decrementing outstanding requests counter duplicately

build.gradle, rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageAdminGrpc.java, rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageGrpc.java, rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionAdminGrpc.java, rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionGrpc.java, rpc/src/main/grpc/com/scalar/db/rpc/TwoPhaseCommitTransactionGrpc.java
Backport of https://github.com/scalar-labs/scalardb/pull/943
=> Backport to branch(3) : Fix CVE-2023-1428 and CVE-2023-32731

build.gradle, rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageAdminGrpc.java, rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageGrpc.java, rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionAdminGrpc.java, rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionGrpc.java, rpc/src/main/grpc/com/scalar/db/rpc/TwoPhaseCommitTransactionGrpc.java
Backport of https://github.com/scalar-labs/scalardb/pull/943
=> Backport to branch(3.9) : Fix CVE-2023-1428 and CVE-2023-32731

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/954
=> Backport to branch(3) : Fix CVE-2023-2976

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/954
=> Backport to branch(3.9) : Fix CVE-2023-2976

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/954
=> Backport to branch(3.7) : Fix CVE-2023-2976

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/954
=> Backport to branch(3.6) : Fix CVE-2023-2976

core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java, core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionManagerTest.java, docs/api-guide.md
Backport of https://github.com/scalar-labs/scalardb/pull/944
=> Backport to branch(3) : Add join() to DistributedTransactionManager

core/src/test/java/com/scalar/db/transaction/consensuscommit/MutationConditionsValidatorTest.java
This PR fixes  java warnings in the `MutationConditionsValidatorTest` class. Please take a look!
=> Fix java warnings in MutationConditionsValidatorTest

core/src/test/java/com/scalar/db/transaction/consensuscommit/MutationConditionsValidatorTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/970
=> Backport to branch(3.10) : Fix java warnings in MutationConditionsValidatorTest

docs/two-phase-commit-transactions.md
Backport of https://github.com/scalar-labs/scalardb/pull/934
=> Backport to branch(3.9): Revise document for handling exceptions for Two-phase Commit Transactions

docs/api-guide.md, docs/two-phase-commit-transactions.md
Backport of https://github.com/scalar-labs/scalardb/pull/975
=> Backport to branch(3.10) : Revise document for Handle exceptions

docs/api-guide.md, docs/two-phase-commit-transactions.md
Backport of https://github.com/scalar-labs/scalardb/pull/975
=> Backport to branch(3.9) : Revise document for Handle exceptions

README.md, docs/api-guide.md, docs/index.md, docs/storage-abstraction.md
Backport of https://github.com/scalar-labs/scalardb/pull/1004
=> Backport to branch(3.10) : Fix broken links to the "Getting Started" doc

README.md, docs/api-guide.md, docs/index.md, docs/storage-abstraction.md
Backport of https://github.com/scalar-labs/scalardb/pull/1004
=> Backport to branch(3.9) : Fix broken links to the "Getting Started" doc

README.md, docs/api-guide.md, docs/index.md, docs/storage-abstraction.md
Backport of https://github.com/scalar-labs/scalardb/pull/1004
=> Backport to branch(3.8) : Fix broken links to the "Getting Started" doc

docs/getting-started-with-scalardb.md
This PR adds some context to the "Execute transactions and retrieve data in the basic electronic money application" section of the "Getting Started with ScalarDB" doc so that users can better follow and understand the sample application.
- https://github.com/scalar-labs/scalardb/pull/990
- In the "Execute transactions and retrieve data in the basic electronic money application" section, I:
- Added an explanation about what the application can do.
- Added headings for each type transaction that users can execute in the application.
- Revised the wording for executing the transactions.
- I also made some minor wording changes and moved a sentence into a note block to better highlight the content.
I ran our docs site locally and confirmed that this doc appears as expected with the addition …
=> Add more context to the "Getting Started with ScalarDB" doc to help users run the sample application

docs/getting-started-with-scalardb.md
=> Backport to branch(3.10) : Add more context to the "Getting Started with ScalarDB" doc to help users run the sample application

docs/getting-started-with-scalardb.md
=> Backport to branch(3.9) : Add more context to the "Getting Started with ScalarDB" doc to help users run the sample application

docs/getting-started-with-scalardb.md
=> Backport to branch(3.8) : Add more context to the "Getting Started with ScalarDB" doc to help users run the sample application

docs/getting-started-with-scalardb.md
=> Backport to branch(3.7) : Add more context to the "Getting Started with ScalarDB" doc to help users run the sample application

docs/getting-started-with-scalardb.md
=> Backport to branch(3.6) : Add more context to the "Getting Started with ScalarDB" doc to help users run the sample application

docs/getting-started-with-scalardb.md
=> Backport to branch(3.5) : Add more context to the "Getting Started with ScalarDB" doc to help users run the sample application

.github/workflows/supported_storages_compatibility_check.yaml
=> Backport to branch(3.10) : Create supported storages compatibility check workflow

.github/workflows/supported_storages_compatibility_check.yaml
=> Backport to branch(3.9) : Create supported storages compatibility check workflow

.github/workflows/supported_storages_compatibility_check.yaml
=> Backport to branch(3.8) : Create supported storages compatibility check workflow

.github/workflows/supported_storages_compatibility_check.yaml
=> Backport to branch(3.7) : Create supported storages compatibility check workflow

.github/workflows/supported_storages_compatibility_check.yaml
=> Backport to branch(3.6) : Create supported storages compatibility check workflow

docs/add-scalardb-to-your-build.md
=> Backport to branch(3.10) : Revise the "Add ScalarDB to Your Build" doc

docs/add-scalardb-to-your-build.md
=> Backport to branch (3.9): Revise the "Add ScalarDB to Your Build" doc

docs/add-scalardb-to-your-build.md
=> Backport to branch (3.8): Revise the "Add ScalarDB to Your Build" doc

docs/add-scalardb-to-your-build.md
=> Backport to branch (3.7): Revise the "Add ScalarDB to Your Build" doc

docs/add-scalardb-to-your-build.md
=> Backport to branch (3.6): Revise the "Add ScalarDB to Your Build" doc

docs/add-scalardb-to-your-build.md
=> Backport to branch (3.5): Revise the "Add ScalarDB to Your Build" doc

.github/workflows/ci.yaml, .github/workflows/supported_storages_compatibility_check.yaml, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTestUtils.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java
=> Backport to branch(3.10): Fix to handle version-specific integration tests

core/src/main/java/com/scalar/db/api/ScanBuilder.java, core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1045
=> Backport to branch(3.10) : Fix ScanBuilder bug

README.md, docs/index.md, docs/requirements.md, docs/scalardb-supported-databases.md
=> Backport to branch(3.10) : Revise supported databases and requirements/recommendations docs

README.md, docs/index.md, docs/requirements.md, docs/scalardb-supported-databases.md
=> Backport to branch(3.9) : Revise supported databases and requirements/recommendations docs

README.md, docs/index.md, docs/requirements.md, docs/scalardb-supported-databases.md
=> Backport to branch (3.8): Revise supported databases and requirements/recommendations docs

README.md, docs/index.md, docs/requirements.md, docs/scalardb-supported-databases.md
=> Backport to branch (3.7): Revise supported databases and requirements/recommendations docs

README.md, docs/index.md, docs/requirements.md, docs/scalardb-supported-databases.md
=> Backport to branch (3.6): Revise supported databases and requirements/recommendations docs

README.md, docs/index.md, docs/requirements.md, docs/scalardb-supported-databases.md
=> Backport to branch (3.5): Revise supported databases and requirements/recommendations docs

core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTestUtils.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
=> Backport to branch(3.10) : Fix to handle supported data types properly when importing tables in MySQL and SQL Server (#1055)

core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminRepairTableIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraColumnValueIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraConditionalMutationIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraMultiplePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSecondaryIndexIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSingleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSinglePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraWithReservedKeywordIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminIntegrationTestWithCassandra.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminRepairTableIntegrationTestWithCassandra.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitIntegrationTestWithCassandra.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitNullMetadataIntegrationTestWithCassandra.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitSpecificIntegrationTestWithCassandra.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/TwoPhaseConsensusCommitIntegrationTestWithCassandra.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/TwoPhaseConsensusCommitSpecificIntegrationTestWithCassandra.java, core/src/integration-test/java/com/scalar/db/storage/multistorage/ConsensusCommitNullMetadataIntegrationTestWithMultiStorage.java, core/src/integration-test/java/com/scalar/db/storage/multistorage/ConsensusCommitSpecificIntegrationTestWithMultiStorage.java, core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageIntegrationTest.java, core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java, core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTestBase.java, docs/getting-started-with-scalardb-by-using-kotlin.md, docs/getting-started-with-scalardb.md
[As discussed](https://github.com/scalar-labs/scalardb/pull/989#discussion_r1285579493) in a previous PR, this updates the default replication factor of namespace created via the Cassandra Admin and Schema Loader from 1 to 3.
=> Set Cassandra default replication factor to 3

docs/scalardb-supported-databases.md
=> Backport to branch(3.10) : Revise supported databases

docs/scalardb-supported-databases.md
=> Backport to branch(3.9) : Revise supported databases

docs/scalardb-supported-databases.md
=> Backport to branch(3.8) : Revise supported databases

docs/scalardb-supported-databases.md
=> Backport to branch(3.7) : Revise supported databases

docs/scalardb-supported-databases.md
=> Backport to branch(3.6) : Revise supported databases

docs/scalardb-supported-databases.md
=> Backport to branch(3.5) : Revise supported databases

core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosEnv.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoEnv.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java, core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageEnv.java, core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java, schema-loader/src/main/java/com/scalar/db/schemaloader/command/CosmosCommand.java, server/src/integration-test/java/com/scalar/db/server/ServerEnv.java
This PR fixes the warnings displayed by my IntelliJ.
N/A
- Reduce the deprecated usages
- Fix the Javadoc warnings
- Fix some other Java warnings
N/A
N/A
=> Fix warnings displayed by IntelliJ

.github/workflows/ci.yaml
Backport of https://github.com/scalar-labs/scalardb/pull/1140
=> Backport to branch(3.10) : Fix Oracle 23 CI

.github/workflows/ci.yaml
Backport of https://github.com/scalar-labs/scalardb/pull/1140
=> Backport to branch(3.9) : Fix Oracle 23 CI

.github/workflows/ci.yaml
=> Backport to branch(3.6) : Fix Oracle 23 CI

.github/workflows/ci.yaml
=>  Backport to branch(3.7) : Fix Oracle 23 CI 

server/Dockerfile
=> Backport to branch(3.6) : Update busybox version in dockerfile

server/Dockerfile
=> Backport to branch(3.7) : Update busybox version in dockerfile

server/Dockerfile
=> Backport to branch(3.8) : Update busybox version in dockerfile

server/Dockerfile
=> Backport to branch(3.9) : Update busybox version in dockerfile

server/Dockerfile
=> Backport to branch(3.10) : Update busybox version in dockerfile

docs/configurations.md, docs/multi-storage-transactions.md, docs/two-phase-commit-transactions.md
> **Note**
> 
> Reviewed and modified the contents of this doc for the `3.10` branch in alignment with the changes and comments on the `3.8` branch in #1084 and #1117.
=> Backport to branch(3.10) : Revise configuration-related docs (3.8)

docs/configurations.md, docs/multi-storage-transactions.md, docs/two-phase-commit-transactions.md
> **Note**
> 
> Reviewed and modified the contents of this doc for the `3.9` branch in alignment with the changes and comments on the `3.8` branch in #1084 and #1117.
=> Backport to branch(3.9) : Revise configuration-related docs (3.8)

docs/configurations.md, docs/multi-storage-transactions.md, docs/two-phase-commit-transactions.md
> **Note**
> 
> Reviewed and modified the contents of this doc for the `3.5` branch in alignment with the changes and comments on the `3.8` branch in #1084 and #1117.
=> Backport to branch(3.5) : Revise configuration-related docs (3.8)

docs/storage-abstraction.md
This PR revises the contents of the storage abstraction doc.
> **Note**
>
> Many of the revisions in this doc are similar to the same changes I made to **api-guide.md** in #1084. So, if we need to make changes in this doc (**storage-abstraction.md**), please confirm if we need to make the same change in **api-guide.md**.
N/A
- Revised contents.
- Added notice blocks for noteworthy content.
Please see my comments in the doc.
N/A
=> Revise the contents of the storage abstraction doc

docs/storage-abstraction.md
=> Backport to branch(3.6) : Revise the contents of the storage abstraction doc

docs/storage-abstraction.md
=> Backport to branch(3.7) : Revise the contents of the storage abstraction doc

docs/storage-abstraction.md
=> Backport to branch(3.8) : Revise the contents of the storage abstraction doc

docs/storage-abstraction.md
=> Backport to branch(3.10) : Revise the contents of the storage abstraction doc

.github/workflows/auto-pr.yaml
Backport of https://github.com/scalar-labs/scalardb/pull/1209
=> Backport to branch(3.10) : Port auto-pr workflow to branch `3`

ci/auto-pr/conv_proj_version_to_branch, ci/auto-pr/create_pull_requests, ci/auto-pr/fetch_gh_proj_versions, ci/auto-pr/fetch_gh_user_info
We tried to port Auto PR to `3.9` or older ones in https://github.com/scalar-labs/scalardb/pull/1210. But I failed to add necessary scripts for Auto-PR.
Fixes https://github.com/scalar-labs/scalardb/pull/1210
Add necessary `ci/auto-pr` scripts.
This change isn't tested.
N/A
=> Add missing scripts for Auto-PR

ci/auto-pr/conv_proj_version_to_branch, ci/auto-pr/create_pull_requests, ci/auto-pr/fetch_gh_proj_versions, ci/auto-pr/fetch_gh_user_info
Backport of https://github.com/scalar-labs/scalardb/pull/1212
=> Backport to branch(3.8) : Add missing scripts for Auto-PR

ci/auto-pr/conv_proj_version_to_branch, ci/auto-pr/create_pull_requests, ci/auto-pr/fetch_gh_proj_versions, ci/auto-pr/fetch_gh_user_info
Backport of https://github.com/scalar-labs/scalardb/pull/1214
=> Backport to branch(3.6) : Backport to branch(3.8) : Add missing scripts for Auto-PR

ci/auto-pr/conv_proj_version_to_branch, ci/auto-pr/create_pull_requests, ci/auto-pr/fetch_gh_proj_versions, ci/auto-pr/fetch_gh_user_info
Backport of https://github.com/scalar-labs/scalardb/pull/1212
=> Backport to branch(3.7) : Add missing scripts for Auto-PR

docs/configurations.md, docs/multi-storage-transactions.md, docs/two-phase-commit-transactions.md
Backport of #1117
> **Note**
> 
> Reviewed and modified the contents of this doc for the `master` branch in alignment with the changes and comments on the `3.8` branch in #1082 and #1117.
=> Backport to branch(master) : Revise configuration-related docs (3.8)

docs/backup-restore.md
=> Backport to branch(3.10) : Revise the backup and restore guide

docs/backup-restore.md
=> Backport to branch(3.9) : Revise the backup and restore guide

docs/configurations.md, docs/two-phase-commit-transactions.md
This backport addresses changes discussed in https://github.com/scalar-labs/scalardb/pull/1190.
=> Backport to branch(3.5) : Revise configuration-related docs

docs/configurations.md, docs/two-phase-commit-transactions.md
This backport addresses changes discussed in https://github.com/scalar-labs/scalardb/pull/1190.
=> Backport to branch(3.6) : Revise configuration-related docs

docs/configurations.md, docs/two-phase-commit-transactions.md
This backport addresses changes discussed in https://github.com/scalar-labs/scalardb/pull/1190.
=> Backport to branch(3.7) : Revise configuration-related docs

docs/configurations.md, docs/two-phase-commit-transactions.md
Backport to branch(3.7) : Revise configuration-related docs
=> Backport to branch(3.9) : Revise configuration-related docs

docs/configurations.md, docs/two-phase-commit-transactions.md
Backport to branch(3.7) : Revise configuration-related docs
=> Backport to branch(3.10) : Revise configuration-related docs

docs/backup-restore.md
=> Backport to branch(3.5) : Revise the backup and restore guide

docs/backup-restore.md
=> Backport to branch(3.6) : Revise the backup and restore guide

docs/backup-restore.md
=> Backport to branch(3.7) : Revise the backup and restore guide

docs/backup-restore.md
=> Backport to branch(3.8) : Revise the backup and restore guide

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1238
=> Backport to branch(3) : Bump org.apache.commons:commons-text from 1.10.0 to 1.11.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1240
=> Backport to branch(3) : Bump com.azure:azure-cosmos from 4.51.0 to 4.52.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1241
=> Backport to branch(3) : Bump log4jVersion from 2.21.0 to 2.21.1

.github/workflows/auto-pr.yaml, ci/auto-pr/conv_proj_version_to_branch
=> Backport to branch(3.6) : Should not create PR for base branch in Auto-PR

.github/workflows/auto-pr.yaml, ci/auto-pr/conv_proj_version_to_branch
=> Backport to branch(3.7) : Should not create PR for base branch in Auto-PR

.github/workflows/auto-pr.yaml, ci/auto-pr/conv_proj_version_to_branch
=> Backport to branch(3.8) : Should not create PR for base branch in Auto-PR

.github/workflows/auto-pr.yaml, ci/auto-pr/conv_proj_version_to_branch
=> Backport to branch(3.9) : Should not create PR for base branch in Auto-PR

.github/workflows/auto-pr.yaml, ci/auto-pr/conv_proj_version_to_branch
=> Backport to branch(3.10) : Should not create PR for base branch in Auto-PR

.github/workflows/auto-pr.yaml, ci/auto-pr/conv_proj_version_to_branch
=> Backport to branch(3) : Should not create PR for base branch in Auto-PR

.github/workflows/create-release.yaml, .github/workflows/release.yaml, .github/workflows/upload-artifacts.yaml
=> Backport to branch(3) : Split release.yaml to two sub workflows

.github/workflows/create-release.yaml, .github/workflows/release.yaml, .github/workflows/upload-artifacts.yaml
=> Backport to branch(3.10) : Split release.yaml to two sub workflows

.github/workflows/create-release.yaml, .github/workflows/release.yaml, .github/workflows/upload-artifacts.yaml
=> Backport to branch(3.9) : Split release.yaml to two sub workflows

.github/workflows/create-release.yaml, .github/workflows/release.yaml, .github/workflows/upload-artifacts.yaml
=> Backport to branch(3.8) : Split release.yaml to two sub workflows

.github/workflows/create-release.yaml, .github/workflows/release.yaml, .github/workflows/upload-artifacts.yaml
=> Backport to branch(3.7) : Split release.yaml to two sub workflows

.github/workflows/create-release.yaml, .github/workflows/release.yaml, .github/workflows/upload-artifacts.yaml
=> Backport to branch(3.6) : Split release.yaml to two sub workflows

docs/schema-loader.md
Backport of https://github.com/scalar-labs/scalardb/pull/1196
=> Backport to branch(3.10) : Revise Schema Loader documentation

docs/schema-loader.md
Backport of https://github.com/scalar-labs/scalardb/pull/1196
=> Backport to branch(3.9) : Revise Schema Loader documentation

docs/schema-loader.md
Backport of https://github.com/scalar-labs/scalardb/pull/1196
=> Backport to branch(3) : Revise Schema Loader documentation

docs/schema-loader.md
=> Backport to branch(3.8): Revise Schema Loader documentation

schema-loader/README.md
=> Backport to branch(3.7): Revise Schema Loader documentation

schema-loader/README.md
=> Backport to branch(3.6): Revise Schema Loader documentation

schema-loader/README.md
=> Backport to branch(3.5): Revise Schema Loader documentation

.github/workflows/merge-release-notes.yaml
=> Backport to branch(3) : Added merging the release notes workflow

.github/workflows/merge-release-notes.yaml
=> Backport to branch(3.10) : Added merging the release notes workflow

.github/workflows/merge-release-notes.yaml
=> Backport to branch(3.9) : Added merging the release notes workflow

.github/workflows/merge-release-notes.yaml
=> Backport to branch(3.7) : Added merging the release notes workflow

.github/workflows/merge-release-notes.yaml
=> Backport to branch(3.6) : Added merging the release notes workflow

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1287
=> Backport to branch(3) : Bump com.github.spotbugs:spotbugs-annotations from 4.8.0 to 4.8.1

core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
=> Backport to branch(3) : Fix to prevent importing existing storage table

build.gradle, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTestUtils.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/config/DatabaseConfig.java, core/src/main/java/com/scalar/db/io/BigIntColumn.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java, core/src/main/java/com/scalar/db/storage/dynamo/Namespace.java, core/src/main/java/com/scalar/db/storage/jdbc/ConditionalMutator.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java, core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithFetchFirstNRowsOnly.java, core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithLimitQuery.java, core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithTop.java, core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java, core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java, core/src/main/java/com/scalar/db/storage/rpc/ScannerImpl.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java, schema-loader/src/main/java/com/scalar/db/schemaloader/ImportSchemaParser.java, schema-loader/src/main/java/com/scalar/db/schemaloader/ImportTableSchema.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaParser.java, schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java, server/src/main/java/com/scalar/db/server/ServerConfig.java
Backport of https://github.com/scalar-labs/scalardb/pull/1289
=> Backport to branch(3) : Bump spotbugsPluginVersion from 5.1.4 to 5.2.3

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1299
=> Backport to branch(3) : Bump org.postgresql:postgresql from 42.6.0 to 42.7.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1327
=> Backport to branch(3) : Bump spotbugsPluginVersion from 5.2.3 to 5.2.4

core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java, docs/api-guide.md, docs/configurations.md, docs/schema-loader-import.md, docs/schema-loader.md, schema-loader/sample/import_schema_sample.json
Backport of https://github.com/scalar-labs/scalardb/pull/1301
=> Backport to branch(3) : Update documents for cross-partition scan and import feature

core/src/main/java/com/scalar/db/api/AuthAdmin.java, core/src/main/java/com/scalar/db/api/DistributedTransactionAdmin.java, core/src/main/java/com/scalar/db/exception/storage/ExecutionException.java, core/src/main/java/com/scalar/db/exception/transaction/AbortException.java, core/src/main/java/com/scalar/db/exception/transaction/CommitException.java, core/src/main/java/com/scalar/db/exception/transaction/CrudException.java, core/src/main/java/com/scalar/db/exception/transaction/PreparationException.java, core/src/main/java/com/scalar/db/exception/transaction/RollbackException.java, core/src/main/java/com/scalar/db/exception/transaction/TransactionException.java, core/src/main/java/com/scalar/db/exception/transaction/ValidationException.java
Backport of https://github.com/scalar-labs/scalardb/pull/1318
=> Backport to branch(3) : Add AuthAdmin

docs/api-guide.md, docs/storage-abstraction.md
Backport of https://github.com/scalar-labs/scalardb/pull/1310
=> Backport to branch(3.8) : Add API doc for `admin.repairTable` method for v3.X

docs/api-guide.md, docs/storage-abstraction.md
Backport of https://github.com/scalar-labs/scalardb/pull/1310
=> Backport to branch(3.9) : Add API doc for `admin.repairTable` method for v3.X

docs/api-guide.md, docs/storage-abstraction.md
Backport of https://github.com/scalar-labs/scalardb/pull/1310
=> Backport to branch(3.10) : Add API doc for `admin.repairTable` method for v3.X

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1341
=> Backport to branch(3) : Bump com.github.spotbugs:spotbugs-annotations from 4.8.1 to 4.8.2

.github/workflows/ci.yaml, core/build.gradle, core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithCassandra.java, core/src/integration-test/java/com/scalar/db/storage/cassandra/TwoPhaseConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithCassandra.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithCosmos.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithDynamo.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/TwoPhaseConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithDynamo.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithJdbcDatabase.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/TwoPhaseConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithJdbcDatabase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminImportTableIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminRepairTableIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitCrossPartitionScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestUtils.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithIncludeMetadataEnabledIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitCrossPartitionScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitWithIncludeMetadataEnabledIntegrationTestBase.java, server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithServer.java, server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithServer.java, server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithServer.java
Backport of https://github.com/scalar-labs/scalardb/pull/1346
=> Backport to branch(3) : Refactor integration tests for Consensus Commit

.github/workflows/ci.yaml, .github/workflows/create-release.yaml, .github/workflows/merge-release-notes.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/upload-artifacts.yaml, .github/workflows/vuln-check.yaml
Backport of https://github.com/scalar-labs/scalardb/pull/1344
=> Backport to branch(3) : Bump actions/setup-java from 3 to 4

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1342
=> Backport to branch(3) : Bump spotbugsPluginVersion from 5.2.4 to 5.2.5

core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitProvider.java, core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionProvider.java
Backport of https://github.com/scalar-labs/scalardb/pull/1362
=> Backport to branch(3) : Add TRANSACTION_MANAGER_NAME to XXXConfig

docs/scalardb-supported-databases.md
This PR fixes broken links in the ScalarDB supported databases doc.
N/A
Fixed two broken links.
N/A
N/A
=> Fix broken links in supported databases doc

docs/scalardb-supported-databases.md
Backport of https://github.com/scalar-labs/scalardb/pull/1361
=> Backport to branch(3.6) : Fix broken links in supported databases doc

docs/scalardb-supported-databases.md
Backport of https://github.com/scalar-labs/scalardb/pull/1361
=> Backport to branch(3.9) : Fix broken links in supported databases doc

docs/scalardb-supported-databases.md
Backport of https://github.com/scalar-labs/scalardb/pull/1361
=> Backport to branch(3.10) : Fix broken links in supported databases doc

docs/scalardb-supported-databases.md
Backport of https://github.com/scalar-labs/scalardb/pull/1361
=> Backport to branch(3) : Fix broken links in supported databases doc

integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminRepairIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionCrossPartitionScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionCrossPartitionScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithIncludeMetadataEnabledIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitWithIncludeMetadataEnabledIntegrationTestBase.java
This PR modifies the integration tests for creations and deletions of coordinator tables.
N/A
- Modified the integration tests to create coordinator tables first
- Modified the integration tests to drop coordinator tables last
N/A
N/A
=> Modify integration tests for creations and deletions of coordinator tables

core/src/main/java/com/scalar/db/common/TableMetadataManager.java, core/src/main/java/com/scalar/db/util/ThrowableConsumer.java, core/src/main/java/com/scalar/db/util/ThrowableFunction.java, core/src/test/java/com/scalar/db/common/TableMetadataManagerTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1373
=> Backport to branch(3) : Add ThrowableConsumer

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1372
=> Backport to branch(3) : Bump org.postgresql:postgresql from 42.7.0 to 42.7.1

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1389
=> Backport to branch(3) : Bump com.github.spotbugs:spotbugs-annotations from 4.8.2 to 4.8.3

.github/workflows/ci.yaml
Backport of https://github.com/scalar-labs/scalardb/pull/1387
=> Backport to branch(3) : Bump actions/upload-artifact from 3 to 4

core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
Backport of https://github.com/scalar-labs/scalardb/pull/1395
=> Backport to branch(3) : Enable setting of transaction expiration handler in active transaction management

README.md, docs/getting-started-kotlin/build.gradle.kts, docs/getting-started/build.gradle, docs/index.md
This PR updates ScalarDB dependency version to 3.11.0.
N/A
- Updated ScalarDB dependency version to 3.11.0
N/A
N/A
=> Update ScalarDB dependency version to 3.11.0

README.md, docs/getting-started-kotlin/build.gradle.kts, docs/getting-started/build.gradle, docs/index.md
Backport of https://github.com/scalar-labs/scalardb/pull/1417
=> Backport to branch(3) : Update ScalarDB dependency version to 3.11.0

.github/workflows/scheduled-vuln-check.yaml
This PR updates Scheduled Vulnerability Check.
N/A
- Removed the check for v3.6 from Scheduled Vulnerability Check as it's EOL
- Added a check for v3.11 to Scheduled Vulnerability Check as it's released
N/A
N/A
=> Update Scheduled Vulnerability Check

docs/scalardb-supported-databases.md
=> Backport to branch(3) : Update supported databases

docs/scalardb-supported-databases.md
=> Backport to branch(3.11) : Update supported databases

docs/scalardb-supported-databases.md
=> Backport to branch(3.10) : Update supported databases

docs/scalardb-supported-databases.md
=> Backport to branch(3.9) : Update supported databases

docs/scalardb-supported-databases.md
=> Backport to branch(3.8) : Update supported databases

docs/scalardb-supported-databases.md
=> Backport to branch(3.7) : Update supported databases

docs/requirements.md
=> Backport to branch (3): Add a requirement for privileges of underlying databases

docs/requirements.md
=> Backport to branch (3.7): Add a requirement for privileges of underlying databases

docs/requirements.md
=> Backport to branch (3.8): Add a requirement for privileges of underlying databases

docs/requirements.md
=> Backport to branch (3.9): Add a requirement for privileges of underlying databases

docs/requirements.md
=> Backport to branch (3.10): Add a requirement for privileges of underlying databases

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1432
=> Backport to branch(3) : Bump com.azure:azure-cosmos from 4.53.1 to 4.54.0

core/src/main/java/com/scalar/db/config/ConfigUtils.java, core/src/test/java/com/scalar/db/config/ConfigUtilsTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1443
=> Backport to branch(3) : Add getStringFromFilePath() to ConfigUtils

.github/workflows/release-snapshot.yaml, .github/workflows/upload-artifacts.yaml
Backport of https://github.com/scalar-labs/scalardb/pull/1453
=> Backport to branch(3) : Bump actions/cache from 3 to 4

core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java, core/src/main/java/com/scalar/db/util/ActiveExpiringMap.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/util/ActiveExpiringMapTest.java, docs/two-phase-commit-transactions.md
Backport of https://github.com/scalar-labs/scalardb/pull/1451
=> Backport to branch(3) : Change TwoPhaseConsensusCommitManager.join() behavior

core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosUtils.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosConfigTest.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosUtilsTest.java, docs/configurations.md
Backport of https://github.com/scalar-labs/scalardb/pull/1470
=> Backport to branch(3) : Make Cosmos DB consistency level configurable

.github/workflows/ci.yaml, .github/workflows/vuln-check.yaml
Backport of https://github.com/scalar-labs/scalardb/pull/1472
=> Backport to branch(3) : Bump gradle/gradle-build-action from 2 to 3

core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/UncommittedRecordException.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1476
=> Backport to branch(3) : Should perform lazy recovery in implicit pre-read

core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/UncommittedRecordException.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1476
=> Backport to branch(3.11) : Should perform lazy recovery in implicit pre-read

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1500
=> Backport to branch(3) : Bump com.azure:azure-cosmos from 4.54.0 to 4.55.1

docs/configurations.md
=> Backport to branch(3.8) : Add description about placeholders of database.properties

docs/configurations.md
=> Backport to branch(3.9) : Add description about placeholders of database.properties

docs/configurations.md
=> Backport to branch(3.10) : Add description about placeholders of database.properties

docs/configurations.md
=> Backport to branch(3.11) : Add description about placeholders of database.properties

docs/configurations.md
=> Backport to branch(3) : Add description about placeholders of database.properties

docs/scalardb-supported-databases.md
This PR updates the supported databases.
N/A
- Added supported databases for ScalarDB 3.12.
- Deleted supported databases for the EOL versions.
N/A
N/A
=> Update supported databases

docs/scalardb-supported-databases.md
Backport of https://github.com/scalar-labs/scalardb/pull/1510
=> Backport to branch(3.12) : Update supported databases

.github/workflows/ci.yaml, core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraJapaneseIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosJapaneseIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoJapaneseIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseJapaneseIntegrationTest.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageJapaneseIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/1518
=> Backport to branch(3.12) : Remove hard-coded collation in JDBC adapter

build.gradle
=> Backport to branch(3.12) : Bump org.postgresql:postgresql from 42.7.1 to 42.7.2

build.gradle
=> Backport to branch(3.11) : Bump org.postgresql:postgresql from 42.7.1 to 42.7.2

build.gradle
=> Backport to branch(3.10) : Bump org.postgresql:postgresql from 42.6.0 to 42.7.2

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1548
=> Backport to branch(3) : Bump log4jVersion from 2.22.1 to 2.23.0

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3) : Update CI to use no superuser for SQL Server test

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.11) : Update CI to use no superuser for SQL Server test

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.10) : Update CI to use no superuser for SQL Server test

core/src/main/java/com/scalar/db/common/error/CoreError.java, schema-loader/src/main/java/com/scalar/db/schemaloader/ImportSchemaParser.java, schema-loader/src/main/java/com/scalar/db/schemaloader/ImportTableSchema.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaParser.java, schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java, schema-loader/src/main/java/com/scalar/db/schemaloader/alteration/TableMetadataAlterationProcessor.java, schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java, schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommand.java, schema-loader/src/test/java/com/scalar/db/schemaloader/ImportTableSchemaTest.java, schema-loader/src/test/java/com/scalar/db/schemaloader/TableSchemaTest.java, schema-loader/src/test/java/com/scalar/db/schemaloader/alteration/TableMetadataAlterationProcessorTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1564
=> Backport to branch(3) : Add error codes to error messages of Schema loader

core/src/main/java/com/scalar/db/common/error/CoreError.java, schema-loader/src/main/java/com/scalar/db/schemaloader/ImportSchemaParser.java, schema-loader/src/main/java/com/scalar/db/schemaloader/ImportTableSchema.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaParser.java, schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java, schema-loader/src/main/java/com/scalar/db/schemaloader/alteration/TableMetadataAlterationProcessor.java, schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java, schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommand.java, schema-loader/src/test/java/com/scalar/db/schemaloader/ImportTableSchemaTest.java, schema-loader/src/test/java/com/scalar/db/schemaloader/TableSchemaTest.java, schema-loader/src/test/java/com/scalar/db/schemaloader/alteration/TableMetadataAlterationProcessorTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1564
=> Backport to branch(3.12) : Add error codes to error messages of Schema loader

core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
This PR revises error messages.
- https://github.com/scalar-labs/scalardb/pull/1493
- Revised error messages.
N/A
N/A
=> Revise error messages

core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
Backport of https://github.com/scalar-labs/scalardb/pull/1590
=> Backport to branch(3) : Revise error messages

core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
Backport of https://github.com/scalar-labs/scalardb/pull/1590
=> Backport to branch(3.12) : Revise error messages

docs/requirements.md, docs/scalardb-supported-databases.md
This PR updates the requirements and recommendations for the Underlying Databases of ScalarDB since the existing doc doesn't cover many aspects.
N/A
- Summarized the general requirements and added them to the doc.
- Summarized the database-specific requirements and added them to the doc.
- Summarized the database-specific recommendations and added them to the doc.
- (to @josh-wong) I think the current padding around tabs might need to be updated. Roughly speaking, no padding on the top and too much padding on the bottom, I feel.
- I will create another doc for …
=> Update requirements and recommendations

docs/requirements.md, docs/scalardb-supported-databases.md
=> Backport to branch(3.8) : Update requirements and recommendations

docs/requirements.md, docs/scalardb-supported-databases.md
=> Backport to branch(3.9) : Update requirements and recommendations

docs/requirements.md, docs/scalardb-supported-databases.md
=> Backport to branch(3.10) : Update requirements and recommendations

docs/requirements.md, docs/scalardb-supported-databases.md
=> Backport to branch(3.11) : Update requirements and recommendations

docs/requirements.md, docs/scalardb-supported-databases.md
=> Backport to branch(3.12) : Update requirements and recommendations

docs/requirements.md, docs/scalardb-supported-databases.md
=> Backport to branch(3) : Update requirements and recommendations

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.12) : Update CI to fix issues of SQL Server integration test

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.11) : Update CI to fix issues of SQL Server integration test

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.10) : Update CI to fix issues of SQL Server integration test

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.9) : Update CI to fix issues of SQL Server integration test

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.8) : Update CI to fix issues of SQL Server integration test

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1609
=> Backport to branch(3) : Bump com.scalar-labs:scalar-admin from 2.1.2 to 2.2.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1610
=> Backport to branch(3) : Bump org.postgresql:postgresql from 42.7.2 to 42.7.3

README.md, docs/getting-started-kotlin/build.gradle.kts, docs/getting-started/build.gradle, docs/index.md
This PR updates ScalarDB dependency version to 3.12.2.
N/A
- Updated ScalarDB dependency version to 3.12.2.
N/A
N/A
=> Update ScalarDB dependency version to 3.12.2

.github/workflows/ci.yaml
=> Backport to branch(3) : Remove the CI trigger for branch pushes

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1618
=> Backport to branch(3) : Bump com.azure:azure-cosmos from 4.56.0 to 4.57.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1632
=> Backport to branch(3) : Bump com.github.spotbugs:spotbugs-annotations from 4.8.3 to 4.8.4

docs/overview.md
=> Backport to branch(3) : Add an overview page

docs/overview.md
=> Backport to branch(3.8) : Add an overview page

docs/overview.md
=> Backport to branch(3.9) : Add an overview page

docs/overview.md
=> Backport to branch(3.10) : Add an overview page

docs/overview.md
=> Backport to branch(3.11) : Add an overview page

docs/overview.md
=> Backport to branch(3.12) : Add an overview page

core/build.gradle
=> Backport to branch(3) : Use AWS SDK BOM

core/build.gradle
=> Backport to branch(3.12) : Use AWS SDK BOM

core/build.gradle
=> Backport to branch(3.11) : Use AWS SDK BOM

core/build.gradle
=> Backport to branch(3.10) : Use AWS SDK BOM

core/build.gradle
=> Backport to branch(3.8) : Use AWS SDK BOM

core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
=> Backport to branch(3) : Fix NullPointerException in EXTRA_READ validation

core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
=> Backport to branch(3.12) : Fix NullPointerException in EXTRA_READ validation

core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
=> Backport to branch(3.11) : Fix NullPointerException in EXTRA_READ validation

core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
=> Backport to branch(3.10) : Fix NullPointerException in EXTRA_READ validation

core/build.gradle, core/src/main/java/com/scalar/db/util/groupcommit/BackgroundWorker.java, core/src/main/java/com/scalar/db/util/groupcommit/DelayedGroup.java, core/src/main/java/com/scalar/db/util/groupcommit/DelayedSlotMoveWorker.java, core/src/main/java/com/scalar/db/util/groupcommit/Emittable.java, core/src/main/java/com/scalar/db/util/groupcommit/Group.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCleanupWorker.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitConfig.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitException.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitter.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupManager.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupSizeFixWorker.java, core/src/main/java/com/scalar/db/util/groupcommit/KeyManipulator.java, core/src/main/java/com/scalar/db/util/groupcommit/Metrics.java, core/src/main/java/com/scalar/db/util/groupcommit/NormalGroup.java, core/src/main/java/com/scalar/db/util/groupcommit/Slot.java, core/src/test/java/com/scalar/db/util/groupcommit/BackgroundWorkerTest.java, core/src/test/java/com/scalar/db/util/groupcommit/DelayedGroupTest.java, core/src/test/java/com/scalar/db/util/groupcommit/DelayedSlotMoveWorkerTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCleanupWorkerTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitConfigTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterConcurrentTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupManagerTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupSizeFixWorkerTest.java, core/src/test/java/com/scalar/db/util/groupcommit/NormalGroupTest.java, core/src/test/java/com/scalar/db/util/groupcommit/SlotTest.java, core/src/test/java/com/scalar/db/util/groupcommit/TestableKeyManipulator.java
Backport of https://github.com/scalar-labs/scalardb/pull/1607
=> Backport to branch(3) : Add `util/groupcommit` package in `core` subproject

core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java, core/src/main/java/com/scalar/db/api/OperationBuilder.java, core/src/main/java/com/scalar/db/api/Put.java, core/src/main/java/com/scalar/db/api/PutBuilder.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java, core/src/test/java/com/scalar/db/api/PutBuilderTest.java, core/src/test/java/com/scalar/db/api/PutTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposerTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/1679
=> Backport to branch(3) : Introduce insert mode for Consensus Commit Put operations

core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1681
=> Backport to branch(3.11) : Should execute lazy recovery for Put and Delete in Consensus Commit

core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1681
=> Backport to branch(3.12) : Should execute lazy recovery for Put and Delete in Consensus Commit

core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitter.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupManagerTest.java, core/src/test/java/com/scalar/db/util/groupcommit/NormalGroupTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1683
=> Backport to branch(3) : Fix flaky test and warnings in group commit

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1685
=> Backport to branch(3) : Bump com.azure:azure-cosmos from 4.57.0 to 4.58.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1687
=> Backport to branch(3) : Bump org.apache.commons:commons-text from 1.11.0 to 1.12.0

core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitConfig.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitMetrics.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitMonitor.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitter.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitConfigTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterConcurrentTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1684
=> Backport to branch(3) : Make group commit metrics log configurable

core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminImportTableIntegrationTestWithJdbcDatabase.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTableIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderImportIntegrationTest.java, integration-test/build.gradle, integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminImportTableIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminRepairTableIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageColumnValueIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageConditionalMutationIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageCrossPartitionScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageJapaneseIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultipleClusteringKeyScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultiplePartitionKeyIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageSecondaryIndexIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageSingleClusteringKeyScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageSinglePartitionKeyIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageWithReservedKeywordIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminImportTableIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionCrossPartitionScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionCrossPartitionScanIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderImportIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/1699
Fixes https://github.com/scalar-labs/scalardb/issues/1701
=> Backport to branch(3) : Fix resource leaks in `integrationTestJdbc`

core/src/main/java/com/scalar/db/api/OperationBuilder.java
=> Backport to branch(3) : Make OperationBuilder public

core/src/main/java/com/scalar/db/api/OperationBuilder.java
=> Backport to branch(3.12) : Make OperationBuilder public

core/src/main/java/com/scalar/db/api/OperationBuilder.java
=> Backport to branch(3.11) : Make OperationBuilder public

core/src/main/java/com/scalar/db/api/OperationBuilder.java
=> Backport to branch(3.10) : Make OperationBuilder public

core/src/main/java/com/scalar/db/api/OperationBuilder.java
=> Backport to branch(3.9) : Make OperationBuilder public

core/src/main/java/com/scalar/db/api/OperationBuilder.java
=> Backport to branch(3.8) : Make OperationBuilder public

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1724
=> Backport to branch(3) : Bump info.picocli:picocli from 4.7.5 to 4.7.6

core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/1727
=> Backport to branch(3) : Fix to prevent scan with index after overlapping put

core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/1727
=> Backport to branch(3.12) : Fix to prevent scan with index after overlapping put

core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/1727
=> Backport to branch(3.11) : Fix to prevent scan with index after overlapping put

core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
=> Backport to branch(3.10) : Fix to prevent scan with index after overlapping put

data-loader/build.gradle, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/ColumnKeyValue.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/ColumnKeyValueConverter.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommandOptions.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/ColumnKeyValueConverterTest.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/FileFormat.java
Backport of https://github.com/scalar-labs/scalardb/pull/1742
=> Backport to branch(3) : Add picocli argument convertor for column key value and file format

core/build.gradle, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTestUtils.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminRepairTableIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseColumnValueIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseConditionalMutationIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseCrossPartitionScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultipleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultiplePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSecondaryIndexIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSingleClusteringKeyScanIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSinglePartitionKeyIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderImportIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcTestUtils.java, core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminRepairTableIntegrationTest.java, integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
Backport https://github.com/scalar-labs/scalardb/pull/1747
=> Backport to branch(3): Improve JDBC integration tests

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1751
=> Backport to branch(3) : Bump com.google.code.gson:gson from 2.10.1 to 2.11.0

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/build.gradle, data-loader/cli/build.gradle, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommand.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommandOptions.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/exception/DirectoryValidationException.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/exception/InvalidFileExtensionException.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/DirectoryUtils.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommandTest.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/DirectoryUtilsTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1754
=> Backport to branch(3) : Add export --output-file flag and validation

core/src/main/java/com/scalar/db/api/CrudOperable.java, core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java, core/src/main/java/com/scalar/db/api/TransactionManagerCrudOperable.java, core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/AbstractDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/AbstractTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/DecoratedDistributedTransaction.java, core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransaction.java, core/src/main/java/com/scalar/db/common/TransactionDecorationDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/TransactionDecorationTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/service/TransactionService.java, core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java, core/src/test/java/com/scalar/db/common/TransactionDecorationDistributedTransactionManagerTest.java, core/src/test/java/com/scalar/db/common/TransactionDecorationTwoPhaseCommitTransactionManagerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java, server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithServer.java, server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithServer.java, server/src/main/java/com/scalar/db/server/DistributedTransactionService.java, server/src/main/java/com/scalar/db/server/TwoPhaseCommitTransactionService.java
Backport of https://github.com/scalar-labs/scalardb/pull/1755
=> Backport to branch(3) : Allow directly executing CRUD operations with transaction managers

core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransactionManager.java
Backport of https://github.com/scalar-labs/scalardb/pull/1774
=> Backport to branch(3) : Add DecoratedDistributedTransactionManager and DecoratedTwoPhaseCommitTransactionManager

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
=> Backport to branch(3.12) : Change hard-coded password for Oracle user in JDBC adapter

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
=> Backport to branch(3.11) : Change hard-coded password for Oracle user in JDBC adapter

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
=> Backport to branch(3.10) : Change hard-coded password for Oracle user in JDBC adapter

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
=> Backport to branch(3.9) : Change hard-coded password for Oracle user in JDBC adapter

core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
=> Backport to branch(3.8) : Change hard-coded password for Oracle user in JDBC adapter

data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/ColumnKeyValueConverter.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/ColumnKeyValueConverterTest.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/ColumnKeyValue.java
Backport of https://github.com/scalar-labs/scalardb/pull/1770
=> Backport to branch(3) : Move ColumnKeyValue to the data loader core project

docs/configurations.md
Backport of https://github.com/scalar-labs/scalardb/pull/1753
=> Backport to branch(3.12) : Fix default value of cross-partition scan in docs

docs/configurations.md
Backport of https://github.com/scalar-labs/scalardb/pull/1753
=> Backport to branch(3.11) : Fix default value of cross-partition scan in docs

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1790
=> Backport to branch(3) : Bump com.azure:azure-cosmos from 4.60.0 to 4.61.0

README.md
Backport of https://github.com/scalar-labs/scalardb/pull/1801
=> Backport to branch(3.12) : Remove CI status badge

README.md
Backport of https://github.com/scalar-labs/scalardb/pull/1801
=> Backport to branch(3.11) : Remove CI status badge

README.md
Backport of https://github.com/scalar-labs/scalardb/pull/1801
=> Backport to branch(3.10) : Remove CI status badge

core/src/main/java/com/scalar/db/api/ScanBuilder.java, core/src/main/java/com/scalar/db/common/checker/OperationChecker.java, core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java, core/src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java, core/src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/api/ScanBuilderTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java, core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageSecondaryIndexIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithServer.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageIntegrationTestWithServer.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageSecondaryIndexIntegrationTestWithServer.java, server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithServer.java
Backport of https://github.com/scalar-labs/scalardb/pull/1763
=> Backport to branch(3) : Add arbitrary filtering for partition scan and index scan

integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/1803
=> Backport to branch(3) : Fix a flaky test of `integration-test-for-group-commit` test cases

buildSrc/src/main/java/com/scalar/db/JdkConfigurationPlugin.java
=> Backport to branch(3.12) : Revert behavior : the Gradle build does not require to use JDK 8 (temurin)

buildSrc/src/main/java/com/scalar/db/JdkConfigurationPlugin.java
=> Backport to branch(3.10) : Revert behavior : the Gradle build does not require to use JDK 8 (temurin)

buildSrc/src/main/java/com/scalar/db/JdkConfigurationPlugin.java
=> Backport to branch(3.8) : Revert behavior : the Gradle build does not require to use JDK 8 (temurin)

buildSrc/src/main/java/com/scalar/db/JdkConfigurationPlugin.java
=> Backport to branch(3.9) : Revert behavior : the Gradle build does not require to use JDK 8 (temurin)

buildSrc/src/main/java/com/scalar/db/JdkConfigurationPlugin.java
=> Backport to branch(3.11) : Revert behavior : the Gradle build does not require to use JDK 8 (temurin)

buildSrc/src/main/java/com/scalar/db/JdkConfigurationPlugin.java
=> Backport to branch(3) : Revert behavior : the Gradle build does not require to use JDK 8 (temurin)

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1830
=> Backport to branch(3) : Bump com.azure:azure-cosmos from 4.61.0 to 4.61.1

core/build.gradle
=> Backport to branch(3) : Increase heap size for Cosmos DB integration test

core/build.gradle
=> Backport to branch(3.12) : Increase heap size for Cosmos DB integration test

core/build.gradle
=> Backport to branch(3.11) : Increase heap size for Cosmos DB integration test

core/build.gradle
=> Backport to branch(3.10) : Increase heap size for Cosmos DB integration test

core/build.gradle
=> Backport to branch(3.9) : Increase heap size for Cosmos DB integration test

core/build.gradle
=> Backport to branch(3.8) : Increase heap size for Cosmos DB integration test

core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommit.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitter.java, core/src/main/java/com/scalar/db/util/groupcommit/DelayedGroup.java, core/src/main/java/com/scalar/db/util/groupcommit/DelayedSlotMoveWorker.java, core/src/main/java/com/scalar/db/util/groupcommit/Emittable.java, core/src/main/java/com/scalar/db/util/groupcommit/Group.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCleanupWorker.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitMetrics.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitter.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupManager.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupSizeFixWorker.java, core/src/main/java/com/scalar/db/util/groupcommit/KeyManipulator.java, core/src/main/java/com/scalar/db/util/groupcommit/NormalGroup.java, core/src/main/java/com/scalar/db/util/groupcommit/Slot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitterTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorTest.java, core/src/test/java/com/scalar/db/util/groupcommit/DelayedGroupTest.java, core/src/test/java/com/scalar/db/util/groupcommit/DelayedSlotMoveWorkerTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCleanupWorkerTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterConcurrentTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupManagerTest.java, core/src/test/java/com/scalar/db/util/groupcommit/GroupSizeFixWorkerTest.java, core/src/test/java/com/scalar/db/util/groupcommit/NormalGroupTest.java, core/src/test/java/com/scalar/db/util/groupcommit/SlotTest.java, core/src/test/java/com/scalar/db/util/groupcommit/TestableKeyManipulator.java
Backport of https://github.com/scalar-labs/scalardb/pull/1805
=> Backport to branch(3) : Split Group Commit Emitter method for normal group emit and delayed group emit

docs/getting-started/build.gradle, docs/getting-started/gradle/wrapper/gradle-wrapper.properties
=> Backport to branch(3.12) : Fix a build error of docs/getting-started

docs/getting-started/build.gradle, docs/getting-started/gradle/wrapper/gradle-wrapper.properties
=> Backport to branch(3.11) : Fix a build error of docs/getting-started

docs/getting-started/build.gradle, docs/getting-started/gradle/wrapper/gradle-wrapper.properties
=> Backport to branch(3.10) : Fix a build error of docs/getting-started

docs/getting-started/build.gradle, docs/getting-started/gradle/wrapper/gradle-wrapper.properties
=> Backport to branch(3.9) : Fix a build error of docs/getting-started

docs/getting-started/build.gradle, docs/getting-started/gradle/wrapper/gradle-wrapper.properties
=> Backport to branch(3) : Fix a build error of docs/getting-started

docs/getting-started/build.gradle, docs/getting-started/gradle/wrapper/gradle-wrapper.properties
=> Backport to branch(3.8) : Fix a build error of docs/getting-started

.github/workflows/ci.yaml
=> Backport to branch(3.10) : Add build tests for `getting started` example projects

.github/workflows/ci.yaml
=> Backport to branch(3.12) : Add build tests for `getting started` example projects

.github/workflows/ci.yaml
=> Backport to branch(3) : Add build tests for `getting started` example projects

README.md
=> Backport to branch(3) : Change relative docs links to docs site links in README

README.md
=> Backport to branch(3.12) : Change relative docs links to docs site links in README

README.md
=> Backport to branch(3.11) : Change relative docs links to docs site links in README

README.md
=> Backport to branch(3.10) : Change relative docs links to docs site links in README

README.md
=> Backport to branch(3.9) : Change relative docs links to docs site links in README

README.md
=> Backport to branch(3.8) : Change relative docs links to docs site links in README

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1894
=> Backport to branch(3) : Bump com.yugabyte:jdbc-yugabytedb from 42.3.5-yb-4 to 42.3.5-yb-5

core/src/main/java/com/scalar/db/api/Get.java, core/src/main/java/com/scalar/db/api/GetBuilder.java, core/src/main/java/com/scalar/db/api/ScanBuilder.java, core/src/main/java/com/scalar/db/api/SelectionBuilder.java, core/src/main/java/com/scalar/db/common/checker/OperationChecker.java, core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java, core/src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/api/GetBuilderTest.java, core/src/test/java/com/scalar/db/storage/cassandra/CassandraTest.java, core/src/test/java/com/scalar/db/storage/cosmos/CosmosTest.java, core/src/test/java/com/scalar/db/storage/dynamo/DynamoTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java, core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/singlecrudoperation/SingleCrudOperationTransactionIntegrationTestBase.java, server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithServer.java, server/src/integration-test/java/com/scalar/db/server/DistributedStorageIntegrationTestWithServer.java, server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithServer.java
Backport of https://github.com/scalar-labs/scalardb/pull/1834
=> Backport to branch(3) : Add arbitrary filtering for get operations

.github/workflows/ci.yaml, core/build.gradle
=> Backport to branch(3.10) : Use Cosmos DB emulator for the integration tests

.github/workflows/ci.yaml, core/build.gradle
=> Backport to branch(3.11) : Use Cosmos DB emulator for the integration tests

.github/workflows/ci.yaml, core/build.gradle
=> Backport to branch(3.9) : Use Cosmos DB emulator for the integration tests

.github/workflows/ci.yaml, core/build.gradle
=> Backport to branch(3.8) : Use Cosmos DB emulator for the integration tests

.github/workflows/ci.yaml, core/build.gradle
=> Backport to branch(3) : Use Cosmos DB emulator for the integration tests

.github/workflows/ci.yaml, core/build.gradle
=> Backport to branch(3.12) : Use Cosmos DB emulator for the integration tests

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/1981
=> Backport to branch(3) : Bump com.github.spotbugs:spotbugs-annotations from 4.8.5 to 4.8.6

core/src/main/java/com/scalar/db/common/DecoratedDistributedTransaction.java, core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionAdmin.java, core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransaction.java, core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransactionManager.java
This PR adds `DecoratedDistributedTransactionAdmin` which is an abstract class of decorator class for `DistributedTransactionAdmin`.
N/A
- Added `DecoratedDistributedTransactionAdmin`.
N/A
N/A
=> Add DecoratedDistributedTransactionAdmin

core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
=> Backport to branch(3.12) : Fix snapshot management issues

core/src/main/java/com/scalar/db/common/TransactionExecutor.java, core/src/test/java/com/scalar/db/common/TransactionExecutorTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/2015
=> Backport to branch(3) : Add TransactionExecutor

core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java, docs/schema-loader.md
Backport of https://github.com/scalar-labs/scalardb/pull/2000 to branch(3)
=> Backport to branch(3): Change some JDBC data types to proper ones

core/src/main/java/com/scalar/db/api/DistributedStorage.java, core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java, core/src/main/java/com/scalar/db/api/DistributedTransactionAdmin.java
Backport of https://github.com/scalar-labs/scalardb/pull/2039
=> Backport to branch(3.13) : Make DistributedStorage, DistributedTransactionAdmin, and DistributedStorageAdmin extend AutoCloseable

integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
This is for the `3` and `3.13` branches.
Depending on the environment executing the integration tests, `DistributedStorageAdmin` can't be instantiated. This PR moves the instantiation to `extraCheckOnCoordinatorTable()`.
- https://github.com/scalar-labs/scalardb/pull/2034
- Fixed `DistributedTransactionAdminIntegrationTestBase`.
N/A
N/A
=> Fix DistributedTransactionAdminIntegrationTestBase

integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/2042
=> Backport to branch(3.13) : Fix DistributedTransactionAdminIntegrationTestBase

core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java, core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/2044
=> Backport to branch(3.13) : Create metadata namespace and table if they does not exist before creating user tables

core/src/main/java/com/scalar/db/api/Admin.java, core/src/main/java/com/scalar/db/api/TableMetadata.java, core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java, core/src/main/java/com/scalar/db/common/error/CoreError.java, core/src/test/java/com/scalar/db/common/CheckedDistributedStorageAdminTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/1907
=> Backport to branch(3) : Add encrypted column concept

core/src/main/java/com/scalar/db/api/TableMetadata.java, schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java, schema-loader/src/test/java/com/scalar/db/schemaloader/TableSchemaTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/1975
=> Backport to branch(3) : Support encrypted columns in Schema Loader

core/src/main/java/com/scalar/db/common/DecoratedDistributedTransaction.java, core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionAdmin.java, core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransaction.java, core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransactionManager.java
Backport of https://github.com/scalar-labs/scalardb/pull/1974
=> Backport to branch(3) : Add DecoratedDistributedTransactionAdmin

core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java, core/src/test/java/com/scalar/db/common/CheckedDistributedStorageAdminTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/2014
=> Backport to branch(3) : Add check for encrypted columns to repairTable()

README.md, docs/getting-started-kotlin/build.gradle.kts, docs/getting-started/build.gradle
This PR updates ScalarDB dependency version to 3.13.0.
N/A
- Updated ScalarDB dependency version to 3.13.0.
N/A
N/A
=> Update ScalarDB dependency version to 3.13.0

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2051
=> Backport to branch(3) : Bump com.azure:azure-cosmos from 4.61.1 to 4.62.0

core/build.gradle
=> Backport to branch(3) : Reduce Cosmos DB log messages in the integration test

core/build.gradle
=> Backport to branch(3.13) : Reduce Cosmos DB log messages in the integration test

core/build.gradle
=> Backport to branch(3.12) : Reduce Cosmos DB log messages in the integration test

core/build.gradle
=> Backport to branch(3.11) : Reduce Cosmos DB log messages in the integration test

core/build.gradle
=> Backport to branch(3.10) : Reduce Cosmos DB log messages in the integration test

core/build.gradle
=> Backport to branch(3.9) : Reduce Cosmos DB log messages in the integration test

.github/workflows/ci.yaml
Backport of https://github.com/scalar-labs/scalardb/pull/1978
=> Backport to branch(3) : [CI] Install Oracle JDK 8 and 11 for integration test runtime

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2077
=> Backport to branch(3) : Bump org.apache.commons:commons-lang3 from 3.14.0 to 3.15.0

.github/workflows/ci.yaml, ci/no-superuser/create-no-superuser-sqlserver.sh
This PR fixes the following CI error.
https://github.com/scalar-labs/scalardb/actions/runs/10073247103/job/27861606398?pr=2075
Recently, the container image of MS SQL Server 2022 was updated, and the file path in the container was changed from `/opt/mssql-tools/bin/sqlcmd` to `/opt/mssql-tools18/bin/sqlcmd`.
- Related issue
- https://github.com/microsoft/mssql-docker/issues/892
- Official document
- https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker
```
In SQL Server 2022 (16.x) CU 14 and later versions, container images include the new mssql-tools18 package. The previous directory /opt/mssql-tools/bin is being phased out. The new directory for Microsoft ODBC 18 tools is /opt/mssql-tools18/bin, aligning with the latest tools offering. For more information about …
```
=> Fix CI issue SQL Server 2022 failed

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3) : Fix CI issue SQL Server 2022 failed

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.12) : Fix CI issue SQL Server 2022 failed

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.11) : Fix CI issue SQL Server 2022 failed

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.10) : Fix CI issue SQL Server 2022 failed

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.9) : Fix CI issue SQL Server 2022 failed

core/src/main/java/com/scalar/db/api/TableMetadata.java, core/src/test/java/com/scalar/db/api/TableMetadataTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/2075
=> Backport to branch(3) : Fix TableMetadata

.github/workflows/ci.yaml
Backport of https://github.com/scalar-labs/scalardb/pull/2061
=> Backport to branch(3) : [CI] Add integration test for MariaDB 11.4 and Oracle 19 

core/src/main/java/com/scalar/db/common/ProjectedResult.java, core/src/main/java/com/scalar/db/common/ResultImpl.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/AbstractMutationComposer.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposer.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/FilteredResult.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java, core/src/main/java/com/scalar/db/util/ScalarDbUtils.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposerTest.java, core/src/test/java/com/scalar/db/util/ScalarDbUtilsTest.java
Backport of https://github.com/scalar-labs/scalardb/pull/2076
=> Backport to branch(3) : Add getPartitionKey() and getClusteringKey() to ScalarDbUtils

core/src/main/java/com/scalar/db/api/OperationBuilder.java
Backport of https://github.com/scalar-labs/scalardb/pull/2080
=> Backport to branch(3) : Make interfaces in OperationBuilder public

core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/DistributedTransactionExpirationHandlerSettable.java, core/src/main/java/com/scalar/db/common/TwoPhaseCommitTransactionExpirationHandlerSettable.java
This PR introduces `DistributedTransactionExpirationHandlerSettable` and `TwoPhaseCommitTransactionExpirationHandlerSettable`.
N/A
- Introduced `DistributedTransactionExpirationHandlerSettable` and `TwoPhaseCommitTransactionExpirationHandlerSettable`.
N/A
N/A
=> Introduce DistributedTransactionExpirationHandlerSettable and TwoPhaseCommitTransactionExpirationHandlerSettable

core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/common/DistributedTransactionExpirationHandlerSettable.java, core/src/main/java/com/scalar/db/common/TwoPhaseCommitTransactionExpirationHandlerSettable.java
Backport of https://github.com/scalar-labs/scalardb/pull/2082
=> Backport to branch(3) : Introduce DistributedTransactionExpirationHandlerSettable and TwoPhaseCommitTransactionExpirationHandlerSettable

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2107
=> Backport to branch(3) : Bump com.azure:azure-cosmos from 4.62.0 to 4.63.0

core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
=> Backport to branch(3) : Refactor ScalarDbUtils

core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
=> Backport to branch(3.13) : Refactor ScalarDbUtils

core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
=> Backport to branch(3.12) : Refactor ScalarDbUtils

core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
=> Backport to branch(3.11) : Refactor ScalarDbUtils

core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
=> Backport to branch(3.10) : Refactor ScalarDbUtils

core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
=> Backport to branch(3.9) : Refactor ScalarDbUtils

core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
=> Backport to branch(3) : Fix NullPointerException when table is not found in Consensus Commit

core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
=> Backport to branch(3.13) : Fix NullPointerException when table is not found in Consensus Commit

core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
=> Backport to branch(3.12) : Fix NullPointerException when table is not found in Consensus Commit

core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
=> Backport to branch(3.11) : Fix NullPointerException when table is not found in Consensus Commit

core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
=> Backport to branch(3.10) : Fix NullPointerException when table is not found in Consensus Commit

core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
=> Backport to branch(3.9) : Fix NullPointerException when table is not found in Consensus Commit

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3) : Fix CI issue of SQL Server (Check if the command exsits)

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.13) : Fix CI issue of SQL Server (Check if the command exsits)

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.12) : Fix CI issue of SQL Server (Check if the command exsits)

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.10) : Fix CI issue of SQL Server (Check if the command exsits)

ci/no-superuser/create-no-superuser-sqlserver.sh
=> Backport to branch(3.9) : Fix CI issue of SQL Server (Check if the command exsits)

core/src/main/java/com/scalar/db/common/AbstractDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/AbstractTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java, core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java, core/src/main/java/com/scalar/db/transaction/singlecrudoperation/SingleCrudOperationTransactionUtils.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java, integration-test/src/main/java/com/scalar/db/transaction/singlecrudoperation/SingleCrudOperationTransactionIntegrationTestBase.java
This PR refactors the `AbstractDistributedTransactionManager` class and the `AbstractTwoPhaseCommitTransactionManager` class.
N/A
- Moved the CRUD operations in the `AbstractDistributedTransactionManager` class and the `AbstractTwoPhaseCommitTransactionManager` class to the implementation classes.
N/A
N/A
=> Refactor AbstractDistributedTransactionManager and AbstractTwoPhaseCommitTransactionManager

core/src/main/java/com/scalar/db/common/AbstractDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/AbstractTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java, core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java, core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java, core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/transaction/singlecrudoperation/SingleCrudOperationTransactionUtils.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java, core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java, integration-test/src/main/java/com/scalar/db/transaction/singlecrudoperation/SingleCrudOperationTransactionIntegrationTestBase.java
Backport of https://github.com/scalar-labs/scalardb/pull/2156
=> Backport to branch(3.13) : Refactor AbstractDistributedTransactionManager and AbstractTwoPhaseCommitTransactionManager

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2173
=> Backport to branch(3) : Bump com.azure:azure-cosmos from 4.63.0 to 4.63.1

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2174
=> Backport to branch(3) : Bump org.apache.commons:commons-lang3 from 3.15.0 to 3.16.0

core/src/main/java/com/scalar/db/config/DatabaseConfig.java
Backport of https://github.com/scalar-labs/scalardb/pull/2171
=> Backport to branch(3) : Add utility methods to DatabaseConfig

core/src/main/java/com/scalar/db/api/Admin.java, core/src/main/java/com/scalar/db/api/AuthAdmin.java, core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java, core/src/main/java/com/scalar/db/common/error/CoreError.java
Backport of https://github.com/scalar-labs/scalardb/pull/2182
=> Backport to branch(3) : Revise error messages related to enterprise features

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2192
=> Backport to branch(3) : Bump org.postgresql:postgresql from 42.7.3 to 42.7.4

build.gradle
Backport of https://github.com/scalar-labs/scalardb/pull/2191
=> Backport to branch(3) : Bump com.azure:azure-cosmos from 4.63.1 to 4.63.2

build.gradle, core/build.gradle
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2238
- **Commit to backport:** d5c8457f73583045cdc16d49a765503bc3e43c4a
```console
git checkout 3.13-pull-2238 &&
git cherry-pick --no-rerere-autoupdate -m1 d5c8457f73583045cdc16d49a765503bc3e43c4a
```
Thank you!
=> Backport to branch(3.13) : Fix CVE-2023-22102

build.gradle, core/build.gradle
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2238
- **Commit to backport:** d5c8457f73583045cdc16d49a765503bc3e43c4a
```console
git checkout 3.12-pull-2238 &&
git cherry-pick --no-rerere-autoupdate -m1 d5c8457f73583045cdc16d49a765503bc3e43c4a
```
Thank you!
=> Backport to branch(3.12) : Fix CVE-2023-22102

build.gradle, core/build.gradle
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2238
- **Commit to backport:** d5c8457f73583045cdc16d49a765503bc3e43c4a
```console
git checkout 3.11-pull-2238 &&
git cherry-pick --no-rerere-autoupdate -m1 d5c8457f73583045cdc16d49a765503bc3e43c4a
```
Thank you!
=> Backport to branch(3.11) : Fix CVE-2023-22102

.github/workflows/ci.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2250
- **Commit to backport:** 864e5fbbd7693c523404578af7aff73adc556a81
```console
git checkout 3.12-pull-2250 &&
git cherry-pick --no-rerere-autoupdate -m1 864e5fbbd7693c523404578af7aff73adc556a81
```
Thank you!
=> Backport to branch(3.12) : [CI] Fix SQLServer 2017 job 

.github/workflows/ci.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2250
- **Commit to backport:** 864e5fbbd7693c523404578af7aff73adc556a81
```console
git checkout 3.11-pull-2250 &&
git cherry-pick --no-rerere-autoupdate -m1 864e5fbbd7693c523404578af7aff73adc556a81
```
Thank you!
=> Backport to branch(3.11) : [CI] Fix SQLServer 2017 job 

.github/workflows/ci.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2250
- **Commit to backport:** 864e5fbbd7693c523404578af7aff73adc556a81
```console
git checkout 3.9-pull-2250 &&
git cherry-pick --no-rerere-autoupdate -m1 864e5fbbd7693c523404578af7aff73adc556a81
```
Thank you!
=> Backport to branch(3.9) : [CI] Fix SQLServer 2017 job 

.github/workflows/ci.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2250
- **Commit to backport:** 864e5fbbd7693c523404578af7aff73adc556a81
```console
git checkout 3.10-pull-2250 &&
git cherry-pick --no-rerere-autoupdate -m1 864e5fbbd7693c523404578af7aff73adc556a81
```
Thank you!
=> Backport to branch(3.10) : [CI] Fix SQLServer 2017 job 

.github/dependabot.yml, .github/workflows/scheduled-vuln-check.yaml
This PR updates Scheduled Vulnerability Check and the Dependabot configuration.
N/A
- Updated Scheduled Vulnerability Check and the Dependabot configuration.
N/A
N/A
=> Update Scheduled Vulnerability Check and Dependabot configuration

README.md
This PR updates ScalarDB dependency version to 3.14.0.
N/A
- Updated ScalarDB dependency version to 3.14.0.
N/A
N/A
=> Update ScalarDB dependency version to 3.14.0 in README

.github/workflows/ci.yaml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2302
- **Commit to backport:** f16b810ff81e6704125035b29dea74136f7efd2d
```console
git checkout 3.11-pull-2302 &&
git cherry-pick --no-rerere-autoupdate -m1 f16b810ff81e6704125035b29dea74136f7efd2d
```
Thank you!
=> Backport to branch(3.11) : Update MySQL and PostgreSQL versions tested on the CI

core/src/main/java/com/scalar/db/api/AuthAdmin.java, core/src/main/java/com/scalar/db/common/error/CoreError.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2334
- **Commit to backport:** 3929175b1b92ddc75873b504fa21029e668c2b57
```console
git checkout 3.13-pull-2334 &&
git cherry-pick --no-rerere-autoupdate -m1 3929175b1b92ddc75873b504fa21029e668c2b57
```
Thank you!
=> Backport to branch(3.13) : Revise feature names in error messages

data-loader/build.gradle, data-loader/core/src/main/java/com/scalar/db/dataloader/core/ErrorMessage.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/exception/Base64Exception.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/CollectionUtil.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/CsvUtil.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/DebugUtil.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/DecimalUtil.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/PathUtil.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/RuntimeUtil.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/UnitTestUtils.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/CollectionUtilTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/CsvUtilTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/DecimalUtilTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/PathUtilTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/RuntimeUtilTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2388
- **Commit to backport:** f3c358686fcb2105775a7ccfa11f30b033640ef6
```console
git checkout 3.11-pull-2388 &&
git cherry-pick --no-rerere-autoupdate -m1 f3c358686fcb2105775a7ccfa11f30b033640ef6
```
Thank you!
=> Backport to branch(3.11) : Add Util classes for data loader

data-loader/build.gradle, data-loader/core/src/main/java/com/scalar/db/dataloader/core/ErrorMessage.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/exception/Base64Exception.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/CollectionUtil.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/CsvUtil.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/DebugUtil.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/DecimalUtil.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/PathUtil.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/RuntimeUtil.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/UnitTestUtils.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/CollectionUtilTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/CsvUtilTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/DecimalUtilTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/PathUtilTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/RuntimeUtilTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2388
- **Commit to backport:** f3c358686fcb2105775a7ccfa11f30b033640ef6
```console
git checkout 3.10-pull-2388 &&
git cherry-pick --no-rerere-autoupdate -m1 f3c358686fcb2105775a7ccfa11f30b033640ef6
```
Thank you!
=> Backport to branch(3.10) : Add Util classes for data loader

core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTestUtils.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java, core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java, core/src/main/java/com/scalar/db/config/DatabaseConfig.java, core/src/main/java/com/scalar/db/io/BigIntColumn.java, core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java, core/src/main/java/com/scalar/db/storage/cassandra/CassandraConfig.java, core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java, core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java, core/src/main/java/com/scalar/db/storage/dynamo/Namespace.java, core/src/main/java/com/scalar/db/storage/jdbc/ConditionalMutator.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java, core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithFetchFirstNRowsOnly.java, core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithLimitQuery.java, core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithTop.java, core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java, core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java, core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitConfig.java, gradle/spotbugs-exclude.xml, schema-loader/src/main/java/com/scalar/db/schemaloader/ImportSchemaParser.java, schema-loader/src/main/java/com/scalar/db/schemaloader/ImportTableSchema.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaParser.java, schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2421
- **Commit to backport:** a706e7fdfa506603e9f967f450cb867a9ca927ae
```console
git checkout 3-pull-2421 &&
git cherry-pick --no-rerere-autoupdate -m1 a706e7fdfa506603e9f967f450cb867a9ca927ae
```
Thank you!
=> Backport to branch(3) : Ignore Spotbugs warning CT_CONSTRUCTOR_THROW

core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java, core/src/test/java/com/scalar/db/storage/jdbc/RdbEngine.java, core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2465
- **Commit to backport:** 8c96c1aacb3adc8b18c1fee271bf925e64e8bb78
```console
git checkout 3-pull-2465 &&
git cherry-pick --no-rerere-autoupdate -m1 8c96c1aacb3adc8b18c1fee271bf925e64e8bb78
```
Thank you!
=> Backport to branch(3) : Fix missing unit tests for MariaDB RdbEngine

core/src/main/java/com/scalar/db/common/error/CoreError.java
This PR removes an unnecessary error code.
N/A
- Removed an unnecessary error code.
N/A
N/A
=> Remove unnecessary error code

core/src/main/java/com/scalar/db/common/error/CoreError.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2485
- **Commit to backport:** d96be1191227c040303d9cd9fdecb26b6be7be0d
```console
git checkout 3.12-pull-2485 &&
git cherry-pick --no-rerere-autoupdate -m1 d96be1191227c040303d9cd9fdecb26b6be7be0d
```
Thank you!
=> Backport to branch(3.12) : Remove unnecessary error code

core/src/main/java/com/scalar/db/storage/cosmos/ResultInterpreter.java, core/src/main/java/com/scalar/db/storage/dynamo/ResultInterpreter.java, core/src/main/java/com/scalar/db/storage/dynamo/bytes/BytesUtils.java, core/src/main/java/com/scalar/db/storage/dynamo/bytes/DateBytesEncoder.java, core/src/main/java/com/scalar/db/storage/dynamo/bytes/IntBytesEncoder.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineTimeTypeSqlite.java, core/src/main/java/com/scalar/db/util/TimeRelatedColumnEncodingUtils.java, core/src/test/java/com/scalar/db/storage/TimeRelatedColumnEncodingUtilsTest.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2491
- **Commit to backport:** 9cb186774e8dbc9f3af6394383f55f6bca9c8e57
```console
git checkout 3-pull-2491 &&
git cherry-pick --no-rerere-autoupdate -m1 9cb186774e8dbc9f3af6394383f55f6bca9c8e57
```
Thank you!
=> Backport to branch(3) : Change DATE type encoding to integer

.github/pull_request_template.md
This PR adds an item to the best-effort checklist so that we can notice similar issues in other products or modules when fixing a bug, as discussed in the retrospective meeting.
- scalar-labs/repository-template#2
- Add an item to the best-effort checklist
=> Add a checklist item to consider similar issues in other places

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileTable.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileTableFieldMapping.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataRequest.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataService.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/TableMetadataUtil.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataServiceTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/TableMetadataUtilTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2434
- **Commit to backport:** 85ca0eb166380f76eb514b9275aade21a44d6753
```console
git checkout 3.14-pull-2434 &&
git cherry-pick --no-rerere-autoupdate -m1 85ca0eb166380f76eb514b9275aade21a44d6753
```
Thank you!
=> Backport to branch(3.14) : Add table metadata service

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileTable.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileTableFieldMapping.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataRequest.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataService.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/TableMetadataUtil.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataServiceTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/TableMetadataUtilTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2434
- **Commit to backport:** 85ca0eb166380f76eb514b9275aade21a44d6753
```console
git checkout 3.12-pull-2434 &&
git cherry-pick --no-rerere-autoupdate -m1 85ca0eb166380f76eb514b9275aade21a44d6753
```
Thank you!
=> Backport to branch(3.12) : Add table metadata service

data-loader/core/src/main/java/com/scalar/db/dataloader/core/ErrorMessage.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileTable.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileTableFieldMapping.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataRequest.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataService.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/TableMetadataUtil.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataServiceTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/TableMetadataUtilTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2434
- **Commit to backport:** 85ca0eb166380f76eb514b9275aade21a44d6753
```console
git checkout 3.11-pull-2434 &&
git cherry-pick --no-rerere-autoupdate -m1 85ca0eb166380f76eb514b9275aade21a44d6753
```
Thank you!
=> Backport to branch(3.11) : Add table metadata service

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDBDao.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDBDaoException.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDbStorageManager.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDbTransactionManager.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDBDaoTest.java, gradle/spotbugs-exclude.xml
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2417
- **Commit to backport:** 08dd89383e495afb23d3cfb941a4229a674bee8a
```console
git checkout 3.12-pull-2417 &&
git cherry-pick --no-rerere-autoupdate -m1 08dd89383e495afb23d3cfb941a4229a674bee8a
```
Thank you!
=> Backport to branch(3.12) : Add ScalarDB Dao and related files 

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportEventListener.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportManager.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportOptions.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/CsvImportProcessor.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/DefaultImportProcessorFactory.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessor.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessorFactory.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessorParams.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/JsonImportProcessor.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/JsonLinesImportProcessor.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/TableColumnDataTypes.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportStorageTask.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportTask.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportTaskParams.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportTransactionalTask.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/ColumnUtils.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/KeyUtils.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/UnitTestUtils.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/CsvImportProcessorTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/DefaultImportProcessorFactoryTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/JsonImportProcessorTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/JsonLinesImportProcessorTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/TableColumnDataTypesTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/ColumnUtilsTest.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/KeyUtilsTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2462
- **Commit to backport:** 2eacbbc584f21c7de60a14b5188d487d4ca6751c
```console
git checkout 3.12-pull-2462 &&
git cherry-pick --no-rerere-autoupdate -m1 2eacbbc584f21c7de60a14b5188d487d4ca6751c
```
Thank you!
=> Backport to branch(3.12) : Add the import process implementation for data loader

tla+/consensus-commit/README.md
fix: Fix typo mistake committed
=> fix: Fix typo mistake committed

README.md
This PR updates the root-level README to guide visitors of this repository to beginner-level documentation on the [ScalarDB docs site](https://scalardb.scalar-labs.com/docs/latest). By listing specific docs and short explanations, we can help guide visitors to docs that may help them get started with using ScalarDB.
- For consistency, I've updated the README in the https://github.com/scalar-labs/scalardl repository.
- Revised the `Docs` section to include links to getting-started tutorials, configurations, and features on the docs site.
- Added a link to the ScalarDB overview page to the end of the introductory paragraph.
> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the …
=> Revise README to include links to docs for better guidance

README.md
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2637
- **Commit to backport:** 55b06112effbd433e6fba62217a21857be34920b
```console
git checkout 3-pull-2637 &&
git cherry-pick --no-rerere-autoupdate -m1 55b06112effbd433e6fba62217a21857be34920b
```
Thank you!
=> Backport to branch(3) : Add link to ScalarDB design doc in README

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommand.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/DirectoryUtils.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/FileUtils.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/InvalidFilePathException.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/DirectoryUtilsTest.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/FileUtilsTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2616
- **Commit to backport:** c242d80b44265d1661f88199a4af6932583b4452
```console
git checkout 3.15-pull-2616 &&
git cherry-pick --no-rerere-autoupdate -m1 c242d80b44265d1661f88199a4af6932583b4452
```
Thank you!
=> Backport to branch(3.15) : Add util classes for data loader CLI

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommand.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/DirectoryUtils.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/FileUtils.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/InvalidFilePathException.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/DirectoryUtilsTest.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/FileUtilsTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2616
- **Commit to backport:** c242d80b44265d1661f88199a4af6932583b4452
```console
git checkout 3.13-pull-2616 &&
git cherry-pick --no-rerere-autoupdate -m1 c242d80b44265d1661f88199a4af6932583b4452
```
Thank you!
=> Backport to branch(3.13) : Add util classes for data loader CLI

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommand.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/DirectoryUtils.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/FileUtils.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/InvalidFilePathException.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/DirectoryUtilsTest.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/FileUtilsTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2616
- **Commit to backport:** c242d80b44265d1661f88199a4af6932583b4452
```console
git checkout 3.12-pull-2616 &&
git cherry-pick --no-rerere-autoupdate -m1 c242d80b44265d1661f88199a4af6932583b4452
```
Thank you!
=> Backport to branch(3.12) : Add util classes for data loader CLI

core/src/main/java/com/scalar/db/common/error/CoreError.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommand.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommandOptions.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/MultiColumnKeyValueConverter.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ScanOrderingConverter.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/SingleColumnKeyValueConverter.java, data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/CommandLineInputUtils.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommandTest.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/dataexport/MultiColumnKeyValueConverterTest.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/dataexport/ScanOrderingConverterTest.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/dataexport/SingleColumnKeyValueConverterTest.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/CommandLineInputUtilsTest.java, data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/DirectoryUtilsTest.java, data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/KeyUtils.java, data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/KeyUtilsTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2617
- **Commit to backport:** 32179a68bae04e8fc337d7ccac4e8488bd97dc1f
```console
git checkout 3.12-pull-2617 &&
git cherry-pick --no-rerere-autoupdate -m1 32179a68bae04e8fc337d7ccac4e8488bd97dc1f
```
Thank you!
=> Backport to branch(3.12) : Add export command for data loader CLI

core/src/main/java/com/scalar/db/api/ReplicationAdmin.java, core/src/main/java/com/scalar/db/common/error/CoreError.java, schema-loader/build.gradle, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java, schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java, schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java, schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java, schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java, schema-loader/src/test/java/com/scalar/db/schemaloader/command/SchemaLoaderCommandTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2747
- **Commit to backport:** ec595ae1950babf919172eedc39706932c737ec9
```console
git checkout 3-pull-2747 &&
git cherry-pick --no-rerere-autoupdate -m1 ec595ae1950babf919172eedc39706932c737ec9
```
Thank you!
=> Backport to branch(3) : Add `--replication-tables` option to the Schema Loader

core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java, core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2769
- **Commit to backport:** 0e13365fe8578b1f041c1c84efb0a8938f8cfb90
```console
git checkout 3.14-pull-2769 &&
git cherry-pick --no-rerere-autoupdate -m1 0e13365fe8578b1f041c1c84efb0a8938f8cfb90
```
Thank you!
=> Backport to branch(3.14) : Fix the DynamoDB metadata table upsert operation

core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java, core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2769
- **Commit to backport:** 0e13365fe8578b1f041c1c84efb0a8938f8cfb90
```console
git checkout 3.12-pull-2769 &&
git cherry-pick --no-rerere-autoupdate -m1 0e13365fe8578b1f041c1c84efb0a8938f8cfb90
```
Thank you!
=> Backport to branch(3.12) : Fix the DynamoDB metadata table upsert operation

core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java, core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2769
- **Commit to backport:** 0e13365fe8578b1f041c1c84efb0a8938f8cfb90
```console
git checkout 3-pull-2769 &&
git cherry-pick --no-rerere-autoupdate -m1 0e13365fe8578b1f041c1c84efb0a8938f8cfb90
```
Thank you!
=> Backport to branch(3) : Fix the DynamoDB metadata table upsert operation

.github/workflows/permission-check.yaml, core/build.gradle, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminPermissionIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoEnv.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoPermissionIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoPermissionTestUtils.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminPermissionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStoragePermissionIntegrationTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2847
- **Commit to backport:** 5e002c2ed9dd73e0e5ea934c45c421ef07cab550
```console
git checkout 3-pull-2847 &&
git cherry-pick --no-rerere-autoupdate -m1 5e002c2ed9dd73e0e5ea934c45c421ef07cab550
```
Thank you!
=> Backport to branch(3) : Add DynamoDB permission test

.github/workflows/permission-check.yaml, core/build.gradle, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminPermissionIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoEnv.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoPermissionIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoPermissionTestUtils.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminPermissionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStoragePermissionIntegrationTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2847
- **Commit to backport:** 5e002c2ed9dd73e0e5ea934c45c421ef07cab550
```console
git checkout 3.15-pull-2847 &&
git cherry-pick --no-rerere-autoupdate -m1 5e002c2ed9dd73e0e5ea934c45c421ef07cab550
```
Thank you!
=> Backport to branch(3.15) : Add DynamoDB permission test

.github/workflows/permission-check.yaml, core/build.gradle, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminPermissionIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoEnv.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoPermissionIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoPermissionTestUtils.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminPermissionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStoragePermissionIntegrationTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2847
- **Commit to backport:** 5e002c2ed9dd73e0e5ea934c45c421ef07cab550
```console
git checkout 3.12-pull-2847 &&
git cherry-pick --no-rerere-autoupdate -m1 5e002c2ed9dd73e0e5ea934c45c421ef07cab550
```
Thank you!
=> Backport to branch(3.12) : Add DynamoDB permission test

.github/workflows/permission-check.yaml, core/build.gradle, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminPermissionIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoEnv.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoPermissionIntegrationTest.java, core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoPermissionTestUtils.java, integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminPermissionIntegrationTestBase.java, integration-test/src/main/java/com/scalar/db/api/DistributedStoragePermissionIntegrationTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2847
- **Commit to backport:** 5e002c2ed9dd73e0e5ea934c45c421ef07cab550
```console
git checkout 3.16-pull-2847 &&
git cherry-pick --no-rerere-autoupdate -m1 5e002c2ed9dd73e0e5ea934c45c421ef07cab550
```
Thank you!
=> Backport to branch(3.16) : Add DynamoDB permission test

.github/workflows/release-snapshot.yaml, .github/workflows/upload-artifacts.yaml, build.gradle, core/build.gradle, integration-test/build.gradle, rpc/build.gradle, schema-loader/build.gradle, server/build.gradle
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2849
- **Commit to backport:** 7e746c503069bef778aca63a49335189bd94b7a4
```console
git checkout 3.13-pull-2849 &&
git cherry-pick --no-rerere-autoupdate -m1 7e746c503069bef778aca63a49335189bd94b7a4
```
Thank you!
=> Backport to branch(3.13) : Use JReleaser to release artifacts in Maven Central

.github/workflows/release-snapshot.yaml, .github/workflows/upload-artifacts.yaml, build.gradle, core/build.gradle, integration-test/build.gradle, rpc/build.gradle, schema-loader/build.gradle, server/build.gradle
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2849
- **Commit to backport:** 7e746c503069bef778aca63a49335189bd94b7a4
```console
git checkout 3.12-pull-2849 &&
git cherry-pick --no-rerere-autoupdate -m1 7e746c503069bef778aca63a49335189bd94b7a4
```
Thank you!
=> Backport to branch(3.12) : Use JReleaser to release artifacts in Maven Central

core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2888
- **Commit to backport:** bf49281ebd019623f3f82ca90af39fd5e5c5785b
```console
git checkout 3-pull-2888 &&
git cherry-pick --no-rerere-autoupdate -m1 bf49281ebd019623f3f82ca90af39fd5e5c5785b
```
Thank you!
=> Backport to branch(3) : Fix Oracle engine to support multiple Oracle users for index operations

core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java, core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java, core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2888
- **Commit to backport:** bf49281ebd019623f3f82ca90af39fd5e5c5785b
```console
git checkout 3.14-pull-2888 &&
git cherry-pick --no-rerere-autoupdate -m1 bf49281ebd019623f3f82ca90af39fd5e5c5785b
```
Thank you!
=> Backport to branch(3.14) : Fix Oracle engine to support multiple Oracle users for index operations

core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2897
- **Commit to backport:** d905323b635e92f095ff3bc087d8f2b62b66fd68
```console
git checkout 3.16-pull-2897 &&
git cherry-pick --no-rerere-autoupdate -m1 d905323b635e92f095ff3bc087d8f2b62b66fd68
```
Thank you!
=> Backport to branch(3.16) : Fix Cassandra case insensitive issue

core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2897
- **Commit to backport:** d905323b635e92f095ff3bc087d8f2b62b66fd68
```console
git checkout 3.13-pull-2897 &&
git cherry-pick --no-rerere-autoupdate -m1 d905323b635e92f095ff3bc087d8f2b62b66fd68
```
Thank you!
=> Backport to branch(3.13) : Fix Cassandra case insensitive issue

core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/2897
- **Commit to backport:** d905323b635e92f095ff3bc087d8f2b62b66fd68
```console
git checkout 3.15-pull-2897 &&
git cherry-pick --no-rerere-autoupdate -m1 d905323b635e92f095ff3bc087d8f2b62b66fd68
```
Thank you!
=> Backport to branch(3.15) : Fix Cassandra case insensitive issue

core/src/main/java/com/scalar/db/common/CommonDistributedStorageAdmin.java, core/src/main/java/com/scalar/db/storage/cassandra/CassandraProvider.java, core/src/main/java/com/scalar/db/storage/cosmos/CosmosProvider.java, core/src/main/java/com/scalar/db/storage/dynamo/DynamoProvider.java, core/src/main/java/com/scalar/db/storage/jdbc/JdbcProvider.java, core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdmin.java, core/src/test/java/com/scalar/db/common/CommonDistributedStorageAdminTest.java
- **Original PR:** https://github.com/scalar-labs/scalardb/pull/3009
- **Commit to backport:** ec38d151f7bee32ef6baeecd90210fa22fc1d77e
```console
git checkout 3-pull-3009 &&
git cherry-pick --no-rerere-autoupdate -m1 ec38d151f7bee32ef6baeecd90210fa22fc1d77e
```
Thank you!
=> Backport to branch(3) : Rename CheckedDistributedStorageAdmin
